### ISSUE TITLE
set highlighted story (Organization/Project) (user story #154)

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#100]
User Story #154

**Comment by ghing** [comment]
Is this the admin or a user?

**Comment by jwirfs-brock** [comment]
This was originally intended to be for the Organization or Project owner. We never implemented controls for them. In recent weeks, though, I've received some comments from users who would like to actively control some features about their Organization or Project page after it has been created.

**Comment by ghing** [comment]
@jwirfs-brock You should open issues to capture those other requests in terms of Organization and Project controls.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot.
