### ISSUE TITLE
As a user, I want to see a list of stories chosen and curated by the staff every week on the new home page

### ISSUE THREAD

**Issue by wilbertom** [denverfoundation/storybase#1001]

**Comment by mgrayinnovation** [comment]
- Instead of the second section being Spotlight, it should probably be Explore ... so reverse two and three.

**Comment by mgrayinnovation** [comment]
- I like the fact that you've made this easy for us to change which stories will go here and create a simple pathway for this in the Admin view.

**Comment by mgrayinnovation** [comment]
- Should we render these as three side-by-side vertical columns?  I like the consistency between this appearance and the way the search lays-out stories, but I also like for the homepage to not take too much scrolling.  The goal is to have users see everything that Floodlight has to offer as fast possible on the homepage. 
      The scrolling through search results is okay, and the format is ideal, because I feel that once a user has down a search, they are willing to scroll through at least some of the results.  This isn't always the case with the homepage.
      Let's leave this as you've designed it now, and see how the TDF testers respond.

**Comment by mgrayinnovation** [comment]
We decided to leave this as horizontal/landscape banners since the photo and text sizes will render differently with vertical columns.  The horizontal columns will also allow us to add and remove stories from 2 to 7, very easily ... it just gives us more options down the road.

**Comment by mgrayinnovation** [comment]
This feature is not available and functioning, both on the homepage and on the back end. We just need some qualities stories to feature, but that's for the curation side.
