### ISSUE TITLE
As a user, I want the new home page to give me easy access to crating a story and finding a story so that I don't have to traverse the navigation bar.

### ISSUE THREAD

**Issue by wilbertom** [denverfoundation/storybase#1002]

**Comment by wilbertom** [comment]
The new home page will have a "Create your story" button and "Find Story" search box in the new jumbotron that will replace the random stories.

**Comment by mgrayinnovation** [comment]
- In the Explore section, will the three filters be visible instead of just the one fill-in line:
  Topic           Location            Open Fill-in/Search
  as in Issue #1004 ... looks like you're working on this now ...

**Comment by mgrayinnovation** [comment]
Completed this with home page order and create story button.
