### ISSUE TITLE
As a user, I should be able to explore Floodlight on the home page based on topic, location and custom text

### ISSUE THREAD

**Issue by wilbertom** [denverfoundation/storybase#1004]

**Comment by mgrayinnovation** [comment]
- In the Explore section, will the three filters be visible instead of just the one fill-in line:
  Topic           Location            Open Fill-in/Search
  as in Issue #1004 ... looks like you're working on this now ...

**Comment by mgrayinnovation** [comment]
- I definitely like the way the search page presents the stories, it's cleaner and allows for more clarity about each story prior to reading it, which will give us more momentum to move directly from these thumbnails right into the story viewer, and skip over the current story homepage, as discussed previously. This page also loads pretty fast which I like.  And last, it gives us further initiative to put down size parameters on the main feature photo used in each story, and the length/word count of each story summary.

**Comment by mgrayinnovation** [comment]
Curious if the actual search piece is operating?  I can put in a specific topic and location on the homepage, but it doesn't go anywhere.  The enter keyword does search and filter, but the two drop down menus don't go anywhere.

**Comment by mgrayinnovation** [comment]
Implementing the actual search feature is a priority, simultaneously, we need to create a solution for the location tags.  Currently, the locations are also connected to comprehensive geo location and mapping data.  Ideally, we need to hide, not delete this data (if at all possible), and not worry about the location tags connecting to a map or any map-like feature.  The feature would mirror the topic tags, but with specificity around location, specific to the Denver Foundation work.

**Comment by mgrayinnovation** [comment]
This is related to Issue #997 in Milestone P2
