### ISSUE TITLE
Find a new image for the homepage

### ISSUE THREAD

**Issue by wilbertom** [denverfoundation/storybase#1006]

**Comment by mgrayinnovation** [comment]
The one used in the draft looks awesome.  Do we have permission? I can find another one if necessary but this seems kind of perfect.

**Comment by mgrayinnovation** [comment]
- Decrease height of banner photo so that the header of section 2 is visible.
- Make the "create your story" button a bit larger?

**Comment by mgrayinnovation** [comment]
Changes/feedback incorporated by Wil

**Comment by mgrayinnovation** [comment]
We may need to reopen this later, but the current image works for now.
