### ISSUE TITLE
As reader I would like to know what each badge stands for by hovering over it to see a pop out box, or by seeing a brief definition underneath it.

### ISSUE THREAD

**Issue by mgrayinnovation** [denverfoundation/storybase#1010]
Wil, what's the easiest fix on this?  Did you mention that there is something already built in?  I will get you text for each of the badges as we move into integrating these review issues of P1.

**Comment by mgrayinnovation** [comment]
These are now approved and edited by Rebecca and should allow us to move forward with this feature:

https://docs.google.com/document/d/1hMlK_pyVg6Ybldab90cesT5CaS7dug0WQ3zCrrOWeTg/edit

**Comment by wilbertom** [comment]
Hey Matt, how do we want to handle these. The descriptions are a little long for a hover.

**Comment by mgrayinnovation** [comment]
What would be the ideal character/word limit for a hover?

If not a hover, could we create a pop out dialogue box? Or could it link to another page on Floodlight with the definitions for all the badges?

I think these are key definitions for this new approach to Floodlight, so folks can really understand what the badges are and what they're for ... both for general readers and writers, and super readers.

**Comment by mgrayinnovation** [comment]
Here is our fix for now:

3) Add a web page that can be easily found from the home navigation bar (under "Explore"?), maybe titled "Super Readers and Badges" that includes the content from this doc about Super Readers and Badge Descriptions: https://docs.google.com/document/d/1hMlK_pyVg6Ybldab90cesT5CaS7dug0WQ3zCrrOWeTg/edit

**Comment by mgrayinnovation** [comment]
We added the web page for a new fix to this issue, and since the story has changed significantly, I updated it under a new issue #1039
