### ISSUE TITLE
As a user, I want a new navigation bar styled for the new design

### ISSUE THREAD

**Issue by wilbertom** [denverfoundation/storybase#1022]

**Comment by mgrayinnovation** [comment]
Will this navigation bar be consistent with three sections of the homepage (Create, Explore, Spotlight)?

**Comment by wilbertom** [comment]
Hey Matt, yes. It would be exactly the same except with different styling.
We can move it around though

**Comment by mgrayinnovation** [comment]
There are some edits we need to make for navigation which I'll open as separate issues in this Milestone and in Milestone P5.
