### ISSUE TITLE
Data set download links should be styled for local/external in builder "add data" set

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#147]
Text: Download data as [TYPE]. Type is based on file extension.

View external data.

**Comment by mgrayinnovation** [comment]
Wil, this might be worth looking at.  As I "garden"  I'll sort and close things to our index, Pivot iterations, Bugs, or tweaks.

**Comment by mgrayinnovation** [comment]
Leaving as a tweak, 2/25/15

**Comment by mgrayinnovation** [comment]
Closed and moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
