### ISSUE TITLE
Error linking Twitter and FC account to existing Floodlight user

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#161]
I created a Floodlight user with just an email (no social media account connections) and then tried to connect Twitter and Facebook accounts and received the following error messages:

Twitter connect (matching email) - https://docs.google.com/a/piton.org/document/d/1W8znQLyuFGryX95AJ67_xlWWOCpVsPPCdsAJMnhbX8Q/edit
Twitter connect (non-matching email) - https://docs.google.com/a/piton.org/document/d/1sxwdMlnevCzaiWVHVycuZJeBiuOnlByWGUTHT7tfnNM/edit
FB connect (matching email) - https://docs.google.com/a/piton.org/document/d/1JkUvaThSeD1dQSazExsQP5zis-tjcErts5DVOIsd8Wk/edit

This is related to the fact that in the account creation step, when creating an account via Twitter, we have an extra step that asks for an email address. We don't need to do that for an existing account (that already has an email associated with it).

**Comment by ghing** [comment]
I believe this is fixed by a7f0a86d5ddb203d8496bc3442c48d8688cab745
