### ISSUE TITLE
After registration, user should be taken to the "My Account" page

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#164]
Currently, it takes the user to the home page.

**Comment by ghing** [comment]
The function to tweak to change this is storybase_user.registration.backends.extrainfo.ExtraInfoBackend.post_activation_redirect

**Comment by jwirfs-brock** [comment]
@ghing has this been implemented? I know after logging in, existing users are directed to "My Account" page.

**Comment by ghing** [comment]
@jwirfs-brock It looks like this has been implemented.  The user is taken to the "My Account" page after following the confirmation link in the e-mail. Closing.
