### ISSUE TITLE
Section table of contents ordering is incorrect after adding/removing sections

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#166]
Both Bill and Jordan reported some weirdness when adding/removing sections in the builder.  The result is that the table of contents shows the sections out of order like this:

![Wrongly ordered sections after adding/removing sections](http://i.imgur.com/ODqiJ.png)

**Comment by ghing** [comment]
Is this when adding or removing sections or does this happen under both situations?

Does reloading the page then show the sections in the correct order with the desired section added/removed?

What section was actively selected when the add/remove operation was initiated?

**Comment by ghing** [comment]
Jordan adds:

> So I was playing with the builder on the staging site (not sure if the bug shows up on the test site, too), and I saw the strange reordering behavior happening again after I:
> - create a new section
> - reordered sections
> - added an asset (photo) and edited the caption
> 
> It happened right after I added the photo and caption. Here's a screen shot of what the ordering looks like (story information and call to action are now both at the end):
> 
> Note also that "element 3" is highlighted in blue at the bottom, but I am looking at/editing the new section.

![Misordered sections](http://i.imgur.com/bRKFY.png)

**Comment by ghing** [comment]
@jwirfs-brock : Was the new section selected when you did the reordering?  Was the new section the one that was reordered?

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot.
