### ISSUE TITLE
Contributor can spell check the story before publishing (user story #252)

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#179]
User Story #252

**Comment by jwirfs-brock** [comment]
Should we close this, as it's covered by the spell checker in the browser?

**Comment by ghing** [comment]
I'm going to close this. Doing a good job of implementing spellchecking, particularly if we want to support multilingual spellchecking, is pretty complicated and I don't think it's the best use of our time.  Personally, I can't think of any web app where I use a built-in spellchecker.  I just use the browser.  For instance, I don't think that Google Docs even has a spell-check feature.  Also, using a browser's spell-check feature lets user leverage the dictionaries/overrides they already have instead of having to configure that separately for Floodlight.

We can reopen this if we notice a particular spell-checking issue that isn't met by the browser spellchecker.
