### ISSUE TITLE
Story builder should offer a chart/graph asset type

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#189]
I'm thinking it should function like the map type does in the current version of the builder, allowing the upload of a static image, embedded HTML or a URL to an image/oembedable resource.

**Comment by jwirfs-brock** [comment]
That makes sense. In terms of the fields you would want, I would make them the same as for a table asset (attribution, source URL).

**Comment by jwirfs-brock** [comment]
Can we just tweak the Table asset, so that it is Table/Graph/Chart?

**Comment by ghing** [comment]
@jwirfs-brock We can, or we can make it a separate type.  There's not really a difference in complexity in terms of the implementation.  Tell me which one you'd prefer.  Personally, I'm inclined to having table and graph/chart be separate types because it gives us more flexibility if we end up wanting to have different fields or functionality.

**Comment by jwirfs-brock** [comment]
@ghing Ok, if it's not any more difficult in terms of complexity, let's have them be two separate types. So, "table" and "graph/chart." "Graph/chart" can have the same fields as "table", including the editable caption once the asset has been uploaded.
