### ISSUE TITLE
fonts are not displaying correctly in firefox

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#193]
probably on account of Firefox's strict cross-domain policy.

**Comment by ghing** [comment]
This is some additional information that @patternleaf provided about this issue:

> The nice museo slab font is not showing up in Firefox on deploy.atlas.terrorware.com. I think we may be seeing 
> this:
> 
> ```
>    http://stackoverflow.com/a/3704578
> ```
> 
> The font faces are being served from the static resource location, at, eg
> 
> ```
>    http://static.deploy.atlas.terrorware.com:8081/css/font-face/museo_slab_500-webfont.woff
> ```
> 
> If that's what's happening the stackoverflow answer recommends sending an Access-Control-Allow-Origin header 
> along with the content. Seems not so heinous if set to allow only static.deploy.atlas.terrorware.com:8081 ...

**Comment by ghing** [comment]
I wasn't able to reproduce this issue.  In my Firefox, the font shows up correctly. In Firebug, I see the font being downloaded correctly and don't see any security errors.  As far as I can tell, there shouldn't be a cross-domain issue because the font is being loaded from the same place as the CSS.  Can you send me a screenshot of what you're seeing?

**Comment by ghing** [comment]
@patternleaf also, can you install Firebug and see if you get any error messages related to font loading or cross-domain security issues.

**Comment by patternleaf** [comment]
strange. what version of firefox are you using? 

there are no errors in the download and firebug doesn't report any issues. however, the built-in error console says:

```
Timestamp: 9/7/12 9:08:12 AM
Error: downloadable font: download failed (font-family: "MuseoSlab500Regular" style:normal weight:normal stretch:normal src index:1): bad URI or cross-site access not allowed
source: http://static.deploy.atlas.terrorware.com:8081/css/font-face/museo_slab_500-webfont.woff
Source File: http://static.deploy.atlas.terrorware.com:8081/css/style-new.css
```

i tried inlining the font face in the css and that did fix it.

**Comment by ghing** [comment]
ok. Looks like it's definately a cross-site issue. I'll configure the
webserver with the appropriate headers. Probably won't get to it until
tomorrow though.

**Comment by ghing** [comment]
I'm working on the nginx configuration to add the Access-Control-Allow-Origin headers and I'm having a little problem figuring out the right regex to match the font filenames. Things will be wonky on the deploy instance until I figure this out.

**Comment by ghing** [comment]
@patternleaf I updated the nginx configuration and verified that the access-control-allow-origin headers are being set for the font files.  I'm still getting an error in one of the versions of Firefox I'm testing under, so further debugging might be necessary.  Let me know what you're seeing.

**Comment by ghing** [comment]
@patternleaf I was finally able to replicate your issue (including the error in Firefox's native web console).  I also verified that setting the Access-Control-Allow-Origin headers eliminated the error and showed the fonts.  I'm going to close this issue.  Please reopen if you find my fix doesn't work.
