### ISSUE TITLE
Story Detail Page

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#194]
link on Google Docs: https://docs.google.com/file/d/0B7ipktENBWzTd2dsSjN0bHJvMGM/edit

1) The nav doesn't seem to work on this page

2) (IE only) ... getting a large image container that doesn't show up on other browsers

3) Page doesn't match wireframe layout (I know that's not necessarily a template issue, but it needs to be addressed).  For example, we won't have comments in R1

**Comment by patternleaf** [comment]
1. thanks. fixed.
2. is that just the "image is missing" indicator on IE, or something else?
3. this is still confusing to me. you're referring to http://clients.inovdesigns.com/floodlight/story_detail.php, right? it's not clear how that layout is to be reconciled with the comps, e.g. https://www.dropbox.com/lightbox/home/FLOODLIGHT/JPGs/ROUND_02

thanks,
E

**Comment by bpawlak** [comment]
Check with Jordan, but the comps are really more for the visual style.  The actual layout on this page should be more like the prototype.

**Comment by patternleaf** [comment]
closing this. current issue related to story detail layout is #208.
