### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#195]
https://docs.google.com/file/d/0B7ipktENBWzTYkY4N3VadTR1WnM/edit

1) Orange links in top meganav should show underline on hover

2) Project/Story title and thumbnail should be link to detail page

3) Need to make foundation logo and name links to the detail page (in About).

**Comment by patternleaf** [comment]
1. fixed.
2. subsumed under [#199](https://github.com/PitonFoundation/atlas/issues/199)—these need to be wired up
3. breaking this out into a separate issue for tracking.

closing this one—thanks.
