### ISSUE TITLE
Explore Page rendering problem on IE9

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#196]
https://docs.google.com/file/d/0B7ipktENBWzTM1JrdElRSklYTVU/edit

1) Thought I'd check this on multiple browsers... the filters don't show up at all in IE.

**Comment by patternleaf** [comment]
hi Bill - what version of IE are you using and on what version of Windows? thanks.

**Comment by bpawlak** [comment]
IE9, Windows 7 64bit.  

That was the only browser I saw it on.  Chrome/Firefox on Windows was fine and Chrome/Firefox on Snow Leopard was fine, too.

**Comment by patternleaf** [comment]
just a note from looking at this briefly the other day in ie8. the web inspector (such as it is) in IE reported that the background: url(...) style rule was being "eaten" by another rule nearby. there were no obvious syntax errors in the css.

**Comment by patternleaf** [comment]
@bpawlak this should be reviewable on deploy: http://deploy.atlas.terrorware.com/en/explore/

**Comment by patternleaf** [comment]
just double-checked this is fixed in IE8 on production. going to close. @bpawlak , if you find this isn't fixed, please re-open.
