### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#197]
https://docs.google.com/file/d/0B7ipktENBWzTbFMybFFXYVRsczg/edit

1) would like to the see horizontal rule/border _not_ extend all the way to the left - it breaks up the page and makes it look like the nav only applies to the top section (it looks/feels like the Foundations carousel on the home page).  Plus, on other pages, the left nav can grow quite a bit (incl. 3rd level nav - e.g. in the organizations and projects sections and the Learn section), so we'll need to make sure we're not visually limiting the height of the top container by putting the horizontal rule at the bottom.  

If the left nav has 8-10 items, we'd have a bunch of whitespace on the right to deal with

2) The h4 headers on that page need to be links to lower level pages.  We don't want to always rely on "read more" links (see http://clients.inovdesigns.com/floodlight/about.php)

**Comment by patternleaf** [comment]
1. ok, so that carousel should not be there at all—is that correct?
2. ok.

**Comment by bpawlak** [comment]
1) Yes, that's the thing... it's not supposed to be a carousel - it's sub-navigation for that section of the site.

**Comment by patternleaf** [comment]
closing this—these have been addressed.
