### ISSUE TITLE
homepage: featured story and featured projects not wired in

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#199]
these are powered by template tags

**Comment by ghing** [comment]
I can implement this.  These live in storybase_story.templatetags.story.featured_stories and storybase_user.templatetags.projects.featured_projects respectively right rendering using the 

It looks like you were trying to figure out a way to leverage the fact that the HTML spit out for projects and stories is really similar.  I see that your approach seems to be to transform the queryset into a dictionary.  I'm inclined to add an "interface" to the project and story models that normalizes the object property names via accessor methods on the model.  I'd like to talk this over with you to double-check this strategy.

**Comment by patternleaf** [comment]
> I can implement this.

cool.

> I see that your approach seems to be to transform the queryset into a dictionary.

right. i'm of course not married to this. if the template should instead just be duplicated it's not like it's a huge amount of code.

> I'm inclined to add an "interface" to the project and story models that normalizes the object property names via accessor methods on the model. I'd like to talk this over with you to double-check this strategy.

sure. again, i would not want to create a lot of extra work or forced symmetry just to avoid a small amount of duplicated template code. but if such an interface makes sense generally ...

**Comment by ghing** [comment]
Yeah, the more I think about it, duplicating the template code doesn't seem terrible, especially since I see it as being entirely possible that the HTML for projects and stories could diverge greatly in the future.

**Comment by ghing** [comment]
@jwirfs-brock, assigning this ticket to you for review.  The projects don't have their images wired in yet, but I'm going to track that separately as #286

**Comment by jwirfs-brock** [comment]
This looks good.
