### ISSUE TITLE
explore page: story images not wired in

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#201]

**Comment by ghing** [comment]
@patternleaf This happens through the API.  Let me know where you're at with the general featured image implementation and I'll wire this in.

**Comment by patternleaf** [comment]
@ghing this is working now, yes?

**Comment by ghing** [comment]
@patternleaf This will come in partially with the pull request I'll send you shortly.  I just finished merging the conflicts (they were minor, mostly related to wiring in the images).  I think the cropping/scaling logic needs a little work still.  Can you tell me where featured images are shown and what sizes they need to be so I can clean this up?

**Comment by patternleaf** [comment]
ok, well here are current sizes. they may not be a consistent aspect ratio, so we should perhaps tweak the markup/style if needed so that we can have a few consistent sizes.

story_detail.html: 490x294
homepage.html, "featured on floodlight" carousels: 335x197
homepage.html, featured projects and featured stories: 335x197
banner on homepage.html: dynamic, probably don't need to be larger than the 335x197 size
project_detail.html, main image: 222x132
project_detail.html, "featured story": 150x89
project_detail.html, "recent stories list":65x39

here are my suggestions:
490x&lt;height>
335x&lt;height>
222x&lt;height>
150x&lt;height>
65x65 cropped

i don't know: do we have any use cases for an image that's bigger than 490w?

**Comment by ghing** [comment]
Closing this as the story images are now wired in, but often scaled weirdly.  I'm tracking the image scaling separately at #282
