### ISSUE TITLE
explore page: no modal window story viewer

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#203]
note suggestion over email: use BigScreen JS library to implement a button for full-screen view, launched from modal window view. http://brad.is/coding/BigScreen/

**Comment by ghing** [comment]
Do you mean on the story detail page?  I don't know if we ever intended to launch the story viewer directly from the explore view.  Did you find documentation that said differently?  

On the story detail page, it looks like the viewer is launching, albeit a bit messed up.  To me the problems look like it's an issue of the z-index of the menu and the modal.  

BigScreen looks cool, but it looks like it requires pretty recent browsers for support.  So, I'd just have the viewer launch in a new tab/window for now.

**Comment by patternleaf** [comment]
i did indeed mean story detail page, and yes, the actual launch is now working.

> BigScreen looks cool, but it looks like it requires pretty recent browsers for support. So, I'd just have the viewer launch in a new tab/window for now.

sounds good. i'm going to close this and open a new one for the z-index issue.
