### ISSUE TITLE
explore page: slight "ghost" popup when clicking on filter

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#206]

**Comment by ghing** [comment]
@patternleaf, is this still an issue?  Can you post a screenshot if it is, otherwise close it.

**Comment by patternleaf** [comment]
The main thing I was seeing was something that is still happening, but seems not to persist the way it was—I wasn't able to get a screenshot of it. A related artifact is this, which is pretty minor:

![Screenshot 4:1:13 1:59 PM](https://f.cloud.github.com/assets/73439/325330/17b28afc-9b07-11e2-9487-5b61b9ed69a3.png)

I think it's still an issue, but quite low in priority.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot.
