### ISSUE TITLE
story detail page

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#208]
throwing these in one issue. the page needs some work.
- image not wired in
- related stories not hooked up
- needs some more styling love in general

**Comment by jwirfs-brock** [comment]
The Story Detail page will actually more closely reflect the prototype, which you can view here: http://clients.inovdesigns.com/floodlight/story_detail.php

Main differences between the prototype and the design comps:
1. We won't have the "related stories" section (we haven't implemented it yet).
2. We'll go with the layout of the design comp (3 rows of 2 columns). Keep title, summary, featured image on top, metadata on the second row. Where "Related Stories" is on the design comps, we'll have "How Can You Help?" (Call to Action) instead.
3. On the bottom row, "Connected Stories" will go on the left and "Comments" will go on the right.

**Comment by patternleaf** [comment]
up-to-date in templatizing branch. @jwirfs-brock, assigning to you for review and closing once these changes are available to you. (currently the staging server with this branch is not in a good state).

**Comment by jwirfs-brock** [comment]
@patternleaf  Which version should I be looking at for this -- dev?

**Comment by patternleaf** [comment]
yes, though i don't see one that has been filled with data.

**Comment by jwirfs-brock** [comment]
I'll create a test story for review and close when I'm done.

**Comment by jwirfs-brock** [comment]
@patternleaf  The general layout looks good, with just a couple minor things:
1. We don't want it to say "Explore Floodlight" as the main title. Instead, can the story title go there? If we can do this, it won't be necessary to also have the title above the byline and summary. 
2. This page doesn't have breadcrumbs. Can we activate those? (So Home > Explore > STORY NAME)
3. The "View Story"  button should be aligned below the summary, not at the bottom of that container (right now it showed up next to the bottom of the image).

Here's a picture of the suggested changes: https://docs.google.com/file/d/0B82exFJJWyJqRlYyc1Y3U3hja2s/edit
(The original story is at: http://dev.atlas.terrorware.com/stories/checking-out-the-story-detail-page/)

I think you and Geoff are still working on the featured image sizing, so I won't comment about that on this issue.

**Comment by ghing** [comment]
@jwirfs-brock What's the title of the non-connected story (and the URL of its story detail page) that's still getting the "Contribute to this story" button?  I wasn't able to replicate this when I created a non-connected story.

**Comment by jwirfs-brock** [comment]
Sure thing. It's called "Checking out the story detail page" and is at:
http://dev.atlas.terrorware.com/stories/checking-out-the-story-detail-page/

**Comment by patternleaf** [comment]
> We don't want it to say "Explore Floodlight" as the main title. Instead, can the story title go there? If we can do this, it won't be necessary to also have the title above the byline and summary.

ok, got this.

> This page doesn't have breadcrumbs. Can we activate those? (So Home > Explore > STORY NAME)

i'm not sure why breadcrumbs wouldn't be rendering. the breadcrumbs template tag is in there in the normal place. @ghing, is the story detail page outside of the normal path structure? (i'm not sure how that stuff works.)

> The "View Story" button should be aligned below the summary, not at the bottom of that container (right now it showed up next to the bottom of the image).

this is a css collision. we'll be cleaning that up shortly. (cf #291)

**Comment by patternleaf** [comment]
just a note: 

> The "View Story" button should be aligned below the summary, not at the bottom of that container (right now it showed up next to the bottom of the image).

this should be fixed (via 773be8c) when the staging environment is next updated.
