### ISSUE TITLE
When previewing a story from the Story Builder, you can't get back to Builder

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#209]
When you click "Preview" from within the Story Builder (during the "Build" step), the preview is opening in the same window/tab as the Builder.  The browser's "back" button won't take you back to the Builder, so there is no way to get back without going back to the homepage.

Either the preview should open in a new tab (the way it does when you preview during the "Review" step), or it should have some kind of "back to the Story Builder" link.

**Comment by ghing** [comment]
I think opening it in a new tab/window is the most straightforward way to go.

**Comment by jwirfs-brock** [comment]
Let's open the preview in a new tab.
