### ISSUE TITLE
Can't go directly from "Build" to "Review" step -- link only works if you click through "Add Data"

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#212]
I'm not sure if this is a bug per se, but right now, you have to go through the "Add Data" stage to get to "Review."

When you click on the "Review" tab at the top (from being in the "Build" step), the browser tries to go to the review url (http://staging.denverchildrenscorridor.org/en/build/review/), but gets hung-up/stalls.

**Comment by bpawlak** [comment]
Did we agree to move "Add Data" _to_ the review step?  If so, then the flow should go from Build to Review as in the earlier versions of the wireframes (before we added the "Add Data" step).  I think this will simplify the flow to users as well.

**Comment by ghing** [comment]
@bpawlak I think the issue is less the separate step and more that the tabs at the top aren't working correctly.

**Comment by jwirfs-brock** [comment]
@bpawlak @ghing The problem is happening both with the tabs and with the buttons. Regardless of whether the "Add Data" set gets moved into Review, you should still be able to skip it and go to the next tab.

This might require a quick discussion, but I actually think you should be able to freely go back and forth between all of the steps in the workflow, even the required one (like the copyright selection). You just won't be able to publish if you haven't checked the copyright agreements.

It's a bit confusing to have both tabs and sub screens within the tabs. We probably want to revisit the navigation. It's not clear that to tag, I have to go to "Share," then click through the copyright agreements screen. We should revisit this work flow.

**Comment by bpawlak** [comment]
Doesn't the button text change based on which of the 4 tabs you're in?  And you should be able to click on the 4 tabs at the top, can't you?

It might seem minor, but once we _do_ get some visual components in place, it might help things.  In the wireframes, I tried to "connect" the story section navigation to the main section canvas and placed the "Add Data" (i.e., Go to Next Step) button outside of that to show that it's separate.  Perhaps by making the top navigation look more like tabs would help, as well.

I'm in meetings until 11:30, but can call you then.

**Comment by bpawlak** [comment]
One thing we might want to consider is finding a way to add additional information to the UI to go along with the "single action" verbs.  Although one possibility is to show more text under each item  (e.g.,:

ADD DATA                      REVIEW
Put some substance        Spell check, consistency
behind your story             and accuracy

that takes up a lot of space at the top of the builder interface.  So perhaps we could address it by providing similar information upon hover?  https://docs.google.com/drawings/d/18kEUZv_TMtRVSSaaQnpVg57T--lfxQybRaC5Rr-sIB0/edit

**Comment by ghing** [comment]
Note that the tabs not working is a bug.  I'm going to try to fix this before the call.
