### ISSUE TITLE
Once you've published a story, if you go back to the Builder, you can't go straight to the "Share" section

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#213]
A common thing a user might want to do it, once they've published a story, go back to the story and unpublish it or change the tags (both things you do in the "Share" step). But when you go back to a story after it's been published (through the "My Account") page, you are by default in the "Build" step. If you click on the "Share" step, everything stalls (the url for share is loaded in the browser, but doesn't go anywhere).

**Comment by ghing** [comment]
Fixed around commit dd306434a7a052275f19e7f89c7306aca6d2ac60 or somewhere.
