### ISSUE TITLE
There should be a "View Story" button on the publish screen in the story builder

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#214]
Once a user has published a story, there should be some kind of link for viewing the story/going straight to the Story Detail page from the "Share Your Story" page.

See screenshot:
https://docs.google.com/file/d/0B82exFJJWyJqc0t6aDg5cmlVaHc/edit

**Comment by ghing** [comment]
Closed by 67a98776a6e7e8ccff02a6b64bedf5a9241a8c98
