### ISSUE TITLE
Byline should indicate that it will be displayed with "By" in front of it

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#217]
When you are editing the Byline in the Story Builder, it isn't clear that whatever you type will be displayed with "By" in front of it (thus you don't need to type "By Jordan Wirfs-Brock..." you just need to type "Jordan Wirfs-Brock").

This could be fixed by adding a "By:" in front of the editable text box.

See screenshot:
https://docs.google.com/file/d/0B82exFJJWyJqQ0xoZnRoSW1lTVE/edit

**Comment by ghing** [comment]
I think that this is what preview is for.  Adding the "By:" in front of the input is something that's totally different from any other input in the builder.  I'm not convinced that it's a good idea to do this.

**Comment by jwirfs-brock** [comment]
That's fine. One of the reasons I suggested that was that, even though it
says, "Click to edit byline," people tend to start typing their summary in
that field. Not sure what we can really do about that. (For an example,
take a look at this story one of our trainees contributed:
http://staging.floodlightproject.org/stories/dava-youth-explore-art-and-technology-2/)
Any
suggestions?

**Comment by ghing** [comment]
Off the top of my head here are some alternate suggestions to putting a By: label next to the input.
- Example name as the placeholder in the input (since we no longer need the click to edit message since it's just a form input).  E.g. "Jane Doe - well actually your name"
- Static text in the review stage that warns users of common mistakes to look out for when they preview their story.

**Comment by jwirfs-brock** [comment]
I like both of these suggestions.

**Comment by ghing** [comment]
Ok.  Give me copy for the placeholder and the review page and I'll make this happen.

**Comment by jwirfs-brock** [comment]
Here's the copy for the review page. I'm going to pass it around to a few
folks and possibly revise, but in the meantime you can take a look:

https://docs.google.com/document/d/1vvcuPqLYzBqqNNCZ0Jx_BNm25BUeRmHNe-63vXgzs-A/edit

**Comment by jwirfs-brock** [comment]
Ok, I'm not so good at placeholder text, but let's try this:

"Examples: Jon Denzler; Laura Frank, I-News; Your Name and/or Organization"
