### ISSUE TITLE
For quotation asset, it's unclear that attribution already includes dash (--)/user doesn't need to enter that in the attribution field

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#218]
For quotation assets, the attribution field is automatically formatted with a dash in front of it (-- Geoff Hing). When you are entering information into the attribution field, it's unclear that this is the case, so a user might enter "-- Geoff Hing," which would look like "-- -- Geoff Hing" when it gets displayed.

**Comment by bpawlak** [comment]
Why don't we remove the -- completely from the builder, then?  Just have them enter a name.  We can still show the -- in the viewer, but the builder is just collecting the name.

**Comment by ghing** [comment]
@bpawlak I think your suggestion of just removing the "--" in the builder is a good one.

**Comment by jwirfs-brock** [comment]
@ghing @bpawlak Ok, let's go with that. I like how it looks with the dashes, but maybe we can include help text below the input box that says "Example: -- Geoff Hing" or something.

**Comment by ghing** [comment]
Solution 2 is to add the "--" before the text input for attribution, though that might look a little weird.  I think the idea of the help text is still confusing because it's not clear whether it's telling users whether they need to include the "--" or it's showing how it should look.

**Comment by bpawlak** [comment]
I don't think we should require uses to put in the dashes... the final render can have "--" before the attribution field, but the user is just entering data.  If they want to put in ::AttributionName and it comes out in the viewer as -- ::AttributionName, they can simply edit it, can't they?
