### ISSUE TITLE
In the Story Builder, you can't move between sections without first closing the help text

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#219]
When the help text automatically opens in the Story Builder, you have to close it before moving to a different section. This is a bit cumbersome, especially if you are returning to a story you have already started to edit and want to jump directly to a particular section.

Is it possible to change this so you can move between sections (using the nav at the bottom) without having to first hit "close" on the help text?

**Comment by bpawlak** [comment]
Can a user still click to "don't show help text" and have that persist?  So that if they come back into the story, the help text doesn't show by default?

**Comment by ghing** [comment]
The "don't show help text" checkbox should still work if users don't want to see the help every time they visit a section or open a story for the first time.  Maybe the solution is to make the toggle checkbox more visible? 

While it's certainly possible to have clicking on the sections in the nav at the bottom also close the modal, I want to make sure this is really the behavior we want before I do it.

**Comment by jwirfs-brock** [comment]
@ghing @bpawlak 

Yes, if you set it so that it doesn't show help text, that persists if you exit the Builder and then return.

And yes, we should make the checkbox more visible.

I was thinking that this applies more to someone who is creating a new story. To me, the logical desired behavior is that clicking on a different section would close out the current help and open the help of the selected section. When people first enter the Builder, they tend to want to browse around a bit before they start editing to familiarize themselves with the template.

**Comment by bpawlak** [comment]
I think the checkbox visibility will come with some style applied.  And I agree with that last statement... it shouldn't necessarily _lock_ users into that section, allowing them, instead, to click around freely.  Perhaps some integration of help text might reduce that need?

**Comment by ghing** [comment]
Closing this since, with the advent of the tour, the help text is no longer automatically displayed.
