### ISSUE TITLE
Soundcloud embed isn't rendering from link

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#220]
I tried to create an audio asset using Soundcloud's "share" link (http://soundcloud.com/inews/long-term-care-for-kcfr-public-radio-day-1).

The information is saved in the asset (i.e., visible when I click "edit"), but the sound file isn't showing up/embedding.

Because the audio asset doesn't have an embed code option, I can't use the Soundcloud embed code instead, which would be:

<iframe width="100%" height="166" scrolling="no" frameborder="no" src="http://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F7879836&show_artwork=true&show_artwork=true&maxwidth=0&maxheight=166&auto_play=false&show_comments=false&color=0003ff&callback=reqwest_0&_=1347036569344"></iframe>

**Comment by ghing** [comment]
@jwirfs-brock This is just a configuration issue.  The soundcloud oembed provider didn't point to the correct endpoint and wasn't enabled.  I updated the configuration. Can you confirm that this is fixed?

**Comment by jwirfs-brock** [comment]
Yup, it's working. Thanks!
