### ISSUE TITLE
Need help text for tagging page

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#221]
We'll need some more specific help text for the tagging page in the "Share" section. It's unclear that you can click in the box to choose a predefined topic.

**Comment by ghing** [comment]
@jwirfs-brock Let me know what help text you want and where you want it to be.  Placeholder text inside the inputs? Text above? Both.

**Comment by jwirfs-brock** [comment]
Yup, I'll provide. There's a related issue about the placeholder text that is appearing inside the input boxes right now [#215](https://www.google.com/fusiontables/DataSource?docid=1YvGRPlpxg7VIIrr9Nx2h5fLKyGRhMZxzo7GGAHU&pli=1)
