### ISSUE TITLE
Interface for editing text for Summary on Story Information page in Story Builder is kind of confusing

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#222]
Without having a box around the text, it is a bit confusing when you are editing text for the Summary on the Story Information page in the Story Builder. For the Title and the Byline, there is a box that appears around the text, but there isn't one for editing the Summary. Because they aren't all consistent on this page, it's a bit confusing (plus, it isn't clear that to stop editing/auto-save you need to click anywhere on the page).

**Comment by bpawlak** [comment]
Should we add "Save" and cancel options to every text-entry container (like we do with embedding or uploading an image?)

**Comment by ghing** [comment]
Note that a border has been added around the Summary field, making it more consistent with the title and byline fields, as well as a "Click to edit summary" placeholder.

There still aren't any save buttons, though I'm not positive that they're needed.

**Comment by jwirfs-brock** [comment]
I'm going to close this one and open  a separate but related issue: The way you edit and then save text is different on the Summary and on text assets, which is confusing for users (you have to click "Save" with text assets and with captions, but not with the Summary -- which trains people to not look for the "Save" button, and then they end up losing their text assets because they don't save them).
