### ISSUE TITLE
Need some sort of visual boundaries around editable containers in story builder

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#223]
Was just going to create a story and on the Story Information section, I hadn't noticed the "Add Data to Your Story" button just floating in white space.  So when I clicked into the containers to edit, it looked as if the button was part of the editing UI.  This is not so much a bug as a need to get the visual templates for the builder UI in place.

https://docs.google.com/drawings/d/10troSh0CFtS837tHD8ZMEw4eHr3089pxmtWcEG9RYhE/edit

**Comment by ghing** [comment]
I believe this was closed by 3b53e227e216ef8002f62115af3945b9cc964c2f
