### ISSUE TITLE
Embedding video - youtube Embed Option problems -- Need to add asset-specific text for videos

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#225]
If a user tries to grab the <iframe> code that appears when clicking "Share" on YouTube, they get an odd 404 error in the iframe and (obviously) can't save the changes.  Not being able to save is a good idea, of course, but I'm not sure how we can prevent people from clicking on the "share" option on youtube and grabbing the iframe code

https://docs.google.com/document/d/1oe-nbsMQX4U2G3mcdDyt6uZ8B1vT_DkXJ3ubIIsoylY/edit

**Comment by jwirfs-brock** [comment]
Maybe we should include some asset-specific help text that tells users they should grab the link instead of the embed code for videos.

**Comment by ghing** [comment]
Right now, if a user selects the video asset, they're only presented with the video URL, so they would have to put the embed code in some other asset type to get the behavior Bill is describing.  Give me copy that will show up in the help drawer explaining that users just have to copy and paste the URL and the video will automatically be embedded and I'll wire it in.

**Comment by jwirfs-brock** [comment]
Here is some instructional copy:

**Embed a video from YouTube or Vimeo.** Find the video on YouTube or Vimeo, copy the URL from your browser, and paste it below. 

Make sure you use the link and **not** the embed code, which looks something like this:
`<iframe src="http://player.vimeo.com/video/43671182" width="500" height="281" frameborder="0"></iframe>`
