### ISSUE TITLE
home page: need to make foundation logo and name links to the detail page (in About).

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#227]
referring to logs and names in "Supporting Foundations" in the lower section.

**Comment by patternleaf** [comment]
@jwirfs-brock @ghing : this issue is about making the logos for the foundations in the little carousel at the bottom of the home page link to a page(s) elsewhere—presumably about the foundations. maybe the "Our Partners" page? 

does that page exist yet? on staging or otherwise?

**Comment by jwirfs-brock** [comment]
Yes, it's at /about/partners

http://staging.floodlightproject.org/en/about/partners/

**Comment by patternleaf** [comment]
great. @ghing, these links would need the cms id for that page—is that right? then the url would be

```
{% page_url "<id>" %}
```

?

if so, and if one of you can look up the id, i'll add in the links.

**Comment by ghing** [comment]
I set the id to "partners"
