### ISSUE TITLE
conf template tag duplicates storybase.context_processors.conf

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#229]
It looks like you might not have stumbled upon this, but early on I had a need to make some of the configuration variables in settings available to the template layer.  I implemented this as a context processor, so the variables are available to the template context as things like {{ storybase_site_name }} for settings.STORYBASE_SITE_NAME.

We can talk about if there's some reason why one method is preferred over the other, but should pick one for consistency.

**Comment by patternleaf** [comment]
do you mean like in storybase_user/templatetags/projects.py?

``` python

    # STATIC_URL should be included via context processor ... not sure best way to do that
    context = Context({ "objects": projects, "more_link_text": "View Projects", "more_link_url": "/projects", "STATIC_URL": settings.STATIC_URL })
```

? 

if so yeah: i just couldn't figure out how to get the context processor to be available to the templatetag code! i'm a python/django noob. i definitely will defer to your opinion!

if you're referring to something else ... i'm not seeing a duplication of STORYBASE_SITE_NAME specifically but perhaps i'm missing it.

**Comment by ghing** [comment]
@patternleaf I'm talking about storybase.templatetags.storybase_tags.storybase_conf  However, on closer inspection, I think this is something that I did a long time ago and not something you did, so I'm going to close this issue.

Regarding the question about STATIC_URL, the reason is that you're using a Context instance instead of a RequestContext instance (see https://docs.djangoproject.com/en/dev/ref/templates/api/#django.template.RequestContext).  RequestContext includes the context processors defined in the settings.  However, RequestContext requires a request object as a parameter and I'm not sure if you can fake it by passing None, so that might not work in this case.

I think the best way to deal with this is to support takes_context in the template tag and use that as the starting point for the context for this particular template.  That should have the context variables from the upstream context (including things like STATIC_URL).  See https://docs.djangoproject.com/en/dev/howto/custom-template-tags/#simple-tags and read down to the section on takes_context
