### ISSUE TITLE
Staging site loading very slowly in IE9

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#230]
I'm not sure if this is an IE9 issue, but yesterday I was walking through Floodlight with a Piton staff member and the staging site (both the home page and the story builder) was loading painfully slow in IE9. WIth the story builder, after several minutes it still hadn't loaded the template selection. When we switched over to Chrome, everything worked fine, so I don't think it was the connection.

**Comment by ghing** [comment]
I couldn't replicate the home page loading slowness on staging.  

The builder failing to load is a result of IE's console object having no debug method.  We can fix this by adding one.  See http://msdn.microsoft.com/en-us/library/dd565625%28v=vs.85%29.aspx

**Comment by ghing** [comment]
This fix addresses the reported issue with IE9 (the template selection not loading).  However, in the process of debugging this, I've found some other issues with IE9 that I'll have to figure out.
