### ISSUE TITLE
When adding a link in Story Builder text editor "OK" and "Cancel" buttons need to be more prominent

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#231]
This is a styling issue. When you are adding a link to a text asset in the Story Builder, the "OK" and "Cancel" buttons, which you have to submit to save the link, aren't very visible. The placement of them is also non-intuitive.

Here's a screen shot: https://docs.google.com/file/d/0B82exFJJWyJqQUc3MDZreG1OUXc/edit

**Comment by ghing** [comment]
I'd say this is closed as of 38a71daa4b3ba3331faf910cc9dfc9ac63c67e4b.  It has been staged.  I'm assigning to @jwirfs-brock for review.

**Comment by jwirfs-brock** [comment]
In Chrome, I'm noticing some strange behavior with the link button in the Summary. The button isn't clickable (I don't get the hand icon when I hover over it, and when I click I'm not seeing the box to add the text for the link).

The link button is working fine in text assets. This seems to be only happening in the Summary. I was not able to reproduce it in Firefox.

**Comment by ghing** [comment]
I changed the way that the markup for the icons to address the [issue](https://github.com/PitonFoundation/atlas/issues/231#issuecomment-11631797) that @jwirfs-brock ran into in commit 6baafa2 and tested the updated editor icons and the add link "dialog" buttons in Internet Explorer as well.
