### ISSUE TITLE
In Story Builder, there is no way to go back to the template selector once you've chosen a template

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#232]
Once you've selected a template (first step of the Story Builder) there is no way to go back and change your template selection. This is ok (we don't necessarily need to add the ability to do that), but there is no clear indication to the user that this is what's happening. There is no way for a user to tell that, to change their template selection, they have to exit out of the Story Builder, re-enter and create a new story to change the template.

**Comment by ghing** [comment]
Some analysis for this issue is at https://docs.google.com/document/d/175lJVoyt8UBFPSgMOiKoKaEobZVd_tC5DBi9AanFwPU/edit
