### ISSUE TITLE
In the Story Builder, it's unclear that to edit the next section in your story, you have to use the navigation at the bottom.

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#233]
Can we maybe put a "next section" button somewhere? Even if it's redundant, I think it might help the user understand the work flow.

**Comment by ghing** [comment]
I agree.  Can you coordinate with @bpawlak to decide where this should go.

**Comment by bpawlak** [comment]
I think moving between sections is something that the users will be exposed to in the help information and training.  In fact, we could look into using something like this: 

http://tympanus.net/codrops/2010/12/21/website-tour/  
or 
http://www.zurb.com/playground/jquery-joyride-feature-tour-plugin

to provide that brief introduction.

The bigger issue for me is still the placement (and labeling) of the "Add Data to your Story" button.  Where it currently sits makes it look like it's just floating there, or that it could be a next step - but it's not related to the next section movement...

**Comment by jwirfs-brock** [comment]
@ghing @bpawlak 

Yes, definitely agree that we need to adjust the "Add Data to your Story"
section, both in where it appears on the Builder and hot it fits into the
workflow. I walked through the Builder independently with Laura Frank and
Maisha Pollard, and I brought up this issue with them.

They both favored keeping it where it was in the workflow, but changing
what it was called, and making it clearer what you do in that step. They
liked having it, but thought it should be framed differently. Instead of
"Add Data" they viewed it more as "Add References/Sources" or "Add
Evidence." So, you can embed data tables and visualization in the story,
but this is where you link to the full source. It's more like an appendix,
but we want to make that concept seem less academic.

Also, I really like the tour links. Is this something we could easily implement?

**Comment by ghing** [comment]
This is fixed as of 4ba035ab8194bc1dd470b3bd2072ac2774a74619 by moving the navigation to the top and making a collapsible version of the story section list.
