### ISSUE TITLE
about page content/layout changes

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#241]
from @jwirfs-brock 

Here are the changes to the "About" page. Let me know if you'd also like me to log them in GitHub. Generally, the structure of it looks good now. 

The "How It Works" section (which is forthcoming) will be a single column section (with an image) that goes below "The Vision" and "Our Partners."
Line break in top sub-header (under "About") needs to be moved so that it looks like:
Floodlight is about two things: storytelling and positive change. (break)
Our goal is to help you use the first one to achieve the second.

The Vision - change subheader to:
We can't change what we can't see. But together, our
stories can illuminate issues that matter.

Partners - move line break in subheader and change capitalization:
Created by impassioned storytellers, (break)
data geeks and community change agents.
The Vision doesn't need the "Read More" link
The "Read More" link on the "Our Partners" page goes to a general content page (copy forthcoming)

Eventually, we may want to add general content pages for "The Vision" and "How It Works" that have things like videos -- is that hard to do later, in terms of updating the side nav? If we need placeholders, we can make them now (they just aren't really necessary until we have more content to put there).

Let me know if you have any questions.

**Comment by patternleaf** [comment]
these changes are in the templatizing branch. there is some attempt at making reasonable CMS blocks so that all this content can be overridden per-page. the general layout is:

```
one column top content (with hr underneath)
two columns middle content
one column bottom content
```

if desired you can override the middle and bottom content with blanks and only use the top content (though this will currently leave some empty markup on the page, which isn't great.

> Eventually, we may want to add general content pages for "The Vision" and "How It Works" that have things like videos -- is that hard to do later, in terms of updating the side nav? If we need placeholders, we can make them now (they just aren't really necessary until we have more content to put there).

currently, the sidebar nav menu is auto-populated with links to children of 1st-level pages in the CMS page tree. so if "About" is under the "Home" page and you make a new page under About called "How it Works", this will be found at the url /about/how-it-works and a link to it will show up in the sidebar of the About page, and all its children, and that link will be active (have a little arrow next to it) when on the How it Works page.

if you then add a "Our Partners" page under the About page, a link to that page will live in the sidebar, too, and when you visit Our Partners, that link will be active.

@ghing, @jwirfs-brock: does that sound right?

**Comment by patternleaf** [comment]
@jwirfs-brock, this is now available on dev. assigning to you for review.

**Comment by jwirfs-brock** [comment]
Looks good. Geoff just showed me how to add and edit child pages, so I should be able to update the content here once it's on staging.
