### ISSUE TITLE
Section titles in builder

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#243]
This is an issue broken out from #216 where @jwirfs-brock asked:

> Also, instead of displaying "New Section" let's display "Click here to edit your section heading" 
> (similar to how the title is displayed Story Information section).
> 
> Also, if someone doesn't edit the section title for a new section, can we have it not display, rather than > have it display the unedited title?

**Comment by ghing** [comment]
@jwirfs-brock Is this just for newly added sections ones added by the user (and not ones copied from the template)?  If so, this is easy.  If it's for any section title, that's a lot harder, but possible once I merge in the connected builder changes.  Please clarify.

**Comment by jwirfs-brock** [comment]
Ideally it would be for all sections, including new ones. Couldn't we just
fix this by editing the story template titles?

**Comment by ghing** [comment]
@jwirfs-brock We can change the prompt to whatever we want, but the hard part is telling if the title has been edited or not.  

When a template is selected, the builder makes copies of each of the template sections, including their title, into the new story.  After that, the story doesn't have any knowledge of the template, so there's no way of telling whether the stored section title for the story matches the template or if the use has edited it.  This is a little easier with sections  added to the story by the user (and not from the template) because the title of "New Section" is arbitrary and the same for all new sections.  This could easily be changed to an empty string, and then the builder can check if the section title is empty or not and change the prompt in the builder or hide the title in the viewer.

Part of the connected story builder is the requirement of specifying asset types in the template.  This requires storing the relation to the template section with each of the stories section so that the original asset type can be retrieved, even after the user has exited and re-entered the builder. With this relation, we can check if the section title matches the template title and know whether the user has edited it or not.

I can implement this functionality for new sections (ones added by the user) real quick, or wait until I finish the connected builder and do it for all sections.  Let me know if I should do the intermediary update.

**Comment by jwirfs-brock** [comment]
I think this was covered when we updated the way untitled sections are displayed in the table of contents. Closing.
