### ISSUE TITLE
Placeholders getting cut off in tag view in builder

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#245]
In the "Tag" step of the builder, when the view initially loads, the placeholder text in the taxonomy inputs gets cut off:

![Screenshot of placeholder text getting cut off](http://i.imgur.com/bWoqD.png)

After clicking in the input, the placeholder text is fully visible.

I think this is related to https://github.com/ivaynberg/select2/issues/291

**Comment by jwirfs-brock** [comment]
I'm still seeing this as above in Firefox. In Chrome I'm not seeing the placeholder text at all until after I click inside the field. Then, after clicking away from the drop down, the text shows up.

**Comment by ghing** [comment]
Closed as of ae739e6, live on staging, assigning to @jwirfs-brock for final review.

**Comment by jwirfs-brock** [comment]
This looks good in both Chrome and Firefox.
