### ISSUE TITLE
Add “Save” button to upper tool bar

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#246]

**Comment by jwirfs-brock** [comment]
Note that we decided to add a "Save" button in the Builder, but didn't convey that to Geoff Thomas, so it isn't incorporated into the design comps. I suggest having it in the top orange bar. @bpawlak @ghing does that work, or do you have another suggestion?

**Comment by bpawlak** [comment]
Yep.  Should be near the last saved message...

**Comment by ghing** [comment]
There's not going to be enough space to put it near the last saved message because we're adding those next/previous buttons to scroll through the workflow sections.

**Comment by jwirfs-brock** [comment]
What about in the orange bar, where the "Help" used to be?

**Comment by bpawlak** [comment]
As long as it looks like a button and not just a link.  Could we moved the "last saved" message to the thin black footer bar?  b/c we already have a "Story saved" green bar that appears and fades away

**Comment by ghing** [comment]
@bpawlak, @jwirfs-brock The last saved message doesn't really fit very well in the layout once we add the next/previous buttons.  It also seems incongruous in the workflow bar.  Moving it to the footer is one solution, but I don't really like it because it's just one more thing for users to look at in a different place.

To me it seems like the job done by the last saved message is that it reassures users that the story has been saved.  It seems like adding an explicit save button helps with that.  Could we just make the last saved message a tooltip for the save button?  We could also have some feedback on the Save button when the story is auto-saved to reassure the user.

**Comment by bpawlak** [comment]
I think the tool-tip idea works.  We could also just simply change the color of the "last saved" message for a brief time and then have it return to white.  When the user clicks the save button, they get a small spinner and when the save is done, the "last saved' message briefly changes color and then returns to normal.

**Comment by ghing** [comment]
@bpawlak I think the big issue for me is trying to get rid of the last saved timestamp.  What if on save, the button temporarily gets replaced with a last saved message before fading into a button?

**Comment by bpawlak** [comment]
I'd like to have some way to persistently show when a document was last saved, if possible... I see that feedback as a good reminder to users that they need to save.  Of course, with our auto-save functionality, it may not be _as_ necessary.

**Comment by jwirfs-brock** [comment]
Can we have both the last saved message that fades into a "save" button,
and a tool tip that shows you the last saved time stamp when you hover over
the save button?

That solution allows us both to conserve space and to give users feedback
whenever the auto-save is happening.

**Comment by ghing** [comment]
Demo of this is on dev.

**Comment by ghing** [comment]
@patternleaf added nicer styles for the button. I think this is done now.  Closing.
