### ISSUE TITLE
Form styling looks bad

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#248]
Examples:

/contact/
/accounts/login/

I see that the Formalize CSS was commented out.  Was this breaking something, or did you just comment out all the old CSS to have a clean slate?  Adding it back might be a helpful start.

Also, there are a few form styles in some of the images from the designers. I think the button styles are the biggest things.  

I think form styles are a good place to start using LESS since I'll probably want to include some of these in the builder/viewer.

**Comment by patternleaf** [comment]
yeah, Formalize was doing strange things to page layout. i added some super-simple form CSS (via LESS) to minimally clean up the contact and login pages. will try to match form style in the everything image next.

**Comment by patternleaf** [comment]
should be better on the templatizing branch. assigning to you for review, Geoff.
