### ISSUE TITLE
No padding on container for base_content  block in base.html

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#252]
In the wireframe template, the base_content block was wrapped in a div that provided padding/centering for the content.  So, base.html could be used as a one column template.  This is what I did to implement templates for things that didn't have a fancy layout, e.g. the one for the login page: /accounts/login/ and a bunch of others.  

The way the templates are implemented now, base_content contains some structural divs that wrap the actual content.

While I'm not totally opposed to defining a one column template with a specific block, and doing a search and replace on all the templates that I've made that shove stuff straight into base_content. 

One thought: does that .shell div go in base_content in all the templates you've made?  Could that instead be moved into base.html to wrap base_content?

Let me know what you think.

**Comment by patternleaf** [comment]
> One thought: does that .shell div go in base_content in all the templates you've made? Could that instead be moved into base.html to wrap base_content?

yes, i think that'll be fine.

**Comment by ghing** [comment]
This looks a lot better. Will anything break if I give the .shell style a min-height and a bottom padding?

**Comment by patternleaf** [comment]
possibly it could. i think the shell is used for breadcrumbs and possibly other blocks of content, though in those cases i'm sure there are other (if not better) ways to accomplish what .shell does. as a quicker fix, would adding those things to #main do what you need?

**Comment by ghing** [comment]
Yes, looks like adding it to #main will do the trick and is actually what I
want.  Is it okay for me to add that?

On Wed, Sep 19, 2012 at 6:20 PM, Eric Miller notifications@github.comwrote:

> possibly it could. i think the shell is used for breadcrumbs and possibly
> other blocks of content, though in those cases i'm sure there are other (if
> not better) ways to accomplish what .shell does. as a quicker fix, would
> adding those things to #main do what you need?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/PitonFoundation/atlas/issues/252#issuecomment-8711993.

## 

Geoffrey Hing
geoffhing@gmail.com
773.969.6436
http://geoff.terrorware.com/
Twitter: @geoffhing

**Comment by patternleaf** [comment]
go for it.
