### ISSUE TITLE
Styles for sidebar sub-navigation

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#256]
Are there styles for sidebar sub-navigation, e.g. in the left hand side at /accounts

There's some design treatment for this shown in the "everything" design comp: http://imgur.com/aFlR5

Although, I almost feel like it would be better to use the highlighting style that is used for the different foundations rather than that triangle bracket in the comp.

**Comment by patternleaf** [comment]
they're based on a list with class "sibling-nav". 

``` css
.sibling-nav li a { ... }
.sibling-nav li.selected a,
.sibling-nav li a:hover { ... }
```

if it helps, they're compatible with cms menus, eg:

``` html
<ul class="sibling-nav">
    {% show_menu 1 100 0 1 %}
</ul>
```

**Comment by ghing** [comment]
This still isn't implement for the account management pages.  I'm taking this ticket and will assign it back to @patternleaf if there are changes in the styles that need to happen to make it work for both CMS generated menus and the ones in the account section.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot.
