### ISSUE TITLE
tab key ordering

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#261]
On http://dev.atlas.terrorware.com/en/build/ if you go to the very first section and click into the title, hitting the tab key takes you to the summary field instead of the byline.  While of course many of the fields are optional (a byline isn't required), the logical tab ordering should likely be top-to-bottom on simple layouts.

**Comment by ghing** [comment]
This particular tab key issues appears to have been fixed as the builder design has been refined.  This doesn't necessarily mean there aren't any other tab ordering issues, but I'm going to close this and open new issues for other particular instances.
