### ISSUE TITLE
How to handle publishing incomplete stories

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#262]
If a user creates a story and doesn't put their own content in one of the sections, the story still gets published with "Element 1, Element 2, Synthesis, etc." sections in the final result.  Are we planning on checking for "empty" story sections in the review step?  If not, is there a way to automatically remove story sections for which the user hasn't provided any of their own content?

http://dev.atlas.terrorware.com/stories/this-is-a-title/

**Comment by jwirfs-brock** [comment]
For now, we should not display the titles of empty sections.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot. Probably not applicable in new pivot.
