### ISSUE TITLE
Disappearing assets

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#265]
From Jon: I've been noticing that when the stories are moved into the builder they erase the assets. 

When a story was uploaded before the builder was active, the slides were not given layouts.  When I am asked to give a layout the assets no longer appear in the story.  This seems to be something that only my stories will have issue with due to the builder.  When I re-paste the text or asset there is no issue, just a bit more work on my side to do with the newly edited pieces.  I just started seeing this issue this morning, and had re-uploaded all the assets so far. 

Examples: 
http://staging.denverchildrenscorridor.org/stories/the-poet-athletes/

http://staging.denverchildrenscorridor.org/stories/eating-your-own-dog-food/

**Comment by ghing** [comment]
@tekhneco Did Jon already start fixing some of these?  It looks like some of them are fixed, maybe by him just going through and re-assigning assets or making new versions of the stories?

I was able to open both of those stories in the builder. Is he talking about the behavior when changing layouts?  The assets do disappear but can be dragged back from the "Assets" menu.

I realized that there's no way in the Django admin to assign an asset to a container, so I think I should maybe add that.  Then he should be able to go through and assign assets to containers in the Django admin and then the story should open fine in the builder.

**Comment by wendynorris** [comment]
Forwarding to Jon so he can respond to your questions directly.

**
_wendy norris http://about.me/wendynorris_
 ceo + founder :: tekhne media, inc
 http://tekhne.co/a digital information and media consulting collective
720 281 9378 :: mobile

*\* http://about.me/wendynorris
*
*

---------- Forwarded message ----------

**Comment by ghing** [comment]
It looks like there is already a way to set the container in the Django admin.  It is just scrolled way-off screen due to #270.  Jon should scroll to the right and set the container of his assets before trying to open the story in the builder.

**Comment by wendynorris** [comment]
When I re-create stories in the builder everything is fine.  This seems
like what will have to be done.  I will be making new stories with the old
assets, and then go back and delete the old stories.

**Comment by ghing** [comment]
I think it's actually easier to just go in and assign all the assets to containers in the admin, then edit in the builder.  Can you tell him to ping me on gchat and maybe we can walk through this together to figure out the best option?
