### ISSUE TITLE
Would like to have HTML editor visible for Byline

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#267]
On the story information section within the Story Builder, can we expose the HTML editor for the Byline? Users have mentioned that they'd like to add links into the Byline (for example, if they mention their organization).

**Comment by ghing** [comment]
@jwirfs-brock is this something that we're still considering?  Would it be better to implement a feature where organization names automatically get linked when displayed in the viewer instead of adding complexity in the UI?

**Comment by mgrayinnovation** [comment]
Taken care of under "related stories" during Pivot. Moved to index of issues for reference during Pivot.
