### ISSUE TITLE
Problems with HTML editing in Story Builder on iPad

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#268]
We tested the Story Builder on iPads at The Denver Foundation. Great news -- for the most part, it was a good experience and Floodlight performed well.

We ran into a few issues while trying to edit text within the Story Builder, specifically while editing the Summary. It seems that the iPad has it's own text editor, which includes things like bold, italicize, add link, etc. When a user selects a block of text on the iPad, the iPad text editor pops up, but then won't let the user get back into the text box without leaving the web browser and coming back.

This isn't high priority, because most our target audience will be using desktops, but it's something to be aware of for the future.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot.
