### ISSUE TITLE
When users create a new account, log in, or click "My Account" they should be taken to "My Stories"

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#269]
Right now, when a user goes to "My Account" (either my clicking on the My Account tab, logging in, or signing up), the default screen is the Account Info (which has the email address and connected social media accounts). Several users have been confused by this screen (and thought it meant that they had to change their email.)

It makes more sense to have this default to the "My Stories" section. For users with a blank story list (or even for all users), we should have a big-ass-button that goes to the Story Builder.

**Comment by ghing** [comment]
@jwirfs-brock, In @bpwalak 's prototype, there is sort of accounts landing page.  Currently what shows up at that path is the Account Info page, but we can move that to the a sub-view (like change password).  

So, you should let me know how things should be organized in general in that accounts section:

Should there be a main landing page like http://clients.inovdesigns.com/floodlight/account.php? What goes there?

Should the e-mail and connected accounts be moved into a separate views?

If this all happens, should the default destination be "My Stories" or the account landing page?

**Comment by jwirfs-brock** [comment]
Eventually, we'll have more features in the accounts (managing
projects/organizations, managing the profile pic, etc.), and at that point
it will make sense to have an account landing page. But for now, the
majority of what users will be doing is authoring stories and managing
their stories, so I just wanted to make sure that we are supporting that
behavior until we build in more features.

Account Info is already in the side bar, so users will still be able to
access that (without us moving it into a sub-view of change password).
Can't we just set it so the "My Account" path points to "My Stories" instead of "Account
Info"?

**Comment by jwirfs-brock** [comment]
As I was looking at this again, another option is that we could point a user back to the home page after logging in. The main point is that going to that "Account information" page with the change email address stuff right up front is a bit jarring, and is confusing people.

For now, let's just have it point to "My Stories" (until we build a more sophisticated accounts page). 

People will only need to log in if they want to enter the builder (or if they want to comment, but that just redirects them back to the comment section), so sending them to the "My Stories" page seems logical.
