### ISSUE TITLE
Copy changes for home page main/top slider

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#273]
Just a few changes. If this is something I can do myself in the template, let me know and I'll fix it:
- There's a small typo on the "Build a breakthrough story" slider: "Explrore Stories" needs to be "Explore Stories"
- On the "See and show your community in a new light" slider, let's make "Because what we can’t see, we can’t change" a link to the Explore page.

**Comment by patternleaf** [comment]
i updated this in my branch. the content that's there ultimately be overridden via django CMS admin.

**Comment by jwirfs-brock** [comment]
Great, thanks. I haven't yet played around in the django edit mode in the
templated version of the site. I'll be doing that a bit today.
