### ISSUE TITLE
form labels can overflow into inputs

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#278]
see, eg, http://dev.atlas.terrorware.com/en/accounts/register/, TOS checkbox.

**Comment by ghing** [comment]
Also http://dev.atlas.terrorware.com/accounts

**Comment by patternleaf** [comment]
also needed: styling for help text.

might need some more flexibility in terms of the amount of space allocated for labels.

**Comment by patternleaf** [comment]
the above issues are addressed. if others come up let's make new issues. closing this one.
