### ISSUE TITLE
Google maps embed from a link in Story Builder not rendering

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#280]
Yesterday, this workflow resulted in the map not rendering, but today it seems to be working fine. Here is what we did:
1. Created a new story using the Sandbox template
2. Edited and saved the story
3. Added a new section
4. Selected a map asset in the new section
5. Pasted in a url from a Google map (example: https://maps.google.com/maps?q=the+denver+foundation&hl=en&ll=39.717404,-104.94632&spn=0.006412,0.013572&sll=38.997934,-105.550567&sspn=6.632135,13.897705&hq=the+denver+foundation&t=h&z=17)
6. After doing this, the information was retained in the asset (i.e., you could edit the link), but the map wasn't rendering inside the container. The corresponding embed code ( <iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=the+denver+foundation&amp;aq=&amp;sll=38.997934,-105.550567&amp;sspn=6.632135,13.897705&amp;ie=UTF8&amp;hq=the+denver+foundation&amp;ll=39.7174,-104.946321&amp;spn=0.017166,0.032015&amp;t=h&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=the+denver+foundation&amp;aq=&amp;sll=38.997934,-105.550567&amp;sspn=6.632135,13.897705&amp;ie=UTF8&amp;hq=the+denver+foundation&amp;ll=39.7174,-104.946321&amp;spn=0.017166,0.032015&amp;t=h" style="color:#0000FF;text-align:left">View Larger Map</a></small> ) was working.

**Comment by ghing** [comment]
I wasn't able to replicate this. Pasting in the URL above caused the map to be displayed in the builder..  @jwirfs-brock, can you try this again and see if it still doesn't work for you? If you're not able to replicate, please close this issue.

**Comment by ghing** [comment]
Tested this again and it seems to be working fine.  I'm going to close this.
