### ISSUE TITLE
logo is missing from header

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#283]
note suggestion from @ghing, if it's not too much work to implement:

"On a similar topic – since most logos are created in vector format I would suggest using an SVG rather than a PNG or JPEG. You can embed the vector with the <object> tag and have the image inside as a fall back (for Internet Explorer). I’ve done that on my website, the result is a beautifully scalable logo. Very noticeable on the iPhone 4 Retina display for example. I’m not sure this conforms perfectly to HTML standards but swings and roundabouts as they say.."

(from comment posted at http://csswizardry.com/2010/10/your-logo-is-an-image-not-a-h1/)

**Comment by patternleaf** [comment]
a .png is now in the templatizing branch. going to hold off on the svg idea for the moment.

**Comment by ghing** [comment]
It seems like it could use some padding/margin at the top, at least at http://staging.denverchildrenscorridor.org/

**Comment by patternleaf** [comment]
oh, i bet it's because i forgot to re-compile the css before committing.

**Comment by ghing** [comment]
No problem.  Send me a pull request when you've done this.

On Thu, Oct 4, 2012 at 9:15 AM, Eric Miller notifications@github.comwrote:

> oh, i bet it's because i forgot to re-compile the css before committing.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/PitonFoundation/atlas/issues/283#issuecomment-9142674.

## 

Geoffrey Hing
geoffhing@gmail.com
773.969.6436
http://geoff.terrorware.com/
Twitter: @geoffhing

**Comment by patternleaf** [comment]
closing this; will add a new issue for the svg thing.
