### ISSUE TITLE
Flickr embed via link doesn't seem to be working in Story Builder

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#288]
Ok, so this is really annoying...

Yesterday I was able to embed images from Flickr using the "share" link. Today, it isn't working on the dev site or on staging. To get an embed from Flickr via a link to work, I have to do a right click --> view image, then grab the url.

For example, this link works: http://farm4.staticflickr.com/3497/3458057235_5c9fcb57c4_o.jpg
This one doesn't: http://www.flickr.com/photos/doug88888/3458057235/

**Comment by ghing** [comment]
It looks like Flickr's oEmbed API isn't returning a valid response for that particular image.  I tried another image (http://www.flickr.com/photos/48424848@N03/5529100087/) and it worked.  This could be some kind of subtle bug in the API, or maybe users can exclude some photos from being embedded somehow, though that doesn't make much sense as you can always grab it in the way that you did.  I'm going to close this issue, but we can revisit it if you start encountering this with lots of images.
