### ISSUE TITLE
Styling of links is different in main container and sub-containers of generic content pages

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#293]
I'm not sure if this is intentional or not, but on staging the links in the top container of a basic two column page (Twocol-Content) are showing up as blue. In the columns underneath (Page-Pull-1 and Page-Pull-2), they are showing up as orange and slightly larger than basic text.

**Comment by patternleaf** [comment]
i've added a class for styling that optional "Read More" link. (class="read-more"). other anchor tags should be styled like the links up top.
