### ISSUE TITLE
When adding a side bar to a two column page, sidebar text overlaps main text

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#294]
See: http://staging.denverchildrenscorridor.org/policies/

The sidebar text overlaps the main page text.

@ghing suggested making the sidebar container a little wider and the main content a little narrower, as well as making the sidebar text wrap.

**Comment by ghing** [comment]
To clarify, give the container divs classes of grid_3/grid_9 instead of grid_2/grid_10 and kill the white-space:nowrap.

**Comment by patternleaf** [comment]
the downside of that is that we then have an odd number of grid slots to use for the main content, which currently wants to be divided evenly for two columns. also it leaves a good bit of space over in the sidebar when the links aren't that large.

could we be ok with just killing the nowrap and maybe reducing the font size on sidebar items?

**Comment by patternleaf** [comment]
(i think we'd need to implement the hover arrows differently if sidebar content needs to wrap, however.)

**Comment by ghing** [comment]
@patternleaf, I think your concern is valid about making the grid odd and having extra space.  I think we could try reducing the size and eliminating the white-space:nowrap.  @jwirfs-brock, how do you feel about this?  I agree with @patternleaf that if text wraps, we should have a different hover event (maybe showing the background of the li or a element in orange and the text in white?).

**Comment by jwirfs-brock** [comment]
Reducing the text size and eliminating some of the white space sounds like
a good option, so let's try that first and see how it looks. If after that
we still need to wrap (which might look a bit weird), and we want to go
with a different hover state, I like the for the orange background and
white text.

**Comment by ghing** [comment]
I think we're going to need to allow text wrapping even if we reduce the font size.

**Comment by patternleaf** [comment]
there is now an attempt at addressing this. could you guys check it out once the relevant environments are updated?

**Comment by jwirfs-brock** [comment]
Sure thing just let me know when the fix is up.

**Comment by patternleaf** [comment]
looks like it's updated now. 

http://staging.floodlightproject.org/policies/

shows wrapped text, but with some margin between items, and a vertically-centered arrow on hover. you may need to do a hard-refresh to see changes.

**Comment by jwirfs-brock** [comment]
That looks good.

**Comment by patternleaf** [comment]
great! gonna close this one.
