### ISSUE TITLE
On two column page, page title and headers in main text container aren't centering at the same point

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#295]
See: staging.denverchildrenscorridor.org/policies/

"Floodlight Policies" and "Floodlight Community Values" are not centered on the same spot. Floodlight Policies is the page title, and Floodlight Community Values is a text item (formatted as h3) in the Twocol-Content placeholder.

**Comment by patternleaf** [comment]
to be clear, you're looking for the page title to move, right? i was following the "everything" comp for those header changes, but i see that the page title is left-aligned with respect to the main content area in the comp, whereas currently the page title is center-aligned with respect to both sidebar and content area.

so: make the page title match the content headers? left-aligned with respect to center area?

**Comment by jwirfs-brock** [comment]
I just looked at the updated styling on staging. Now that the content
headers are left aligned, it looks fine to  have the page title centered.
When the content headers were also centered, it didn't look right, but I
think it's ok now.

**Comment by patternleaf** [comment]
great. i'll close this.
