### ISSUE TITLE
nice to have: svg logo

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#299]
suggestion from @ghing, if it's not too much work to implement:

"On a similar topic – since most logos are created in vector format I would suggest using an SVG rather than a PNG or JPEG. You can embed the vector with the tag and have the image inside as a fall back (for Internet Explorer). I’ve done that on my website, the result is a beautifully scalable logo. Very noticeable on the iPhone 4 Retina display for example. I’m not sure this conforms perfectly to HTML standards but swings and roundabouts as they say.."

(from comment posted at http://csswizardry.com/2010/10/your-logo-is-an-image-not-a-h1/)

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot.
