### ISSUE TITLE
Some stories don't have an auto-selected featured image

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#300]
Some stories that contain images aren't auto-selecting a featured image.

Example: http://staging.denverchildrenscorridor.org/stories/school-funding-an-overview-from-ednews-colorado/

Originally, no featured image was shown. I was able to select an image from the story (it only had one) and set it as a featured image on the Publish/Share page, but it still didn't show up on Explore or the Story Detail page.

In this case, the image is embedded via a url, not an upload (not sure if that matters).

Some other stories that aren't showing a featured image, even though the story has image assets:
http://staging.denverchildrenscorridor.org/stories/the-health-education-gap-crosses-generations-2/
http://staging.denverchildrenscorridor.org/stories/school-testing-an-overview-from-ednews-colorado/
http://staging.denverchildrenscorridor.org/stories/school-vouchers-an-overview-from-ednews-colorado/
http://staging.denverchildrenscorridor.org/stories/the-numbers-of-local-food-access/
http://staging.denverchildrenscorridor.org/stories/the-real-cost-of-soccer/
http://staging.denverchildrenscorridor.org/stories/turning-the-tables-at-hinkley-high-school/
(and others...)

**Comment by ghing** [comment]
It looks like there are a couple of different things going on here:
- http://staging.denverchildrenscorridor.org/stories/school-funding-an-overview-from-ednews-colorado/ - First image asset is an ExternalAsset.  This should work and I'll look into this bug.
- http://staging.denverchildrenscorridor.org/stories/the-health-education-gap-crosses-generations-2/ - Some assets are associated with the section, but not the story. This association should happen automatically, and does in my testing. I'll try to figure out what's going on.
- http://staging.denverchildrenscorridor.org/stories/school-testing-an-overview-from-ednews-colorado/ - External asset. I'll look into this.
- http://staging.denverchildrenscorridor.org/stories/school-vouchers-an-overview-from-ednews-colorado/ - External asset. I'll look into this
- http://staging.denverchildrenscorridor.org/stories/the-numbers-of-local-food-access/ -  First asset with type 'image' is an HtmlAsset. This situation shouldn't happen with stories created with the builder.  I'll go in and manually fix this.
- http://staging.denverchildrenscorridor.org/stories/the-real-cost-of-soccer/ - Some assets are associated with the section, but not the story. This association should happen automatically, and does in my testing. I'll try to figure out what's going on.
- http://staging.denverchildrenscorridor.org/stories/turning-the-tables-at-hinkley-high-school/ - First asset with type 'image' is an HtmlAsset. This situation shouldn't happen with stories created with the builder.  I'll go in and manually fix this.

**Comment by ghing** [comment]
Update:
- http://staging.denverchildrenscorridor.org/stories/school-funding-an-overview-from-ednews-colorado/  - Fixed
- http://staging.denverchildrenscorridor.org/stories/the-health-education-gap-crosses-generations-2/ - Some assets are associated with the section, but not the story. This association should happen automatically, and does in my testing. I'll try to figure out what's going on.
- http://staging.denverchildrenscorridor.org/stories/school-testing-an-overview-from-ednews-colorado/ - Fixed
- http://staging.denverchildrenscorridor.org/stories/school-vouchers-an-overview-from-ednews-colorado/ - Fixed
- http://staging.denverchildrenscorridor.org/stories/the-numbers-of-local-food-access/ - First asset with type 'image' is an HtmlAsset. This situation shouldn't happen with stories created with the builder. I'll go in and manually fix this.
- http://staging.denverchildrenscorridor.org/stories/the-real-cost-of-soccer/ - Some assets are associated with the section, but not the story. This association should happen automatically, and does in my testing. I'll try to figure out what's going on.
- http://staging.denverchildrenscorridor.org/stories/turning-the-tables-at-hinkley-high-school/ - First asset with type 'image' is an HtmlAsset. This situation shouldn't happen with stories created with the builder. I'll go in and manually fix this.

**Comment by ghing** [comment]
It looks like Jon created a number of assets that are HtmlAssets with type image.  These show up fine, but don't work with how featured images are generated.  I think I can make a workaround.

**Comment by jwirfs-brock** [comment]
Yeah, this isn't something that we'll be re-creating in the future, so I
think a workaround should be fine.

Thanks.

**Comment by ghing** [comment]
@jwirfs-brock I made a workaround, which provided a default image in some cases.  However, there are still a lot of stories where Jon created image assets in such a way that it's not really possible to grab a default thumbnail (for instance, the type is 'image' but the content is a Google maps iframe).  Also, the workaround isn't great because it forces the user to download the full-size image when all they need is a thumbnail.

Ideally, we should set an explicit featured image for these stories.  I want to do this in a way that doesn't further create muddy content if at all possible.  I think the right way to do it would be to find stories that don't have featured images, make a note of the URL of the story detail page and also which image should be the featured image.  Then we can convert that one asset from an HtmlAsset to an ExternalAsset and assign it as the featured asset.

**Comment by ghing** [comment]
Update:
- http://staging.denverchildrenscorridor.org/stories/school-funding-an-overview-from-ednews-colorado/ - Fixed
- http://staging.denverchildrenscorridor.org/stories/the-health-education-gap-crosses-generations-2/ - Fixed
- http://staging.denverchildrenscorridor.org/stories/school-testing-an-overview-from-ednews-colorado/ - Fixed
- http://staging.denverchildrenscorridor.org/stories/school-vouchers-an-overview-from-ednews-colorado/ - Fixed
- http://staging.denverchildrenscorridor.org/stories/the-numbers-of-local-food-access/ - First asset with type 'image' is an HtmlAsset. This situation shouldn't happen with stories created with the builder. I'll go in and manually fix this.
- http://staging.denverchildrenscorridor.org/stories/the-real-cost-of-soccer/ - Fixed
- http://staging.denverchildrenscorridor.org/stories/turning-the-tables-at-hinkley-high-school/ - First asset with type 'image' is an HtmlAsset. This situation shouldn't happen with stories created with the builder. This needs to be manually fixed.
