### ISSUE TITLE
Old sidebar menu styles popping up in My Account section

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#302]
Path: /accounts/stories/

Screenshot:

![Imgur](http://i.imgur.com/9jMlo.png)

**Comment by patternleaf** [comment]
i have removed the old styles. it's currently styled as a smaller version of the content pages' sidebar nav, but without the hover/active arrows. i actually think the smaller text looks better here, but if we want it to mimic the content nav menu, the markup will have to change a bit.

![screenshot](https://img.skitch.com/20121010-rcp61tr6wbgg4m235pb59bre96.jpg)

**Comment by jwirfs-brock** [comment]
I think this is good for now. Closing.
