### ISSUE TITLE
In Story Builder, section help not opening in modal window

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#303]
The section-specific help is opening up in the main area of the Story Builder (so where the asset containers are). Closing it works fine and just goes back to the regular Builder view.

**Comment by ghing** [comment]
@jwirfs-brock I think what's actually happening is that the modal div lost the styles that gave it a border and made it seem more popup-like.  I don't think this is a big deal right now as that popup styling will change once we get the design.

**Comment by jwirfs-brock** [comment]
Section help will now go in help drawer. Closing.
