### ISSUE TITLE
No sub-navigation needed on Story Builder page

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#304]
We don't need sub-nav on this page.  Would prefer, instead to see some screen shots of the builder and a big ass "Build Story" button.

http://staging.floodlightproject.org/story-builder/

**Comment by jwirfs-brock** [comment]
I removed the side nav.

I'll wait until the design is implemented to add the screen shots. Still waiting on the design for the big-ass button.

**Comment by bpawlak** [comment]
For the big-ass button, why don't we - for now - simply derive one from what we have.  The primary buttons on the comps and on staging are simply orange rectangles with a slight corner radius applied and Museo text with some shadowing.  Can't we just make that larger and have a couple of different font sizes available?  That way we can size it as it needs to be.

**Comment by jwirfs-brock** [comment]
I think that's a good solution.

**Comment by jwirfs-brock** [comment]
@bpawlak You have better design sensibilities than I do, but how about something like this: http://staging.floodlightproject.org/en/story-builder/

(and soon, the big-ass button)

**Comment by bpawlak** [comment]
I like it!
