### ISSUE TITLE
Contact page configuration

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#306]
I created a "Contact Us" page in the admin, which you can view/edit here: http://staging.floodlightproject.org/admin/cms/page/12/

I included a text plugin, but didn't put in the contact form.

When I clicked "View on site," however, I get this page: http://staging.floodlightproject.org/en/contact/?preview

@ghing I think maybe this is something you already wired up, and they use the same slug?

Anyway, to get the "Contact Us" page squared away, we need to:
1) set up the contact emails (ask@floodlightproject.org, help@floodlightproject,org, preguntas@floodlightproject.org)
2) set up the form (or adjust the existing form) and point it to one of the emails (probably ask@)
3) point the emails to the proper places (ask@ and help@ point to jbrock@piton.org, preguntas@ points to vfigoli@piton.org)

**Comment by ghing** [comment]
/contact is the contact form that was one of the features of a past iteration.  I'll integrate everything when I get done with this builder stuff today.

**Comment by jwirfs-brock** [comment]
Great. That form is exactly what we need. We just need the other text above
it (which is in admin/cms/page/12/ as a text plugin).

**Comment by ghing** [comment]
Closed by df2732bae8c27d8322ac37cbe19ee71fe936f6f2
