### ISSUE TITLE
Explore navigation bar tabs

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#310]
When user scrolls the Explore page, the navigation bar changes from a white background to dark grey. The filter tabs are displaying white corners on the rounded boxes. 

Check the moz-box settings on the individual filter tabs when the new nav bar background color is activated by scrolling.

**Comment by patternleaf** [comment]
> The filter tabs are displaying white corners on the rounded boxes.

looks like some static assets haven't been deployed on staging yet. those filter popups are actually images, though it might make more sense to turn them into css. compare to:

http://deploy.atlas.terrorware.com/en/explore/

@ghing, are there assets/css on staging that aren't up to date with the theme branch?

> When user scrolls the Explore page, the navigation bar changes from a white background to dark grey.

@tekhneco, would you suggest this be, eg, white with a border (maybe mimicking the megamenu border styling)?

**Comment by wendynorris** [comment]
My suggestion is choose the option that is easiest to implement. This is a picky issue but it makes the site look unpolished. A white border is cool with me.

**Comment by patternleaf** [comment]
hey @tekhneco: just to clarify. did you want the background on the filter bar to be white? or are you ok with dark gray and were simply noting its color in relation to the white pixels in the corners of the filters? thanks.

**Comment by wendynorris** [comment]
Dark gray is okay by me for the bar. Just noting the white corners looked
odd.

**
_wendy norris http://about.me/wendynorris_
 ceo + founder :: tekhne media, inc
a digital information and media collective
720 281 9378 :: mobile

*\* http://about.me/wendynorris
*
*

**Comment by jwirfs-brock** [comment]
This seems to be working fine now -- we have a white background with shaded corners around the entire container. @tekhneco Can we close?
