### ISSUE TITLE
Increase featured image margins in list view

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#312]
In the list view of the Explore page, featured images need more bottom margin space to accommodate headline and more left margin space to align with headline and copy.

**Comment by patternleaf** [comment]
i wonder if you were viewing it with stale css. if not, i'm not sure i follow you. here's a screenshot:

![screenshot](https://img.skitch.com/20121011-tg2nmkthpygmcc61syyq32r5qb.jpg)

**Comment by wendynorris** [comment]
Yep, looks like the latest push and a hard refresh fixed the problem. Previously, the headline and summary were positioned under the thumbnail. Thanks!
