### ISSUE TITLE
Explore page - show more link

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#314]
Should there be a "show more" link at the bottom of the initial list of stories that appears by default on the Explore page browse view? 

Currently, users need to scroll back up to click the "show more" link under the story count. They then lose their place among the initial set of stories they've already viewed and can't tell which ones are newly viewable.

**Comment by ghing** [comment]
@tekhneco There is actually an infinite scroll.  I will implement a spinner at the bottom of the list so users know that it's fetching more articles.

**Comment by wendynorris** [comment]
Yeah, that's a little strange. Not sure if you've been working on something a few minutes ago which was affecting the load speed but it wasn't fetching all the stories unless I clicked the "show more" link.

I tried it again. It kind of choked on 20 stories and then stopped. Then loaded 40 and stopped. Then loaded all 51. 

Without knowing that there are more stories loading on the background, I'm concerned readers will go elsewhere without knowing there's more to come.

**Comment by ghing** [comment]
I'll check the performance of the story load.  It's possible that things got a little wonky in terms of detecting when the user scrolls to the bottom. when the template styles were added. 

Instead of a spinner, I think a "Loading more stories message" as users scroll to the bottom will address your issue.  That way, when they scroll to the bottom they know to expect more stories.

**Comment by wendynorris** [comment]
Sounds like a good plan. Thanks!

**Comment by ghing** [comment]
@patternleaf I'm going to take a look at this this morning, but might send it your way once I have a better idea of what's going on.

**Comment by ghing** [comment]
@patternleaf, I've taken a pass at this and assigned it to you in case you want to improve the styling and interactions.  Take a look at 0aca735 to see where the relevant code is in explorer/views.js.

**Comment by patternleaf** [comment]
ok, i did _something_ to it. not particularly attached to the result, but you can check it out on deploy: http://deploy.atlas.terrorware.com/explore/

thoughts for improvement in interaction:
- transparent + fixed position in window (on the bottom half probably)
- keep it where it is, but have it slide down on show and slide up on hide ...

seems ok the way it is now, however.

**Comment by wendynorris** [comment]
I like it.

**Comment by ghing** [comment]
I like it too.  I saw we ship this.  Can you send me a pull request to the weekly-0.1.5 branch?

**Comment by ghing** [comment]
Deployed
