### ISSUE TITLE
Viewed link styling 

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#315]
Is there a compelling reason not to have viewed links styled differently?

**Comment by patternleaf** [comment]
@tekhneco how's it look now? it's fairly subtle, but there is a :visited anchor color.

**Comment by wendynorris** [comment]
Might be a little too subtle for my eyes. I'm not seeing any change.

**Comment by jwirfs-brock** [comment]
As we discussed when we addressed the blue color for general links, we're going with what is currently the viewed link blue (slightly darker shade) for both viewed and unviewed links. Closing this one...
