### ISSUE TITLE
sign in page styling 

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#316]
Is this page supposed to have a left column containing the create account prompt and Twitter/Facebook text links? The email and password text is also off-centered from its input boxes. 

Or should it all be centered as one column? 

http://staging.floodlightproject.org/en/accounts/login/

**Comment by patternleaf** [comment]
> Is this page supposed to have a left column containing the create account prompt and Twitter/Facebook text links?

actually the weirdness is on account of the headers being center-aligned and the text left-aligned. my suggestion would be to make the headers left-aligned (with a little more spacing). i'll attach a screenshot for review.

or better, maybe lower-priority, two left-aligned columns: one for social media, one for regular login. also, icons for the social media logins would be good. i'll make another bug for that.

> The email and password text is also off-centered from its input boxes.

hmm. i'm not seeing this. could you clarify?

![screenshot](https://img.skitch.com/20121015-p2etac9c9c31h52wygtbtg9tu9.jpg)

**Comment by wendynorris** [comment]
Thanks Eric.

I was referring to the large gap to the right of the Email and Password labels and their respective input boxes. It's just cosmetic and not necessarily something to spend time on unless there is a super fast fix.

**Comment by patternleaf** [comment]
ah, gotcha. it's not difficult to tighten that up, no.

**Comment by patternleaf** [comment]
@tekhneco any better? http://staging.floodlightproject.org/accounts/login/

**Comment by wendynorris** [comment]
Cleared browser cache but it doesn't look any different than the screenshot you supplied above, with exception of new Facebook sign-in link. What am I doing wrong?

**Comment by patternleaf** [comment]
i think i see what happened. sorry about that—the screenshot above was my local env. after left-aligning the headers. that change got committed, but not the lessening of space between label and input, despite the commit message for b525009 above.

**Comment by patternleaf** [comment]
@tekhneco here's the current look, on dev:

![image](https://www.evernote.com/shard/s9/sh/ef30c00a-d59f-49bf-b77d-291a0db691d5/848511658243469e73c20f38e19f0d89/res/b0d338d8-8d35-419e-9438-8d213e9a24c4/skitch.png)

better?

**Comment by wendynorris** [comment]
perfect!
