### ISSUE TITLE
Search needs to be hidden

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#317]
Entered keyword "food" (which has plenty of published stories) returns: 

Forbidden (403)

CSRF verification failed. Request aborted.
Help

Reason given for failure:

```
CSRF token missing or incorrect.
```

In general, this can occur when there is a genuine Cross Site Request Forgery, or when Django's CSRF mechanism has not been used correctly. For POST forms, you need to ensure:

```
The view function uses RequestContext for the template, instead of Context.
In the template, there is a {% csrf_token %} template tag inside each POST form that targets an internal URL.
If you are not using CsrfViewMiddleware, then you must use csrf_protect on any views that use the csrf_token template tag, as well as those that accept the POST data.
```

You're seeing the help section of this page because you have DEBUG = True in your Django settings file. Change that to False, and only the initial error message will be displayed.

You can customize this page using the CSRF_FAILURE_VIEW setting.

**Comment by ghing** [comment]
Search currently isn't implemented.  A while ago we talked about initially foregoing search in favor of the explore view.  Implementing search is pretty easy, but I'll need some guidance for what the search results page looks like.  We can just hide the search form initially.

**Comment by wendynorris** [comment]
I guess if we're not going to implement search for MVP, then the form should be hidden. 

Jordan -- do you have a strong opinion one way or another?

**Comment by jwirfs-brock** [comment]
Let's hide the search form for now, and then implement it after launch. We will definitely want to have the ability to search by keyword eventually, but don't have time to do the analysis and implement this feature right now.
