### ISSUE TITLE
Pagination on home page

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#318]
The pagination dots for "Featured Projects" and "Featured Stories" on the front page are not repositioning dynamically based on the length of the summary copy. 

http://staging.floodlightproject.org/en/

**Comment by ghing** [comment]
This came up again a few months back when we redesigned the homepage. This is a result of the default behavior of the cycle plugin.  The dots are positioned so they're below the longest element.

After redesigning the homepage and removing all but one of the sliders on the homepage, and making the slider auto-cycle, I'm not sure if this is a big issue anymore.

**Comment by jwirfs-brock** [comment]
I think the way we've structured the homepage after the redesign, this is no longer a concern. Closing.
