### ISSUE TITLE
Element padding/margin in builder

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#321]
Paragraphs (often used as introductory text in each step of the building workflow) don't have any margin or spacing.  I'm guessing this is because of the CSS reset, but I'm not certain.  This should be probably get taken care of when builder styling is applied, but I just wanted to make sure this cosmetic issue was documented somewhere.

@patternleaf, I'm assigning this to you for now.  Feel free to assign it back if it makes more sense to give it to me based on our strategy for styling the builder.

**Comment by patternleaf** [comment]
@ghing this is closeable at this point, ya?

**Comment by ghing** [comment]
Works for me. Closing.
