### ISSUE TITLE
Style and cleanup interactions for inline help

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#322]
Some background from @jwirfs-brock:

> Here are some details of how it might work:
> - When you click on the "help" icon, the window would open
> - It could open to the bottom section of the asset, so the top (where you can actually add/edit) would >still be visible. Obviously we haven't gotten the final designs from Geoff T. yet, so we don't know >exactly where it would make sense to put it.
> - The box would have a "close" feature, and would stay open until you click on that.
> - I really like the suggestion you make, Geoff, this morning about having a draggable box. That way, if >someone does have a lot of screen space, they can move it off to the side. Or, if it's a side-by-side >layout, they can move it on top of the asset they aren't editing, etc.

**Comment by jwirfs-brock** [comment]
We decided to go with the "help drawer" concept, so I'm closing this.
