### ISSUE TITLE
Explore page nav bar needs increase in left margin

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#345]
Just needs a smidgen of margin added to the left of the topic tab. 

![GitHub Logo](http://tekhne.co/wp-content/uploads/2012/10/Explore-Floodlight-nav-bar.jpeg)
Format: ![Screenshot](url)

**Comment by patternleaf** [comment]
that's strange. there must be some discrepancy in the css on staging. this was addressed a while ago. you can see margin on deploy:

http://deploy.atlas.terrorware.com/en/explore/

i'll make sure the css is up to date.

**Comment by patternleaf** [comment]
addressed, updated, etc, viewable on dev. 

http://dev.atlas.terrorware.com/explore/

note that the # of available pixels is odd, so there's a pixel more on one side than the other. :( let's open another issue for that if necessary.

@tekhneco can you check it out and close? thanks.

**Comment by wendynorris** [comment]
Looks good.
