### ISSUE TITLE
Default featured image for stories with no image assets

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#346]
Originally reported by @tekhneco at #344, in very rare instances, some stories like http://staging.floodlightproject.org/stories/why-we-tell-stories-reflecting-on-july-22-2012/ don't have any image assets, so there's no way to get a featured image for it.

We need some kind of default image in these very rare cases to be shown on the story detail page and explore pages.

This is blocked on getting this featured image from Geoff T.

**Comment by jwirfs-brock** [comment]
We have a default featured image. Closing.
