### ISSUE TITLE
password reset form styling broken

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#350]
see http://staging.floodlightproject.org/en/accounts/password/reset/

**Comment by jwirfs-brock** [comment]
The styling is also broken when you reach it through the "My Account" page: http://staging.floodlightproject.org/en/accounts/password/

A similar styling issue seems to be happening with the Notifications and Subscriptions, too: http://staging.floodlightproject.org/en/accounts/notifications/

**Comment by patternleaf** [comment]
these are addressed, available for review on dev. the notifications and subscriptions page is still a little rough-looking, but is probably passable. if not, @jwirfs-brock please open a new bug. thanks.
