### ISSUE TITLE
password reset result page content contains weird header info

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#351]
use password reset feature, see:

> We've emailed you a link to reset your password. Contact us at Project-Id-Version: Django Report-Msgid-Bugs-To: POT-Creation-Date: 2011-03-15 13:14-0400 PO-Revision-Date: 2010-05-13 15:35+0200 Last-Translator: Django team Language-Team: English en@li.org MIME-Version: 1.0 Content-Type: text/plain; charset=UTF-8 Content-Transfer-Encoding: 8bit if you have trouble or don't receive the email.

**Comment by patternleaf** [comment]
so does the email that is received.

**Comment by ghing** [comment]
@patternleaf, I wasn't able to replicate this in the current codebase. I think it's been fixed.  Can you confirm that you're no longer seeing this and close this issue if it appears to be fixed?

**Comment by patternleaf** [comment]
Confirmed. Closing.
