### ISSUE TITLE
Style form errors in builder

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#352]
Off the top of my head here are the places where these will pop-up:
- When agreeing to the legal stuff in the share/publish step
- When specifying a file/URL/HTML snippet in the asset selection form
- Feedback for not finding an address when specifying a location in the Tag step, though this will probably be styled differently and might be ok as -is.

IMHO this should be styled similarly to form errors elsewhere on the site.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot.
