### ISSUE TITLE
When switching between pages, you see a flash of an unstyled page

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#355]
When going between two pages (example, from "Explore" back to "Home"), an unstyled page briefly flashes before the correct page is rendered. 

This is happening in multiple browsers (Chrome and Firefox).

**Comment by jwirfs-brock** [comment]
Closing because Geoff found the fix.

**Comment by ghing** [comment]
Staging had DEBUG=True in the settings which causes the site to use the dynamically rendered LESS stylesheets instead of the precompiled CSS.  The dynamic compilation of the LESS styles is what was causing the temporary visibility of the unstyled content.
