### ISSUE TITLE
Megamenus need to be wired up to pages (Grow Your Skills, About)

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#356]
These need to be hooked up to new pages (when possible). I'll post a list of the links soon.

**Comment by jwirfs-brock** [comment]
The menu content with links indicated is here: https://docs.google.com/a/piton.org/document/d/1Ip73hw3qrFZG66rCKMZggabj_PVkk5PQZk9XNGwpbg0/edit

I highlighted the items that need the links hooked up in red, and put the id of the link next to it. I wasn't sure whether you can use the id with an anchor in that page (it seems like you wouldn't be able to), but in those cases, the id and the slug are identical.

**Comment by ghing** [comment]
@jwirfs-brock Right now there are still a number of links in the "Grow Your Skills" section that don't point anywhere.  Do you want me to a) leave them as pointing nowhere, b) hide them or c) something else.

**Comment by ghing** [comment]
@jwirfs-brock said to hide them.
