### ISSUE TITLE
On Explore page, "Language" filter is showing up below "Topic" filter

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#358]
The "Language" filter is showing up directly below the "Topic" filter, instead of to the right of the "Project" filter (and the width of the browser window doesn't seem to influence it). 

This is happening in both Chrome and Firefox.

Here's a screenshot: https://docs.google.com/open?id=0B82exFJJWyJqZ0pkaElkM2Zqdms

**Comment by ghing** [comment]
Assigning this to @patternleaf as I think its a result of his most recent style fixes.  I think it is an issue of browser width as zooming out via the browser makes all the filter elements fit on the same row.

**Comment by patternleaf** [comment]
i can't seem to reproduce this. @jwirfs-brock, can you provide a url? and specific browser and OS version? thanks.

also, try doing a hard refresh, if you haven't already.

**Comment by jwirfs-brock** [comment]
Sure thing. I'm still seeing it after a hard refresh.

URL: http://staging.floodlightproject.org/explore/ and also
http://staging.floodlightproject.org/en/explore/ (I'm getting it in both
tile and map view.)

Browsers viewed the bug in: Firefox 15.0.1, Google Chrome 22.0.1229.94 m on
Windows 7; Google Chrome 22.0.1229.92 on Mac OS 10.6.8

Let me know if you still aren't seeing it.

**Comment by ghing** [comment]
@patternleaf Try bumping your resolution down maybe?  I'm running at 1280x800 and see this behavior.  I think the issue is the `body.base-template .shell` div's width being set to 1000px.  If you make it even a little wider (1001px), the filters fit on one line.

**Comment by patternleaf** [comment]
i was able to reproduce on chrome and have a fix in a forthcoming push. weird that it didn't happen in firefox or safari. it was a matter of a single pixel though, as you noted.

as an aside, the available margin to the left and right of the row of popups is an odd number of pixels, so they're going to be just slightly off. :(

**Comment by patternleaf** [comment]
this fix was hanging out on a branch for a while. now staged on dev. @jwirfs-brock can you confirm it's fixed and close?

http://dev.atlas.terrorware.com/en/explore/

thanks.

**Comment by jwirfs-brock** [comment]
Looks good.
