### ISSUE TITLE
Need to set up contact email addresses

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#362]
ask@floodlightproject.org -- redirects to jbrock@piton.org
help@floodlightproject.org -- redirects to jbrock@piton.org
preguntas@floodlightproject.org -- redirects to vfigoli@piton.org

**Comment by ghing** [comment]
Set these forwarders up in the Webfaction panel.  I sent out test messages and they didn't bounce.  @jwirfs-brock, you should re-open this ticket if you don't get the emails.
