### ISSUE TITLE
Need to add Original Aurora and Children's Corridor as places

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#363]
@ghing I have the shape files ready to go for these -- what's the best way to upload those? Is it just a matter of, in the admin, going to Places --> Add place?

We also may want to add other cities/municipalities in the Denver metro area for launch. We have the shape files for those as well.

**Comment by ghing** [comment]
@jwirfs-brock No, there's a server side-script that has to be run (to properly import the shape data when adding the place).  Can you thrown the shapefiles up somewhere and put a link to them in this ticket?

**Comment by jwirfs-brock** [comment]
@ghing Sure. Will putting them on Dropbox work?

**Comment by ghing** [comment]
@jwirfs-brock  Sure.

**Comment by jwirfs-brock** [comment]
@ghing 

Shape files for the Children's Corridor (I'm not sure what geolevel this should be, since it's bigger than a neighborhood but smaller than a city):
http://dl.dropbox.com/u/4667118/Shape%20Files%20for%20Floodlight%20Places/Corridor_Boundary.zip

Shape files for Original Aurora (geolevel = neighborhood):
http://dl.dropbox.com/u/4667118/Shape%20Files%20for%20Floodlight%20Places/OriginalAurora.zip

I still need to take a look at municipalities and decide which we want, so those will be coming soon.

**Comment by jwirfs-brock** [comment]
No longer need to do this. Closing.
