### ISSUE TITLE
Spacing/height of section in Story Viewer

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#365]
Some sections are appearing as if they have a lot of "space" between them. I think this may be because there is a standard section height, and for sections with content that is shorter and doesn't fill the entire section, it looks like empty space.

Here are a few examples:
staging.floodlightproject.org/stories/-14/
(see sections: "Demographic Context" and "Bright Spots and Opportunities")

http://staging.floodlightproject.org/stories/a-place-to-be-a-kid/
(see section: "The Holly" -- which may be because the image isn't rendering)

http://staging.floodlightproject.org/stories/school-vouchers-an-overview-from-ednews-colorado/
(pretty much all sections -- text-only sections have the most obvious extra space)

My suggestion is that the sections appear as tall as their tallest asset. It's fine in the side-by-side sections that have a picture and text if the picture is taller than the text (example: http://staging.floodlightproject.org/stories/the-denver-scores-cup/). But with text-only sections, it should only be as tall as the text.

**Comment by ghing** [comment]
Closed by 5f9ea4edeed370944d91afb06d79a8cb7b0347bf
