### ISSUE TITLE
explore page map view: leaflet popups rendering is quirky

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#367]
seen in firefox 16, OS X 10.7.4: leaflet popup arrow on bottom isn't rendering correctly. also the margins around the content could use some attention.

**Comment by ghing** [comment]
Here's a screenshot of the behavior (Chrome 31.0.1650.63, Ubuntu):

![screenshot from 2014-01-15 08 21 50](https://f.cloud.github.com/assets/110420/1920788/6c95c49a-7df0-11e3-948c-5eef70a12c9e.png)
