### ISSUE TITLE
In Story Viewer, Summary and Call to Action need to have styling that is distinct from other sections

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#369]
In the Story Viewer, the Summary and Call to Action should look special and be distinct from the regular story content.

Some suggestions:
- The Summary and Call to Action could have a grey background (similar to the tile view on the Explore page)
- We could  use a horizontal line below the Summary and above the Call to Action (like the one on the Story Detail page)

@bpawlak @ghing do you have other suggestions?

**Comment by patternleaf** [comment]
@jwirfs-brock, @ghing, @bpawlak this is viewable on deploy at the moment, eg http://deploy.atlas.terrorware.com/stories/-14/. it's a pretty subtle difference at the moment. wondering if maybe a slightly different font treatment might help, too. slightly lighter color? something else?

also might be good to work out how to take out the empty white space above the summary and below the fixed-position header. (it's not trivial or i would've just done it.)

**Comment by jwirfs-brock** [comment]
I like the grey background, but I'd prefer it to be slightly darker. I'm
going to forward this on to Brigid, Piton's in-house graphic designer, to
see if she has any other suggestions.

**Comment by jwirfs-brock** [comment]
Oh, and the new font is so much easier to read!

**Comment by bpawlak** [comment]
I think the white space is actually where the breadcrumbs are supposed to go...

Also, wondering if we shouldn't move the "share this story" button up so that it's at the same level as the "View Story" button?  We also might want to use font-awesome and add the share icon to the button?

**Comment by patternleaf** [comment]
i need to switch branches on the deploy server so i'll post a screenshot here for reference:

![screenshot](https://www.evernote.com/shard/s9/sh/92e8f65a-bd60-49f9-9943-31adcc85d312/6da0bafd6e2eae864e174c039db53d26/res/af45c900-e481-406a-a55c-f8d7264e552b/skitch.png?resizeSmall&width=832)

**Comment by patternleaf** [comment]
@jwirfs-brock, is a mockup forthcoming on this? assigning to you; please assign back as necessary.

**Comment by jwirfs-brock** [comment]
@patternleaf Is the link still the same as above? Right now, I can only view via the screen shot.

I think for now the awkward space is ok (we can deal with that later), but bump up the grey to a slightly darker shade. We don't have a mockup, but I know #BFBFBF is in our color palette.

**Comment by bpawlak** [comment]
Sorry, my comment yesterday (above) is in regards to the story detail page, not the story viewer...

**Comment by patternleaf** [comment]
hey @jwirfs-brock - yeah, i had to switch branches on the server to do some work on it. i can do a temporary merge back in of that code if you need to see it live. let me know.
