### ISSUE TITLE
Navigation in Story Viewer: scroll or side arrows?

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#371]
In the design comps, the "previous/next" links are large arrows at the side of the Viewer: https://docs.google.com/file/d/0B1CQ7Qy70V50SVY5MWZDa3E4Z00/edit

Is it confusing to have them at the side if we also have the a scroll bar (which isn't in the comps)? Do we want them somewhere else (like in the top bar or the footer)?

**Comment by ghing** [comment]
@jwirfs-brock, the position in the design comps doesn't make any sense.

I think they should be in the footer (to match the current position and the position in @bpawlak's original UI designs. 

I'm thinking of just replacing the current next/previous text with the chevrons and tooltips that say something like "Next Section" and "Previous Section"

**Comment by jwirfs-brock** [comment]
I think they'll be fine at the bottom as long as they are styled in a way
that makes them visible. Right now, the blue link on a black background is
virtually invisible.

I like using the chevrons with a tool tip. Let's try it.

**Comment by bpawlak** [comment]
The blue is just the default link color, I don't think there's been any styling applied yet... But chevrons with white text (prev/next) would be more explicit for users.  

By the way, getting an error trying to explore: /srv/www/atlas_dev/venv/src/django-haystack/haystack/query.py in _cache_is_full, line 118

**Comment by ghing** [comment]
@bpawlak is right about the blue just being the default color and there being no styling there.

Are you saying something like:

`< previous | next >`

Also, I fixed the issue with Solr on the dev instance.

**Comment by bpawlak** [comment]
Yes.

**Comment by jwirfs-brock** [comment]
Yes I knew that was just the default. I was just pointing out that it isn't
the location that made the unstyled version invisible - it's the color.
