### ISSUE TITLE
Styling of section titles in Story Viewer

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#372]
The easiest thing would just be to use what we are using on generic pages, and have section titles be `<h2>`. But, to throw another option out, I really like the orange that we put into the Help section. Maybe the section titles could be orange instead of grey.

We could also play around with the horizontal lines (like on the main titles of our interior pages) -- that might look weird with the left-justification (see [issue 368](https://github.com/PitonFoundation/atlas/issues/368)), so we'd have to center. And we wouldn't want to do this if we go with a horizontal line in [issue 369](https://github.com/PitonFoundation/atlas/issues/369).

@bpawlak Please chime in.

**Comment by bpawlak** [comment]
I wouldn't go with centered text in the story viewer.  Too hard to read.  The orange text against a white background might not be so bad since it'd be larger font sizes (and bold?)

**Comment by jwirfs-brock** [comment]
Yes the orange would only be for large fonts in the section headers.

**Comment by bpawlak** [comment]
If the main header of the viewer is also orange, might the titles get lost a bit?

**Comment by jwirfs-brock** [comment]
Do you mean for story titles? In the design comps (which we can change, of course), the story title is white on a black background, in a separate bar at the top. The section title also shows up on the bar, but smaller and in orange. See [issue #370](https://github.com/PitonFoundation/atlas/issues/370).

**Comment by jwirfs-brock** [comment]
Let's go with orange `<h2>` size headers for the section titles, left justified.

The story title itself will be white on black, and an `<h1>`.
