### ISSUE TITLE
Default paragraph, header, list styles in the builder

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#377]
This is really apparent when viewing the intro paragraph on the "Review" workflow step.

I'm thinking just borrowing the ones from [.content-block](https://github.com/PitonFoundation/atlas/blob/builder_redesign/static/less/content-page.less#L15)

@patternleaf, what do you think is the best way to generalize these styles?  Let me know in a comment and assign back to me and I'll take care of this.

**Comment by ghing** [comment]
I think the header and introductory paragraph to this comp gives us some good guidance of what these styles might look like:

![Example of builder header and paragraph styles](http://i.imgur.com/reJCd.jpg)

**Comment by patternleaf** [comment]
pretty much done. some tweaking may still be in order (eg, dt elements on the template selection page could use some margin) but let's make separate issues for those.
