### ISSUE TITLE
Style asset type selection view

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#381]
Bill's original concept:

![Bill's original treatment](http://i.imgur.com/p7Tjr.jpg)

Geoff T's treatment:

![Geoff T's treatment](http://i.imgur.com/jmoDx.jpg)

The consensus was that we were lukewarm about this because:
- it didn't reflect all our asset types
- the icons were a little confusing
- the containers didn't show the space that would be occupied by the assets
- the select asset type icons are shown, even when a type has been selected

So we decided to revert to a squared-off version of Bill's original design:

![Bill's new design](http://i.imgur.com/LF9eM.png)

We should probably use the icons from FontAwesome.

**Comment by patternleaf** [comment]
note that in b86d5ea i may be misunderstanding the intent of the design. the big blue plus in the middle looks extremely clickable, but i am interpreting it as a placeholder, rather than something that you interact with. so i implemented it in gray. easy to fix if needed.

**Comment by ghing** [comment]
I think of the "+" as a placeholder too.  After looking at your work, I like the gray.

**Comment by ghing** [comment]
I think of it as a placeholder too.

I pulled this stuff and like the gray.

**Comment by jwirfs-brock** [comment]
We have some updated feedback based on Bill's user sessions:
- the different states (can select any asset type, can only select one asset type, can select a limited set of asset types) don't look graphically consistent, which is confusing.

I'm putting this in Iteration 10.

**Comment by ghing** [comment]
This displays the difference in the styling of the 2 states.

Pre-selected asset type:

![pre_selected_asset](https://f.cloud.github.com/assets/110420/90629/2487e7aa-657d-11e2-9437-8fcf298ecfdc.png)

Any asset type:

![any_asset_type](https://f.cloud.github.com/assets/110420/90633/2f206e9e-657d-11e2-9f7f-cbcb79df8693.png)

**Comment by patternleaf** [comment]
@jwirfs-brock @ghing How's this?

Pre-selected:
![Screenshot 1:31:13 12:53 PM](https://f.cloud.github.com/assets/73439/115845/fc10d84a-6bdf-11e2-9b15-e01b6d9ce4b7.png)

Any (no change):

![Screenshot 1:31:13 12:54 PM](https://f.cloud.github.com/assets/73439/115848/1193995a-6be0-11e2-8bd8-2cc145d5ea72.png)

**Comment by jwirfs-brock** [comment]
@patternleaf That looks nice. On the pre-selected asset type, could you click anywhere to add the asset, or would you have to click on the darkened "image," "text," etc., icon?

**Comment by patternleaf** [comment]
@jwirfs-brock yeah, you gotta click on the actual little icon. :-1: pretty deceiving, particularly with a big button-looking + in the middle of the page.

**Comment by patternleaf** [comment]
ps, you can check this out on deploy:

http://deploy.atlas.terrorware.com/en/build/

**Comment by jwirfs-brock** [comment]
@patternleaf Is there a way we could make it so you can click the big "+"
symbol?

**Comment by jwirfs-brock** [comment]
@patternleaf Although I'm not sure if it would make sense to have the "+" clickable on the pre-determined asset view, because it isn't clickable on the undetermined asset view.

I'm looping @bpawlak in because he might have some suggestions.

**Comment by ghing** [comment]
Also, I feel like the text needs to go or get some better style treatment.

**Comment by jwirfs-brock** [comment]
Oh geez, yeah I didn't even notice that the text was still there. Would it
make more sense to have the text closer to the icon, either directly above
or below?

**Comment by bpawlak** [comment]
- In my original design, all we would show is the + sign to users...  When you hovered that, it would turn blue and then the rest of the icons would show up.  Then when you hovered one of those icons, it too would turn blue.  Then you'd click.
- can we make it so you can click on the icon _or_ the text that goes along with it?

**Comment by patternleaf** [comment]
> In my original design, all we would show is the + sign to users... When you hovered that, it would turn blue and then the rest of the icons would show up. Then when you hovered one of those icons, it too would turn blue. Then you'd click.

Is this what we think should happen now? I wasn't aware of the intended click flow there. I always thought that great big plus looked awfully clickable.

> can we make it so you can click on the icon or the text that goes along with it?

Is this not happening for you? It is working for me. What browser are you using?

**Comment by bpawlak** [comment]
I think we could use it as a hover or a click.  Either way, I designed it so that someone would see it and move their mouse towards it.  

And yes, the words are clickable.  My laptop trackpad is starting to get on my nerves...

**Comment by patternleaf** [comment]
@bpawlak @jwirfs-brock @ghing ok, the big plus is now clickable and toggles display of the asset types. please check out the behavior when you get a chance. the target area for the + is quite large—i imagine this is an ok thing.

http://deploy.atlas.terrorware.com/en/build/

**Comment by bpawlak** [comment]
I don't understand why the target area is so large... I think it should either be restricted to just the size of the graphic itself _or_ the whole container.  I prefer the former.  Right now, left/right of the [+] is target area and a bit above and below is, but it seems a bit arbitrary when trying to find the boundaries

**Comment by jwirfs-brock** [comment]
@bpawlak @patternleaf The fact that you can't see the icons of the asset
you are adding until you clicked on the "+" really threw me off. I don't
think I would know what I was supposed to do if I saw this.

**Comment by jwirfs-brock** [comment]
@bpawlak @patternleaf Also, now you have to click twice to add an asset
(first on the "+", then on the asset type icon). I think this makes things
more difficult for the user.

**Comment by bpawlak** [comment]
Originally I had suggested it was a hover... that way as soon as you were over it, the rest of the icons appeared

**Comment by jwirfs-brock** [comment]
I still think that you need to see the asset types even in a non-hover
state (or non-click) state.

**Comment by jwirfs-brock** [comment]
What if we use the earlier design that Eric made (a little ways up the
thread), but took and the plus symbol (which looks like something you'd
want to click on), and instead put some brief instructional text there,
like, "Click on an asset to add it."

**Comment by bpawlak** [comment]
valid point.  Helps orient the user about what they can do...

**Comment by patternleaf** [comment]
> I don't understand why the target area is so large... I think it should either be restricted to just the size of the graphic itself or the whole container.

it's just a side effect of how it's implemented, and it didn't seem worth spending the time to fix earlier. doing the whole container would actually be easier than restricting to the "+".

>  Also, now you have to click twice to add an asset

yeah—less than ideal, though for some reason it doesn't bother me overly in this case.

> Originally I had suggested it was a hover... that way as soon as you were over it, the rest of the icons appeared

this certainly can be done, though it's slightly trickier. 

> What if we use the earlier design that Eric made (a little ways up the thread), but took and the plus symbol (which looks like something you'd want to click on), and instead put some brief instructional text there, like, "Click on an asset to add it."

per discussion earlier in the thread, the "+" was interpreted as a placeholder to show the space the asset would take.  how about this:

similar layout of asset types, visible at the outset, with the words "Select an Asset Type" in the middle. on hover over each asset type, the container displays a full-sized version of that asset's icon, lightly in the background. those icons are vector-based do they will scale OK. clicking on the asset type icon loads the form for that asset type, as it does now. i can mock this up if anyone would like to see it (though it may be just as fast to implement it).

?

**Comment by jwirfs-brock** [comment]
That suggestion sounds like a it could work. Can you do the mock-up so we
can see it?

**Comment by bpawlak** [comment]
That's my bad then, I never intended the + to indicate size of the final asset.  

I should have been more clear in that regard.  I was simply trying to make it overly obvious to someone that if they wanted to do anything, they needed to head towards the giant + sign.  As they did, they'd get all of these options presented to them as to what to do next (on hover).  When they leave, the options go away and the + goes back to grey.  

That way, the UI wouldn't be filled with a bunch of icons (esp. if we had 3 containers side by side) and repeating text "select an asset type" (again, if multiple containers).

**Comment by bpawlak** [comment]
Trying to avoid:

![2013-02-05_151737](https://f.cloud.github.com/assets/2250519/129560/067294d0-6fe2-11e2-940a-81d02eb78970.png)

**Comment by patternleaf** [comment]
ok, Bill's suggestion for showing icons on hover is now running on deploy, with the full-container-responds-to-hover variant (because it's easier to implement).

**Comment by jwirfs-brock** [comment]
This is ok, but I think that it's too subtle before the hover. I can barely
even see the grey "+".

Maybe the pre-hover state could be a version of the hover state (with the
appropriate asset icons showing), but just lighter?

**Comment by patternleaf** [comment]
currently staged is a version where the icons are always present, and the _words_ for each icon show up on hover. also made the "+" darker on hover ...

i dunno. that big "+" just still seems like something i should be interacting with directly.

**Comment by bpawlak** [comment]
If we're going to always show the icons, then I think they should be the same opacity as the + and on hover make them darker and show the words.  Still seems kind of busy to me

![2013-02-05_155637](https://f.cloud.github.com/assets/2250519/129674/53515ba6-6fe7-11e2-8614-3ce621f07e14.png)

**Comment by patternleaf** [comment]
>  they should be the same opacity as the + and on hover make them darker and show the words. 

done. @jwirfs-brock , what do you think?

**Comment by jwirfs-brock** [comment]
I still think the starting opacity is much too light. At least on my
screen, I can barely see it. Bump up the non-hover opacity, though, and I
think we'll be good.

**Comment by bpawlak** [comment]
I'll let Jordan make the call on initial opacity, but otherwise looks good to me

**Comment by patternleaf** [comment]
i've bumped up non-hover color a bit. also changed the "unavailable" color to match. that's the color for those asset types that aren't allowed in, eg, PhotoVoice stories. (otherwise it looked strange to have three difference colors going on.)

**Comment by bpawlak** [comment]
Is there any way to not have the text show up on hover for those assets that aren't valid?

**Comment by jwirfs-brock** [comment]
@patternleaf The darker gray looks good, and I agree that it looks better
with just two colors.

I agree with @bpawlak's suggestion. If having the text not show up for the
non-available assets is fairly easy, I say let's do it. If it'll be
difficult, we're good to go as-is.

**Comment by patternleaf** [comment]
Ok, the text only shows up for available types on hover. Closing.
