### ISSUE TITLE
Gloabal button styles

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#384]
See button styles at the bottom of this comp:

![Everything](http://i.imgur.com/0QOk3.jpg)

**Comment by patternleaf** [comment]
available as .button-style(hot) and .button-style(cool) less mixins. applied to &lt;button> elements by default.

**Comment by ghing** [comment]
@patternleaf FYI, I also added .button-hot, .button-cool and .button-gray CSS classes (that are implemented using the mixins) to be able to style elements directly from HTML markup
