### ISSUE TITLE
stream of js errors from wysiwyg editor

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#385]
To reproduce:
1. navigate to builder, pick PhotoVoice
2. open js console
3. click in story body wysiwyg editor to give it focus
4. click on Image and Text section in section bar

result:

stream of js errors: a.nativeSelection is null. doesn't appear to have any negative effect on functionality.

this doesn't happen if you take focus away from the wysiwyg editor before changing story sections. likely fix is to programmatically move focus before hiding the editor.

**Comment by ghing** [comment]
I'm getting logs of another error from WYSIHTML5:

ERROR: javascript error: {"url": "http://floodlightproject.org/static/js/libs/wysihtml5/wysihtml5-0.3.0.min.js", "message": "Uncaught TypeError: Cannot read property 'document' of null", "HTTP_USER_AGENT": "Mozilla/5.0 (Windows NT 5.1; chromeframe/24.0.1312.57) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.57 Safari/537.17", "user": "xxx", "lineNumber": "152"}

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot.
