### ISSUE TITLE
Need to remove default text from interior pages

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#390]
Sample text for "The Vision," "Our Partners," and "How it Works" is showing up in the two column area and footer in all pages. We need to turn this off.

**Comment by patternleaf** [comment]
This markup+copy _is_ wanted on the About page, correct? Or is it not wanted anywhere? If the former we'll need to re-create the markup/copy on the About page by hand when it's removed as default content.

**Comment by jwirfs-brock** [comment]
Correct. I've already added it by hand on the About page on staging.

**Comment by patternleaf** [comment]
this is now staged on dev, but it looks like the about page is missing those sections below the fold. :/

**Comment by jwirfs-brock** [comment]
All right, I'll make sure I update the About page. Thanks!

**Comment by patternleaf** [comment]
closing this.

**Comment by jwirfs-brock** [comment]
@patternleaf It actually looks like you removed the containers for the two columns at the bottom on the page template. So now I can't add (non-default) text back into them.

We just wanted to remove the default content that was showing up in those containers,  not the containers themselves.

**Comment by patternleaf** [comment]
sorry for the confusion. there were multiple placeholders there (separate ones for titles and copy, for example) in order to keep editors from having to get the markup/classnames right. if those placeholders are left blank, the markup would still be there, so on pages using that template without any content below the fold, there would be empty markup. 

that's not terrible, but not ideal. so my thinking/interpretation of this request was to just provide a single, empty placeholder and let you/editors work out the markup. that placeholder is called "twocol-content-below". i have the markup output from the previous version if that'd be helpful to have (see below).

we could also put the multiple placeholders back in and live with empty markup, or, if @ghing has an idea for a better way to implement this, we could do that.

``` html
<div class="page-pull grid_5 alpha">
    <h4><h2 id="vision">The Vision</h2></h4>
    <br/>
<p><strong>We can’t change what we can’t see. But together, our stories can illuminate issues that matter and brighten the world.</strong></p>
<p>We believe in the inherent power, desire and creativity of people to enlighten the others in their community about critical issues that affect us all. We also believe that thriving communities hinge on full citizen engagement.</p>
<p>Floodlight strives to empower as many community members as possible to translate their own firsthand, on-the-ground experiences and knowledge into stories to that can direct action to improve people’s lives.</p>
</div>


<div class="page-pull grid_5 omega">
    <h4><h2 id="partners">Our Partners</h2></h4>
    <br/>
<p><strong>Created by impassioned storytellers, data geeks and community change agents.</strong></p>
<p>Floodlight was created by a team of impassioned social change agents, investigative journalists, data visualization experts and technology gurus with the goal of helping community members create and share inspiring, data-driven stories. Through the use of a free, open source platform, Floodlight helps residents illuminate their own issues while contributing to a larger unfolding story about our community.</p>
<p><a href="../../../../../../about/partners/">Read more</a></p>
</div>



<div class="page-pull grid_10 alpha omega">
    <h4><h2 id="how-it-works">How it Works</h2></h4>

    <p>(content forthcoming) Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

</div>
```

**Comment by patternleaf** [comment]
@jwirfs-brock, after chatting with Geoff, we'll be putting in a slightly simplified version of the previous incarnation of this. 

there will be three content placeholders below the fold: page-pull-1, page-pull-2 and page-pull-3. 1 and 2 will live in two columns; 3 will be in a single column below 1 and 2. there won't be separate placeholders for section headers versus copy text.

i'll update staging with the previous content once the code changes are staged.

**Comment by jwirfs-brock** [comment]
That sounds fine. We don't need this for tomorrow morning. I'll just add
the other About content back in the main container (two-col content) until
the fix is in.

**Comment by patternleaf** [comment]
ok, the content is back in place on the about page, and editable via the admin. the only difference in this version is that  the headings must be put in by hand, rather than via placeholder. @jwirfs-brock, if you need something more here, let me know.

**Comment by jwirfs-brock** [comment]
This looks great. Closing.
