### ISSUE TITLE
Need nore explicit link for "Browse Stories" in top navigation

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#391]
Under the mega-nav for Explore Floodlight, it's not immediately clear that the top heading "Browse Stories" is a link.

Would suggest making the main headings orange to look like links:

https://docs.google.com/drawings/d/1hbU7IfyH8LLjgafrxZ4toqWy_codggt2VBRPS4Y2u0k/edit

**Comment by jwirfs-brock** [comment]
I agree -- I like this change.

I'm not flagging it as critical, because it's not blocking launch, but it should be fairly easy to change, right?

**Comment by patternleaf** [comment]
yes, easy to change.

**Comment by ghing** [comment]
Looks like link color was changed in 03dcf41, closing.
