### ISSUE TITLE
Need to update tour content to match new layout of Story Builder

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#392]
@ghing I'll update the copy and then send back to you.

**Comment by jwirfs-brock** [comment]
I've put all of the changes we need to make to the tour into this Google doc: https://docs.google.com/document/d/1PzVXnGMcYSPUPojfbVMDGCMn9yCy4cCVuHW1NeaSEzY/edit

Some tour items needs to be moved, some need new copy, and some need both. I've noted that in the document.

@ghing If it's easier for you, I can make a pull request and then modify the copy in the template on my side. Let me know how you think we should do this.

**Comment by ghing** [comment]
@jwirfs-brock, merge in this pull request (https://github.com/jwirfs-brock/atlas/pull/2) to bring your fork up-to-date.  Then, update the copy.  Finally, make a pull request to me so I can review/merge in the copy updates and I'll take care of the moving.

**Comment by jwirfs-brock** [comment]
@ghing  I merged the pull request, but I'm having some trouble because it looks like some of the tour content is being pulled from somewhere else. I want to make sure I'm editing the right files. I am editing: https://github.com/jwirfs-brock/atlas/blob/develop/static/js/builder/views.js

For example:

```
       position: 6,
        title: gettext("You can also add, move or delete sections."),
        description: this.template['section-manipulation-guider'](),
```

Where do I edit `this.template['section-manipulation-guider']()`? Is it somewhere in this file, or elsewhere?

**Comment by ghing** [comment]
Those are in story_builder_handlebars.html (
https://github.com/jwirfs-brock/atlas/blob/develop/apps/storybase_story/templates/storybase_story/story_builder_handlebars.html#L513)
the id of the template tag matches the key in the code (e.g.
'section-manipulation-guider').

On Mon, Oct 29, 2012 at 11:17 AM, Jordan Wirfs-Brock <
notifications@github.com> wrote:

> @ghing https://github.com/ghing I merged the pull request, but I'm
> having some trouble because it looks like some of the tour content is being
> pulled from somewhere else. I want to make sure I'm editing the right
> files. I am editing:
> https://github.com/jwirfs-brock/atlas/blob/develop/static/js/builder/views.js
> 
> For example:
> 
> ```
>    position: 6,
>     title: gettext("You can also add, move or delete sections."),
>     description: this.template['section-manipulation-guider'](),
> ```
> 
> Where do I edit this.template['section-manipulation-guider']()? Is it
> somewhere in this file, or elsewhere?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/PitonFoundation/atlas/issues/392#issuecomment-9874141.

## 

Geoffrey Hing
geoffhing@gmail.com
773.969.6436
http://geoff.terrorware.com/
Twitter: @geoffhing

**Comment by jwirfs-brock** [comment]
@ghing Ok, I updated the copy and created a pull request:

https://github.com/PitonFoundation/atlas/pull/407

Some of the tour elements still need to have their position updated (I wasn't sure how to do that).

**Comment by jwirfs-brock** [comment]
@ghing Or should I make a pull request for ghing/atlas instead of PitonFoundation/atlas?

**Comment by ghing** [comment]
@jwirfs-brock PitonFoundation/atlas is correct.  I'll look at this later today.
