### ISSUE TITLE
Projects page should have a list of all existing projects

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#399]
See: http://dev.atlas.terrorware.com/en/projects/

This should have a list of all existing projects. Each should link to the project detail page.

**Comment by ghing** [comment]
@jwirfs-brock, Is there any guidance for what this should look like design wise?  I can't remember seeing it in the comps, but I might have overlooked it.

**Comment by jwirfs-brock** [comment]
The acceptance tests are the clearest way we described it. I don't believe
we had any comps for this. @bpawlak could you help with this?

**Comment by bpawlak** [comment]
I had created a basic page in the prototype (clients.inovdesigns.com/floodlight)
