### ISSUE TITLE
Clicking on "Contribute to this story" from a connected story should launch a PhotoVoice story

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#400]
The behavior for what should happen when a user contributes to a connected story is outlined in the Iteration 6 acceptance tests, in T0164 and T0168 (https://docs.google.com/document/d/1jne00MgfxXg2ym01Et6CD0ZNoLo0iTG4EYdyWaj_erc/edit).

I am not sure if we'll be able to have a stripped down version of the Story Builder, but we should at least have:
- the photovoice template pre-selected
- the prompt visible somewhere

**Comment by jwirfs-brock** [comment]
Right now, I'm not marking this as critical. @ghing if this is relatively easy to do, then it becomes a high priority. If it will take a large chunk of time, then we can leave it as post-launch (maybe something to make sure we have by our marketing push in late November).

**Comment by ghing** [comment]
@jwirfs-brock This should be working. I'll take a look and see why it's not.  Some functionality might have gotten clobbered when the theme was applied.

**Comment by jwirfs-brock** [comment]
I'm seeing the template chooser when I create a connected story.

**Comment by jwirfs-brock** [comment]
I'm not sure if this is possible, but here's a (really ugly) sketch of the elements we'd want to get rid of in the stripped-down version of the Story Builder for connected stories:

https://docs.google.com/file/d/0B82exFJJWyJqTHRESV9wT0F5YWM/edit

The prompt could maybe go in the orange bar at the top. Or, if we get rid of section nav bar, it could go there. Again, I am not sure if these elements are toggle-able or not. For getting rid of workflow steps 2 and 3, we could just grey them out (they don't have to be removed from the bar).

Another option is that the prompt could become the section-specific help, and we set it so that the help drawer is open.

**Comment by ghing** [comment]
@jwirfs-brock By default, the app looks for a template with a slug of `connected` to use for the connected story builder template.  I changed the value of `settings.STORYBASE_CONNECTED_STORY_TEMPLATE` to be `photovoice` and it works now.  

See http://dev.atlas.terrorware.com/en/stories/beyond-sprawl-the-southwest-zombie-problem-2/build-connected/
