### ISSUE TITLE
Wire in social icons

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#404]
Jordan, is there a Twitter account and Facebook page for Floodlight yet?  If so, let me know the URLs.  If not, I'll hide the icons for now.

**Comment by jwirfs-brock** [comment]
We have a Twitter account. Don't think we have a Facebook page yet. @tekhneco can you send Geoff the Twitter info?

**Comment by wendynorris** [comment]
@FloodlightStory

password: piton5280$

No Facebook account.
