### ISSUE TITLE
Persistent login credentials

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#406]
Can we add a "remember me" checkbox on the login to store passwords and avoid the need for users to remember their credentials?

**Comment by jwirfs-brock** [comment]
Right now, it automatically remembers you as long as your are using the same browser. (Even if you close your browser and re-open it, I think.)

@tekhneco Are you suggesting we have a way for it to remember you across different browsers? @ghing is that possible?

**Comment by wendynorris** [comment]
When I just logged in -- using the same browser I normally use -- it didn't remember me and I had to dig out the password from the email I sent myself. I added the Floodlight account to the persistent password add-on in Firefox but not everybody does that.

**Comment by ghing** [comment]
@tekhneco Is this on staging or dev?  On both, I was able to log-in, close my browser, and remain logged-in.  

When was the last time you had logged in previously?

You may have either hit the default session timeout (I think it's 2 weeks).   This is pretty standard.  I haven't ever noticed a site that keeps sessions active for longer than a month (this is for security reasons).

**Comment by wendynorris** [comment]
This is on the staging site. I don't recall precisely when I was last logged-in but it was definitely within the last two weeks.

**Comment by ghing** [comment]
I wasn't able to replicate this.

I closed my browser and opened it and my login session persisted.  I also switched from the wifi hotspot to a tethered phone to ensure a different IP and the session still persisted.  I tried this with both Firefox and Chrome and my login session persisted.

Please let me know if you continue to experience this.

**Comment by wendynorris** [comment]
Sorry, I think we're talking past each other. I understand the need to timeout sessions for security reasons. That's smart. 

What I'm looking for is the fairly standard function of signing in with a user name and then the password auto-completes. There's no "remember me" checkbox when logging in.

**Comment by ghing** [comment]
@tekhneco I think I understand you.  What I'm saying is that the default behavior is to "remember me" for two weeks.  I haven't been able to replicate the issue where it doesn't remember you.

Storing passwords is always handled by the browser, not by an individual site, and that's working for me on staging.  Is it possible you chose the "never for this site" (or your browser's equivalent) when it prompted you to remember the password?

**Comment by wendynorris** [comment]
I guess anything is possible but I generally don't select never for the password recall. If I don't affirm, I exit out. 

Why don't we close this issue with a note to monitor user behavior post-launch. If we find users have figured out how to store their passwords, great. If we see a spike in "forgot password" calls, then we revisit. Sound good?

**Comment by jwirfs-brock** [comment]
@tekhneco That sounds good to me.
