### ISSUE TITLE
builder section nav hover issue

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#408]
hovering to create an add section spacer causes current selection arrow to be rendered in the wrong place.

**Comment by jwirfs-brock** [comment]
Also see issue #506 for some related styling updates.

**Comment by patternleaf** [comment]
so with the styling changes in #506 (add-section widgets are horizontally more compact), this is now less egregious. the little pointer doesn't render way outside of the section box, just a little off-center. i think to avoid this _might_ require changing the markup, or some javascript, and i'm not sure that it's worth it. a css-only fix is possible, but would require some investigation. would anyone object to closing this or deferring it?

**Comment by jwirfs-brock** [comment]
I'm actually not seeing the weird spacing of the pointer/arrow. I'm fine with closing.
