### ISSUE TITLE
Content for "Featured on Floodlight" area on homepage

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#409]
I have three sample items for the homepage, which you can view at: https://docs.google.com/document/d/1MaxZjyKWLppeMbRbWg9nQK48_O5KEbW6iDk_qBNEqsw/edit

A couple of notes:
1. These don't have corresponding images yet -- I'm still working on getting those. @patternleaf Do you know what the dimensions need to be for the images?
1. Having multiple images for a single slider item isn't necessary. In fact, with this batch, the only one I could see doing that with is "Stories of the Children's Corridor," which could have an image for each project it links to. The others will just have one image.

**Comment by patternleaf** [comment]
> Do you know what the dimensions need to be for the images?

@jwirfs-brock: 335x200 is what's in the current slideshow.

**Comment by jwirfs-brock** [comment]
Here are the images for the second two items (still waiting on the first):

Stories of the Children's Corridor - http://dl.dropbox.com/u/4667118/Childrens_Corridor_FL_homepage.jpg

Colorado Data Engine - http://dl.dropbox.com/u/4667118/Childrens_Corridor_FL_homepage.jpg

Both are 335x200 px.

**Comment by patternleaf** [comment]
hey @jwirfs-brock - those look to be the same links! :)

**Comment by jwirfs-brock** [comment]
Oops, I'll get the correct ones up there soon.

**Comment by jwirfs-brock** [comment]
Ok, here's the Colorado Data Engine image link - http://dl.dropbox.com/u/4667118/Data_Engine_FL_homepage.jpg

The third image will be coming soon...

**Comment by jwirfs-brock** [comment]
And here's the final image: http://dl.dropbox.com/u/4667118/NearNortheast_800px.jpg

It is larger, but has the same aspect ratio as the smaller images so should scale. @patternleaf  Let me know if you need me to resize it.

**Comment by ghing** [comment]
Closed by bf8025b, deployed on staging.
