### ISSUE TITLE
With the Help drawer, don't have a way to go back to section-specific help

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#410]
Once you've clicked on the "?" icon next to an asset to bring up the asset-container-specific help, to get back to the section-specific help, you have to look at a different section and then come back or click on the current section in the section-nav bar.

This is ok for now and pretty low-priority, but in the future we may want to include a note about this somewhere (or a reset button within the Help drawer).

**Comment by ghing** [comment]
This is a known issue that @bpawlak went back and forth about how to best address.  If I recall we came up with a few suggestions:
- @bpawlak suggested having the help reset to the section help when the user clicks anywhere in the section
- I suggested showing all the available help for a section with an [accordion widget](http://jqueryui.com/accordion/)

Or we could do something else, like showing all the help for a section and its containers and scrolling the appropriate section.

**Comment by jwirfs-brock** [comment]
I like the accordion widget idea. Let's return to this after launch.

**Comment by jwirfs-brock** [comment]
You can now close the Help tab and re-open it to see the section-specific help. Closing.
