### ISSUE TITLE
Caption not saving for uploaded image asset

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#412]
I know this was an issue before and was closed, but I'm seeing the same behavior.  It may be related to  to #441, but I'm also not able to save my caption in story:  http://dev.atlas.terrorware.com/en/build/544430debfdf4fa0a3dac6b6d96f4a7e/

**Comment by ghing** [comment]
I wasn't able to replicate this on dev.  Can you re-try and see if you're still getting the issue?

**Comment by bpawlak** [comment]
Still getting the same behavior on the story that has the broken image asset (ref in #441), but works on other stories...

**Comment by ghing** [comment]
I still wasn't able to replicate this.  We can reopen if other users report this.
