### ISSUE TITLE
Builder tour popup falls off screen in IE

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#415]
![Imgur](http://i.imgur.com/ago3p.png)

**Comment by patternleaf** [comment]
i can take this, but i may have to upgrade to Windows 7 and IE9 and/or fix #503 first.

**Comment by ghing** [comment]
I'll take this since I have IE9/Win7 already

**Comment by ghing** [comment]
_Update_:

So it looks like I had also run into this problem in FF/Chrome and had to hack the Guiders Javascript to correct it (see dfd9873f61626bc30941bc5eef40dad5aa1c85fa).  However, my tweak doesn't seem to take in IE.

I added some debugging messages to `guiders.show`, and it looks like the style attribute of the guider element has the correct left: 0px when it needs to be nudged to the right (when it's falling off the left of the window).  However, it the incorrect negative left value is being used when viewing the source in IE's developer tools.

If I do a $('#workflow-step-guider').css('left');  in the javascript console, I get a value of -60px back

If I do $('#workflow-step-guider').css('left', 0px); then the guider element snaps to where it should be.

@patternleaf, let me know if you have any insight into this.

**Comment by patternleaf** [comment]
in my testing in IE8, winXP, there was some indeterminacy in whether the first guider showed half-offscreen or not. i'd clear the cache and reload and probably 8 out of 10 times, it was half offscreen, but 2 out of 10 times it wasn't. yay IE!

a hack that _seemed_ to eliminate this was to invoke your nudge method on a timer with a delay of 1 millisecond. i recall having to use such hacks before with IE to get its rendering to be less ... _organic_. the code is then, e.g.:

``` javascript
    if (isGuiderLeft) {
      setTimeout(function() {
        guiders._nudge(myGuider, 0 - guiderOffset.left);
      }, 1);
    }
```

since this is a browser-specific hack, we might want to browser sniff and only do this for IE, or certain versions of IE, etc...

**Comment by ghing** [comment]
@patternleaf, I had good luck with using the `onShow` callback to bind my nudge functions to the `guiders.show` jQuery event that the `guiders.show` function triggers on the guider element at the function's execution.  I think this fixes the IE issue as well. I need to clean this up a little and I'll probably have you take a look because I'm unsure about where I've declared my functions.

**Comment by jwirfs-brock** [comment]
I'm still seeing the first window of the tour cut off on the left side of the screen if I have a window that isn't extremely wide (but is still wide enough for all the elements of the Story Builder to fit). When I increase the width, the tour fits.

Screen shot:
![IE_tour_issue](https://f.cloud.github.com/assets/1020518/11291/71ca4362-454a-11e2-9390-aa531a79505b.png)

**Comment by jwirfs-brock** [comment]
Oh, I was using IE9 on Windows 7.

**Comment by ghing** [comment]
Update: I was able to replicate this, more consistently on the staging instance, but not every time, and only with a completely clear cache.  After loading the page once and re-loading it, I was unable to replicate this issue.

I was not able to replicate this consistently on the development instance.

**Comment by ghing** [comment]
@jwirfs-brock, I increased the timeout on this and have not been able to replicate this on staging.  I tested with a clear cache and with different window widths.  Can you see if you're still able to replicate this?
