### ISSUE TITLE
Internet Explorer doesn't support input placeholders

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#416]
Internet Explorer 9 and lower don't support placeholders!!! 

There are a number of polyfills available.  See http://stackoverflow.com/questions/5522164/input-placeholders-for-internet-explorer

**Comment by jwirfs-brock** [comment]
@patternleaf Can you send me the link so I can view this on the dev site and test if necessary? Thanks.

**Comment by jwirfs-brock** [comment]
@ghing @patternleaf I tested http://dev.atlas.terrorware.com/ on IE9. The Story Builder seems to be having a lot of problems. See below for the full list.
- After signing in, before getting redirected to the “My Account” page, I got a pop-up message/error that said “undefined.”
- Template selection page is formatting strangely ![IE9_templateselection.png](https://f.cloud.github.com/assets/1020518/4186/ce3b59f0-42fd-11e2-9e22-59370ed2c23a.png)
- The containers on the Story Information section did not show up until I clicked Story Information in the section nav bar.
- After I clicked on "Story Information" in the section nav menu, Summary displayed, “Click to edit the summary” but Title and Byline were blank (no placeholders)
  ![IE9_storyinformationplaceholders.png](https://f.cloud.github.com/assets/1020518/4188/ea809a44-42fd-11e2-99ff-de4e504dd74a.png)
  - “Image and Text” and “Call to Action” sections appeared blank (no containers). This happened both before and after the story was saved.
    ![IE9_imageandtext.png](https://f.cloud.github.com/assets/1020518/4189/f3d97ea8-42fd-11e2-8713-b6f27b05d4ab.png)
- When I clicked “Exit” to get out of the Story Builder, I got the same “undefined” error message as when I first logged in. After I clicked “OK,” I got a message that said, “[cycle] terminating: zero elements found by selector.” When I clicked “OK” on that message, it just re-opened. I had to “x” out of it to get back to the FL homepage.

I tried this with the each template and observed the same bugs.

**Comment by patternleaf** [comment]
just an update: i have so far not been able to get a working copy of Win7/IE9 :( so haven't had a chance to look at this personally yet.

**Comment by patternleaf** [comment]
So there are a few issues here. In my tests, the bugs showed up without clearly deterministic reproduction steps (yay IE!).

> After signing in, before getting redirected to the “My Account” page, I got a pop-up message/error that said “undefined.”

I was able to reproduce this a couple of times (thought not 100%), but am not sure of what is causing it. I'll file a separate issue for it.  (#536)

> Template selection page is formatting strangely 

I think this is unrelated to the placeholder changes and is just something happening in IE. I'll make a separate issue for it. (#538)

> The containers on the Story Information section did not show up until I clicked Story Information in the section nav bar.

This and the next few builder-related bugs are all on account of the JS interpreter bailing after hitting a reference error because the `Modernizr.load` call to pull in our placeholder polyfill was inline in the document before jQuery had been defined, and our placeholder polyfill requires jQuery. It may be (though I don't know this) that the non-deterministic behavior of the bug is because `Modernizr.load` pulls in files asynchronously, so sometimes jQuery was defined in time, and sometimes it wasn't.

At ay rate, moving the `Modernizr.load` call to a point after jQuery has been defined seemed to fix the issue. The builder behaved normally, with placeholders, on every run through the repro steps I tried.

> When I clicked “Exit” to get out of the Story Builder, I got the same “undefined” error message as when I first logged in. 

Same as above—i'll make a separate issue for this.

> After I clicked “OK,” I got a message that said, “[cycle] terminating: zero elements found by selector.” When I clicked “OK” on that message, it just re-opened. I had to “x” out of it to get back to the FL homepage.

This is strange—the cycle terminating thing is a message our slider plugin coughs out, but it should be directed to the log, and not to an alert dialog. I'll make a separate issue for this, too. (#537)

@jwirfs-brock, when you get a chance, please try again on deploy (http://deploy.atlas.terrorware.com/), where this fix is currently staged.

**Comment by jwirfs-brock** [comment]
@patternleaf 

I just looked at this again.

The containers are now showing up on the Story Information section, but I'm still not seeing placeholder text in the Title or Byline.

I also still got the "undefined" message after logging in, and the "[cycle] terminating: zero elements found by selector," message when I exited the Builder.

I was viewing on deploy.atlas.terrorware.com in IE9 -- is that the right place to see the fixes?

**Comment by patternleaf** [comment]
@jwirfs-brock, sorry, no—the branch with that fix was not checked out on deploy just now. 

i just checked it out. could you try again? thanks.

**Comment by jwirfs-brock** [comment]
@patternleaf  When I just tried opening the Builder in deploy, I got the following error:

Environment:

Request Method: GET
Request URL: http://deploy.atlas.terrorware.com/build/

Django Version: 1.3.1
Python Version: 2.7.2
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.gis',
 'cms',
 'easy_thumbnails',
 'filer',
 'mptt',
 'menus',
 'reversion',
 'south',
 'sekizai',
 'cms.plugins.text',
 'cmsplugin_filer_file',
 'cmsplugin_filer_folder',
 'cmsplugin_filer_image',
 'cmsplugin_filer_teaser',
 'cmsplugin_filer_video',
 'haystack',
 'taggit',
 'tastypie',
 'categories.editor',
 'tinymce',
 'registration',
 'social_auth',
 'django.contrib.comments',
 'threadedcomments',
 'notification',
 'storybase',
 'storybase_help',
 'storybase_user',
 'storybase_asset',
 'storybase_story',
 'storybase_taxonomy',
 'storybase_geo',
 'storybase_messaging',
 'cmsplugin_storybase']
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'cms.middleware.multilingual.MultilingualURLMiddleware',
 'cms.middleware.page.CurrentPageMiddleware',
 'cms.middleware.user.CurrentUserMiddleware',
 'cms.middleware.toolbar.ToolbarMiddleware',
 'storybase.middleware.ExtractContentMiddleware')

Traceback:
File "/srv/www/atlas_deploy/venv/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
1.                         response = callback(request, _callback_args, *_callback_kwargs)
   File "/srv/www/atlas_deploy/venv/lib/python2.7/site-packages/django/views/generic/base.py" in view
2.             return self.dispatch(request, _args, *_kwargs)
   File "/srv/www/atlas_deploy/venv/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapper
3.             return bound_func(_args, *_kwargs)
   File "/srv/www/atlas_deploy/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
4.                 return view_func(request, _args, *_kwargs)
   File "/srv/www/atlas_deploy/venv/lib/python2.7/site-packages/django/utils/decorators.py" in bound_func
5.                 return func(self, _args2, *_kwargs2)
   File "/srv/www/atlas_deploy/atlas/apps/storybase_story/views.py" in dispatch
6.         return super(StoryBuilderView, self).dispatch(_args, *_kwargs)
   File "/srv/www/atlas_deploy/venv/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
7.         return handler(request, _args, *_kwargs)
   File "/srv/www/atlas_deploy/atlas/apps/storybase_story/views.py" in get
8.         context = self.get_context_data(object=self.object, **kwargs)
   File "/srv/www/atlas_deploy/atlas/apps/storybase_story/views.py" in get_context_data
9.             'organizations_json': mark_safe(self.get_organizations_json()),
   File "/srv/www/atlas_deploy/atlas/apps/storybase_story/views.py" in get_organizations_json
10.                             for org in self.request.user.organizations.all()]
    File "/srv/www/atlas_deploy/venv/lib/python2.7/site-packages/django/db/models/query.py" in _result_iter
11.                 self._fill_cache()
    File "/srv/www/atlas_deploy/venv/lib/python2.7/site-packages/django/db/models/query.py" in _fill_cache
12.                     self._result_cache.append(self._iter.next())
    File "/srv/www/atlas_deploy/venv/lib/python2.7/site-packages/django/db/models/query.py" in iterator
13.         for row in compiler.results_iter():
    File "/srv/www/atlas_deploy/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py" in results_iter
14.         for rows in self.execute_sql(MULTI):
    File "/srv/www/atlas_deploy/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py" in execute_sql
15.         cursor.execute(sql, params)
    File "/srv/www/atlas_deploy/venv/lib/python2.7/site-packages/django/db/backends/util.py" in execute
16.             return self.cursor.execute(sql, params)
    File "/srv/www/atlas_deploy/venv/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py" in execute
17.             return self.cursor.execute(query, args)

Exception Type: DatabaseError at /build/
Exception Value: relation "storybase_user_organization_members" does not exist
LINE 1: ...ge" FROM "storybase_user_organization" INNER JOIN "storybase...
                                                             ^

**Comment by patternleaf** [comment]
shoot, that's right. the database and code had gone out of sync on that branch. it should be fixed now. thanks.

**Comment by jwirfs-brock** [comment]
@patternleaf Ok, I can confirm that the containers are showing up, but the placeholders are still empty.

**Comment by patternleaf** [comment]
@jwirfs-brock errgh. just double-checked in Win 7, IE9 (build 9.0.8112), and it seems to be working for me. my repro steps were:
1. http://deploy.atlas.terrorware.com
2. log out if logged in
3. log in
4. click the big "Create Your Story" button in the BUILD menu
5. pick PhotoVoice template
6. app loads; placeholders in place

could you post your repro steps, in case there's something specific you're doing that i'm not doing? or maybe we should have that skype screensharing session we talked about?

thanks.

**Comment by patternleaf** [comment]
@jwirfs-brock assigning to you for comments. please assign back if needed.

**Comment by jwirfs-brock** [comment]
@patternleaf Ok, I went through it again after clearing my browser cache and now the placeholders are there. Hoorah!

Note that I am still getting the error messages, but I believe you opened those as separate issues, so I'm closing this one.

**Comment by patternleaf** [comment]
yay! thanks @jwirfs-brock .
