### ISSUE TITLE
Homepage text looks weird

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#423]
This is what I mentioned in my e-mail to you. 

It looks like a result of the lines you commented out in misc.less in 2b33d5782bb2fea4d25a8a794082092029c63901

Specifically, this style:

`#main .text p { color:#5a5a5a; .plain-serif-text; }`

Also the "View ..." links are the wrong color and some of the spacing is weird.  I think it's all related to styles commented out around the previously mentioned rule.

**Comment by patternleaf** [comment]
staged on dev; closing.
