### ISSUE TITLE
Spanish-language menus are too wide and are overflowing onto a second row

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#425]
See: http://staging.floodlightproject.org/es/about/

The short-term solution we discussed on the stand-up this morning was coming up with a shorter title for "Grow Your Skills" in Spanish. I'll get the shorter title from Veronica.

**Comment by ghing** [comment]
@jwirfs-brock I'd say this is critical just because it makes the layout look so crazy.  Remove critical label if you don't think this is blocking.

**Comment by jwirfs-brock** [comment]
Yes, this is critical. I'll get the shortened text from Veronica and update
on Transifex ASAP....

**Comment by jwirfs-brock** [comment]
@ghing All right, I changed "DESARROLLA TUS HABILIDADES" to "TUS HABILIDADES" in Transifex. Is that short enough to render on a single line?
