### ISSUE TITLE
Top navigation isn't correctly reflecting where user is in site taxonomy

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#427]
Example: http://dev.atlas.terrorware.com/en/projects/  The "Home" link shows as active when in fact it should be "Explore Floodlight"

**Comment by jwirfs-brock** [comment]
@bpawlak I'm confused ... the bread crumbs seem to be right (Home / Explore Floodlight / Projects). Do you mean the top nav menu should have "EXPLORE FLOODLIGHT" highlighted in orange? I thought we wanted home to always be highlighted in order to give it emphasis.

**Comment by bpawlak** [comment]
Yep, "EXPLORE FLOODLIGHT" should be highlighted - when the user is in that section of the site.  HOME is only highlighted when the user is on the home page.

**Comment by jwirfs-brock** [comment]
I recall having a conversation where we decided users know where they are because of the breadcrumbs, so we didn't need to highlight the main nav. We decided that "HOME" would always be orange.

I am fine revisiting this, but it's currently working the way that we wanted it to per the design.

**Comment by bpawlak** [comment]
I must not have been part of that conversation, because I wouldn't have agreed to that.  :)

**Comment by jwirfs-brock** [comment]
Just making sure that this issue gets back on the radar, since it had been assigned to me.

@patternleaf Let's go with Bill's suggestion, so have the orange highlighted/underlined text in the main menu reflect where the user is.

**Comment by ghing** [comment]
Docs for navigation in Django CMS: https://django-cms.readthedocs.org/en/latest/getting_started/navigation.html

Docs for custom menus in Django CMS: http://docs.django-cms.org/en/2.3.5/extending_cms/app_integration.html#menus

I'm pretty sure that some wiring of our custom views into the Django CMS menu structure happens in `cmsplugin_storybase.menu`

**Comment by patternleaf** [comment]
@bpawlak @jwirfs-brock guys, just to clarify: does this issue refer to the megamenu or to the breadcrumbs (in the gray bar below the megamenu)?

**Comment by bpawlak** [comment]
Both the megamenu and the breadcrumbs should correctly reflect where the user is within the structure of the site.  (2nd level navigation, when within a section of the site, should also reflect where the user is as well)

**Comment by patternleaf** [comment]
> Both the megamenu and the breadcrumbs should correctly reflect where the user is within the structure of the site.

certainly. but does _this_ issue refer to highlighting in breadcrumbs or highlighting in the megamenu? the comments don't make this clear. 

we now have an issue for highlighting in the megamenu: #644.

if this issue is for highlighting the megamenu, then we should merge these two issues. if it is for highlighting in the breadcrumbs, then is it the case that on the original example given:

http://dev.atlas.terrorware.com/en/projects/

it should (also showing megamenu highlighting, once #644 is completed) look like this?

![Screenshot 2:21:13 9:52 AM](https://f.cloud.github.com/assets/73439/181134/6713ecaa-7c47-11e2-8156-7fad2e4d38d8.png)

**Comment by bpawlak** [comment]
It should look like:

![image](https://f.cloud.github.com/assets/2250519/181219/d1410ab2-7c48-11e2-85ce-089fa4fa3142.png)

**Comment by patternleaf** [comment]
OK: i presume then that those are _links_ up to the current page, and not just styled orange?

**Comment by bpawlak** [comment]
yes.  The breadcrumb should be able to be used for navigation back up the site hierarchy
