### ISSUE TITLE
“You are here” feedback is needed on secondary navigation in My Account.

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#428]
To make it more obvious to the user where they are in the navigation, I suggest changing the link color for the current location to increase its visibility:

https://docs.google.com/drawings/d/1EFGpjCvhwRAIQ_6EfGhIZa5INgRm7IsMyxKGczbqUjk/edit

This is also part of a larger effort at evaluating how 2nd & 3rd level navigation should be displayed on the site.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot.
