### ISSUE TITLE
Need to add BAB to the “Build a Story” nav dropdown.

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#429]
We don’t want to have to force people to have to go to the /story-builder page; they should be able to get right to story telling from the drop-down.

https://docs.google.com/drawings/d/1HinF8dSJLa9HcUPz7V9FKFRwHMv4W2yFdx78Wz51SdY/edit

Also added small "Learn more" link in text under the "Create an amazing story in minutes..." lead-in text

**Comment by jwirfs-brock** [comment]
We want the to go to the /story-builder page on their first visit, then be able to directly enter /build on subsequent visits. I like this layout for experienced users, but will it suffice for new first-time users?

**Comment by bpawlak** [comment]
I think if there's a prominent call to learn more about storytelling (yet still allow experienced users to immediately get to it), we should be able to cover both cases

**Comment by ghing** [comment]
Deployed
