### ISSUE TITLE
Make the Big-Ass-Button Bigger and more "Assier”

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#431]
Right now, the button looks out of place and isn't prominent enough.  Suggest this layout:

https://docs.google.com/drawings/d/1-nFYKL7niQ1vxQVZc7MPoYFmNN2jZv6XVUwn3lOHf30/edit

**Comment by jwirfs-brock** [comment]
Totally agree. Bigger and assier for sure.

**Comment by ghing** [comment]
Fix deployed, markup updated on production.
