### ISSUE TITLE
Need to address body font for readability and consistency of presentation

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#435]
Museo serif should probably be paired with a sans-serif font for on-screen readability.  Need to address line-height/rhythm for increased comprehension, as well

Reference: http://typecast.com/blog/4-simple-steps-to-vertical-rhythm/  and http://www.gridlover.net/

See https://docs.google.com/document/d/1fOGsS8O_R3A-OqMLG7zExtHWRyHI5sMAmv2JWAaxFCo/edit for an example of how the typography can be greatly improved

**Comment by patternleaf** [comment]
a few screenshots of variations:

https://docs.google.com/document/d/1GZjXkyG62f5HtB_zW2h5O0eJ9jOKjP5ZgNC6Tn5iqAg/edit

there was talk of using Arial so i included one with Arial and a couple of other vertical spacing tweaks that should probably be made wrt headings. comments, @all?

**Comment by bpawlak** [comment]
Headings in serif fonts is fine by me but I recommend a sans-serif body font for readability's sake. Line-height adjustments will also help that regard as well (in addition to just looking nicer, it actually makes it easier to read).  Have a play with http://www.gridlover.net/  Try "body font size" of 1em and "body line height" of 1.4em.  So much easier on the eyes!

**Comment by jwirfs-brock** [comment]
I prefer Arial for body text (and like the version with more line spacing better), and agree with @bpawlak that serif fonts are ok for the headings. My recommendation is that we use Museo for headers and Arial for body text.

**Comment by patternleaf** [comment]
@PitonFoundation/developers the site-wide font change to Arial and a few adjustments to viewer font rendering can be seen on deploy, at http://deploy.atlas.terrorware.com/

note that in some places—most noticeably on the About page—there are extraneous &lt;br> tags in the CMS content causing particularly horrible spacing issues.

**Comment by jwirfs-brock** [comment]
Great. I'll clean up the About page -- I probably added those breaks to
make the small Times New Roman text more readable.

**Comment by patternleaf** [comment]
i've gone through and made some additional corrections and tweaks to spacing and general issues in the viewer, CMS-powered content, and the megamenu. if new issues arise, let's make new bugs for them. i'm going to close this one now.
