### ISSUE TITLE
Need to change text for a user who tries to login before confirming account through email

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#436]
If you create an account and try to sign in before clicking on the confirmation link in your email, you get the following message:

"Your Floodlight account has been deactivated by the Floodlight administrators. If you would like to reactivate your account, please contact us at . "

Today, we had several people trying to log in at a training session, and before I got there, there was a bit of freak-out-age about this.

We should change this so that it says something along the lines of, "You signed up, but haven't yet clicked on the confirmation link we sent to you via email. If you can't find the email, contact us at help@floodlightproject.org."

Also, the message saying to check your email for a confirmation link is not very visible. It is right at the top of the page, and gets covered up by the megamenu nav. I'll provide some alternate text. I suggest we use some formatting to make it larger/easier to read.

@ghing Should I send you this copy, or does it make sense for me to just edit it in the templates?

**Comment by jwirfs-brock** [comment]
Here is the updated text for a user who tries to login with an unconfirmed account:

> Hi [email address],
> 
> You still need to confirm your email address. We emailed you a link when you first signed up. Click on the link in that  message and you will be all set to log in.
> 
> If you can’t find the email we sent you or have further questions, contact us at help@floodlightproject.org.
> 
> Thanks,
> The Floodlight Team

**Comment by jwirfs-brock** [comment]
And here is the text for http://staging.floodlightproject.org/en/accounts/register/complete/:

> Thanks for signing up!
> 
> There’s one last step before you can begin creating stories on Floodlight. We’ve sent you a confirmation email. Click the link in that email to verify your account and log in.
> 
> If for some reason you don’t receive an email (make sure you check your spam filter), contact us at  help@floodlightproject.org.

"Thanks for signing up!" should be h2.

**Comment by ghing** [comment]
@jwirfs-brock, I updated the template with a hybrid error message:

>    Hi geoff-nospam@terrorware.com,
> 
>    It looks like you still need to activate your account by confirming your email address. We emailed you a link when you first signed up. Click on the link in that message and you will be all set to log in.
> 
>    If you can’t find the email we sent you or have further questions, contact us at info@floodlightproject.org.
> 
>    If you've already activated your account, it may have been deactivated by the Floodlight administrators. If you would like to reactivate your account, please contact us at info@floodlightproject.org.
> 
>    Thanks,
>    The Floodlight Team

Does this work for you?

**Comment by jwirfs-brock** [comment]
This looks good.

**Comment by ghing** [comment]
Ok.  I need to update some styling for these messages and then I'll push.
