### ISSUE TITLE
Need to add contact email to system-generated messages (help@floodlightproject.org)

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#437]
The email people get when they create an account, asking them to click on the confirmation link, needs to have a contact email address.

Currently, the text is:

"Welcome to Floodlight!

To activate your account, please verify your email by clicking this link, or pasting the address into your internet browser:

http://staging.floodlightproject.org/accounts/activate/429b10d405599463bb4f815d9f3a768d18ec2d53/

You must activate your account in 7 days

If you have any problems, contact us at .

The Floodlight Team"

It should be:

"Welcome to Floodlight!

To activate your account, please verify your email by clicking this link, or pasting the address into your internet browser:

http://staging.floodlightproject.org/accounts/activate/429b10d405599463bb4f815d9f3a768d18ec2d53/

You must activate your account in 7 days

If you have any problems, contact us at help@floodlightproject.org.

The Floodlight Team"

**Comment by ghing** [comment]
This was the same missing setting as #438.  Fixed.
