### ISSUE TITLE
Password reset email needs correct contact address (help@floodlightproject.org)

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#438]
This is an extension of the closed issue [#350](https://github.com/PitonFoundation/atlas/issues/350). The text of the email that gets sent has the wrong contact information.

Right now, it says:

"Hi Jordan,

You requested to reset the passsword for the Floodlight account associated with this email address.

Please go to the following page to reset your password:

http://staging.floodlightproject.org/accounts/password/reset/confirm/9-3c1-675e370aa8279901c4d4/

If you need further help, please contact us at help@floodlight.us.

The Floodlight Team"

The contact email should actually be help@floodlightproject.org.

**Comment by ghing** [comment]
This is a setting (in settings/INSTANCE_NAME.py) and has been updated on staging and dev.
