### ISSUE TITLE
Help page styling

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#439]
I like how Data Engine resolved the giant block of retina damaging orange links on the Help page with a border line and padding between the links. Perhaps something we can implement post-launch? 

![DataEngine help](http://emlis.pair.com/users/emdash//Floodlight/DataEngine_help.jpeg)
Format: ![Data Engine Help page](http://developer.codataengine.com/help)

**Comment by patternleaf** [comment]
@tekhneco , this can be reviewed on deploy: http://deploy.atlas.terrorware.com/en/help/ . may your retinas be ever unscathed.

**Comment by jwirfs-brock** [comment]
This looks great. Should we still make the subject-headings grey instead of
orange? (Both to save our retinas, and because, unlike the questions, they
are unclickable.)

**Comment by wendynorris** [comment]
Nice work! Agree with Jordan that grey subject headings might help cool the page down a bit.

**Comment by patternleaf** [comment]
ok, done: http://deploy.atlas.terrorware.com/en/help/

**Comment by jwirfs-brock** [comment]
Fantastic! I say go ahead and close.
