### ISSUE TITLE
Adjust position and style of layout selector

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#442]
To summarize the motivations for this:
1. With padding, the layout chooser takes up a lot of vertical space,  pushing "content" lower and lower
2. Many users were unclear about what this does

@bpawlak proposed the following solutions:

> Option 1: simply place it up in the section browser bar:
> Option 2: shrink it in size (leave it where it is) and add a label to the drop down: "Layout Template?"
> Option 3: move and shrink:
> Option 4: Potentially integrate it into the active section thumbnail.  May need to change the position of the section thumbnail text

Any of the options that move it are more complicated since it would place the element inside of another element's view and that view may have to be updated to correctly render and handle interactions for the layout selection widget.  "Option 2" is definitely the most straighforward.

I don't think there were ever mock-ups of what these different options looked like.

@jwirfs-brock said:

> I think it needs to have some kind of label. Without that, as a first time user you don't know what it is.
> 
> My preference is for Option 3 (shrinking it and having it in the section nav).

After hearing the different development complexities, @jwirfs-brock said:

> Ok, based on the amount of coding it would take, my next preference would then be Option 2.

@patternleaf, before implementing this, you might want to take a closer look and see what you think is the development pain for moving the widget into the section browser bar.  Before wiring things up, it might be worthwhile to mock up (in images or non-functional HTML) your preferred approach.

**Comment by ghing** [comment]
Note to self: discussion about this is in an email thread with the subject "thoughts on placement of layout chooser?"

**Comment by ghing** [comment]
@patternleaf Let me know if you weren't CCed on the email thread about this and I'll add the analysis here.

**Comment by patternleaf** [comment]
@ghing it is not showing up in my mailbox. please do include it or a link to it here. thanks.

**Comment by patternleaf** [comment]
@PitonFoundation/developers, any objection to something along these lines?

![layout-chooser-1](https://f.cloud.github.com/assets/73439/68819/f9904536-5f43-11e2-9ac3-840c2ae5c13c.png)

**Comment by jwirfs-brock** [comment]
@bpawlak My only concern is that it might get lost if it's on the right hand side. Other than that, I like it.

**Comment by bpawlak** [comment]
Does it have any implications for the implied size limits of the title?

**Comment by patternleaf** [comment]
@bpawlak A user might assume that the title must fit within the text box, but of course this is only a cosmetic change. When the user types past the end, the input will scroll to accommodate.

@jwirfs-brock By lost you mean that folks are likely not to notice it? Any suggestions? We could put layout on the left of the title input. Or, I could imagine that labeling both the title and the layout might visually heighten the sense that they are peers; that each is worth attention. Honestly, I think the purpose of the title input isn't super-clear anyway the first time through.

**Comment by jwirfs-brock** [comment]
@patternleaf Yes, I was concerned that people wouldn't see the layout selector. I can show it to a few people around Piton and see if they have any feedback.

I also agree that the title field, as it is now, is problematic. That should definitely be addressed in our Builder redesign at some point.

**Comment by jwirfs-brock** [comment]
Would it make sense to have the drop-down menu itself a little narrower? I guess it's hard to tell until you see the items inside what the width needs to be.

No one yet has said that they would miss it, but then again, I've been showing it to people who are already familiar with Floodlight.

**Comment by bpawlak** [comment]
Do the example layouts need to be so large?  Can't they be smaller icons?

**Comment by patternleaf** [comment]
the icons could be smaller. also the width of the menu widget doesn't need to match the width of the drop-drown. however if it's too small i'd be more concerned that people would not realize it's there.

another thought below. use current icon instead of text, move it to the left. we could adorn the icon with a tooltip that says "Change Layout".

![layout-chooser-2](https://f.cloud.github.com/assets/73439/69356/d76d9dfc-5f5a-11e2-8354-611f5b467887.png)

**Comment by jwirfs-brock** [comment]
I actually prefer the version that says, "Layout / Side by Side," to the one that is just an icon. I was just thinking we could narrow up the drop-down menu a bit.

**Comment by jwirfs-brock** [comment]
So, something like this:

![layout_selector2](https://f.cloud.github.com/assets/1020518/71701/ac029d4a-5ff3-11e2-9507-553c5eb3e2ac.jpg)

**Comment by patternleaf** [comment]
@jwirfs-brock i think the only thing that bugs me about this is that in your mock-up, the popup widget isn't obviously aligned to anything. would it be ok for it to be narrower, but right-aligned? the title input would probably then be wider as well.

**Comment by jwirfs-brock** [comment]
@bpawlak I think that makes sense. A right-aligned widget would look better.

**Comment by bpawlak** [comment]
:thumbsup:

**Comment by patternleaf** [comment]
@bpawlak @jwirfs-brock this can be reviewed on deploy: http://deploy.atlas.terrorware.com/en/build/

**Comment by jwirfs-brock** [comment]
I like it!

**Comment by bpawlak** [comment]
Ditto

**Comment by patternleaf** [comment]
alright. closing this.
