### ISSUE TITLE
"highlight blue" link color seems a little too lightweight in some contexts

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#449]
maybe it's just me, but a couple of examples: body copy text, story headers on explore page when in tile view. the blue is so light it feels like it not opaque, or somehow indicates some special status for that text. it works for me when in, for example, larger headers that are bold.

**Comment by ghing** [comment]
@patternleaf, is there a style guide somewhere that lists all the colors used in the site, or do I just need to dig through the LESS?

**Comment by patternleaf** [comment]
color definitions are all in variables.less.

**Comment by ghing** [comment]
Here's  a quick list of the blues used in the contexts @patternleaf mentioned:
-  Titles in explore page tiles: `#03CCFE`, defined in explorer.less
- Links in body: `#20C6FD`, (`highlight-blue`), defined in variables.less
- Visited links in body: `#19A3D1` (`visited-blue`), defined in variables.less

FWIW, GitHub uses a pretty light blue for its links, which is (`#4183C4`) as does Twitter's Bootstrap CSS Framework, which uses (`#08C`).

**Comment by ghing** [comment]
Comparison of link colors: http://dabblet.com/gist/4525005

**Comment by ghing** [comment]
It also appears that, in Chrome, the front-page links are matching the `a:visited` selector, even though I cleared my history/cache:

![Screenshot from 2013-01-13 17:47:37](https://f.cloud.github.com/assets/110420/63425/b7f1f5de-5ddb-11e2-98d7-4533a72a8439.png)

I'm not sure if this exacerbates the problem or not.

**Comment by ghing** [comment]
I ran the different colors through the [Colour Contrast Check tool](http://www.snook.ca/technical/colour_contrast/colour.html) with these results (note that for AA compliance, text should have a ratio of at least 4.5:1. For AAA compliance, text should have a ratio of at least 7:1):
- Titles in explore page tiles: `#03CCFE`, defined in explorer.less: 
  *\* Contrast ratio: 1.9:1
  *\* Fails WCAG 2 AA
  *\* Fails WCAG 2 AAA
- Links in body: `#20C6FD`, (highlight-blue), defined in variables.less
  *\* Contrast ratio: 1.99:1
  *\* Fails WCAG 2 AA
  *\* Fails WCAG 2 AAA
- Visited links in body: `#19A3D1` (visited-blue), defined in variables.less
  **\* Contrast ratio: 2.92:1
  *\* Fails WCAG 2 AA
  *\* Fails WCAG 2 AAA

For reference, I tried the Twitter Bootstrap color and got these results:
- Contrast ratio: 3.89:1
- Fails WCAG 2 AA
- Fails WCAG 2 AAA

I'm going to play around to see if I can improve our contrast ratio a bit while still maintaining the general theme of our styles.

**Comment by ghing** [comment]
I noticed that the blue colors in our styles differ somewhat from those in the original PSDs, though the original colors don't fare any better in terms of contrast.

Colors in the original PSD:
- Front-page blue headers: `#33ccff`, contrast ratio of 1.87:1
- Links, headers on explore page:  `#00ccff`, contrast ratio of 1.9:1

The blue in our styles also differs from that in the [style guide](https://docs.google.com/file/d/0B1CQ7Qy70V50NjktMExMamtXYWc/edit):
- Blue from style guide: `#32C5F4`, contrast ratio of 2.01:1

It looks like the different blue color (`#20C6FD`) and color for explore page headers (`#03CCFE`) was introduced in the styles from HTML Burger.

**Comment by ghing** [comment]
Here are how other colors in the style guide work out in terms of contrast ratio:
- Orange (`#F7931D`): 2.3:1
- Dark Gray (`#6B6B6B`): 5.33:1
- Brownish Orange from secondary pallet (`#D27027`): 3.45:1
- Redish Orange from secondary pallet (`#F26821`): 3.1:1

**Comment by ghing** [comment]
@patternleaf, @jwirfs-brock, I made a quick-and-dirty demo of using the brownish orange and redish orange from the secondary pallet of the [style guide](https://docs.google.com/file/d/0B1CQ7Qy70V50NjktMExMamtXYWc/edit).

Brownish Orange (`#D27027`):
- [Homepage](http://dev.atlas.terrorware.com/?trystyle=brownish-orange)
- [Grow Your Skills](http://dev.atlas.terrorware.com/en/grow-your-skills/?trystyle=brownish-orange)

Redish Orange (`#F26821`):
- [Homepage](http://dev.atlas.terrorware.com/?trystyle=redish-orange)
- [Grow Your Skills](http://dev.atlas.terrorware.com/en/grow-your-skills/?trystyle=redish-orange)

The dark gray (`#6B6B6B`), while having great contrast against the white background, didn't differentiate itself enough from the normal text color to work well.

Let me know what you think of these.  I think the "Brownish Orange" is good because it has the highest contrast and also looks more different from the regular orange.

**Comment by jwirfs-brock** [comment]
I think the reddish orange looks nicer. But it is pretty close to the other
orange we use for main links. Would it make sense to scrap the two
different link colors trope, and use the reddish orange for everything?

**Comment by ghing** [comment]
@jwirfs-brock, I think the problem with the colors is that they don't seem to have any kind of consistent semantic value. Currently, how is the function of an orange link different than a blue link?  How is the function of an orange button different than a blue button?  I think we need to resolve that before deciding to go with one color for all links.

I also agree that the redish-brown looks oddly close to the Orange, so we should think about that before just going with it.

**Comment by jwirfs-brock** [comment]
Yes, I agree that we need to figure out the semantic purpose of the colors. When we originally talked about this issue, that was the longer term solution, and we had decided to change the blue to the darker shade as a short-term fix until we figured it out.

If you think now is a good time to address the semantics of the color scheme, we can do that. This would be a good time to involve @bpawlak.

**Comment by jwirfs-brock** [comment]
Personally, I'd rather have all the links be the same color. The one exception I can think of is story titles.

**Comment by patternleaf** [comment]
@ghing @jwirfs-brock i feel like having blue on the page provides a certain harmony of warm/cool that is lost when everything is warm. also, blue is pretty conventional visual language for "this is a link".

regarding semantic value, i could envision having the chrome/megamenu links, buttons, and widgets generally all be orange (referring to the orange in the logo), while any links in copy/content are blue. so the rule would be floodlight chrome is orange, floodlight content is blue. that would include story titles. for reduced retina damage, we might make buttons/widgets gray + orange on hover, or something.

also regarding semantics, i could see cases where we might want to call out a button or content by switching it around—a big blue button, say—_if_ there's only one instance of such a thing on the page.

so i think i'd prefer to keep the two-color scheme, and keep the blue, but modify it for contrast.

**Comment by bpawlak** [comment]
Consistency of link colors is always a good idea; and even if the titles are different, they should be consistently different.  I had referenced the WCAG link colors and contrast issues back when GT was creating the .psd files; it doesn't look like he made any changes...

**Comment by jwirfs-brock** [comment]
I like the simplicity of @patternleaf's suggestion about having application-type links be orange and content-type links be blue.

@ghing were you able to find a blue that meets the contrast recommendations?

**Comment by ghing** [comment]
@jwirfs-brock, I haven't yet found a blue that meets the contrast recommendations. I'll try to work on this today.

**Comment by ghing** [comment]
Ok, here's a summary and links to preview some of the options, including 3 new blues:

| Color Value | Description | Example | Contrast Ratio | Meets WCAG 2 AA | Meets WCAG 2 AAA |
| --- | --- | --- | --- | --- | --- |
| `#D27027` | Brownish orange from style guide | [Homepage](http://dev.atlas.terrorware.com/?trystyle=brownish-orange), [Grow Your Skills](http://dev.atlas.terrorware.com/en/grow-your-skills/?trystyle=brownish-orange) | 3.45:1 | For >18pt font | No |
| `#F26821` | Redish orange from style guide | [Homepage](http://dev.atlas.terrorware.com/?trystyle=redish-orange), [Grow Your Skills](http://dev.atlas.terrorware.com/en/grow-your-skills/?trystyle=redish-orange) | 3.1:1 | For >18pt font | No |
| `#2F99F6` | Close to the style guide blue but with better contrast | [Homepage](http://dev.atlas.terrorware.com/?trystyle=2f99f6), [Grow Your Skills](http://dev.atlas.terrorware.com/en/grow-your-skills/?trystyle=2f99f6) | 3:1 | For >18pt font | No |
| `#2a88db` | Bill's suggestion | [Homepage](http://dev.atlas.terrorware.com/?trystyle=2a88db), [Grow Your Skills](http://dev.atlas.terrorware.com/en/grow-your-skills/?trystyle=2a88db) | 3.72:1 | For >18pt font | No |
| `#007BF6` | A more blue and more saturated than the style guide blue. Doesn't pass WCAG 2, but has higher contrast than Bootstrap | [Homepage](http://dev.atlas.terrorware.com/?trystyle=007bf6), [Grow Your Skills](http://dev.atlas.terrorware.com/en/grow-your-skills/?trystyle=007bf6) | 4.07:1 | For >18pt font | No |
| `#0062F6` | Much more blue and much more saturated than style guide blue. | [Homepage](http://dev.atlas.terrorware.com/?trystyle=0062f6), [Grow Your Skills](http://dev.atlas.terrorware.com/en/grow-your-skills/?trystyle=0062f6) | 5.15:1 | Yes | For >18pt font |

**Comment by jwirfs-brock** [comment]
I like #2F99F6 ("Close to the style guide blue but with better contrast"). Any other votes?

**Comment by bpawlak** [comment]
That one is nice, but I also tried it with #2a88db (slightly darker than 2f99f6, but still same hue and saturation) and it's a little better.

**Comment by ghing** [comment]
I added @bpawlak's suggestion (#2a88db) to the "decision matrix" above and I like it.  A good balance between the original color and being significantly higher contrast.

**Comment by jwirfs-brock** [comment]
Great. Let's go with @bpawlak's suggestion.

**Comment by jwirfs-brock** [comment]
Note that the user story about having a consistent link hierarchy is Issue #514.

**Comment by ghing** [comment]
This is done.  @jwirfs-brock, you can review this on the development instance.

**Comment by jwirfs-brock** [comment]
This looks great.

**Comment by patternleaf** [comment]
yeah, that looks a ton better.
