### ISSUE TITLE
Optimize Explore page loading performance

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#455]
We need to improve the loading speed of the explore page in the initial state and the infinite scroll. Note: Filters are nice and speedy.

**Comment by ghing** [comment]
I'm going to close this as of commit 2ef8a5020a5410e659f64dbff85e9ac486d3d48e

Through caching (using the memcached cache backend), I was able to reduce the number of queries from ~1200 (in about 1200MS) to ~300 (in about 300MS).  On the development server this took page (data) load times from around 30s to 6s (once the caches are warmed up).  On staging (the production server), page (data) load times went from around 12s to around 2s.
