### ISSUE TITLE
"X" in top right of Story Builder tour doesn't actually close -- should either close or remove

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#456]
The "x" in the top right corner of the tour messages doesn't do anything when  you click on it right now.

We should either:
1) Let users close out of the tour by clicking the "x"
2) If we want to force users to view the entire tour, remove the "x"

**Comment by patternleaf** [comment]
that's strange. pretty sure they were working on staging.

**Comment by jwirfs-brock** [comment]
I was using Chrome when looked at it, and had switched to the
Spanish-language version of the builder (although I don't think that should
matter).

**Comment by patternleaf** [comment]
oh, yeah: i was able to reproduce it myself. just have no idea what might've happened. :)

**Comment by wendynorris** [comment]
Having same problem in Firefox just now. Can't close the tour. 

Strange, too, that link hover CSS works on the X. Just doesn't do anything.

**Comment by ghing** [comment]
Closed by 85110427d07f58dc0039ab1d77b8cb7727cfedfd
