### ISSUE TITLE
Users can visit stories through a shortened URL for use when sharing with social media (user story #16)

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#457]
User Story #16

**Comment by ghing** [comment]
@jwirfs-brock I'm assigning this to you for clarification, assign it back to me when you've clarified this.

I can't remember what this means.  Do you mean that we want to use a custom short domain name so URLs will be like http://fldl.it/asASx, or do you mean that URLs should just be shortened when using AddThis to share stories on Twitter and Facebook (in which case, this is essentially a duplicate of #421)?

**Comment by jwirfs-brock** [comment]
Yes, this is just a duplicate of #421. We just need a short url, it doesn't
have to be customized.

**Comment by ghing** [comment]
Closing as duplicate of #421.
