### ISSUE TITLE
A logged in user can make a request to create a new organization (user story #52)

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#458]
User Story #52

**Comment by jwirfs-brock** [comment]
Full analysis is here: https://docs.google.com/document/d/1S9AnEoHeeh65ZOvJV-FYrWxKZo1BeP8eH5DcoNcvaFQ/edit

**Comment by jwirfs-brock** [comment]
Essentially, we want to automate the request process, so instead of a user sending an email with the information that is on the ["Create a Project or Organization" page](http://www.floodlightproject.org/en/project-organization/), they would fill out a form that automatically creates a project or organization.

**Comment by ghing** [comment]
Assigning this to @jwirfs-brock as I'll need copy for the notification e-mail that an Organization/Project owner gets once their Organization/Project has been approved.  Assign it back to me when this has been done.

**Comment by jwirfs-brock** [comment]
@ghing the emails are below. In this version of the project and organization request form, we don't have a featured image, right? There's a line in the emails about adding a featured image that I wasn't sure whether to include or not.  Let me know if you have questions about it.

New organization email

SUBJECT: [Organization name] has been added on Floodlight

[User’s first name],

Hello from the Floodlight team. Per your request, we’ve created an organization for [organization name] on Floodlight.

You can view your organization here: http://floodlightproject.org/en/organizations/ORGANIZATION-SLUG/

Your Floodlight account is now listed as a member of your organization, so when you create and publish stories on Floodlight you will be able to add them to your organization page. You can find instructions for how to do that here: http://floodlightproject.org/en/help/#projects-and-organizations

[If you want to add a featured image to your organization page, please reply to this email with the image attached.]

Please contact us at ask@floodlightproject.org if you have any other questions.

Happy storytelling,
The Floodlight Team

New project email

SUBJECT: [Project name] has been added on Floodlight

[User’s first name],

Hello from the Floodlight team. Per your request, we’ve just created a project for [organization name] on Floodlight.

You can view your project here: http://floodlightproject.org/en/projects/PROJECT-SLUG/.

Your Floodlight account is now listed as a member of your project, so when you create and publish stories on Floodlight you will be able to add them to your project page. You can find instructions for how to do that here: http://floodlightproject.org/en/help/#projects-and-organizations

[If you want to add a featured image to your project page, please reply to this email with the image attached.]

Please contact us at ask@floodlightproject.org if you have any other questions.

Happy storytelling,
The Floodlight Team

**Comment by jwirfs-brock** [comment]
@ghing Copy for submitted organization (after submitting, user stays on "Create a Project or Organization Page" with this message):

**Thanks for creating an organization.**
We’ll do a quick review to make sure everything looks good and send you a confirmation email when your organization page is live in Floodlight.

**Comment by ghing** [comment]
Per a chat with @jwirfs-brock, we should make the following revisions:
- Make description a required field

**Comment by ghing** [comment]
@jwirfs-brock, in c2c6ca938e25181ced51f5d610d1ba80cc3f34d8, I made `description` a required field.  I'm assigning this to you for final review.  If it's okay, please close the issue, otherwise assign it back to me and add a comment about any outstanding issues.
