### ISSUE TITLE
Anonymous user can get embed code from story pages and embed stories (or story excerpts) on their blogs, websites, etc (user story #40)

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#459]
User Story 40

Analysis is at https://docs.google.com/document/d/1E70xygbfMKMDQ0mqExwScG-_LIzIvoXYDCt7qcgQE-0/edit

**Comment by ghing** [comment]
I'm conflicted about the best way to do this and whether to use an IFRAME or Javascript to load the widget.
1. IFRAME

Advantages: Simple for users, more likely to be allowed to be embedded in a variety of contexts.  Works better with Javascript off
Disadvantages: Harder to style to match embedding site, [hard to get it to automatically grow with content](http://stackoverflow.com/questions/2872967/how-to-grow-an-iframe-depending-on-the-size-of-its-contents), [blocks onLoad](http://www.aaronpeters.nl/blog/iframe-loading-techniques-performance) (but the IFRAMEd content will be really lightweight).
1. SCRIPT

Advantages: Easier to style contents to match embedding site, don't have to worry about scaling to height, doesn't block onLoad
Disadvantages: Some user CMSs might now allow this kind of embed.  Somewhat more difficult implementation server-side, probably have to configure CORS on the webserver

I think if I did it this way I'd want to use AHAH to load the widget HTML from the server.  (see http://www.openjs.com/articles/ajax/ahah_asynchronous_html_over_http/, http://microformats.org/wiki/rest/ahah#Send_AHAH_Request)

I think I'm going to try to get things going with the IFRAME because it seems the simplest server-side and most portable.

Also, this is a pretty good summary of most of my own findings: http://codeutopia.net/blog/2012/05/26/best-practices-for-building-embeddable-widgets/

**Comment by ghing** [comment]
I ended up looking at how Twitter, Foursquare and AddThis did this, and universally, they use a Javascript snippet to add another Javascript script, which eventually adds an IFRAME, so I decided this was how I would do it.  This method has the advantage of not blocking onload, degrading to a simple link to the story if Javascript is disabled.

A AHAH solution that writes to the embedding page's DOM directly and auto-resizing the IFRAME height are things I won't do because they're really messy on account of cross-domain issues.

**Comment by ghing** [comment]
Another advantage of using the script embedding method is that it lets us modify the IFRAME code, say if we want to add launching the viewer in Fullscreen mode.

**Comment by ghing** [comment]
@jwirfs-brock , @bpawlak I haven't heard any negative feedback about this yet so I'm closing.  Open a new issue if there are specific issues with the embeddable widget.

**Comment by jwirfs-brock** [comment]
@ghing I tested this again in Wordpress (Corridor website) and Blogger, and it looks like it's working beautifully.

**Comment by jwirfs-brock** [comment]
@ghing It also works nicely on Tumblr. I think we are good to deploy.
