### ISSUE TITLE
Contributor can change publish status of stories from "My Stories" section within "My Account" page (user story #294)

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#460]
User Story 294

If you're smart about this, you can probably knock off #374 at the same time.

I would do this as a generic view in `storybase_story.views` that takes a keyword argument (from the URL conf) to update the story publication status.

So, /stories/SLUG/unpublish/ would unpublish the story /stories/SLUG/publish/ would publish the story, /stories/SLUG/delete/ would "delete" the story (I don't think we should actually delete it, we should just set the status field to deleted)

You can use the same view for all these operations and just set the status based on a keyword argument to the view.

So, a URL conf line might look something like this:

```
url(r'^stories/(?P<slug>[0-9a-z-]+)/unpublish/$',  StoryUpdateView.as_view(), {'status': 'draft'}, name='story_unpublish'), 
url(r'^stories/(?P<slug>[0-9a-z-]+)/publish/$',  StoryUpdateView.as_view(), {'status': 'published'}, name='story_publish'), 
...
```

You would just handle the status keyword argument in the view's `post` method.  You'll also want to be sure you check that the user is authenticated and has permission to update the story (there are hooks in Django and our codebase for that, you just have to call them)

Finally, you'll have to edit `apps/storybase_user/templates/storybase_user/account_stories.html` to link to your new view (you'll use the `ur`l template tag with the `name` you've defined in the url conf).

Useful resources:
- Django URL routing docs: https://docs.djangoproject.com/en/1.3/topics/http/urls/
- Django Generic Views docs: https://docs.djangoproject.com/en/1.3/ref/generic-views/ 
- `apps/storybase_user/views.py` has some examples of using generic views that will be similar to what you'll need to do for this issue

**Comment by ghing** [comment]
Assigning to @patternleaf.  Let me know if you have any questions.

**Comment by patternleaf** [comment]
closed via commits pul request 460 (head at 3a42627).

**Comment by jwirfs-brock** [comment]
Sorry I wasn't more explicit about this before, but there is a loophole/problem with this feature. On staging, you can publish a story for the first time from the "My Stories" page. This allows users to publish a story without agreeing to the legal permissions or choosing a Creative Commons license.

Suggestions for stories that have not yet been published:
- The "Publish" button could link to the Publish/Share step in the Story Builder for that story
- The "Publish" button could be deactivated (only "Build" and "Delete" are selectable)

**Comment by ghing** [comment]
@patternleaf I think the second option (The "Publish" button could be deactivated (only "Build" and "Delete" are selectable) is cleaner to implement.  The way you check for this is if the story's 'published' datestamp is None.  Stories that have never been published will have this null datetimestamp.  Stories that are 'draft' but were once published will have a non-null datetimestamp.

**Comment by jwirfs-brock** [comment]
We don't need to make this update for Iteration 8 because it's a minor change, but at some point in the future, I would suggest having the confirmation step ("Are you sure you want to delete/publish/unpublish '[Story Name]'?" as a pop-up notification rather than a separate page.

**Comment by ghing** [comment]
@jwirfs-brock Eric and I talked about the popup option and have brainstormed some approaches to this.  We wanted to keep it simple for this iteration, but it's something we've been thinking about.

**Comment by jwirfs-brock** [comment]
I'm also now getting an "Unexpected Error" message for a story that I unpublished then republished through the "My Stories" page:

http://staging.floodlightproject.org/en/stories/dataviz-how-to-make-a-bar-chart-in-fusion-tables/viewer/

This story shows up on the Explore page, and you can view its Story Detail page, but when you try to launch the viewer it returns an "Unexpected Error."

**Comment by jwirfs-brock** [comment]
@ghing @patternleaf Agree that for this iteration it's fine to keep it simple and not have the pop-up notification. I'll create an issue for that we can address in a future iteration.

**Comment by ghing** [comment]
@jwirfs-brock Re: "Unexpected Error" - this is an unrelated issue.  Can you open a separate issue?
