### ISSUE TITLE
A logged in user can make a request to create a new project (user story #53)

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#463]
User Story #53

**Comment by jwirfs-brock** [comment]
Full analysis is here: https://docs.google.com/document/d/1S9AnEoHeeh65ZOvJV-FYrWxKZo1BeP8eH5DcoNcvaFQ/edit

**Comment by jwirfs-brock** [comment]
@ghing Copy for submitted project (after submitting, user stays on "Create a Project or Organization Page" with this message):

**Thanks for creating a project.**
We’ll do a quick review to make sure everything looks good and send you a confirmation email when your project page is live in Floodlight.

**Comment by ghing** [comment]
Per a chat with @jwirfs-brock, we should make the following revisions:
-  remove "They can be open to contributions from any Floodlight user, or constrained to a group of authors." from the intro copy
- Make description a required field

**Comment by ghing** [comment]
@jwirfs-brock In 076b9344df3f8f949485058ec4e146cda55c0573 I removed "They can be open to contributions from any Floodlight user, or constrained to a group of authors." from the intro copy and in c2c6ca938e25181ced51f5d610d1ba80cc3f34d8, I made `description` a required field.  I'm assigning this issue to you for final review.  Please close it if it's ok, or assign it back to me if there are issues.
