### ISSUE TITLE
Image captions should be constrained to width of image

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#469]
Take a look at this story: http://floodlightproject.org/stories/officer-hollis-peace-memorial/

Having the captions run to the full width of the viewer looks a bit strange. The captions should only be as wide as the photo they appear under.

**Comment by ghing** [comment]
(Quickly) tested under IE8.  I think that the captions could use some better styling in general, but this update definitely fixes the specific issue with caption width. Deployed and closing.
