### ISSUE TITLE
Users can click a "Share" button to get the embed code for the story widget

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#475]
The social sharing widgets (currently AddThis) should be moved into the popup as well.

The analysis for this is at https://docs.google.com/document/d/1E70xygbfMKMDQ0mqExwScG-_LIzIvoXYDCt7qcgQE-0/edit

This task helps implement #459

**Comment by ghing** [comment]
I pushed the sharing widget generating code to the embed_widget branch on my (ghing) fork the endpoint is /stories/SLUG_OR_ID/share-widget/

Relevant AddThis docs are at http://support.addthis.com/customer/portal/articles/381263-addthis-client-api

Hypothetically, dynamically adding a script tag in the success callback for your AHAH request should cause the special AddThis markup to be turned into the magic widgets.

**Comment by patternleaf** [comment]
closed via commits in pull request 475, head for branch at 64d4a98
