### ISSUE TITLE
Source code appearing in Story Builder

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#476]
Issue discovered by Jon Denzler when editing a previously published story in Chrome. 

![Dog Food Story](http://emlis.pair.com/users/emdash/Floodlight/floodlight%20issues.jon.jpg)
Story: ![Eating Your Own Dog Food](http://www.floodlightproject.org/stories/eating-your-own-dog-food/)

The code does not appear in the Story Viewer.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot.
