### ISSUE TITLE
Homepage rendering funny on an Android tablet

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#478]
This screen shot is from a Samsung 10.1 tablet using Android 4.0.4 standard browser:

https://docs.google.com/file/d/0B82exFJJWyJqbENsNDlPR3JTNE0/edit (portrait view)

https://docs.google.com/file/d/0B82exFJJWyJqZHRMRUcydVY1QlU/edit (landscape view)

**Comment by ghing** [comment]
Closing this for same reasons for closing #479.
