### ISSUE TITLE
Featured stories/featured projects widgets not showing up on Floodlight homepage on Android tablet

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#479]
This screenshot is from when you scroll over from issue #478 (also on a Samsung 10.1 tablet, using Android 4.0.4):

https://docs.google.com/file/d/0B82exFJJWyJqYTBhMGtMWmxST2M/edit

**Comment by ghing** [comment]
I'm going to close this because the homepage layout has changed significantly since this issue was opened.  I looked at the homepage in an emulated samsung galaxy tablet in Chrome and it seemed fine.  We can open new issues for device-based quirks when testing the responsive design.
