### ISSUE TITLE
Connected story prompt -- need to replace "TODO" message

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#481]
On the "make this a connected story" area of the Call to Action section in the Story Builder, need to replace "TODO: Add placeholder for connected stories prompt" with actual prompt text.

@ghing I'll write the prompt text and add it as a comment here.

**Comment by ghing** [comment]
The "TODO" prompt text has been removed. @jwirfs-brock, what should we use as a placeholder? Or is it fine to omit it since this has been "in the wild" without placeholder text for quite some time?
