### ISSUE TITLE
Stories have tags with duplicate names

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#483]
This shows up in the search results.  Tags are listed multiple times, even though they have the same name.  This is because there are actually multiple `storybase_taxonomy.Tag` objects with the same value in the name field that have been added to `Story.tags` for a given story instance.  Need to see if this is just user error or if there's something weird with the UI in the tagging view of the builder.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot.
