### ISSUE TITLE
Call to action overlaps with sharing information on story detail page

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#486]
This only seems to be happening for this story: http://floodlightproject.org/stories/strengthening-neighborhoods/

The call to action is overlapping with the sharing button on the story detail page (when viewing in Chrome -- happens regardless of browser window width).

![strengthening_neighborhoods_screenshot.png](https://f.cloud.github.com/assets/110420/3728/f0ebd1d6-42e0-11e2-971e-d7ebb3de1bed.png) 

(originally at See screenshot: https://docs.google.com/a/piton.org/file/d/0B8WqzzOLSmpXYTNXbzd0WlB3VTQ/edit)

**Comment by patternleaf** [comment]
this is currently staged at http://dev.atlas.terrorware.com/stories/strengthening-neighborhoods/. closing.
