### ISSUE TITLE
Header should have Floodlight "beta" logo

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#488]
See the latest design comps from Geoff Thomas: https://docs.google.com/file/d/0B1CQ7Qy70V50anZidU56Snlvbm8/edit

**Comment by patternleaf** [comment]
i assume the storybuilder logo should also have beta. do we have an original for this? bitmap or vector?

**Comment by patternleaf** [comment]
ok, found the psd for the everything comp in dropbox. that might have what i need.

**Comment by patternleaf** [comment]
note: merged issue #454 (logo subheader hard to read) into this one. commit 85aee8e addresses both.

**Comment by ghing** [comment]
The builder header image should probably get the "beta" in the logo too.
