### ISSUE TITLE
When a user switches site language to Spanish, the Floodlight Spanish logo should appear in the header

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#489]
Spanish logo from Geoff Thomas' latest design comps: 
https://docs.google.com/file/d/0B1CQ7Qy70V50Z1czOEY3eVhrSDQ/edit

(Note: We don't have a Spanish "beta" logo.)

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot.
