### ISSUE TITLE
Text input on Sign In page should be non-italicized 

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#490]
Italics are hard to read. Text should be non-italicized when user types in their email address/login.

**Comment by jwirfs-brock** [comment]
Keep placeholder text italicized.

**Comment by patternleaf** [comment]
@jwirfs-brock Are we using placeholder text anywhere except in the builder at the moment? If so could you direct me to it? thanks.

**Comment by jwirfs-brock** [comment]
Nope, it's only in the Story Builder.

**Comment by patternleaf** [comment]
@jwirfs-brock available for review on staging.

**Comment by jwirfs-brock** [comment]
Looks good.
