### ISSUE TITLE
issues with explore page view mode buttons in IE8

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#501]
- Tile button does not have a background—just shows up as Tile, and not clickable. (i suspect bad markup)
- top of explore masonry overlaps bottom of mode buttons

**Comment by ghing** [comment]
I'm seeing some version of this in IE9 as well.  I think it's related to the positioning of the "show more" link.

Here's how it looks in Chrome:

![show_more-chrome](https://f.cloud.github.com/assets/110420/365571/0f94b0bc-a24f-11e2-8dc1-01c0df6feeb7.png)

And here it is in IE9:

![show_more-ie](https://f.cloud.github.com/assets/110420/365572/19f06d58-a24f-11e2-9f4d-42ee6a7b10aa.png)

**Comment by ghing** [comment]
@patternleaf, I'm not seeing "Tile button does not have a background" in IE9.  Did you report this in IE8 because you saw it there but not in IE9, or just because IE8 is the version of IE you happened to have available?

**Comment by mgrayinnovation** [comment]
Leaving as a tweak, 2/25/15

**Comment by mgrayinnovation** [comment]
Closed and moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
