### ISSUE TITLE
Add section symbol (+) is really hard to see -- should be a darker color

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#506]
This is based on feedback from a user (Maisha). The "+" symbol for adding a section in the Story Builder should be darker, perhaps a dark grey.

**Comment by bpawlak** [comment]
I sent out an email a while back describing how this could look/operate.  I redid it and posted it to https://docs.google.com/drawings/d/1FIMPgmV38LDZtA0pSPyosCChtFyiTkkWb6-oPrKYq1k/edit

**Comment by jwirfs-brock** [comment]
@bpawlak I like that solution because it addresses both the visibility of the "add section" feature and the clickability of it.

**Comment by patternleaf** [comment]
i have bill's suggestion implemented (with a css transition, even!), but i was wondering what you @PitonFoundation/developers think about some subtle affordance for the spacers. the fact that there's no visual cue that you hover in order to create a new section has always bothered me a little. here's an implementation of it (sorry for pixely-ness of it; snapped in firefox which doesn't support retina yet):

![spacers](https://f.cloud.github.com/assets/73439/6606/1dfcae36-43ca-11e2-80cc-d1f38f19d3de.png)

**Comment by jwirfs-brock** [comment]
Did @bpawlak's initial mock-up have a non-hover state? What if the non-hover state included a subtle "+" that gets darker (or the background gets darker) when you hover (Bill, that might have been your original suggestion)?

**Comment by patternleaf** [comment]
> What if the non-hover state included a subtle "+" that gets darker (or the background gets darker) when you hover (Bill, that might have been your original suggestion)?

sounds good to me. sorry if that was a part of the suggestion and i didn't see it.

**Comment by bpawlak** [comment]
No, I didn't actually include a non-hover state; thought it was covered by the tour/help info.  I think it works, however.  So, when you actually hover between the two sections, the container (as shown above) expands to be darker in color and has a visible + sign w/ tooltip (with the idea being that you can click anywhere in the darker area?

**Comment by patternleaf** [comment]
@bpawlak @jwirfs-brock @tekhneco @ghing: this is currently staged on [http://deploy.atlas.terrorware.com/en/build/](http://deploy.atlas.terrorware.com/en/build/). one note: the tooltip behavior, when attached to the whole widget, interferes with the CSS transition. so currently the tooltip is only attached to the "+" in the widget. however the whole button will respond to a click. i'm only _slightly_ attached to the transition :), so the tooltip can be attached to the whole thing instead.

**Comment by jwirfs-brock** [comment]
Huh, yeah I did find it odd that the tool tip only shows up when you are over the "+" icon. Otherwise, I think it looks really slick. Eric, would it be possible for you to show us what it would look like without the transition, and with the tool tip displaying over the entire widget?

**Comment by bpawlak** [comment]
I'm not seeing it on deploy... tried it on Chrome and Firefox.  No tooltip, no transition.  However, I would think that just having the tooltip on the + sign isn't a big enough target area for the tooltip.

**Comment by patternleaf** [comment]
@bpawlak hmm. hard refresh? also i believe the story must be saved for the add new section widgets to be visible.

@jwirfs-brock, sure; will update when the version without the transition is up.

**Comment by bpawlak** [comment]
Looks like I had to save the story before the add/delete sections functionality shows up (is this by design or just the test instance)?  In any case, I do like the transition.  That said, if we're going to add those niceties, then we should probably add them to scrolling (each click of scroll should slide everything over by a whole section), deletion of a section (should fade or transition out), etc.

**Comment by jwirfs-brock** [comment]
@bpawlak You aren't the only one who forgets to add a story title before trying to dive into the builder. I do that all the time, too. This will hopefully be addressed with our updates to the Story Builder work flow, based on our discussion when Geoff was in town.

**Comment by patternleaf** [comment]
@jwirfs-brock @bpawlak the version without transitions but with full-frontal tooltip action is now up on deploy.

i agree that adding niceties would be better done in many places rather than seemingly randomly in one.

**Comment by patternleaf** [comment]
i need to switch the server over to another branch. attaching a screenshot for reference. the widget just pops open and closed without fuss and the whole thing is clickable and triggers the tooltip. let me know if you need to see it in action or if we're good to go with this.

![add-section](https://f.cloud.github.com/assets/73439/11627/c4c4df62-455b-11e2-8ab7-5dd8137be2aa.png)

**Comment by patternleaf** [comment]
@jwirfs-brock assigning to you for comment. please assign back to me if needed. note that this fix is _not_ currently staged. if you need it staged to review, let me know.

**Comment by jwirfs-brock** [comment]
@patternleaf This is good to go. Assigning back to you...

**Comment by patternleaf** [comment]
great. thanks, @jwirfs-brock . i'm going to make a pull request for this and close it.

**Comment by ghing** [comment]
@bpawlak Reports that sections are getting added to the end of the section list instead of in the position where the "+" button is clicked.  I was able to replicate this. 

![image003](https://f.cloud.github.com/assets/110420/22320/57fd2f6a-49f7-11e2-8f8b-7ff72af27c55.jpg)

**Comment by ghing** [comment]
I added [comments to the pull request](https://github.com/PitonFoundation/atlas/commit/617432a02ad05aec666c68697bd19a7efffbb36f#L4L2547) that identify the changes that cause the problem. It's an easy fix, but I wanted to confer with @patternleaf rather than just fixing it myself.

**Comment by ghing** [comment]
Assigning to @jwirfs-brock for final review.

**Comment by jwirfs-brock** [comment]
Looks good.
