### ISSUE TITLE
Help drawer in Story Builder needs "View the tour again" button

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#508]
This came out of our recent discussion on user feedback (https://docs.google.com/document/d/1eBYGQJJ9G0sWBQS2QNPYD1bP6fC3LxTQGIODfSYT-qw/edit). It's also User Story 297.

**Comment by ghing** [comment]
Assigning to @jwirfs-brock for feedback on button placement and styling.  Would also love to hear from @bpawlak on this.

**Comment by ghing** [comment]
Did some basic wiring up of this feature in ef2363672d49235ee91fb9f46a298e6e8b47b66a, deployed on dev

**Comment by ghing** [comment]
@jwirfs-brock Should this be visible during all workflow steps, or only during the build step?

**Comment by bpawlak** [comment]
If we show it during all steps, we'd need different content as the "tour" of the tagging page is different enough (no section browser, for example) from the rest if the builder.

**Comment by ghing** [comment]
@bpawlak, I was thinking more that if it was on a different workflow step, it would take the user back to the build step before showing the tour, but that might be a confusing side-effect and probably not desirable. The more I think about this, I'm leaning toward only showing it in the builder.

**Comment by bpawlak** [comment]
No, I don't think it should take them back to the builder, especially if they're done building... So it should just be on the builder section....

**Comment by jwirfs-brock** [comment]
Agree that it only makes sense during the build step. Does that add coding
complexity?

**Comment by bpawlak** [comment]
I think the button styling is fine (it's consistent with the rest of the app), but I wonder if it calls _too_ much attention to itself at the top like that?  It kind of takes precedence over the rest of the help text which, arguably, is more important, especially if someone _has_ viewed the tour before...

**Comment by ghing** [comment]
@bpawlak, I'll try making the button the gray style and making it a little smaller

**Comment by ghing** [comment]
@bpawlak, I made the button gray, smaller and right-aligned it.  Check it out in the attached screenshot or on http://dev.atlas.terrorware.com/ Does this address your concerns?

![less_prominent_tour_button](https://f.cloud.github.com/assets/110420/22201/21bb8156-49f0-11e2-8acf-a303b6298571.png)

**Comment by jwirfs-brock** [comment]
One suggestion I had was that the tour is blue (very bright blue!), so if the button were similarly styled it might be a visual cue reminding the user that it's about the tour. @bpawlak and @ghing if you think that would look too loud, we can keep it grey.

By the way, I also showed this to Brigid to get some quick feedback. Her general sense was that she doesn't really notice the Help or Asset drawers, so she'd like to see the tour button somewhere else. We don't really have a lot of room elsewhere, so it's OK in the drawer for now. When we change the workflow steps, we may want to reconsider this.

**Comment by ghing** [comment]
@bpawlak and @jwirfs-brock,

Check out the latest pass, now up on dev.

As Bill suggested, I changed the button to an icon, but kept the blue as a reminder.  It's noticeable, but less competitive with the help text.  In order to make this more noticeable, I added a step to the tour that pointed out that the tour could be shown again using the icon (how meta).

![show_tour_again_icon](https://f.cloud.github.com/assets/110420/22990/492365e2-4a1d-11e2-8ee2-d291e1136d1e.png)

**Comment by bpawlak** [comment]
I suggested to Geoff that perhaps a small, light blue (same color as tour) icon (maybe that looks like a speech bubble since that's what we're using for the tour) either as part of (or instead of) the button, with a tooltip?

**Comment by jwirfs-brock** [comment]
I like the icon! Looks good.

Without the tool tip (which I'm not seeing now on dev), it's too subtle. I like @bpawlak's suggestion of a tool tip, and maybe also small text underneath the chat bubble that says "Tour."

**Comment by jwirfs-brock** [comment]
Oops, I am seeing the tool tip. It's just not styled the way the others are, so I missed it at first.

**Comment by ghing** [comment]
@jwirfs-brock, I did another pass, visible on dev, where I added the text "Tour" and the fancy tooltips.

**Comment by jwirfs-brock** [comment]
@ghing I think this looks great. It's good on my end.

**Comment by ghing** [comment]
@jwirfs-brock This is done and staged.  The only changes I made since yesterday are back-end stuff to ensure it doesn't show up in other workflow steps.  Feel free to take another pass and reopen if you find anything weird.
