### ISSUE TITLE
IE8 XP: JS error when uploading image in PhotoVoice builder

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#510]
1. begin photovoice story builder
2. create a summary, etc
3. in Image and Text stage, upload an image

result: "detachEvent is null or not an object", views.js#2206

While the image is uploaded successfully and appears in the story, the script is halted so nothing appears to happen in the builder.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot.
