### ISSUE TITLE
Clean up Publish/Share page by removing orange buttons, adding numeric headings (user story #298)

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#515]
User Story #298

**Comment by ghing** [comment]
Some of the details about this issue are in the document [User feedback discussion notes 11/20](https://docs.google.com/document/d/1eBYGQJJ9G0sWBQS2QNPYD1bP6fC3LxTQGIODfSYT-qw/edit)

**Comment by ghing** [comment]
Currently, when selecting the featured image in the Publish/Share view there are a couple of pieces of functionality:
- Viewing the currently selected featured image (if there is one)
- Uploading a new image (or specifying a URL) for the featured image
- Selecting an asset associated with the story for the featured image

All these pieces of functionality are available, but getting to them is a bit convoluted and is achieved by clicking on different orange buttons.  

To clean up this interface a bit, I thought of using pills, similar to [Bootstrap's](http://twitter.github.com/bootstrap/components.html#navs).  Pills work like tabs, but the typical tab layout and styling seems a bit off to me when not at the top of a layout.

So the pills would be listed as:

Current | Add a new image | From your story

Clicking on the individual pill would reveal the interface to do each task.

If a particular piece of functionality wasn't available, the pill would not be listed.  So, if no image assets have been associated with the story, the "From your story" pill wouldn't be shown.

Also, I'd like to display the default image for stories when the current pill is selected when no featured image has been specified, because that's what will be used and it's probably fair to let users know that.  Hopefully it will compel them to use a better image.

@PitonFoundation/developers, @PitonFoundation/owners what do you think of this proposal?

**Comment by bpawlak** [comment]
Another way to handle it is to show them the featured image with the option to "Change Image."  Clicking that brings up a dialog that asks for an upload, a URL or a means to choose from the story.  Save and cancel buttons.

**Comment by ghing** [comment]
@bpawlak, that's sort of how it works now, though I think the styling of the "Change Image' button is confusing.  I think that showing the default image will make the "Change Image" option make more sense.  However, I'm still not sure of the best way to toggle between the "Add a new image" and "select image from a story" dialog.

**Comment by ghing** [comment]
In the accepted suggestions for cleaning up the publish/share view (see https://docs.google.com/document/d/1eBYGQJJ9G0sWBQS2QNPYD1bP6fC3LxTQGIODfSYT-qw/edit#bookmark=id.ia0i47wa2kip) @bpawlak suggests moving the "Publish" button to the bottom of the page.

I think this makes sense, but one issue is that the "Publish" button currently gets replaced with "View" and "Unpublish" buttons once the story has been published:

![publish_share_published](https://f.cloud.github.com/assets/110420/92461/a3b3d0f2-65d2-11e2-815f-3a73ef1311a9.png)

It doesn't seem to make sense to move these buttons to the bottom along with the publish button. Should the "View" and "Unpublish" buttons remain at the top? Alternately, they could go to the right, above the sharing information.

**Comment by ghing** [comment]
Assigning to @bpawlak to get his feedback on toggling between adding a new image and selecting an image from a list as well as the placement of the "View my story" and "Unpublish my story' buttons.  Please assign it back to me after you've chimed in.

**Comment by bpawlak** [comment]
I think the View Story and Unpublish buttons should probably remain at the top... @jwirfs-brock ?

**Comment by jwirfs-brock** [comment]
@bpawlak @ghing I think it makes sense for the buttons to stay at the top once the story has been published. 

I'm having a little trouble visualizing this, so just to make sure I'm clear: initially the "Publish" button would be at the bottom, below the legal agreement, license, and featured image selection, but then after publishing it would appear at the top?

Would it make sense to keep a publish/unpublish button at the bottom as well, just in case people are accustomed to looking at the bottom of the page for it? If it's below the fold, I don't think it would be redundant to have it both places.

**Comment by jwirfs-brock** [comment]
@ghing @bpawlak I think the pills suggestion sounds good. Is there an example you can share?

**Comment by jwirfs-brock** [comment]
@ghing @bpawlak Right now, the "select an image from your story" option doesn't appear if you don't have one -- is that how the pills would work, where you would only see "upload a new image" (because there wouldn't be a default image and you wouldn't be able to select one from your story)?

**Comment by jwirfs-brock** [comment]
@ghing Ooops, I missed the link to Bootstrap. You don't need to post another example. Sorry for the confusion.

**Comment by ghing** [comment]
The default featured image is now set to the first image asset used in the story.  @jwirfs-brock, can you verify that the publish step now works as expected?

**Comment by ghing** [comment]
This has been in production for a week, with no objects from @jwirfs-brock. Closing.
