### ISSUE TITLE
When a user opens a story in the Story Viewer, one section is displayed per view. Reader can navigate between sections using horizontal arrows. (user story #305)

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#518]
User Story #305

**Comment by patternleaf** [comment]
@jwirfs-brock @ghing @bpawlak could you all check this to see if it's doing the right thing? on deploy, eg,

http://deploy.atlas.terrorware.com/stories/charting-a-new-course-in-sheridan/

Couple of thing that might be worth addressing while I'm in there: 
- the next/forward buttons move around a little. either because the forward or next button disappears when not applicable, or when a scrollbar appears in the view. would be good to make them be pinned in place.
- for that matter, it might be nice to disable the fwd/next buttons rather than remove them. to minimize visual confusion.
- i noticed that the table of contents will have blank spots when sections have no header element. perhaps we insert a placeholder [Section x] when that happens?

**Comment by jwirfs-brock** [comment]
The position of the previous/next buttons didn't bother me. Pinning them in
place sounds like a good option, though. I'm not sure what you mean by
disabling them -- how would you navigate between sections?

In this particular story, sections with no header are actually just
extensions of the previous section. Essentially, it's a two-part section.
So having "Section X" doesn't really make sense. But not every story will
be like that, so I think generally that suggestion will actually work. Can
we try it and see how it looks?

Along those lines, would it make sense to have a 2/10 counter that tells
you which section you are on and the total number of sections (maybe directly underneath the previous/next
buttons)? Now that you can't scroll throughout the entire store, there's no
visual cue that tells you how far you've gone or how far you have left to
go.

Another thing I noticed was that if you are using the table of contents to
navigate, it's a bit awkward to have to close it after you've jumped to a
section. Could we have it collapse if you click anywhere else outside the
table of contents?

**Comment by bpawlak** [comment]
I like the idea of "2/10" counter _and_ having the TOC collapse if you click anywhere outside of it.  I always assumed that's how it worked (earlier build?) and never actually tested it.

**Comment by ghing** [comment]
I think we should use the "Section X" workaround for now and see how many stories have this case.  I think people creating stories with sections without titles is a result of the scrolling view of the story and that they'll be less likely to do this when sections are viewed one at a time.  If we find users are still creating sections without titles, we can either force them to be titled in the builder, or try to figure out what the most common case is for users doing this and build our logic around that.

The table of contents should definitely close after clicking a section. 

After our conversation last week, my preference is to have the next/prev links be enabled and disabled when needed rather than being shown and hidden.

**Comment by patternleaf** [comment]
i'll also add: would be nice to be able to navigate via left/right arrow keys.

**Comment by patternleaf** [comment]
also: highlight current section in toc (5223f76)

**Comment by patternleaf** [comment]
@ghing @jwirfs-brock @bpawlak Hey all - could you review on deploy? 

http://deploy.atlas.terrorware.com/

I think i've got everything in there except that some footer controls are still nudged over when a scroll bar appears. This bugs me but not enough to spend time on it right now. :)

**Comment by jwirfs-brock** [comment]
This looks good to me. I really like the styling on the table of contents
-- it's a great improvement.

**Comment by patternleaf** [comment]
Would anyone else like to check this out? It's not currently available on deploy, but I could make it so. 

If not, I'll close the issue.

**Comment by patternleaf** [comment]
@bpawlak: it's staged on deploy now.

**Comment by bpawlak** [comment]
Nice!  I think we need to create an issue for how we'll handle sections without titles, both in the story viewer and table of contents.  Check the table of contents for this story: http://deploy.atlas.terrorware.com/stories/charting-a-new-course-in-sheridan/  "Section 2" "Section 6" etc...

**Comment by patternleaf** [comment]
Closing this. @bpawlak there was some discussion in this issue for how to handle those. I'll leave it to you to create a new issue for new analysis.
