### ISSUE TITLE
Background behind story viewer modal should be greyed/blurred, unscrollable

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#519]
When you launch the story viewer from the story detail page, the area behind the modal window should look unclickable (greyed or blurred out). Also when you should only be able to scroll within the story viewer window. Right now,  you can actually scroll the area behind it, which is a bit awkward.

Brigid will be providing a mock-up of this.

**Comment by ghing** [comment]
Update: SimpleModal creates an overlay element to blur the background.  We just need to style it.  It might be enough to adjust the `opacity` option when creating the modal.  See the SimpleModal docs at http://www.ericmmartin.com/projects/simplemodal/

I think to adjust the scrolling we'll have to do this ourselves in  the appropriate JS event handler.

**Comment by ghing** [comment]
Edited original issue to clarify.

**Comment by ghing** [comment]
Assigning to @jwirfs-brock  for final review.

**Comment by jwirfs-brock** [comment]
This looks good (tested in Firefox, Chrome, and IE9).
