### ISSUE TITLE
Non-text assets (image, video, audio, chart, table) should have border in story viewer

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#520]
Non-text assets appear as if they are floating/haphazardly placed in the story viewer. A subtle border  around the asset and its caption (light grey, maybe? and reminiscent of how they appear in the builder) should help.

Brigid will be providing a sketch.

**Comment by ghing** [comment]
@jwirfs-brock, did you ever get the sketch for this from Brigid?

**Comment by ghing** [comment]
It looks like all non-text assets get wrapped in a `<figure>` tag that could be used to apply a border style.  We might want to add a class to this to make the CSS selectors a little more flexible.  If we wanted to add an additional wrapper element, the place to do it would either be in the `storybase_story.templatetags.story.container` function or in any of the `storybase_asset.models.Asset.render_html` implementations.

We'll probably have to modify the JavaScript fix for #469 to resize the figure container to the width of the image.

**Comment by jwirfs-brock** [comment]
@ghing Here is the design treatment Brigid did for non-text elements (it's a downloadable PDF):

https://www.box.com/s/f7c5dp3hy7dzkxrpo79s

But I don't think the colors and drop-shadows fit with the site aesthetic, so we should go a different route (either asking Brigid to redo it, or using elements from the existing style guide and comps from Geoff Thomas).

**Comment by ghing** [comment]
Brigid's treatment inline:

I agree it's a bit too "heavy":

![Screenshot from 2013-01-08 14:52:14](https://f.cloud.github.com/assets/110420/51579/65bf692c-59d5-11e2-9671-9594aa35b6e8.png)

This is the closest thing I could find from the "everything" page that Geoff T. provided:

![Screenshot from 2013-01-08 14:49:08](https://f.cloud.github.com/assets/110420/51582/88001400-59d5-11e2-8af2-78b949c9f326.png)

I'm not sure if it addresses the issue though, and doesn't help with non-captioned items.

This is a very minimalist approach taken in the NYT Snowfall interactive story:

![Screenshot from 2013-01-08 14:55:11](https://f.cloud.github.com/assets/110420/51589/eeae8fe2-59d5-11e2-879c-94ead1103840.png)

Though, they generally use whitespace to set images apart.

**Comment by ghing** [comment]
@jwirfs-brock, can you point me at examples of stories that really suffer from the assets not being visually identified somehow?

**Comment by jwirfs-brock** [comment]
I also like the minimalist aesthetic. Originally, I was just thinking a thin grey line or a light grey box.

**Comment by jwirfs-brock** [comment]
This was a design critique that Brigid originally brought up. Here are some stories where I think the lack of a border makes the layout feel a bit off:

http://floodlightproject.org/stories/-14/
http://floodlightproject.org/stories/charting-a-new-course-in-sheridan/
http://floodlightproject.org/stories/officer-hollis-peace-memorial/

**Comment by jwirfs-brock** [comment]
Here's one where Brigid added her own borders and created her own layers (a good example of a user hacking the template -- which I think is great):
http://floodlightproject.org/en/stories/building-peace-one-pole-at-a-time/

**Comment by ghing** [comment]
Example of a subtle border around assets:

![asset_border_in_viewer](https://f.cloud.github.com/assets/110420/55038/48678aae-5ab0-11e2-87a9-d79efa75e9fd.png)

**Comment by ghing** [comment]
@jwirfs-brock Any update on whether the border is a keeper?

**Comment by jwirfs-brock** [comment]
Haven't heard back from Brigid yet... I'll give you an update later today.
