### ISSUE TITLE
Homepage layout broken for logged-in admin users

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#526]
I'm guessing this is related to the toolbar ("+" icon in the upper-right-hand corner) that Django CMS adds to the layout.

I'm not seeing this in my local development instance, so this might have been introduced in #523.

![broken_homepage_layout.png](https://f.cloud.github.com/assets/110420/4140/2ca9342a-42fa-11e2-8fd4-89a2c269bcbb.png)

**Comment by patternleaf** [comment]
I don't think this is an issue anymore. @ghing can you confirm?

**Comment by ghing** [comment]
@patternleaf, I think this is still an issue, and not just on the homepage.

**Comment by patternleaf** [comment]
@ghing I'm not able to reproduce ... am I missing something?

**Comment by ghing** [comment]
I'm not able to reproduce this any more either.  I thought I saw it recently, but apparently not.  Closing.
