### ISSUE TITLE
"View all stories" button on project and organization pages is hidden below the fold (at bottom)

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#531]
@tekhneco pointed out that people are missing the "view all stories" button on projects and organizations because it's at the bottom of the page. Also, the spacing of the page (with the summary and featured image layout on top) can push the stories below the fold on smaller screens.

Easiest fix: Move the "view all stories" button to just below the project/organization summary.

More complicated/long-term fix: Do we want to reconsider the layout of this page to include the list of recent stories near the top? @bpawlak what are your thoughts? I know you aren't a fan of the sliders on the homepage, but we could include a slider of stories from that project here. Or we could have something more like a two column layout.

Here's what the the project page looks like now:
![proj_page1](https://f.cloud.github.com/assets/1020518/8851/d2c9efee-4489-11e2-9c02-f6a9633befc7.png)

The "view all stories" button at the very bottom of the page:
![proj_page2](https://f.cloud.github.com/assets/1020518/8853/dedb08ae-4489-11e2-93cd-16dbb0a3b0dd.png)

Here's what a simple solution might look like ("view all stories" bottom at the top):
![proj_page3](https://f.cloud.github.com/assets/1020518/8855/e97db022-4489-11e2-9847-8af3de2eeebf.png)

I suggest we do the quick-fix soon (iteration 9 or 10), and hold off on a potential re-design for later iterations.

Thoughts?

**Comment by bpawlak** [comment]
I agree.  Earlier prototypes of the Project or Organization page showed a more condensed version of the story list that could work (esp. when combined with a bright blue button - http://clients.inovdesigns.com/floodlight/explore_organizations_piton.php), but moving it up will make it that much more salient.
