### ISSUE TITLE
A user can add two assets to the same section and container

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#535]
This is likely to occur if the user is editing the same story in multiple tabs.  

The easiest way to fix this would be to fire an error when the user tries to add an asset to a place that already has one.

It would be cool to poll for (or use websockets) changes and update all open builders with the changes.

For now, I'm going to implement error handling with a warning for users to check if the builder is open in another browser window and suggesting that they reload their browser.  Syncing updates across browser windows might be a little out of scope for this iteration, but I'm going to at least investigate the implications.

**Comment by ghing** [comment]
To replicate:
1. Create a new PhotoVoice story (though this error isn't exclusive to the PhotoVoice template)
2. Enter a title so that the story autosaves
3. Open the story builder for your newly created story in a second browser tab or window
4. In the first tab:
   - Navigate to the "Image and Text" section in the section list
   - Add asset content to the left container
5. In the second tab: 
   - Navigate to the "Image and Text" section in the section list
   - Add asset content to the left container
6. In either tab, click on the "Preview" link

**Comment by jwirfs-brock** [comment]
In the fix for #653, it looks like any assets created which two tabs were open are blank. (At least, both of those stories have blank sections.) If users now attempt to edit those stories in the Builder (and do so in just one tab/window/browser), will they be able to repair the missing assets? I'd like to follow up with them about how they can make sure their story looks good.

**Comment by ghing** [comment]
@jwirfs-brock, The users won't be able to re-select an appropriate asset in the builder until I clean things up on the back-end.

**Comment by ghing** [comment]
I think that I can do this with a [unique_together](https://docs.djangoproject.com/en/dev/ref/models/options/#unique-together) constraint on the model with `section`, `container` and `weight` fields defining the constraint.  This would prevent having the same asset assigned to a section multiple times, but right now I can't imagine a use case where we'd want to support that, so I think it's ok.

I like this strategy because it saves an additional query to check whether a uniqueness constraint is met before saving the model.

I'm going to try to query the database to see if I can find any published assets that don't meet this uniqueness constraint.

**Comment by ghing** [comment]
This code finds sections with assets that violate the constraint:

```

from storybase_story.models import Section, SectionAsset

for section in Section.objects.filter(story__status__in=("published", "draft")):
    seen = {}
    for sa in SectionAsset.objects.filter(section=section):
        key = "%s:%d" % (sa.container, sa.weight)
        if key in seen:
            if seen[key] == 1:
                # First time we run into conflict, show a message
                print "multiple assets found for section %s (%s), container %s and weight %d in story %s (%s)" % (section.title, section.section_id, sa.container, sa.weight, section.story.title, section.story.story_id)
            seen[key] += 1
        else:
            seen[key] = 1
```

There aren't a terrible number of them.  The majority are old stories, created through the Django admin, but a few are old

I think this can be fixed with a data migration or manually cleaning things up.  There doesn't seem to be a legitimate case where the uniqueness constraint described above holds true.

**Comment by ghing** [comment]
It looks like [unique_together might not prevent duplicates outside of the admin](http://stackoverflow.com/questions/8844283/django-unique-together-not-preventing-duplicates).

Testing this ...

**Update:** `unique_together` seems to get honored when calling `Model.save()` by raising `IntegrityError` when the constraint is violated.  This is the way that I'm checking this constraint.

**Comment by ghing** [comment]
This is mostly working other than further testing of the required data migration with production data and a little bit of polish.

This screencast shows the current behavior of the fix: http://www.screenr.com/lbu7

@jwirfs-brock, I'm assigning this to you to get some feedback on 2 items.  Please reply and assign back to me.
1. Microcopy for the error message (see the screencast above to see how it appears).  Currently it says:

> Could not add your asset to this container. This is probably because you already did so in another window. Hold tight while we refresh this section's assets ...

I think this could be better, but I'm not sure how.
1. How to deal with users and the data migration

I want to enforce the one asset per section container at the database level.  However, in order to put this constraint in place we have to first clean up existing section/asset/container associates that violate the constraint.  There are two scenarios that two scenario where this has happened.  The first is old stories created in the Django admin.  The other is assets added in a way that triggers the bug described in the original posting of this issue.  I've written a data migration that cleans things up, but it will alter users data.  In particular, it will remove the older assets from a section/container.  It keeps them associated with the story, so the user should still be able to access them via the assets drawer.  This only affects a handful of stories/users that are published, but could affect a few dozen unpublished assets.  Do you think we need to let users know that their stories are being altered?

**Comment by jwirfs-brock** [comment]
@ghing One quick clarification question on how this works -- so it actually refreshes the assets after the user gets the error message? That is, will they see the asset they already added in the first window in the window?
1. I think the error message is pretty good. Small suggestion:

> Oops, couldn't add your asset here. This is probably because you already did so in another tab or window. Hold tight while we refresh this section's assets.

And then, depending on how the refresh works, instructions for what to do if they don't see the asset appear. (Should they close that window and go back to the first? Do a hard refresh?)
1. For the problematic existing assets...
   a) Can you send me a list of the older ones created in Django admin? Once you've cleaned those up via the data migration, I can just check the stories to make sure everything looks good and then fix as needed.
   b) One the one hand, I don't want to bug users needlessly, if their story's appearance hasn't changed. On the other hand, it's probably good practice to tell users what happened, even if it didn't affect the way their stories look.  Can you send me a list of those problematic user-created assets? I think that will help us decide what to do. I can check and see if it's from a story that has already been published and appears fine (in which case we don't need to contact them them), or if it's a draft story (in which case they may be hoping to use that asset, and I will contact them).

**Comment by ghing** [comment]
@jwirfs-brock, to answer your questions:

>  so it actually refreshes the assets after the user gets the error message? That is, will they see the asset they 
> already added in the first window in the window?

The fix does refresh the assets after the user gets the error message, so they see the asset they originally added (in the first window or tab) and should be able to keep working on that section in their current window.

> For the problematic existing assets... a) Can you send me a list of the older ones created in Django admin? 

Sure.

>  Can you send me a list of those problematic user-created assets? 

Sure.
