### ISSUE TITLE
IE9: occasional "undefined" alert box after logging in or exiting builder

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#536]
Based on the report in #416. 

> After signing in, before getting redirected to the “My Account” page, I got a pop-up message/error that said “undefined.”

and later:

> When I clicked “Exit” to get out of the Story Builder, I got the same “undefined” error message as when I first logged in.

This was reproducible in my tests, but not reliably.

**Comment by ghing** [comment]
I've run into this too.  This seems to be only for logged in "administrator" users who see the Django CMS toolbar.  For normal users, I don't think they see the "undefined" popup.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
