### ISSUE TITLE
IE9: slider plugin printing logs to alert box in certain circumstance

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#537]
From comments in issue #416:

> After I clicked “OK,” I got a message that said, “[cycle] terminating: zero elements found by selector.” When I clicked “OK” on that message, it just re-opened. I had to “x” out of it to get back to the FL homepage.

This was following a series of steps during which a known bug existed. It's possible this behavior was caused by this. I wasn't able to reproduce this either before or after fixing the main bug in #416.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
