### ISSUE TITLE
IE9: builder Template Selection page formatting is wonky

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#538]
Looks like a float/width/flow issue. cf #416 for screenshot.

**Comment by jwirfs-brock** [comment]
@patternleaf I'm now seeing this in Chrome and Firefox, too.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
