### ISSUE TITLE
Add Google Analytics Events script to specific pages

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#539]
Wendy is developing a list of GA events to track user paths, UX stalls, help drawer visits and conversions. Some events will need script added to the page code. 

Will turn over assignment to @ghing after reviewing GA events list with @jwirfs-brock on Monday.

**Comment by ghing** [comment]
@tekhneco had some questions about detecting different workflow steps in the builder (e.g. "Add Data", "Publish/Share").

They all have unique URLs and Google Analytics will track them if the user visits the URL directly (i.e. from a bookmark).  However, as the builder app uses the History API to navigate within the builder, when the user clicks on a menu item to switch between workflow steps, this will not be recorded by Google Analytics.  The workaround is to use the Google Analytics API and set up a Virtual Page View as described here: http://stackoverflow.com/questions/5306454/how-to-use-google-analytics-with-html-5-history

For things like viewing help text in the help drawer, or clicking on links in the call to action section, we can use event tracking as described in the documentation here: https://developers.google.com/analytics/devguides/collection/gajs/eventTrackerGuide

**Comment by ghing** [comment]
I'm going to close this as I didn't get any specific feedback for which events need to be tracked.  The builder code now supports tracking events through Google Analytics and there are a few instances where this is used like tracking the "Show Tour Again" button clicks and detecting if users access the builder via URL with a hashed story ID in the URL.
