### ISSUE TITLE
unsightly gap between megamenu and header

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#540]
Somewhere recently (probably with font changes), an unsightly gap has crept in between the megamenu and the header. See screenshot:

![gap](https://f.cloud.github.com/assets/73439/13716/e71d4146-4612-11e2-9b93-cb1c96841438.png)

**Comment by ghing** [comment]
This looks ok to me, but I'm still seeing this in Chrome.  Is this completely gone for you?

**Comment by patternleaf** [comment]
nope, seeing it on chrome and safari. bummer.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
