### ISSUE TITLE
Reusable styles for alert messages

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#543]
I'd like to see something like [Bootstrap's alert styles](http://twitter.github.com/bootstrap/components.html#alerts) in our LESS/CSS.  One place where I've been missing these right away is for the message describing how a user profile image is set.  This could also be used for form-level error or success messages when submitting forms.

**Comment by mgrayinnovation** [comment]
Leaving as a tweak, 2/25/15

**Comment by mgrayinnovation** [comment]
Closed and moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
