### ISSUE TITLE
Ordering of "My Account" links in top nav don't match ordering as shown with the My Account section

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#544]
Minor, but the top-to-bottom vertical ordering should be the same.

Should be:
- My Stories
- Account Information (should we merge communication preferences with this page?)
- Communication Preferences
- Change My Password

Also the page that I'm on (e.g., "My Stories" or "Account Information" isn't reflected - visually- in the left nav

**Comment by jwirfs-brock** [comment]
Agreed. I'm moving this into Iteration 10 and assigning it to @patternleaf.
