### ISSUE TITLE
Sharing widget should resize as the embed widget textarea is resized

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#545]
Originally reported by @jwirfs-brock in #529 

![embed_screenshot](https://f.cloud.github.com/assets/1020518/17788/62962808-4887-11e2-9b35-c1650dabbc3d.png)

**Comment by patternleaf** [comment]
Should be fixed in abb20e5. Tested in Chrome, Safari, Firefox, and IE8.
