### ISSUE TITLE
Save message and presentation needs addressing

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#548]
Using the tool for an extended amount of time in one builder visit, I must have seen the "The story has been saved" green banner about 40 times...  I think it's good that we're saving so often, but I suggest we revisit the use of the green banner as the messaging mechanism for saving as it could quickly get annoying, I suspect

**Comment by jwirfs-brock** [comment]
@bpawlak If we got rid of the green bar, would the "Last Saved DATE/TIME"
message be sufficient, if we made it persistent (instead of fading away)?

**Comment by bpawlak** [comment]
What if we changed the color of the saved message briefly (to green) and then had it fade back to normal?

**Comment by jwirfs-brock** [comment]
@bpawlak So, just to clarify, are you suggesting the "Last Saved" message turns briefly green?

Also, the current green bar/message takes a very long time to fade away. So we if we don't get rid of it completely, we should at least make it fade more quickly.

**Comment by bpawlak** [comment]
Yep, that's what I'm considering...  And I think I submitted an issue about the slow fade out time being a problem ...

**Comment by ghing** [comment]
@jwirfs-brock There's a version of this with a green flashing last-saved message on save instead of the alert bar on dev. Let me know what you think.

**Comment by jwirfs-brock** [comment]
I like this solution. Looks good.

**Comment by ghing** [comment]
@jwirfs-brock I've updated dev with an approach that I prefer, toggling the color and text of the button itself rather than flashing the last saved message.  Please take a look on dev and let me know what you think.

Also, I'd like to update the last saved timestamp (that is revealed by hovering over the save button) so that it's more human readable (e.g. "Last saved 3 minutes ago" instead of "Last saved 2013-04-08 14:00")

**Comment by jwirfs-brock** [comment]
@ghing My only comment is that the "Saved" state looks like a button, which
makes me think that it's clickable when it isn't, but I don't think that's
really a problem. It's fine as is.

I like the idea of turning it to "Last saved 3 minutes ago..." instead of
the time stamp.

**Comment by ghing** [comment]
@jwirfs-brock It's supposed to look like a button, really it is a button, but I need to get the toggling of enabled/disabled states right.  My idea is that the auto save triggers the button state/style which also tells the user "This is where you click to manually save the story" or "actions related to saving happen here".  

I'm happy to explore showing a message separate from the button, but I like the idea of the state-changing button to limit the amount of UI clutter.

**Comment by jwirfs-brock** [comment]
@ghing I agree that it should look like a button. To restate my earlier
comment in a better way, when it says "Saved" (green) it looks like the
clickable state of the button and when it says "Save" (grey) it likes like
it's the unclickable state. I think that's probably just because of the
color scheme. I don't really have a better solution in mind, because the
"green means your story has been saved" analogy is appropriate.

**Comment by patternleaf** [comment]
@ghing @jwirfs-brock how about a little check icon within the save button rather than green color? http://fortawesome.github.io/Font-Awesome/#icon/icon-ok

**Comment by ghing** [comment]
@patternleaf, @jwirfs-brock I like the suggestion of the check icon.  I'm going to try that after lunch.

**Comment by ghing** [comment]
@jwirfs-brock, @patternleaf The version of this with the more human-readable timestamps and icons to indicate saving state is now on dev.  Please give it a final look over and assign this issue back to me once we're good.

**Comment by bpawlak** [comment]
Looks good but the only comment I have is the positioning of the "last saved" message... is there any room to move it to the right of the button so that we avoid having it overlap the "Start Over" link (which stays visible until you hover over it)

![image](https://f.cloud.github.com/assets/2250519/358695/129f7d70-a149-11e2-9742-1d2bee2c1eb5.png)

**Comment by ghing** [comment]
@bpawlak, I moved the last saved tooltip to appear to the right of the button instead of above it.  This is live on dev now.

**Comment by bpawlak** [comment]
Thanks, Geoff.  Still seeing some weird positioning behavior:

![image](https://f.cloud.github.com/assets/2250519/359093/f80a9b0a-a154-11e2-878d-c3f4d1d2347d.png)

**Comment by jwirfs-brock** [comment]
I'm also seeing the overlap behavior (in Chrome).

**Comment by ghing** [comment]
@bpawlak, @jwirfs-brock I made the button a consistent width so it's width doesn't change as the button icon/text changes, avoiding the [overlap described by Bill](https://github.com/PitonFoundation/atlas/issues/548#issuecomment-16138391).  I think this is the best we can do right now.  The newer version of the [jQuery Tooltipster plugin](http://calebjacob.com/tooltipster/) has a much wider API, which would let us do things like hide the tooltip when the button is clicked, or update it's text as the button state changes.  However, updating the library seems to break styling and behavior in a number of places, and I'm not sure hunting all those instances down is the best use of my time right now.
