### ISSUE TITLE
Tour popup falls outside of window when resizing window

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#551]
@jwirfs-brock discovered this when doing QA for #415.

So far I've seen this in IE9 and Chrome, but I suspect it affects all browsers.

To replicate:
1. Remove cookies for floodlightproject.org and dev.atlas.terrorware.com so that tour will be forced to show again.
2. Open a browser window to a width narrow enough that the tour popup nudge effect occurs.
3. Load the builder page and create a new story or edit an existing story.  Since you removed the cookies in the first step, this should start the tour.
4. Observe that the first tour popup opens and is nudged so it fits within the window.  It is likely to be at the far right of the browser window.
5. Resize the window

Expected result:

The tour popup remains entirely in the browser window.

What happens:

The left side of the tour popup falls to the left of the browser window.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
