### ISSUE TITLE
In IE9, Explore page "tiles" are overlaping with tile/list/map view icons

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#552]
I observed this on both staging and production. It doesn't appear to be happening on other browsers.

See screenshot:

![Explore_page_IE9](https://f.cloud.github.com/assets/1020518/22502/21f593bc-4a01-11e2-92ad-23069854f7c2.png)

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
