### ISSUE TITLE
IE9: cascade of bizarre JS errors when launching viewer

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#553]
examples:
- 'Function' is undefined.
- 'Object' is undefined.

... that is, javascript built-ins are not being found. Sources are Modernizr, jQuery, underscore, etc. All well-tested cross-browser libraries.

No functionality _appears_ to be affected by these errors.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
