### ISSUE TITLE
"Unable to get value of the property 'placeholders': object is null or undefined" error in connected story builder

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#558]
To replicate:
1. Load the connected story builder (e.g. /stories/born-into-poverty-1400-in-the-childrens-corridor-e/build-connected/) using Internet Explorer (I was using IE 9)

Expected result:

Simplified version of the builder loads.

What happens:

The header loads, but the content area is blank.

The JavaScript console shows the following error:

```
SCRIPT5007: Unable to get value of the property 'placeholders': object is null or undefined 
```

views.js, line 3612 character 7

The connected story builder uses the same Backbone app as the regular story builder but just turns off some UI elements and branches through some separate paths in the code.  Perhaps the polyfill for placeholders is initialized in a block that gets skipped when the connected builder options are set.

**Comment by ghing** [comment]
I looked into this a little bit and it seems like this is likely a timing issue.

The polyfill is loaded in the Django template for the story builder (`story_builder.html`) not a Backbone view.  Because there's less to initialize for the connected story builder, I bet that Modernizer.load() just hasn't finished by the time that `SectionEditView.applyPolyfills` is called.

I don't know if it's possible to have Modernizer.load to send a signal on the dispatcher, or if it's better to have applyPolyfills to start polling for the polyfill when it isn't found.

The quick and dirty workaround is to add a guard around the call to `window.polyfills.placeholders()` to make sure `window.polyfills.placeholders` exists.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
