### ISSUE TITLE
Search by address (on map view of Explore page) is hard to see

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#559]
The search field is below the map, which makes it really easy to miss (especially when viewing the map on a small screen). We should move it above the map, so that users see it.

**Comment by patternleaf** [comment]
note to self: probably can just change https://github.com/PitonFoundation/atlas/blob/develop/static/js/explorer/views.js#L997 to use prepend instead of append. (currently dev environment is unavailable to test.)

**Comment by ghing** [comment]
@patternleaf, can this be closed now?

**Comment by patternleaf** [comment]
Yes.
