### ISSUE TITLE
In Chrome, map on Explore page has weird "swooping" behavior while zooming

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#560]
When using Chrome, I'm seeing weird behavior on the map view of the Explore page while zooming. The map appears to swoop/wobble, so that the center moves briefly and then returns back to its original location during the zoom.

I was able to reproduce this in Chrome on Windows and MacOS, but didn't see it in Firefox or IE.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
