### ISSUE TITLE
Pull-quotes should have styling as shown in design comps

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#565]
Pull-quotes in stories (created as Quotation assets in the Story Builder) should be styled as they are in the design comps: https://docs.google.com/file/d/0B1CQ7Qy70V50anZidU56Snlvbm8/edit
- Grey background
- Italicized text

**Comment by patternleaf** [comment]
hey @jwirfs-brock, do you mean block quotes instead of pull-quotes? also can you point me to a story that has one in it? thanks.

**Comment by jwirfs-brock** [comment]
@patternleaf There are actually two things this refers to:
a) block quotes (within text, indicated via html) -- as far as I know these
have no styling
b) quote assets

I'll have to double-check, but I believe in
http://floodlightproject.org/stories/charting-a-new-course-in-sheridan/,
there's a block quote on section 9 and a quote asset on section 4.

**Comment by jwirfs-brock** [comment]
@patternleaf Oops, had that backwards...

There's a quote asset on section 9 (and 11).

I don't think this story has any block quotes. Let me look for an example...

**Comment by patternleaf** [comment]
ok, @jwirfs-brock i've applied the gray/italic box style to those quote assets. could you review? also, is there a place where the pull-quote style is ever used? we have a definition for it in the stylesheets, but it probably isn't wired up to anything.

**Comment by jwirfs-brock** [comment]
@patternleaf One example of the block quote style (which I just made bold,
because it didn't have its own styling) is in "Six-Word Memoirs" (
http://floodlightproject.org/en/stories/six-word-memoirs/) on section 3.

**Comment by jwirfs-brock** [comment]
@patternleaf Note that the bold styling is something I added in (not a
default for styling the blockquote tag).

**Comment by ghing** [comment]
@patternleaf, to add the pull quote cladd to the `<blockquote>` element for _quoatation_ type assets, edit `storybase_story.models.HtmlAsset.render_html` in `storybase_asset/models.py`

**Comment by patternleaf** [comment]
note after discussion with @jwirfs-brock: use the "pull-quote" style in the everything comp for quote assets, and the bordered-gray style for instances of blockquote in story text content.

**Comment by patternleaf** [comment]
ok, here's the pull-quote style applied (w/left alignment) to a quote asset:

http://deploy.atlas.terrorware.com/en/stories/charting-a-new-course-in-sheridan/viewer/#sections/d163f2d2a8ce4472b11b5e30c8504ec8

and here's the blockquote style applied to a blockquote:

http://deploy.atlas.terrorware.com/en/stories/six-word-memoirs/viewer/#sections/3b618d96223b4702aa3f5fd4a08d381f

@jwirfs-brock is this what we discussed? is there anything that needs to change?

**Comment by patternleaf** [comment]
actually i'm going to post screenshots so i can work on other things on the server. blockquote:

![Screenshot 3:11:13 1:14 PM](https://f.cloud.github.com/assets/73439/245410/f1c89b70-8a7f-11e2-91cb-da96f743352f.png)

quote asset (pull-quote style):

![Screenshot 3:11:13 1:16 PM](https://f.cloud.github.com/assets/73439/245414/27b7f0fa-8a80-11e2-9256-26b8eaf32b8d.png)

**Comment by jwirfs-brock** [comment]
This looks good, Eric.
