### ISSUE TITLE
Admins should be able to update featured news items on the home page through the Django admin

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#567]
Currently, news items are manually added through the template.  Admins should be able to enter them manually through the Django admin.  This implements part of #433.

Based on the existing items, these are the fields that are probably needed:
- Title
- Body
- Image
- Author
- Creation date
- Last edited date

Should these be translatable?

**Comment by jwirfs-brock** [comment]
Yes, the news items should be translatable. Would the translation be through the Django admin, or through Transifex?

**Comment by ghing** [comment]
@jwirfs-brock 

The translation would be through the Django admin.  Transifex is for things that are more permanently translated, like text in UI elements.  The Django admin is for things that are dynamic content.

Would only the title and body need to be translated or would you also want to specify different images for different languages?

**Comment by jwirfs-brock** [comment]
Well, the past few news items have had text in the associated image. Based on that, we will want to have a translatable image.

**Comment by ghing** [comment]
@jwirfs-brock, for past news items, have you pulled in an image via a URL from another source (Flickr, Instagram, etc) or uploaded it.  I'm trying to decide how to implement the image.

The two options are:
1. Use the Asset abstraction used elsewhere.  This is useful in terms of having a consistent interface and letting you use arbitrary image sources (either uploads or URLs).  However, it would make the default workflow more complicated for adding the image in the Django admin or I'd have to spend more time writing customizations to make this easier.
2. Just have an uploadable image field.  This would be quick and easy in the Django admin, but would only support uploaded images.

My preference is for just having an image field, because it gets us up and running the fastest with user-editable news.  We could always change this later.  However, I'd be willing to use the Asset framework if you'd like to be able to specify either uploads or URLs in the admin.  Writing some code to make this more usable in the admin would be useful for improving asset selection elsewhere in the Django admin, so its pretty useful, but maybe not the highest priority at the moment.

**Comment by jwirfs-brock** [comment]
I think it's fine to just use an uploadable image field. In reality,
anything we are putting in a news item we'd be uploading anyway.
