### ISSUE TITLE
Homepage redesign: big white space under left header column.

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#573]
The content of the slider in the right column can be quite large vertically. This leaves a big blank spot on the left, and because the slider is always sized to accommodate the largest slide, even when that slide isn't visible, it can leave a big blank spot on the right, too.

![Home Floodlight 20130118 ](https://f.cloud.github.com/assets/73439/78870/99ef9f96-6196-11e2-8b04-f2bbd761b3d1.jpeg)

cf issue #433

**Comment by ghing** [comment]
This is so annoying.  I think that the cycle plugin sizes the container to the height of the largest element.

**Comment by patternleaf** [comment]
Yeah. My thoughts were: 
1. limit excerpt length on the homepage programmatically via ellipsis.
2. do something clever like limit the text container's vertical height and then reveal it on hover or something.

1 seems to make more sense short-term by an order of magnitude.

**Comment by patternleaf** [comment]
even if we reduce the height of the excerpt text, there's still going to be blank space on the left. one crazy thought: could we start the story-building process right there on the homepage? dunno how technically feasible it is, but something like ...

![homepage-1](https://f.cloud.github.com/assets/73439/87906/7430e060-64d6-11e2-96b4-e8e60f85c0cc.png)

**Comment by jwirfs-brock** [comment]
@patternleaf Your suggestion (1) sounds good to me.

I also like the piece where you can begin to write a story. Although I think it needs a bit more analysis before we add it to the homepage.

**Comment by patternleaf** [comment]
@jwirfs-brock the thing is, based on my experiments, even if the excerpt is shortened and the right-side column thus made smaller, the left column still has a lot of unused space in there. it's not _as_ bad, but still doesn't look polished.

**Comment by ghing** [comment]
@patternleaf It's not currently possible to start the story building process like you described, because of how the builder initializes stories.  Right now, the builder needs to know the template to correctly create the initial sections.  If a story were created from the homepage, without selecting a template, the builder would probably get confused.  If not, the user would get confused becuase things like the tour and help expect there to be at least one section.

Also, there's been some discussion about whether it's a good idea to encourage users to start telling their story with a title and a summary (in the builder itself or elsewhere).

**Comment by jwirfs-brock** [comment]
Yes, I'd prefer that the first pieces a user enters in aren't
title/author/summary, but I do like the idea of putting in some piece
immediately. It's interesting enough that we should talk about it more.
Maybe that would be a cool area to feature connected stories (once we start
pushing them more). You could have something like "Add your photo to this
story..." right up front.

**Comment by bpawlak** [comment]
:smiley: 

![image](https://f.cloud.github.com/assets/2250519/87951/59a1157e-64d8-11e2-9e40-c7a840ed9649.png)

**Comment by patternleaf** [comment]
yeah, the author/title/summary was just for illustration purposes, not anything thought through. mainly wanted a way to say "start your story now" as opposed to "click this link to do this other thing to start your story" ... and to fill up that space with something meaningful. i imagined it wouldn't be trivial to implement it, either. :(

how about: random content from the FAQ? with a link to it. or some copy from the About page?

**Comment by jwirfs-brock** [comment]
Oh, I like the random content from the FAQ idea. Is this something that could change so that it wouldn't be static? Would be fun if it was a new tip every time -- but would be more complex, of course.

**Comment by ghing** [comment]
@patternleaf, @jwirfs-brock The random content from the FAQ is non-trivial as well because the FAQ elements aren't individual pieces of content, they're all on one page.  We could use JavaScript or server-side code to parse out items from the FAQ page, but that seems hack-ish to me.  We could also re-implement the FAQ so that each question is one piece of content, but I'm worrying that this is getting too far from the fundamental issues.

**Comment by jwirfs-brock** [comment]
I think for now we should implement the homepage with the truncated slider
text and leave the white space as is. Then we can discuss what to do with
it and come up with a solution that we can slot into the next iteration.

**Comment by jwirfs-brock** [comment]
If we just need to fill space, there is copy from the current homepage that
we can use.

**Comment by patternleaf** [comment]
**Decision, based on discussion**: Make “View Stories”, “View Projects”, “View Organizations” list vertical, add brief descriptive text below each item and add a thumbnail to the left of each item.  Jordan will send Eric and Geoff copy and images.

Copy for vertical list:

View Stories
From glimpses to in-depth explorations, see your community in a new light.

View Projects
A project is a collection of stories about a common theme, place, issue or event.

View Organizations
An organization is a group of people creating stories together.

**Images**:

Story:
http://www.floodlightproject.org/media/filer_thumbnails/2012/11/06/hollistiles-6625.jpg__490x0_q85.jpg

Project:
http://www.floodlightproject.org/media/filer_thumbnails/2012/10/31/soccer_project_new.jpg__335x0_q85.jpg

Organization:
http://www.floodlightproject.org/media/filer_thumbnails/2012/11/30/liveunited_milehighuw_10-31-11.jpg__335x0_q85.jpg

**Comment by patternleaf** [comment]
@PitonFoundation/developers please review the current homepage, including the new list of stories, organizations, and projects in the left column. i actually think it looks pretty good—particularly when the right-column slider is full of text. Truncating the text in news items might leave us with too much space in the _right-hand_ column ... but i'm not sure.

http://deploy.atlas.terrorware.com/

**Comment by ghing** [comment]
@patternleaf, I like the general concept, but those images seem a little big to me and overpower the Stories, Projects and Organizations links

Could you try to downsize them to either 150px wide or 100px wide to be consistent with what's used elsewhere on the site?

If you want to you could use CSS to crop them to either 150x90 or 100x60. Check out the CSS for the images in the latest stories list to see how I do this in that context. I guess you have full control over the image, so you could just crop in manually to, or not crop them at all.  I don't think it's a huge deal.

**Comment by ghing** [comment]
@patternleaf, I just pushed the truncation code (#589) (essentially a 1-liner) to develop.  You can decide if we want to keep it or not given the changes you made here.  It's easy to change obviously.

**Comment by jwirfs-brock** [comment]
@patternleaf I agree that the images need to be smaller -- maybe try making
them the size of the images below the fold?

**Comment by patternleaf** [comment]
@jwirfs-brock @ghing i actually disagree about the size of the images. i think that size is appropriate for the overall information hierarchy of the home page. 

the slider on left has one item (at a time) and has the largest image on the page. this list has three items and indicates the three major "objects" you interact with on the site. below the fold, the Latest X lists have three items each, for a total of nine, and those images are the smallest.

regarding consistency, the homepage is a special case in terms of the overall experience of the site, and i think it's ok for it to have its own "rules" in some cases.

> seem a little big to me and overpower the Stories, Projects and Organizations links

also note that the images themselves are links.

i'll make them smaller of course if that's the consensus, but wanted to put my reasoning out there. :)

**Comment by jwirfs-brock** [comment]
@patternleaf Those are good points. Could we make them slightly smaller
than they are now, but larger than the thumbnails below the fold?

**Comment by patternleaf** [comment]
@jwirfs-brock OK, I've made them smaller. Want to check it out now?

@ghing So it seems like the hard-coded 75-word truncation at the moment doesn't necessarily address the issue, since the main issue is appropriate sizing of that right column and the truncation doesn't take into account the size of other things in the news item: if the photo is tiny, for example, the truncation leaves _too much_ space.

Do you think this will be remedied by more standardization on image size with "real" data?

If we really want to address the spacing issue, it seems like it might in fact require a client-side solution. Maybe that would be too much trouble at the moment.

**Comment by jwirfs-brock** [comment]
@patternleaf I find the extra space on the right-hand side, when it does
happen, a lot less troublesome than when it was on the left. I actually
like it the way it is now.

Should the ellipses be links to detail pages?

**Comment by bpawlak** [comment]
I think in addition to saying "View all stories" it should also have a link that says "View Story."  Yes, the story title is there already, but after I read the text (with ellipses or not), I'd likely want to click on a link to let me get to the story or the story detail page.

**Comment by ghing** [comment]
@patternleaf I think that the big variations in relative column sizing will be helped by real content and avoiding those awful little images.  I'll deploy the finished code to staging with the data currently on production so we can see if there's any issues with "real" data.  I think the list with the photos is a step in the right direction and the page looks much more balanced.

I think @bpawlak's suggestion of a "View Story" link is good and preferable to making the elipses a link.  I'm going to try to do this.

**Comment by patternleaf** [comment]
@ghing @bpawlak @jwirfs-brock should those links be not orange and Museo, now that we're trying to pin down the semantics of link color?

**Comment by patternleaf** [comment]
I took off the special styling on those links (and all links that have class "more"). We can revisit link semantics again if we need to, but for now it seems to make sense to move towards normalizing everything.

Also, i'm closing this.
