### ISSUE TITLE
The “story information” section is confusing, deters users from working through the story building process

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#578]
The “story information” section is confusing and deters users from working through the story building process:
- It’s not what people expect to start with (it’s meta-data, not story content)
- People end up putting the whole story in the summary (see issue #530, summary needs a word limit)
- It’s not a logical starting point

**Comment by jwirfs-brock** [comment]
@bpawlak This is another important upcoming fix that needs some UI work. Thoughts? We can brainstorm here on GitHub first, then discuss in-person on Tuesday, perhaps?

**Comment by bpawlak** [comment]
I thought at one point we had talked through a re-imagined flow for story creation and steps where title and name were on the first step "called Title" while the summary field was going to be presented when the user clicked "Publish/Share?"  e.g., it's only at that point that the author needs to summarize the story for inclusion on Floodlight

**Comment by jwirfs-brock** [comment]
Yup that's right. The details just need to be solidified.

**Comment by ghing** [comment]
@jwirfs-brock and I talked about this as a possible solution, that's part of the implementation of #579 described in [this comment](https://github.com/PitonFoundation/atlas/issues/579):
- Make title omnipresent at top of the builder (we'll make the space by replacing the big logo with something smaller)
- Make a separate "Story Information" step of the builder that will contain the summary and featured image. This comes after editing the main content of the story.
- We'll try to fit the byline with the Title at the top of the builder, but put it in the "Story Information" workflow step if it doesn't fit

**Comment by ghing** [comment]
Sample title lengths for moving the story title:

Min: 8 ('En Route') in story /stories/en-route/

Max: 134 ('Taking Action for the Social and Emotional Health of Young Children: A Report to the Community from the Denver Early Childhood Council') in story /stories/taking-action-for-the-social-and-emotional-health/

Avg: 45 ('Near Northeast Profile: Interactive Slideshow') in story /stories/near-northeast-profile-interactive-slideshow/

**Comment by ghing** [comment]
As a reference, this is how Google Drive handles long titles.  They truncate using an elipses via a `text-overflow: elipses` style:

![screenshot from 2013-10-30 12 30 35](https://f.cloud.github.com/assets/110420/1439291/21bfd5a8-4189-11e3-8333-2cb88ed632e1.png)

**Comment by jwirfs-brock** [comment]
@ghing Generally, I like the layout on the new Story Information section. My only suggestion would be to try flipping the position of the summary and the featured image, so the summary is on the left and the featured image is on the right. Right now, with the featured image on the left and the summary on the right, this matches the layout of the story detail page, which makes sense. But I feel like the summary will have more weight if it is on the left, and users will be less likely to miss it.

I'd definitely like to show this new format to a few people to see if it makes sense, because I'm still a little worried that users may miss steps.

**Comment by jwirfs-brock** [comment]
@ghing These might be known issues, but I noticed while doing some testing that:
- The "Publish" button didn't appear to be working in the updated builder. 
- That featured image I selected on the Story Info step did not appear in the preview.

**Comment by ghing** [comment]
@jwirfs-brock, what's up on dev isn't  ready for testing.  I just wanted to show it to you to give you an idea of UI layout.
