### ISSUE TITLE
Map not rendering properly on "Explore" page if you first set a place filter

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#587]
Here's what I did:
1. Navigated to http://www.floodlightproject.org/en/explore/
2. Set the place filter to Clayton
3. Clicked "Map" to get the map view
4. Saw the following blurry map:
![mapbug](https://f.cloud.github.com/assets/1020518/91898/2fee3aa0-65b3-11e2-87bd-efe983b3780b.png)

I tried this same process, but with setting a different filter (i.e., set a topic filter, then switched from the tile view to the map view), and the map seems to render fine.

If I click "Reset Filters," the filters are cleared, but the map is still not rendering properly (even if I go back to tile view then back to map -- only a refresh will return the map to rendering properly).

**Comment by jwirfs-brock** [comment]
Oh, and if you go into the map view first then set a place filter, it works properly.

**Comment by jwirfs-brock** [comment]
Also, if you set a place filter and another filter before switching over to the map view, then it renders fine. Weird.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
