### ISSUE TITLE
Builder allows upload of non-image files as image assets, but can't show thumbnail

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#595]
In the builder, you can upload a PDF for an image, but then viewing it in the builder, viewer and really anywhere you need to get a thumbnail will fail because the underlying file isn't a format that easy_thumbnails can deal with.

We should restrict image uploads in the builder to supported image types.

Only one user has run into this so far, so I don't think it's too important to support PDFs as images.  We could add a new asset type like "document" or "rich media" that supports this.  Also, we could steer people toward Scribd (which I think also supports oEmbed) or implement our own inlining of PDFs using [pdf.js](http://mozilla.github.com/pdf.js/).

**Comment by ghing** [comment]
Another workaround could be for LocalImageAsset.get_thumbnail_url to catch InvalidImageFormatError and just return the default image in this case.

**Comment by ghing** [comment]
Another user ran into this issue while trying to use an Applie iWork Pages document as an image.

**Comment by ghing** [comment]
@jwirfs-brock I think that this issue (and it's fix) should be focused on giving the user feedback about valid image types and preventing the saving of non-image files rather than supporting PDF files.  I don't think we know enough about how users want to use PDFs (or other document files) in their stories to do a good job of implementing this, and that implementation would touch other parts of the code.  When we find out more about user needs around PDFs, we can open a separate issue.

**Comment by jwirfs-brock** [comment]
@ghing I agree that we should focus on giving user feedback. My
interpretation of this this issue was that it referred to making it so that
they *couldn't *upload an non-supported image in the first place, rather
than being able to upload it but then not view it.

We should definitely add some of the supporting information that is on the
FAQ page to the image asset upload.

If, in the future, we want to allow users to upload PDFs, that should be a
separate asset type, I think. (And we could recommend using an online
document viewer like Scribd, as @ghing suggested.)

**Comment by jwirfs-brock** [comment]
To clarify, my suggestions for this issue are...
- add information about supported image asset types, with a link to FAQ page for further information
- return an error if a user tries to upload an unsupported image type

I will also open a separate issue about creating a "document" asset type, which will require analysis to find out if this is something users want/need.

**Comment by ghing** [comment]
One important consideration: the asset creation for image uploads happens in two requests: the first one creates the Asset instance in the database, the second one uploads the file.

Should we validate this client-side or server-side or both. If we do it client-side we can save having to clean up the asset model instance from the first request if the file uploaded is not a valid format.  If we validate the file client-side, can we get the file type from older browsers, or do we have to rely on the filename extension of the uploaded file?  If we validate server-side, we can more reliably detect the file type.

Also, this should probably happen along with #606 since both deal with validation of image uploads.

**Comment by ghing** [comment]
After talking to @patternleaf about this, it seems like the validation should happen server-side and that we shouldn't create an Asset model if the file type doesn't validate.  Because of this, we need to be able to send the file and the metadata in one request.  We can either make a separate endpoint, or make the existing endpoint support multipart form data.

It looks like https://github.com/toastdriven/django-tastypie/issues/42 and https://github.com/toastdriven/django-tastypie/pull/606 represent some prior work.

**Comment by ghing** [comment]
There's not a great way to provide user feedback in IE <= 9 when the image type validation fails.  This is partly because [it's not easy to get the headers from the iframed request](http://cmlenz.github.com/jquery-iframe-transport/#section-13), but mostly because of [IE throwing an exception that I can't figure out](https://github.com/cmlenz/jquery-iframe-transport/issues/7).

I'm not going to bang my head against a wall because nothing breaks and no incorrect data is created, the user just doesn't get a message as to why the submission has failed.
