### ISSUE TITLE
Homepage slider isn't auto-cycling in Chrome

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#598]
It seems to be working fine in Firefox, but in Chrome the slider isn't automatically moving (this was done in issue #584). I'm using Chrome Version 24.0.1312.52 m on Windows 7.

**Comment by ghing** [comment]
It's working for me in Chrome  24.0.1312.56 on Ubuntu 12.10.

**Comment by jwirfs-brock** [comment]
I'll see if it works on my Mac. It's most definitely not auto-progressing
on my Windows machine (I had it open for several minutes).

**Comment by ghing** [comment]
@jwirfs-brock, can you make sure you try a hard refresh?

**Comment by jwirfs-brock** [comment]
It's working fine on Version 24.0.1312.56 on Mac OS 10.8.2.

**Comment by jwirfs-brock** [comment]
Ok, the hard refresh worked.
