### ISSUE TITLE
The builder should create an empty Story model instance when starting a new story

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#600]
Scattered throughout the builder code are listeners on the event bus for the `story:ready` event so that views that expect a model aren't broken when the builder is initialized without an existing story (i.e. when the user is shown the template menu).

For example in the `initialize` method of `WorkflowNavView`:

```
    if (_.isUndefined(this.model)) {
      this.dispatcher.on("ready:story", this.setStory, this);
    }
```

and the `setStory` implementation:

```
  setStory: function(story) {
    this.model = story;
    this.dispatcher.on("save:story", this.handleInitialSave, this);
    this.render();
  },
```

This seems a little silly and the source of a lot of repetitive code.  Instead, I feel like the builder should create a new story instance when it's initialized.  Then, all other views can just bind events to the story instance's `save` event and avoid doing checks like `if (_.isUndefined(this.model)) { .. }`

It looks like an empty story is initialized in BuilderView and it might just make sense to do this in AppView instead, making the model instance available to all the subviews.

**Comment by ghing** [comment]
In e-mail @jwirfs-brock said:

> It could go in Iteration 12 if you think it's straightforward, or something that won't be affected by changes in the 
> Story Builder workflow.

The implementation for this issue represents a significant refactor of the builder code, but I think its worth it and should happen **before** implementing any changes to the builder workflow.  It should come before, because it will make new builder code cleaner, and let us use a better, more consistent pattern for responding to story initialization moving forward.

**Comment by jwirfs-brock** [comment]
@ghing Moving to Iteration 12.

**Comment by ghing** [comment]
I'm going to move this out of the current iteration.  Though this would be a nice code cleanup, it doesn't affect user experience nearly as much as some of the other open issues, and won't matter when we reimplement the builder.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
