### ISSUE TITLE
After editing a connected story in the Builder via admin, story becomes "unconnected" story

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#604]
This is an edge case, but I wanted to make sure it was documented.

If a user create a connected story, then an admin edits it by selecting, "Edit in Builder" in the admin view, the story becomes "unconnected." That is, the story is launched in the full builder, and once it's saved it shows up on the Explore page and no longer shows up on the original seed story.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
