### ISSUE TITLE
Connected story byline discrepancy

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#607]
The connected story, Like bellows; breathe in, breathe out," that Brigid created shows a DIFFERENT byline on seed story page (http://floodlightproject.org/en/stories/six-word-memoirs/viewer/#sections/b82c5e8b2e734235835ba451e7dcfacb) and on the story's view page (http://floodlightproject.org/en/stories/six-word-memoirs/viewer/#connected-stories/70587bd12e7e467ab6262bcb51c9f20d).

On the first page, it lists the byline as "Jordan Wirfs-Brock, The Piton Foundation," which is not the correct byline. When you click the story, it shows the correct byline, "Brigid McAuliffe."

This one's a bit hairy, so here's how it happened:
1) Brigid created the connected story, but did not publish it (probably because of the publish issue raised in #602).
2) Via the admin, I went into the story and attempted to change the story's status to publish.
3) I got an error because the story didn't have a byline, so I added one, "Brigid McAuliffe."
4) I was then able to successfully publish the story.
5) When I went to view it, I noticed that the byline was showing up incorrectly on the seed story, but correctly on the story itself.

Seed story view:
![connected_story1](https://f.cloud.github.com/assets/1020518/125079/ad9807e8-6f08-11e2-9824-61f2875947f5.png)

Connected story view:
![connected_story2](https://f.cloud.github.com/assets/1020518/125082/b402bc68-6f08-11e2-8fe1-f0ba707396e7.png)

**Comment by ghing** [comment]
@jwirfs-brock The fix for this is live on staging.  I've assigned this to you for review.  Please re-open the issue if you find that it persists.

**Comment by jwirfs-brock** [comment]
Looks good.
