### ISSUE TITLE
Image not rendering in connected story

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#608]
In the connected story, "I create my own head wind," the image is not showing up in the story view (http://floodlightproject.org/en/stories/six-word-memoirs/viewer/#connected-stories/193f7bd2104543f19e61c24efa48827e). When this story was in the "recent stories" list on the homepage, the image appeared.

**Comment by jwirfs-brock** [comment]
Also, in the story detail page, the image shows up: http://floodlightproject.org/en/stories/not-just-about-running/

**Comment by jwirfs-brock** [comment]
And shows up when you launch the story viewer from it's detail page. The only time the image doesn't render is when you launch it from http://floodlightproject.org/en/stories/six-word-memoirs/viewer/#sections/connected-stories

**Comment by ghing** [comment]
This is a latency issue related to our fix for matching the border and caption width to the images.  I fixed this in 14e1f536fb18f09c8d49f7a415a0ee31a99c5904 as part of the fix for #601.
