### ISSUE TITLE
Edited a published seed story, and its related connected stories were "disconnected"

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#611]
I edited the story "Six-Word Memoirs" (http://www.floodlightproject.org/en/stories/six-word-memoirs/), which at the time was a seed story with two associated connected stories (http://www.floodlightproject.org/en/stories/like-bellows-breathe-in-breathe-out-2/ and http://www.floodlightproject.org/en/stories/not-just-about-running/). After I saved the edits, those stories no longer appeared as connected stories, and looked like independent stories on the site.

**Comment by jwirfs-brock** [comment]
I was editing the seed story in the story builder (accessed through "my account," NOT through the django admin) when this happened.

**Comment by ghing** [comment]
@jwirfs-brock, I wasn't able to replicate this in my local development instance.  I tried editing the seed story in the builder, editing the seed story in the Django admin, editing the connected story in the builder.  I'll try to set up staging to do some more testing on this with productionish data.

**Comment by jwirfs-brock** [comment]
@ghing Using Firefox on Windows 7, I...
- Created a new seed story on staging (http://staging.floodlightproject.org/en/stories/this-is-a-connected-story-test/) and published it
- Created a two new connected stories (http://staging.floodlightproject.org/en/stories/it-connects/ and http://staging.floodlightproject.org/en/stories/testing-connected-stories-again/) and published them
- Verified that they appeared as connected stories
- Edited ONLY the "Call to Action" for the seed story via the Story Builder (which I access from My Account --> My Stories), and clicked "Save" in the Story Builder
- Exited the Builder, and observed that the stories are now "unconnected" (they now appear on the recent stories feed, the seed story no longer has any connected stories attached to it)

I can do a screen capture if that would help.

**Comment by ghing** [comment]
Ok, I was now able to replicate this and find the problem.  I'm working on a fix right now.

**Comment by ghing** [comment]
Fixed and deployed to production.
