### ISSUE TITLE
Use window.onerror to give users a friendlier notification and log uncaught JavaScript exceptions in builder/viewer

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#623]
See http://dev.opera.com/articles/view/better-error-handling-with-window-onerror/

**Comment by ghing** [comment]
Did a quick fix for this in 8e7c24f210edf71f1cb364370dc36b887570e907 that shows the user an error message instead of a partially rendered view.  Still need to implement logging.

**Comment by ghing** [comment]
@jwirfs-brock:

The error text currently being shown is:

There was an unexpected error. You should try to reload the page while <a href='http://wikipedia.org/wiki/Wikipedia:Bypass_your_cache' title='Bypass your cache' onclick='window.open(this.href);return false;'>bypassing the cache</a>. If that doesn't fix the error, <a href='/contact/' title='Contact' onclick='window.open(this.href);return false;'>tell us what happened</a>.

Let me know if you have suggestions for better language.

**Comment by jwirfs-brock** [comment]
@ghing Is this error message shown in every instance of an error, or just for specific ones that we can identify?

**Comment by ghing** [comment]
Actually, it's shown for errors that we don't know about or expect that
would likely cause some confusing behavior (like a partially rendered or
blank page).  Errors that we expect might happen are shown in the error bar
of the builder.  This error message shows up as a  pop-up because we can't
be sure that the builder scaffolding has been initialized when the error is
shown.

**Comment by ghing** [comment]
Added logging tot he server in 8395e1e.  Assigning to @jwirfs-brock to see if she wants to update the error message text, if not, close it.
