### ISSUE TITLE
Static assets should be versioned and compressed

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#624]
Since we're deploying often and our static asset filenames aren't changing, users can be viewing Floodlight pages with a stale, cached version of the JavaScript or CSS and get weird errors, such as #667.

Versioning the assets so users always get the freshest CSS and JavaScript is the most important, because it prevents odd behavior, but it would be nice to get the performance bump for users by compressing JavaScript as well.

I put both versioning and compression into this issue since a lot of the tools to handle versioning also do compression.
## Versioning

If we just want to do versioning, the pattern described at [Automatic asset versioning in Django](http://muffinresearch.co.uk/archives/2008/04/08/automatic-asset-versioning-in-django/) seems pretty reasonable.
## Compression

A lot of our CSS is already compressed because we're using LESS. For compressing assets in a general way, [django-compressor](http://django_compressor.readthedocs.org/) seems like the best candidate.

[django-pipeline](http://django-pipeline.readthedocs.org/en/latest/) is another option, but I prefer how django-compressor has the compression specified in the template, where it seems natural to look for information about static assets, rather than the settings file.

However, I'd ultimately like to use [RequireJS](http://requirejs.org/) to clean up the code in our Backbone apps and make the dependencies on external libraries more clear, especially if we do a rewrite of the builder app.  RequireJS has an [optimizer](http://requirejs.org/docs/start.html#optimize) that combines and compresses JavaScript.  I think using it's compressor makes more sense because it more intelligently reflects the dependencies between our custom JavaScript and external libraries.  I'm worried that taking the time to set up and test _django_compressor_ might not be worth it if we ultimately have to re-think it using RequireJs.
## Decision

Use the pattern described at [Automatic asset versioning in Django](http://muffinresearch.co.uk/archives/2008/04/08/automatic-asset-versioning-in-django/). Worry about compression strategy when we decide the future of the builder.

**Comment by ghing** [comment]
Assigning to @patternleaf for review, assign it back to me when you've weighed in on which strategy seems the most reasonable.

**Comment by patternleaf** [comment]
seems legit! :+1: 

(... to clarify, i think the waiting for compression strategy until the builder is retrofitted seems good, and also the asset versioning pattern looks reasonable, as you say.)

**Comment by ghing** [comment]
I started playing around with django-compressor because I wanted to double-check my assumption that using it really would be too much time.  Though the versioning-only 

So far, I found that:
- [sekizai support doesn't support offline compression](https://groups.google.com/d/msg/django-cms/j8IM1ZmT9f0/wT5MXQAC518J)
- The current stable version of django-compressor (1.2) doesn't ship with the [sekizai postprocessor](http://django_compressor.readthedocs.org/en/master/django-sekizai/).

**Comment by ghing** [comment]
I wired up django-compressor and it seemed to "just work" and it didn't complicate the templates very much at all.  This is the route I want to take.

**Comment by ghing** [comment]
This thread has some information about (not) using django-compressor with requirejs for future reference.
