### ISSUE TITLE
Explore page filters: map position is off when selecting a filter

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#631]
1. load map view
2. select a filter from a drop-down

result: map view jumps up say 50 px, partially obscuring the tile/list/map icons. see issue #480 for screenshot.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
