### ISSUE TITLE
Explore Page filters: using search box results in search icon rendering in wrong place

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#632]
From issue #480: "I'm also seeing a bunch of other odd intermittent behaviors: see below. I tried to do a search in one of the filter dropdowns and ended up seeing this in the upper left"

[see screenshot in #480]

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
