### ISSUE TITLE
Explore page filters: "x" to clear a filter is not visible in webkit

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#633]
It shows up on hover, but not otherwise.

**Comment by ghing** [comment]
@patternleaf, I'm seeing the "X" in Chrome 0.25 on Ubuntu even when not hovering.  Are you still seeing this?

![Screenshot from 2013-03-27 14:36:03](https://f.cloud.github.com/assets/110420/310179/9984dae4-9715-11e2-8201-73fc6c709de7.png)

**Comment by patternleaf** [comment]
@ghing yeah, still seeing it on Safari and Chrome on OS X.

**Comment by ghing** [comment]
@patternleaf, can you post a screenshot so I can see how it looks different than Chrome on Ubuntu?

**Comment by patternleaf** [comment]
![Fullscreen 4:3:13 10:24 AM-2](https://f.cloud.github.com/assets/73439/334716/028641da-9c7b-11e2-9cf1-181b72a28719.png)

**Comment by ghing** [comment]
@patternleaf, wow. Weird.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
