### ISSUE TITLE
Make error window for uncaught JavaScript Errors less obtrusive.

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#634]
The implementation for #623 added a pop-up window (and logging) of uncaught JavaScript exceptions:

It looks like this:

![Screenshot from 2013-02-15 16:48:14](https://f.cloud.github.com/assets/110420/162590/e7cbb8c6-77c1-11e2-874e-6ee0506e35c2.png)

I had originally anticipated that this would only be shown for severe errors where this popup would be preferable to an inexplicably impartially rendered view, but after being deployed for a couple of days, it looks like users may see this error popup for non-critical errors that don't break the functionality of the builder or viewer.  In these cases, the popup is annoying because it doesn't allow users to remove it and try to proceed.

I've currently disabled the popup in production, but I'd like to find a way to show it when appropriate. These are a few ideas of how to handle the error:
- Add a close button to the window. That way, if the view still seems usable, they can close the window or proceed.
- Only show the popup for errors in certain files.
- Check if the builder event bus is present and trigger an error on the event bus (allowing it to show up in the standard location, below the toolbars in the builder) instead of showing the popup.
- Make the popup smaller, and not centered in the middle of the screen, so users can work around it.
- Make the popup go away after a certain period of time.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
