### ISSUE TITLE
Update text in help drawer for all story builder steps

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#641]
Right now, we really are only using the help drawer during the "Build" step. With our new (streamlined) story building workflow, we also need to add help text to the "Publish" and "Enhance" steps.

**Comment by jwirfs-brock** [comment]
This is less of a tech update than a content and UI update, but I wanted to include it on the list (1) so that we make sure it gets the attention it needs, and (2) in case it does end up raising any (unforeseen) technical updates.

**Comment by jwirfs-brock** [comment]
Note to self:

To do -- go through each template and identify help items that are missing or need to be updated.

**Comment by jwirfs-brock** [comment]
Help text update punch list:

All Templates:
- Story Information (ALL TEMPLATES) -- Maybe include a sentence at the beginning of where this will show up and how this information pulls the reader in/is how the reader decides whether or not to read the story. Include info about character limit (try to keep to 250 characters).
- Make sure they have asset-specific help associated with them when appropriate.

Photovoice Template:
- Image and Text (PHOTOVOICE) -- Maybe give a different title (now that the section is "Untitled")? Step 2 needs to be updated to reflect fact that you can only add a text asset.
- Image asset (PHOTOVOICE) -- Creative Commons text should link to Floodlight's CC page. Instructions need to be updated to reflect proper buttons (Click on "Image" instead of click on "add your image"). 
- Text asset (PHOTOVOICE) -- Need to shorten so that instructions fit in Help drawer. Need to adjust spacing.
- New Section (PHOTOVOICE) -- It is defaulting to the photovoice (text + image) layout, but has the generic new section text.
- Should it have custom Story Information help?

Data Story Template:
- Should it have custom Story Information help?
- Introduce Your Data Visualization (DATA STORY) -- Needs editing to be more concise. Should include something about what is the single biggest takeaway, what is the "Why?"
- Introduce Your Data Visualization/Text Asset (DATA STORY) -- Doesn't have individual asset help - is this needed?
- Data Visualization: Chart, Graph or Map (DATA STORY) -- Weird formatting (first PP is indented) needs to be fixed. Once we have integrated data sources into data assets, need to update last paragraph to reflect how to add source data.
- Data Visualization: Chart, Graph or Map (DATA STORY) -- Right now, users can add any kind of asset - should it be restricted to Image, Chart, Table, Map?
- New Section (DATA STORY) -- The default new section is a text-only one-up - should it be a different layout?

Explainer Template:
- Should it have custom Story Information help?
- In general the template is confusing, especially now that the sections all appear as "Untitled"...
- This one really needs EXAMPLES (all sections)

Sandbox Template:
- Should it have custom Story Information help?
- Why does the default blank section not have asset-specific help (generic help for choosing which asset to add?)

**Comment by jwirfs-brock** [comment]
@ghing When I was editing the help text for the chart/map/graph container in the Data Story template, I noticed that there's a bit of help text tacked onto the end that says, "There isn't help for this type of asset yet, or you haven't selected an asset type." Any idea where that's coming from?

Here's a screen shot:
![data_asset_help](https://f.cloud.github.com/assets/1020518/705658/a0364f60-ddda-11e2-9219-66b26e6199f2.png)

When I edit this help text in the admin, it doesn't appear: http://floodlightproject.org/en/admin/storybase_help/help/12/

Any ideas? Thanks.

**Comment by jwirfs-brock** [comment]
CHECKLIST 

All Templates:
- [x] Story Information (ALL TEMPLATES) -- Maybe include a sentence at the beginning of where this will show up and how this information pulls the reader in/is how the reader decides whether or not to read the story. Include info about character limit (try to keep to 250 characters).
- [ ] Make sure they have asset-specific help associated with them when appropriate.

Photovoice Template:
- [x] Image and Text (PHOTOVOICE) -- Maybe give a different title (now that the section is "Untitled")? Step 2 needs to be updated to reflect fact that you can only add a text asset.
- [x]  Image asset (PHOTOVOICE) -- Creative Commons text should link to Floodlight's CC page. Instructions need to be updated to reflect proper buttons (Click on "Image" instead of click on "add your image"). 
- [x]  Text asset (PHOTOVOICE) -- Need to shorten so that instructions fit in Help drawer. Need to adjust spacing.
- [ ]  New Section (PHOTOVOICE) -- It is defaulting to the photovoice (text + image) layout, but has the generic new section text.
- [ ]  Should it have custom Story Information help?

Data Story Template:
- [ ]  Should it have custom Story Information help?
- [x]  Introduce Your Data Visualization (DATA STORY) -- Needs editing to be more concise. Should include something about what is the single biggest takeaway, what is the "Why?"
- [x]  Introduce Your Data Visualization/Text Asset (DATA STORY) -- Doesn't have individual asset help - is this needed?
- [x]  Data Visualization: Chart, Graph or Map (DATA STORY) -- Weird formatting (first PP is indented) needs to be fixed. Once we have integrated data sources into data assets, need to update last paragraph to reflect how to add source data.
- [ ]  Data Visualization: Chart, Graph or Map (DATA STORY) -- Right now, users can add any kind of asset - should it be restricted to Image, Chart, Table, Map?
- [ ]  New Section (DATA STORY) -- The default new section is a text-only one-up - should it be a different layout?

Explainer Template:
- [ ]  Should it have custom Story Information help?
- [ ]  In general the template is confusing, especially now that the sections all appear as "Untitled"...
- [ ]  This one really needs EXAMPLES (all sections)

Sandbox Template:
- [ ]  Should it have custom Story Information help?
  *[ ]   Why does the default blank section not have asset-specific help (generic help for choosing which asset to add?)

**Comment by jwirfs-brock** [comment]
Note to self: Look at what the default "New Section" is on each template.

**Comment by jwirfs-brock** [comment]
Default new sections are...

Data Story:
- One-up with text-only (can't change asset type)
- If you switch to other layouts (i.e. side-by-side) you can then choose any asset type, but there's no way to change the asset type for a new one-up (for example, if you wanted to add a second featured data visualization)
- Needs to be fixed.

PhotoVoice:
- Side-by-side with image on right, text on left
- This looks good!

Sandbox:
- One-up with an asset type selectable.
- Looks good.

Explainer:
- Side-by-side with any asset type selectable.
- Looks good.

**So, the only template that needs to be fixed is the Data Story. Instead of a one-up text asset, it should be a 0ne-up with any asset type.**

**Comment by jwirfs-brock** [comment]
@ghing Some of the help items have extra text  added on to the end that I can't edit through the admin (at least not at http://floodlightproject.org/en/admin/storybase_help/help/). Everything **before** that I can edit via the admin.

It looks like it's happening for asset-specific help text. Image, text (and maybe some other types) have predefined help text. Containers that can be any asset are getting the message described above above ("There isn't help for this type of asset yet, or you haven't selected an asset type.")

In addition to the example I cited above, on the PhotoVoice story, the asset-specific help for both the text and image has extra text tacked on to the end. The text asset has, "Click on 'Add your text,' and start typing. If you’d like to add a different type of asset, click below," and image asset has, "Click on 'Add your image,' then enter a URL or upload an image from your computer. If you’d like to add a different type of asset, click Cancel."

I can't find where this text is coming from or where I can edit it. I'd like to change it because it doesn't actually match up with how the UI currently works.

If this is still confusing, let me know and I'll try to post some more screen shots or do a screen capture.

**Comment by ghing** [comment]
@jwirfs-brock, these are in the [client side templates](https://github.com/PitonFoundation/atlas/blob/develop/apps/storybase_story/templates/storybase_story/story_builder_handlebars.html), and the default message is in the source code for the builder views.  I'm going to take a look at the code and try to summarize the behavior and then you can let me know if the behavior needs to change, or just the text.

**Comment by ghing** [comment]
First part of how the asset help works:

When the user clicks the question mark icon next to a container, it opens the help drawer and adds help text to the drawer. The help text-is pre-defined for many (but not all) types (and can be added for others) in the client-side templates. If there isn't a template for a particular asset type, or one hasn't been selected yet, a default message of "There isn't help for this type of asset yet, or you haven't selected an asset type." is shown.

I haven't yet figured out how this is interacting with the section help text (what you're editing in the Django admin)

**Comment by ghing** [comment]
Second part of how the asset help works:

Again, to clarify, this is the text that is shown when a user clicks on the "?" icon.

If a particular section has help text for the section, the help text for the asset is appended to the bottom of it.

The reason for this, is, if I recall, because we wanted to make the last shown help remain in the help drawer, even after its closed.  We couldn't think of a good trigger to switch back to section help from asset help, so we show both.

That sums up what happens. @jwirfs-brock, can you clarify whether you want to change the behavior or just the text.

**Comment by jwirfs-brock** [comment]
@ghing I think it is actually showing container help and asset help. I'm not seeing the asset help along with the section help (which is good - that's the expected behavior). I think that's fine, and reflects the expected behavior.

My question was about where I can edit the text for the asset-specific help. I can't seem to find it in the admin.

Also, as far as I can tell, there is no way to switch back to the section help once you've clicked on the container help (the one you get to from clicking on a question mark).

**Comment by ghing** [comment]
@jwirfs-brock, you're right. I meant container help and asset help, not section help and asset help.

The asset-specific help is in a [template file](https://github.com/PitonFoundation/atlas/blob/develop/apps/storybase_story/templates/storybase_story/story_builder_handlebars.html).  You can either fork it using git, edit and send a pull request, or just send me the edits.  Let me know which you'd prefer.

We decided to put it there because it doesn't change very often and it's more efficient to load it from the template than from the database. If you want to be able to edit it more frequently, we can implement it like the container/section help.

We could also just do away with the default asset-type help and just be sure to include information about that in each container's help.

> Also, as far as I can tell, there is no way to switch back to the section help once you've clicked on the container help

Yeah. If I recall, we couldn't figure out a sensible action way to trigger this switch.  Is there one that makes sense for you?  I suppose we could just unload the container-specific help once the drawer is closed.

**Comment by jwirfs-brock** [comment]
@ghing I think switching back to the section help every time the container is closed then reopened makes the most sense.

**Comment by jwirfs-brock** [comment]
@ghing Here is the updated asset-specific help. What works best for you, given the time zone difference, in terms of updating this? I can download the file and edit it myself, then merge it back into GitHub, but I might need you to walk me through it again.

Image
If you upload an image file from your computer, it must be in JPEG, GIF or PNG format.
Or, you can add a file hosted anywhere on the web (examples: Flickr, Dropbox, Imgur) by pasting its url.

Audio
To embed an audio file, it must be hosted externally on the web. We recommend creating a free Soundcloud account to host your audio files. Copy the link from the Soundcloud audio player and paste it here.

Video
[Can keep as is.]

Map
If you upload an image file from your computer, it must be in JPEG, GIF or PNG format.
If you are embedding an interactive map (i.e. from Google Maps, Tile Mill), copy the embed code and paste it here.

Chart
If you upload an image file from your computer, it must be in JPEG, GIF or PNG format.
If you are embedding an interactive chart (i.e. from Google Charts, Tableau Public, Infogram), copy the embed code and paste it here.

Table
If you upload an image file from your computer, it must be in JPEG, GIF or PNG format.
If you are embedding a live table (i.e. from Google Drive, Free Dive, Colorado Data Engine), copy the embed code and paste it here.

Quotation
Type the body of the quote in the first field. Enter the name of the person who said the quote in the “Attribution” field. You can include a url to the full article, book, blog post, etc., from which the quote is excerpted.

Text
Type your text and click “Save Changes” when you are finished.

**Comment by ghing** [comment]
@jwirfs-brock I think it will be fastest for me to just update it based on the list that you sent.

**Comment by ghing** [comment]
@jwirfs-brock, my impression is that this issue is completed, so I'm closing.  Please let me know if you find otherwise.
