### ISSUE TITLE
Active section highlighting in megamenu

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#644]
This is a sub-task of #426 and it should be implemented after #642

Docs for navigation in Django CMS: https://django-cms.readthedocs.org/en/latest/getting_started/navigation.html

Docs for custom menus in Django CMS: http://docs.django-cms.org/en/2.3.5/extending_cms/app_integration.html#menus

I'm pretty sure that some wiring of our custom views into the Django CMS menu structure happens in `cmsplugin_storybase.menu`

**Comment by ghing** [comment]
I can envision a CSS-based solution to this since there are only a few top-level menu items and they're hard coded.

You could use Django CMS' [page_attribute](http://docs.django-cms.org/en/2.3.5/advanced/templatetags.html#page-attribute) tag to grab the slug for the root page and use it as a class for the body tag (I think we have a block in our template for that):

```
{% page_attribute "slug" request.current_page.get_root %}
```

For views that we create ourselves and don't use Django CMS to generate content for (Explore, Build, Project Detail, Organization Detail) the class would just be hard-coded in the template.

Then, give each megamenu top-level item a class/id.  When the body class and the nav item class match, show it as highlighted, otherwise normal.

If this looks like it's overly verbose or brittle, I would make the megamenu an inclusion template tag and put some logic in the template tag to detect the active path (maybe using [django.core.urlresolvers.resolve](https://docs.djangoproject.com/en/dev/ref/urlresolvers/#resolve)) and generate markup with the appropriate classes.

**Comment by patternleaf** [comment]
OK, this is implemented. @ghing, you mentioned that the "id" should be a language-agnostic page attribute, but in my test that seemed not to output anything. So at the moment it's using slug. Also this will need to be updated slightly when #642 is done.

**Comment by ghing** [comment]
Eric, according to https://groups.google.com/forum/?fromgroups=#!topic/django-cms/PzHwKYHaAIg, the page ID might not be accessible through that template tag `{% page_attribute %}`.  Do either of the strategies in that google group post work?

**Comment by patternleaf** [comment]
@ghing reverse_id worked. thanks. (see 70cca1b)

**Comment by ghing** [comment]
STILL TODO:
- Give news and updates page an id, add styles for menu highlighting for this section

**Comment by ghing** [comment]
@patternleaf, taking this issue to do the last bit of wiring

**Comment by ghing** [comment]
Gave _News & Updates_ page an id of _news_, moving on to update the CSS to reflect that
