### ISSUE TITLE
Builder toolbar icons misaligned in Chrome 0.25

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#649]
![Screenshot from 2013-02-25 08:39:38](https://f.cloud.github.com/assets/110420/192131/42f60672-7f59-11e2-99bc-a973e1ada113.png)

**Comment by ghing** [comment]
Assigning this to @patternleaf just because he did the original styling/CSS work (or likely wrestling with the CSS from the subcontractor).  @jwirfs-brock I'd nominate this for Iteration 12, just because it's very noticeable and not too difficult of a fix.

**Comment by jwirfs-brock** [comment]
@ghing Ok, moving to Iteration 12.

**Comment by patternleaf** [comment]
ugh. initial investigation indicates something hacky may be required. using jQuery or the webkit inspector, you can flip the float:left property off and then on again and the menu will draw correctly. will continue investigating for other options.

**Comment by patternleaf** [comment]
Have a not-terribly-hacky fix for this, though it's unclear where the problem lies: is it a bug in Chrome's rendering or is Chrome rendering something properly which other browsers are missing?
