### ISSUE TITLE
Googlebot gets a JavaScript Error

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#650]
The [Fetch as Google](http://support.google.com/webmasters/bin/answer.py?hl=en&answer=158587) tool might be a good way to diagnose these problems

Errors are like this:

```
[Django] ERROR: javascript error: {"url": "http://floodlightproject.org/static/js/models.js", "message": "TypeError: 'undefined' is not a function", "HTTP_USER_AGENT": "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)", "location": "http://floodlightproject.org/stories/camoplauge/viewer/", "lineNumber": "365"}
```

I'm tagging this as low, because Google should at least be indexing the story detail page and this error doesn't seem to be affecting real browsers.  Still, it would be nice to supress this error, or show Google the rendered page output.  I'll have to do more research into what Google's bot supports in terms of JavaScript. It might make more sense to fall back to a simplified rendering of the story in `<noscript>` tag so Googlebot can at least index the story content

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
