### ISSUE TITLE
Unable to edit unpublished story in Builder -- had Google chart embedded in it

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#659]
I created a story (that I did not end up publishing) for the purpose of testing out a Google charts embed:

http://floodlightproject.org/en/stories/test-embedding-a-chart-created-from-a-live-survey/

When I attempt to open it in the Story Builder, I get the following error (I see a bunch of white space, then this text when I scroll below the fold):

", "caption": "", "content": "
\n\n
", "created": "2013-02-22T10:51:59.135425", "display_title": "{\"dataSourceUrl\":\"//docs.google.com/spreadsheet/tq?key=0As2exFJJWyJqdFBHSkJuaW9yZG1yOWIwRFlPdXlhTXc&", "image": null, "language": "en", "languages": [{"id": "en", "name": "English", "url": "/en/assets/e37a4a06a03b4a04a22397132cbdf740/"}], "last_edited": "2013-02-22T10:51:59.528552", "license": "CC BY", "published": null, "resource_uri": "/api/0.1/assets/e37a4a06a03b4a04a22397132cbdf740/", "section_specific": false, "source_url": "", "status": "draft", "thumbnail_url": null, "title": "", "type": "chart", "url": null}]}; featuredAssetsJSON = {"objects": []}; containerTemplatesJSON = {"objects": [{"asset_type": "text", "can_change_asset_type": false, "container": "center", "container_template_id": "7e639ac5f6ed4df2adaf25b0d432abff", "help": {"body": "\r\n
What can readers learn from exploring the data? Here, you might want to highlight some of the most interesting facts or findings that your data visualization or data analysis reveals.

\r\n
Make sure you also include the data source and relevant information like date and geographic area the data covers.

\r\n", "help_id": "49f4151293f74c329a1bd687e24fd10a", "title": "Introduce Your Data - Text Help"}, "resource_uri": "", "section": "571f78d5945543a489a8f256400a5b61", "template": "7e86c335e5c940eb9ff82108011b51f8"}, {"asset_type": "table", "can_change_asset_type": true, "container": "center", "container_template_id": "d4c3bc55b5e347d4a81a01e6134da25c", "help": {"body": "\r\n
Your data visualization goes here. It can be an embedded interactive visualization or a static image pulled from a URL or from your computer. You can include information about the visualization, such as the data source, in the caption at the bottom.

\r\nClick on “Add your chart,” then enter a URL or embed code, or upload an image from your computer. If you’d like to add a different type of asset, click below.", "help_id": "fd0a5c16879c4c21b1b05bb38bdd7c71", "title": "Chart, Graph or Map "}, "resource_uri": "", "section": "0def601c9cc24239805ba9eb4a92f4dd", "template": "7e86c335e5c940eb9ff82108011b51f8"}]}; if (relatedStoriesJSON) { options.relatedStories.reset(relatedStoriesJSON.objects); } if (templateSectionsJSON) { options.templateStory.sections.reset(templateSectionsJSON.objects); } if (options.model && assetsJSON) { options.model.assets.reset(assetsJSON.objects); } if (options.model && featuredAssetsJSON) { options.model.setFeaturedAssets( new storybase.collections.FeaturedAssets( featuredAssetsJSON.objects) ) } if (containerTemplatesJSON) { options.containerTemplates.reset(containerTemplatesJSON.objects); } options.storyTemplates.reset(storyTemplatesData.objects); options.help.reset(helpData.objects); storybase.builder.router = new storybase.builder.routers.Router({ dispatcher: storybase.builder.globals.dispatcher, hasStory: !_.isUndefined(options.model), hasTemplate: !_.isUndefined(options.templateStory) }); storybase.builder.app = new storybase.builder.views.AppView( options ); Backbone.history.start({pushState: true, root: storybase.builder.globals.APP_ROOT}); });

**Comment by ghing** [comment]
@jwirfs-brock Does the embed code for your chart have a `<script>` tag?  If so this is probably another instance of #658, which Jon was running into as well.  If that's what's going on, can you close this issue and add the emebed code to #658 so I can start getting a sense of which kinds of `<script>` embed codes we want to support.

**Comment by jwirfs-brock** [comment]
Yup, I believe it did. Will do.

**Comment by mgrayinnovation** [comment]
See #658, #686
