### ISSUE TITLE
Section list wraps to second row when there are a large number of sections

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#662]
In a story with 23 sections, the section list appears like this:

![Screen Shot 2013-02-27 at 3 35 58 PM](https://f.cloud.github.com/assets/110420/207698/8409ddda-81f9-11e2-84f8-10f5909632a7.png)

When the section list wraps, the section and page titles are obscured.

**Comment by ghing** [comment]
I was able to replicate this issue with a story with 10 sections (or 12 elements in the list including the "Story Information" and "Call to Action") in the latest versions of both Firefox and Chrome.

**Comment by ghing** [comment]
Giving the `#section-list` element a height of 108px seems to fix the wrapping.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
