### ISSUE TITLE
Sidebar nav on interior pages doesn't reflect page hierarchy

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#665]
For example, on About:

![sidebar_nav](https://f.cloud.github.com/assets/1020518/218953/5e0fdb42-851a-11e2-8a1a-c4c33db9e464.png)

Parent (About) and children (The Vision, Community Values, Partners, How it Works) all have the same color and size.

Should we display the hierarchical structure in the side nav?

If we want two, options are:
- Text color
- Text size

Note that if we even add in third-level pages (children of the children), this may become more important. For now, it's ok.

**Comment by bpawlak** [comment]
Since we're repeating the top level nav item (to address people not clicking on the main menu after invoking the meganav, I think it actually makes more sense the way it's shown above.  The alternative:

About
    - - The Vision
    - - Community Values
    - - Partners
    - - How it Works

Would look odd, especially in the left-nav
