### ISSUE TITLE
Homepage banner rendering oddly before hard refresh

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#667]
I noticed this in both Firefox and Chrome (on Windows): The first time I visited the homepage after the Iteration 11 updates were deployed the banner did not appear correctly (was resizing but not cropping images).

After a hard refresh it rendered fine, but I just wanted to document this in case any one else runs into it.

Here's a screen shot:
![banner_weirdness](https://f.cloud.github.com/assets/1020518/228101/9d37b6da-8675-11e2-84aa-0769c0549264.png)

**Comment by ghing** [comment]
This is a result of #624.  I'm going to add #624 to Iteration 12 because I think with all the JavaScript changes in the builder/viewer, we'll want to make sure that users get them when they load the builder.
