### ISSUE TITLE
Templates should suggest next steps, not predefine sections

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#670]
As @patternleaf and I were discussing #616, and trying to figure out how to handle suggested titles for sections, it made me think about how our concept of templates is broken.

Right now templates are:
- Metadata describing the types of stories the template is directed to
- A pre-defined set of sections with default titles, layouts and default or suggested asset types
- Help text describing what to put in each section

When a story is created from a template, the sections are copied from the template story.  However, as @bpawlak has suggested, this can be intimidating and it also more forcefully proposes an organization for the story.

When creating a new story from a template, it should just show a single initial section.  The help/layout/suggested fields/assets might change from template to template. 

Then, an add-section dialog would present users to create a new section based on its purpose within the storytelling domain, and keep track of which sections users had added to the story.  In that way, users can see the big picture of the template, but not box them into it, forcing them to delete pre-created sections.

So, a user selecting the _Explainer_ template might get started with just the _Introduction_ section in their workspace (or, be presented with a dialog asking them which section they wanted to start with)

Then, if the user clicked the "Add Section" button/icon, they'd get a dialog with options like this (the microcopy sucks, but hopefully gives you an idea of what I'm going for):
- Definition - Define the components of your complex subject
- Element - Describe a single component of your complex subject
- Something else
- Conclusion - wrap things up for your audience

Clicking on any one of these would load any default values or set the appropriate help in the viewer.

**Comment by bpawlak** [comment]
This is definitely in line with where I've been going in terms of thinking about this.  Great synthesizing!

**Comment by mgrayinnovation** [comment]
We are hiding the templates for now during Milestone Iteration P4, but this is an important dialogue to consider at a later date and after we get some feedback from users and storytellers.
