### ISSUE TITLE
Paste bin for scripts

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#672]
One of our big problems is supporting arbitrary embed codes.  One way to deal with it would be to set up a separate pastebin-like service that would let users input a script embed code and then get another IFRAME embed code that they coulld use in floodlight.  Since the iframe would be a different domain, a malicious script inside the iframe couldn't do any damage.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
