### ISSUE TITLE
Character counter/limit indicator is active for text assets

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#673]
For now, this should only be active for the summary.  I could see it being useful in text assets, but with a different limit.  It would be nice to be able to just set an option in the code to easily toggle this behavior (maybe that's how it works now, I haven't looked).

Since the limit is just a warning, this doesn't prevent users from entering their text, but it might be confusing.

![Screenshot from 2013-03-08 08:04:19](https://f.cloud.github.com/assets/110420/236681/2cf71822-87f9-11e2-9745-b022f0ca1c0a.png)

**Comment by patternleaf** [comment]
Right now the counter JS is triggered by the presence of an element with class character-counter. Which, it turns out, is always present in the editor-toolbar-template handlebars template, used in the RichTextEditorMixin. @ghing At what level do you think it would be most appropriate/convenient to toggle the counter?

**Comment by ghing** [comment]
@patternleaf, Off the top of my head, I think the quick fix would be to have a character limit option passed into views that implement the RichTextEditorMixin.  Then, somewhere in that view code, add the character-counter element if the character limit option is present.

**Comment by patternleaf** [comment]
@ghing would you mind sanity-checking 92d268a?

**Comment by ghing** [comment]
@patternleaf What's the status of this?

**Comment by patternleaf** [comment]
@ghing I think I'd like to implement your suggestion:

> It might make more sense to move the character limit out of the template and use this instead of the showCharacterCount flag. If the count evaluates to something truthy, it's shown, otherwise the limit warning is disabled.

which shouldn't be difficult. Then it should be ready for pull request.

**Comment by ghing** [comment]
@patternleaf, sounds good
