### ISSUE TITLE
Soundcloud embed via link is not working in Story Builder

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#681]
This one's a bit odd, because I know Soundcloud was working in the past. I did a test of a Soundcloud embed (here's the story: http://floodlightproject.org/build/5d99f64481c0471b9f176d9a357d7e6a/) by...
1. Choosing an audio asset
2. Pasting the link providing by Soundcloud when you click on the "Share" option for a clip (https://soundcloud.com/floodlightproject/test-3)
3. Saved the asset, and it did not render in the Builder
4. Previewed the story, and it was still not rendering in the preview

This one's high priority since we have some users who are planning on embedding audio in their stories on Saturday.

**Comment by jwirfs-brock** [comment]
Note that Soundcloud also provides embed code for a widget. Here's an example:

`<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F82774070"></iframe>`

But our audio asset doesn't have a field to enter embed code, only one for entering a link.

**Comment by ghing** [comment]
Moving to Iteration 12 because of high priority status.

**Comment by ghing** [comment]
Just tested the SoundCloud oEmbed endpoint and it seems to be returning things ok, e.g. http://soundcloud.com/oembed?url=https://soundcloud.com/floodlightproject/test-3&format=json returns:

```
{
version: 1,
type: "rich",
provider_name: "SoundCloud",
provider_url: "http://soundcloud.com",
height: 166,
width: "100%",
title: "Test 3 by Floodlight Project",
description: null,
thumbnail_url: "http://a1.sndcdn.com/images/fb_placeholder.png?ca77017",
html: "<iframe width="100%" height="166" scrolling="no" frameborder="no" src="http://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F82774070&show_artwork=true"></iframe>",
author_name: "Floodlight Project",
author_url: "http://soundcloud.com/floodlightproject"
}
```

I need to see if this isn't getting through to our app or if it's more an issue of the IFRAMEd player not displaying properly in the viewer.

**Comment by ghing** [comment]
@jwirfs-brock, the issue with this is the "https" in the URL vs. the "http".  I'll fix this to make the URL matching operation more flexible (I just copied them from the library's examples), but the quick workaround is to just use "http://" when you enter the URL instead of "https://"

```
>>> from storybase_asset.oembed import bootstrap_providers
>>> providers = bootstrap_providers()
>>> providers.request("https://soundcloud.com/floodlightproject/test-3")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/micawber/providers.py", line 84, in inner
    return fn(self, url, **params)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/micawber/providers.py", line 111, in request
    raise ProviderNotFoundException('Provider not found for "%s"' % url)
ProviderNotFoundException: Provider not found for "https://soundcloud.com/floodlightproject/test-3"
>>> providers.request("http://soundcloud.com/floodlightproject/test-3")
{u'provider_url': u'http://soundcloud.com', u'description': None, u'title': u'Test 3 by Floodlight Project', 'url': 'http://soundcloud.com/floodlightproject/test-3', u'html': u'<iframe width="100%" height="166" scrolling="no" frameborder="no" src="http://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F82774070&show_artwork=true"></iframe>', u'author_name': u'Floodlight Project', u'height': 166, u'width': u'100%', u'version': 1.0, u'author_url': u'http://soundcloud.com/floodlightproject', u'provider_name': u'SoundCloud', u'thumbnail_url': u'http://a1.sndcdn.com/images/fb_placeholder.png?ca77017', u'type': u'rich'}
```

**Comment by jwirfs-brock** [comment]
Interesting. Brigid had this issue when embedding from Vimeo too, right?

It's odd in that I wasn't logged in to Soundcloud when I grabbed the link
-- the default one that they provide has https. I am wondering if maybe we
should make a note/provide some help text around this?

**Comment by ghing** [comment]
@jwirfs-brock, no need to provide help for this.  I'm going to make it "just work" in a second.
