### ISSUE TITLE
Line separator unicode characters in asset JSON breaks builder

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#683]
## To replicate
1. Navigate to the builder
2. Create a new "Photovoice story"
3. In the right hand container, create a text asset and click the "HTML" icon to enter HTML.
4. Enter this HTML in the text area:

```
<p>Here are the
facts: </p>
<p>1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong>1 in 7 Students in Grades K-12 is
either a bully or a victim of bullying.</strong><strong> </strong><span><br>
<br>
<strong>2.&nbsp;&nbsp;&nbsp;&nbsp; </strong>90%<strong> of 4th through
8th graders report being victims of bullying</strong><strong></strong></span></p>

<strong>3.&nbsp;&nbsp;&nbsp;&nbsp; </strong>1 out of every 10<strong> students who drops out of school because of </strong>repeated bullying.
```
1. Click the "Save" button
2. Reload the builder page using the browser's reload button or keyboard shortcut
## Expected result

The story is loaded in the builder for editing
## Observed result

The builder is loaded but the section list bar and main content bar are empty.

The actual problem HTML is some unprintable unicode characters in this substring:

```
<strong></strong>
```

I found the unicode characters:

```
>>> s.encode('string_escape')
'<strong>\\xe2\\x80\\xa8</strong>'
```

Originally reported in #658 in [this comment](https://github.com/PitonFoundation/atlas/issues/658#issuecomment-14593189)

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
