### ISSUE TITLE
Stories with long titles make title bar cut off content in viewer

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#684]
## To replicate
1. Open http://floodlightproject.org/en/stories/the-denver-foundation-prepares-for-the-seventh-cla/viewer/ 
## Expected result

Summary (and other body) content is visible.
## Observed result

Summary (and other body) content is cut off.

![Screenshot from 2013-03-18 09:06:58](https://f.cloud.github.com/assets/110420/270827/54107c26-8fd5-11e2-9118-62df10579003.png)

**Comment by patternleaf** [comment]
So right now the body container has a hard-coded padding-top while the header is position:fixed. I'm not sure off-hand if there's a pure CSS way to make this work. @ghing do you have a suggestion on that front? If not it should be easy to add in some JS to dynamically set the padding on the body.

**Comment by patternleaf** [comment]
Another option might be to reconfigure the layout and use overflow:auto on the body container, rather than position:fixed for header and footer elements. This would also take care of the footer position bump that happens when moving between longer sections and shorter sections. @ghing any thoughts?

**Comment by ghing** [comment]
@patternleaf, I might be missing something, but my first thought is that we can just get rid of the `position:fixed` CSS property on the header element and any hard-coded padding on the body.  I think that's an artifact from when we had the linear, vertically scrolling story viewer where the active section heading would be shown in the header.  All that's long gone, so it seems silly to have the fixed position header to me.  I think having overflow:auto for the body container seems fine.
