### ISSUE TITLE
In Story Builder, if section titles are long, contents bar obscures title and layout selection fields

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#687]
See screen shot:
![SB_bug_32213](https://f.cloud.github.com/assets/1020518/292733/205a11c2-9330-11e2-9bb1-a1ca83480263.JPG)

This is happening int he story http://floodlightproject.org/en/build/924489b3f14a452ab1e6ae259a1ced32/. Note that the user fixed this by shortening the titles (had to delete existing sections and add new ones).

This story is now displaying sections on two rows in the table of contents bar (issue #556).

**Comment by ghing** [comment]
This is actually a manifestation of #556.  The bar shows up in two rows because of the number of sections, not because the length of titles.  Closing and continuing to troubleshoot this as part of #556.
