### ISSUE TITLE
Back scroll arrow in table of contents bar in builder not working properly

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#688]
In the story http://floodlightproject.org/en/build/924489b3f14a452ab1e6ae259a1ced32/, the back arrow is not working. That is, once you've scrolled to the last section, you can't scroll back to the beginning.

**Comment by ghing** [comment]
This is also a manifestation of #556. The back scroll button stops working when there are a large number of sections (>10) because the slides are pushed down to two rows.  I'm closing this and will work on it as part of #556.
