### ISSUE TITLE
Asset drawer scrolls out of view for 3-up layout

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#692]
## Summary
- Dragging and dropping an asset from the asset drawer into a container doesn't always work
- Dragging and dropping assets from the drawer to a container can be difficult if you have large photos.
## Original report

A new Floodlight user passed along some feedback on difficulty she had with the asset drawer: 

> Wish I had some specifics regarding functionality for feedback to the developers. The only issues I seemed to have were for the videos. At one point the side-by-side layout only gave me two options for content type: image and text (I believe I created mine using the sandbox template if that makes a difference). Somehow I overran this by dragging a video from the assets panel into one of the frames, which didn't always work so I had to keep trying. The assets panel was a bit cumbersome though because if you have large photos, you may have to scroll down the panel to get other assets, and it can be difficult therefore to drag it back up the page into the template.

**Comment by ghing** [comment]
I broke the first item regarding the available content types into a separate issue (#699 Side-by-side layout only allows image and text content types).

**Comment by ghing** [comment]
@tekhneco, I broke out what I see as the core issues that the user raised in the issue summary above.  Regarding the second point (issues dragging and dropping when there are large photos), I'm not sure if the user means large photos in the asset drawer or large photos in the section containers.  If I could get the story's builder URL (best) or title (ok, still lets me lookup the story), I can take a peek and get a better idea of what's going on.

**Comment by wendynorris** [comment]
Here's the Story Builder URL: 

http://www.floodlightproject.org/en/build/7a22cadacb2f48bbbaa0d571f80f8d5b/

Here's the public story in the viewer: 

http://floodlightproject.org/stories/new-freedom-park-community-garden-service-project/

One issue here that might relate: I have found that authors do not appear to be compressing their images or video before uploading resulting in huge files (both physical size and file size). My sense of the problem on this story is that the photos display quite large in the asset drawer.

**Comment by ghing** [comment]
I took a closer look at this.  I believe the problem is that the asset drawer scrolls out of view for tall layouts (like 3-up).

![asset_drawer_scrolling_out_of_view](https://f.cloud.github.com/assets/110420/365611/0b8d82e8-a252-11e2-8f3f-c18e834c2e31.png)

In this screenshot, I've scrolled down to the second of the 3 elements in the 3-up layout.  Note that the asset drawer has almost scrolled out of view.

I'm updating the issue title to better reflect what's going on.

**Comment by wendynorris** [comment]
Thanks Geoff!

**Comment by ghing** [comment]
The drawer layout is pretty broken. I think my original intent was to rely on CSS to scale the main content when the drawer was opened, and this works pretty well, but the more I use the drawer, and based on this issue, I think the drawer needs to be positioned fixed so it doesn't scroll with the rest of the content.  I'm going to work on fixing this today and tomorrow.

**Comment by ghing** [comment]
This is fixed and deployed into production.  Maps in the drawer are still ugly (see #708), but the fix in 29930b2 should at least make the scrolling and dragging behavior work correctly.
