### ISSUE TITLE
Side-by-side layout only allows image and text content types

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#699]
Originally reported by a user via @tekhneco in #692

> At one point the side-by-side layout only gave me two options for content type: image and text (I believe I created mine using the sandbox template if that makes a difference).

**Comment by ghing** [comment]
@tekhneco, I wasn't able to replicate this with the Sandbox template.  I suspect that the user was actually using the PhotoVoice template which does restrict to image and text.  If you can get the URL when the user opens the story in the story builder (ideally) or the story title (a bit more difficult to lookup but still ok), I can take a look and get a better sense of what's going on with this.

**Comment by wendynorris** [comment]
Here's the Story Builder URL: 

http://www.floodlightproject.org/en/build/7a22cadacb2f48bbbaa0d571f80f8d5b/

Here's the public story in the viewer: 

http://floodlightproject.org/stories/new-freedom-park-community-garden-service-project/

**Comment by ghing** [comment]
I confirmed that this story was using the PhotoVoice template, which does limit the left container to an image and the right to text. This is working as designed, though I understand why it's frustrating to the user.  I'm going to close this issue.  But, @tekhneco, let me know if the user wants a specific layout for this story.  I can twiddle things on the backend to let them do whatever they want.
