### ISSUE TITLE
Maps look bad, are too large in asset drawer

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#708]
Maps are rendered as their actual size in the asset drawer so they both look weird and make it difficult to see other assets.

![Screenshot from 2013-04-11 10:38:41](https://f.cloud.github.com/assets/110420/368362/5946039a-a2be-11e2-98b1-8dff816a51bf.png)

**Comment by ghing** [comment]
There are a couple of options to address this:
1. Show an icon instead of the rendered map. This is easy to do, the downside is that if there are multiple maps, the user can't easily know which one is which without adding it to a container
2. Show an icon instead of the rendered map.  Show the rendered map in a popup when the user hovers (or maybe clicks a preview link, it might take a little tweaking to get this to work right so that it doesn't conflict with the draggable interactions)
3. Render the map into a thumbnail image that's scaled to the appropriate width.  This might be very hard to do, though I have some ideas how to do it.  This would take the longest, but be helpful if we ever wanted to generate thumbnails of sections.

Thoughts?

**Comment by bpawlak** [comment]
I think even #3 would require a popup/hover/click that would let the user see a larger version of the map.  The details of the map would likely be too small to differentiate at thumbnail size.

**Comment by ghing** [comment]
@bpawlak, good point.  2 seems the best then?

**Comment by bpawlak** [comment]
I'd love to see 3 implemented, as I think it's more inline with showing thumbnails of images, but I understand that it has its challenges.

**Comment by ghing** [comment]
@bpawlak Well, since the popup is needed anyway, I can do 2 and then start experimenting with 3.  If you know of any good, easy ways to generate images of arbitrary rendered HTML, let me know.  I've not had to do this before and my best guess is to use a library wrapping an HTML rendering engine (or headless browser).

**Comment by bpawlak** [comment]
Found some online tools (http://www.prodraw.net/online-tool/google-maps-image-generator.php) and http://www.phpriot.com/articles/static-google-maps

**Comment by ghing** [comment]
@bpawlak Thanks for looking that up.  I'll look into the approach described in the [Generating Static Google Maps](http://www.phpriot.com/articles/static-google-maps) article. I wasn't aware of the static image API. Unfortunately, I don't think the approach will work for us since we're given arbitrary Google Maps urls or embed codes from the user.  Furthermore, we don't require Google Maps, so users could embed a Bing map, or something else if they wanted, though I believe most users are using Google Maps.

**Comment by jwirfs-brock** [comment]
I like the #2 option. I agree with Bill that when a Google map is shown as a thumbnail, it's hard to distinguish between them anyway. It also seems like it flows pretty easily out of #1. That is, you could implement 1 first in the short term, then add in 2 if it ends up taking more time.

I'm not sure how common it would be for someone to tend up having multiple maps in the asset drawer. Seems like a pretty edge case.

**Comment by jwirfs-brock** [comment]
Another option would be to add a title field to map assets. That way, you could distinguish multiple maps with the same icon via the title. What I don't like about this is that then you have to decide whether to display the title. Often, if I'm creating a map that is an image, I'll include the title in there. But...I guess if it's a map that is uploaded as an image file, creating a thumbnail wouldn't be a problem anyway...

**Comment by bpawlak** [comment]
It seems like we'd be asking people to artificially create a title for a map, just for the purposes of distinguishing them in the asset container.  Do we ever change the order that assets are listed in the container?  I ask because if I'm building a story, _I_ know which assets I've put in there, so maybe there won't be as much confusion as we're anticipating.  Esp. true if, like you say, multiple maps is an edge case.

**Comment by jwirfs-brock** [comment]
Well, it's good (and standard) practice for every map to have a title. Just
like it's good practice for every chart/graph to have a descriptive title.
The question is, we don't know if whatever map they are embedding already
has a title associated with it. But yes...I don't thinking enforcing a
title is necessary a good solution for this. Just throwing it out in case
it inspires something better...

It looks like the oldest asset is always at the top, if multiple assets end
up in the drawer. Is that right?

**Comment by bpawlak** [comment]
Sorry, I wasn't clear in my explanation... I was thinking about the fact that the map (just like any other "imported" assets) may actually have a title associated with it, but we might not be able to access that title for the purposes of the asset drawer, so we'd be asking them to create a new title just for that purpose.

**Comment by ghing** [comment]
Moving out of Iteration 13. We'll get to this later

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
