### ISSUE TITLE
Initial view of topic map on spider story should have "next" button

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#71]
When a user views a enters the story viewer of a spider story and sees the topic map, a "Next" button should appear on the bottom navigation bar (the way it does when a user goes to the topic map from a story section/node). 

The "Next" button should take the user to the root section. 

See screen shot: http://a.yfrog.com/img705/7406/ed.png

**Comment by ghing** [comment]
Closed by 9104dc00927e955473ca8df99bd2c22d3676779d
