### ISSUE TITLE
Inconsistencies in way you save summary text versus text in other places (text assets, caption text)

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#711]
The way you edit and then save text is different on the Summary and on text assets, which is confusing for users. You have to click "Save" with text assets and with captions, but not with the Summary. This trains people to not look for the "Save" button, and then they end up losing their text assets because they don't save them. Or at least...this has probably happened to me a dozen times and I'm not new to the builder at all.

Some suggestions:
- Eliminate the "Save" button for text assets and captions, and just use auto-save for those. @ghing Does this pose some problems in terms of the data structure, and the way assets are created and stored?
- Add a "Save" button for the Summary and Call to Action fields (the only text fields that don't have them).

**Comment by ghing** [comment]
> Eliminate the "Save" button for text assets and captions, and just use auto-save for those.

This doesn't pose problems in terms of the way assets are created and stored. My bigger concern is that the "Save" button makes sense for assets where a file upload is involved, and I think it might be a little bit weird to have some asset forms with a save button and some without.  

Based on that, I guess the best option would be to have a save button for the summary and call to action fields.

**Comment by ghing** [comment]
Tagged as "high" priority, but moving out of Iteration 13.  Will try to get to this if we have a break or get blocked in Iteration 14.
