### ISSUE TITLE
Problem adding link in Call to Action

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#713]
I'm not sure what is going on here, as this problem doesn't seem to be replicable 100% of the time. But when I try to add links in the Call to Action (and go through the entire process of clicking the add link icon, then entering ok, then saving), the link shows up within the Builder, but not in the Preview or in the published story.

It's happening right now with: http://floodlightproject.org/en/stories/growing-a-story/

Here's a screen shot of the saved link in the Builder (the misbehaving link is the second one):
![Screen Shot 2013-04-12 at 4 26 43 PM](https://f.cloud.github.com/assets/1020518/375011/ade2b078-a3af-11e2-9175-77a642035cb9.png)

And the link not showing up in the published story:
![Screen Shot 2013-04-12 at 4 26 54 PM](https://f.cloud.github.com/assets/1020518/375013/b7a5a372-a3af-11e2-9cca-d1df2b437530.png)

I was editing the story in Chrome.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
