### ISSUE TITLE
Section list scroll arrows don't work

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#721]
Is there a limit to the number of sections one can add in the Sandbox template?

Here's a link to the story: 
http://floodlightproject.org/en/stories/six-word-memoirs-from-tedxyouthmilehigh/

I categorized the student's six-word memoirs into 10 themes to make the presentation a little more readable. Each theme is its own section. I used the 3-up layout within the Sandbox template.

However, the navigation arrow stops at section 5 and won't go any further. I know the other sections exist (confirmed by viewing in the story admin panel as well as in preview and the table of contents).

I was finally able to navigate to the last five sections only by changing their weights in the admin panel to push them to the front of the list. But that's not going to work for regular users without admin panel access.

Built the story in Firefox 20.0, if that matters.

**Comment by ghing** [comment]
There isn't a limit. I'll look into why the scroll arrows aren't working.

**Comment by ghing** [comment]
@tekhneco I wasn't able to replicate this, either with the story in question or starting from scratch and creating a story with 10 sections from scratch.  When the section scrolling arrow stopped working, did you try reloading the browser tab?  Do you have any other details you recall from when you saw this issue?

**Comment by wendynorris** [comment]
When I clicked the scrolling arrow there was no response. Tried it several times. No response.

I refreshed the browser. No response.

I exited the story. Re-entered. No response.

I exited the story. Logged out. Logged back in. Reentered the story. No response.

The only way I could view the sections was to change the weights in the admin panel.

Are you trying to replicate this big in Firefox? That's what I was using to construct the story.

**Comment by ghing** [comment]
@tekhneco I tried replicating this using both Firefox 20.0 and Chrome 26.0.1410.63

Can you try opening it now and see if the issue persists?

**Comment by wendynorris** [comment]
The scrolling arrow advances to section number 7 (Perseverance). But no further.

The arrow color-change activates on hover but doesn't respond to the click.

**Comment by ghing** [comment]
@tekhneco, I'm picking this back up. Could you take another look at this and paste the output of your Firebug console window in this issue so I can get more of an idea of where the bug might be?

**Comment by ghing** [comment]
Updated title from "Limit on number of sections allowed in Story Builder?"

**Comment by ghing** [comment]
I tried again to replicate this in two ways:

First I opened a copy of the story on staging, which has the same codebase as production.  I was able to scroll through all the sections without any problems.

I then tried creating a similar story, with the same number of sections and section titles from scratch.  I copied and pasted the text into some of the containers.  I was able to navigate through the sections in the section list without problems. This was on dev.

I used Firefox 20.0 (on Ubuntu) in both cases.

I'm going to close this.  If it reoccurs and you're able to capture JavaScript console output, please reopen.
