### ISSUE TITLE
Section displaying as blank after text asset failed to save on dev.floodlightproject.org

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#724]
Story I was working on: http://dev.floodlightproject.org/en/build/a0eeef66a2d84b0fadac652908e8cf70/

This happened while I was trying to replicate #723 

Here are the steps I took:
1. Created a new story from the sandbox template, filled in story information  (title, summary, byline)
2. Edited “untitled section” to create a side-by-side layout section (while doing this, I added an asset, toggled the layouts, then dragged the asset back from the asset drawer) and renamed it, “A story in only six words? No way...”
3. Created a new section
4. Edited the title (“You don’t have to be Hemingway...”)
5. Tried to copy text from an existing Floodlight story into a text asset (that is, the text I was copying/pasting had HTML formatting in it)

Expected result:

Text asset is updated and can be saved

Observed result:

My computer timed out/seemed frozen (it’s been having some issues lately...). So I changed the lay-out from side-by-side to 1-up  
- Instead of seeing the new layout, I saw a blank section
- When I tried moving the section, the table of contents showed two “+” symbols between neighboring sections instead of one.
- I hit refresh, and saw, “error saving the asset” message.

Screen shots of what I saw:
Blank section...
![Screen Shot 2013-04-17 at 1 34 51 PM](https://f.cloud.github.com/assets/1020518/392799/c185fbdc-a786-11e2-92ea-0b86da849a7d.png)
Extra "+" between sections in table of contents...
![Screen Shot 2013-04-17 at 1 35 49 PM](https://f.cloud.github.com/assets/1020518/392801/c6543494-a786-11e2-8d4b-e77931c1824b.png)

**Comment by ghing** [comment]
Edited the original issue report slightly to make it easier to walk through the steps to try to replicate this issue..

**Comment by ghing** [comment]
@jwirfs-brock I wasn't able to replicate this.  For copying and pasting the text, I just used the text from the initial report in this ticket (because it contained HTML).  Do you remember the exact text that you used that triggered this issue?

I'm thinking this might be a cascade of issues related to your browser crashing.

**Comment by ghing** [comment]
I'm going to close this since I can't replicate it exactly and at least some of the behavior seems to be symptomatic of #725
