### ISSUE TITLE
Chart asset using Socrata embed is rendered in a confusing way in the asset drawer

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#734]
## To replicate
1. Open a story in the builder
2. In a container that doesn't have an asset assigned, create a new chart asset by clicking the "Chart" icon.
3. In the textarea labeled "Paste the embed code for the chart", paste:

```
<div><iframe width="500px" title="Fruit and Tree Nuts Yearbook Data tables" height="425px" src="https://explore.data.gov/w/r6wy-597z/md55-89i9?cur=rjipadmWOGs&from=root" frameborder="0" scrolling="auto"><a href="https://explore.data.gov/Agriculture/Fruit-and-Tree-Nuts-Yearbook-Data-tables/r6wy-597z" title="Fruit and Tree Nuts Yearbook Data tables" target="_blank">Fruit and Tree Nuts Yearbook Data tables</a></iframe><p><a href="http://www.socrata.com/" target="_blank">Powered by Socrata</a></p></div>
```
1. Click the "Save Changes" button. The embedded item should appear in the container.
2. Click the remove icon
3. Open the asset drawer by clicking the "Assets" tab
## Expected result

A clearly identifiable representation of the chart should be visible.
## Observed result

"Powered by Socrata" is shown

Original report:

> From sandbox test story on dev.floodlight: 
> http://dev.floodlightproject.org/stories/375044e162aa40968ff239a6d52b2aec
> 
> I embedded a widget in a 1-up layout on the build section titled: Fruit and Tree Nuts Yearbook Data tables
> 
> When I decided to add a chart, I changed the layout to side-by-side. 
> 
> The widget disappeared. The only asset displayed in the drawer was a "Powered by Socrata" link that was embedded in the widget but not the widget script itself. 
> 
> I had to copy and paste the widget embed script from the data source.

**Comment by ghing** [comment]
@tekhneco Is the "widget" you mentioned in your issue report the chat (seemingly made via Google) in the right hand side of the "Fruit and Tree Nuts Yearbook Data tables" section?

**Comment by ghing** [comment]
Note: The "Powered by Socrata" link shown in the asset drawer is an `HtmlAsset` with type `chart` with a `body` attribute that looks like this:

```
u'<div><iframe width="500px" title="Fruit and Tree Nuts Yearbook Data tables" height="425px" src="https://explore.data.gov/w/r6wy-597z/md55-89i9?cur=rjipadmWOGs&from=root" frameborder="0" scrolling="auto"><a href="https://explore.data.gov/Agriculture/Fruit-and-Tree-Nuts-Yearbook-Data-tables/r6wy-597z" title="Fruit and Tree Nuts Yearbook Data tables" target="_blank">Fruit and Tree Nuts Yearbook Data tables</a></iframe><p><a href="http://www.socrata.com/" target="_blank">Powered by Socrata</a></p></div>'
```

I'm thinking that we just need to do a better job of displaying widget assets in the asset drawer.  For widgets with emebed codes, there's not a clean, consistent way to show the widget, so maybe we should just show a generic icon.

**Comment by wendynorris** [comment]
The widget is produced by Data.gov and displays on the left side of the Fruit and Nut Trees Yearbook Data page. 

![widget_image](https://f.cloud.github.com/assets/2329239/446019/528f6fc0-b1cb-11e2-957d-73f115ffe374.jpg)

**Comment by wendynorris** [comment]
The Google spreadsheet-produced chart (on the right) not displaying as a thumbnail on the builder page is another issue reported in Issue #735.

**Comment by ghing** [comment]
Updated issue report and changed title from "Asset missing after changing layout on dev.floodlight" to better reflect the nature and underlying cause of the issue.

**Comment by ghing** [comment]
The content for the asset drawer representation of an `HtmlAsset` (the underlying model for chart or table-type assets that use an embed code) is just the `body` property.  We need to decide on a consistent representation of IFRAMEd content in the asset drawer.

#708 is a different version of this issue, but with maps instead of charts.  In either case, the content is represented by an IFRAME.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
