### ISSUE TITLE
Asset drawer does not appear in new section on dev.floodlight

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#736]
From sandbox test story on dev.floodlight:
http://dev.floodlightproject.org/stories/375044e162aa40968ff239a6d52b2aec

I added a new section to the story "More Tables" following the "Fruit and Tree Nuts Yearbook Data Tables." 

The asset drawer did not appear on the new section. 

Added an image (chart_1-24.png) in the new section. Deleted the image. The asset drawer with the uploaded image did not appear.

**Comment by ghing** [comment]
@tekhneco, I wasn't able to replicate this.  Did the "Assets" tab for the drawer disappear completely? Or are you saying that an icon/thumbnail for the added (and subsequently removed) asset didn't show up in the drawer?

**Comment by wendynorris** [comment]
The asset drawer completely disappeared. Even after adding an asset, it did not appear on the right margin of the screen.

**Comment by ghing** [comment]
I was unable to replicate this using Firefox 20.0.  I tried recreating the story mentioned in the initial report of this issue and couldn't get the asset button to disappear.  Please reopen if it reoccurs.
