### ISSUE TITLE
Assets with associated data sets should have link to the data set in story viewer

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#74]
From the "bootstrap" view for an image asset that has data sets associated with it (example: http://staging.denverchildrenscorridor.org/assets/db7139ae4431426594ce77894b57896b/), you can view the associated data sets and download or view them. (Note: Shouldn't the link for an external data set be "view" instead of "download"?) That information -- that you can associate an image or any other asset with a data set -- isn't conveyed in the story viewer (example: http://staging.denverchildrenscorridor.org/stories/near-northeast-profile-drill-down-story/). 

Can we have a link to "view the data" (external assets) or "download the data" (local assets) when they are available? It could be rendered as in this screen shot: http://a.yfrog.com/img208/8389/kv9v.png (similar to the bootstrap view but without the description).

**Comment by ghing** [comment]
Yup.  This is easy to do.

Regarding the link text, the "download" vs. "view" distinction is really up to you, and in my opinion, its not tied to whether it's external vs. internal.

An external dataset can point to any URL.  In the case of the box.net examples, it's hard to get the direct download URL of the file.  However, if the file was on an organizational website, you could put the URL of the file itself in the external asset and you would be able to download the data.

We could try to do some inspection of the URL of an external asset to try to guess whether the link is to a page or a file, but this will never be 100% accurate.

My thinking is that we should use a more generic term, like "Get the data" which doesn't suggest a particular behavior for the user.  

What do you think?

**Comment by jwirfs-brock** [comment]
I like "get the data" as a generic term. My only reservation is that you
won't know if you are about to start downloading something (which, as you
pointed out, is a problem if the external data set is a direct download
link). I like the url inspection idea, and ideally, it would be great if
you could identify what type of data source it is (xls file, cvs file, link
to Google spreadsheets, etc.), but I don't think we need that for now. I
will add that as a user story that is N2H. It will come in handy if, say,
you are linking to the Data Commons because we'll want to encourage
cross-site use when we can.

Jordan

On Mon, Apr 23, 2012 at 3:07 PM, Geoffrey Hing <
reply@reply.github.com

**Comment by ghing** [comment]
I just thought of the easiest route.  I can add a field that the admin can set if the file is downloadable.  This will toggle the  link text between view and download.  Does this work for you?

**Comment by jwirfs-brock** [comment]
Sure, that sounds good.

On Mon, Apr 23, 2012 at 3:51 PM, Geoffrey Hing <
reply@reply.github.com
