### ISSUE TITLE
Summary text often appears with strange line breaks on story detail page

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#740]
Here's an example of a story where the summary text has strange formatting with un-wanted line breaks (from the story http://floodlightproject.org/en/stories/seeking-unity-through-the-grant-beacon-peer-mentor/):
![screen shot 2013-05-06 at 8 09 51 am](https://f.cloud.github.com/assets/1020518/465841/f9fe8380-b645-11e2-9a70-8fb6f3b3e642.png)

I've also had several users ask me about this, and I've gone in and fixed it manually.

When I go to edit it in the admin view, I'm not actually seeing break tags where the line breaks are. Here's the story above -- note that there's only a break tag at the end, but there are visible line breaks elsewhere:
![screen shot 2013-05-06 at 8 11 54 am](https://f.cloud.github.com/assets/1020518/465847/3afc67c6-b646-11e2-8309-0e4b9f4eac1a.png)

**Comment by ghing** [comment]
The filter that renders the HTML automatically converts newlines to breaks.  This can be turned off.  I want to check and see what's reflected in the WYSIWYG editor before we decide to turn it off.

**Comment by ghing** [comment]
It looks like the WYSIWYG editor also inserts line breaks in the HTML. I think we can safely remove the code in the template that converts newlines to `<br>` tags.
