### ISSUE TITLE
Use SessionAuthentication for API

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#742]
It might be a good idea to use Tastypie's new [SessionAuthentication](http://django-tastypie.readthedocs.org/en/latest/authentication.html#sessionauthentication) authentication class. It explicitly provides CSRF protection, though I'm having a hard time thinking about what the CSRF attack vector would be for Floodlight.  

We'd have to [initialize a CSRF token for the AJAX requests](https://docs.djangoproject.com/en/dev/ref/contrib/csrf/#ajax)

It's also complicated because different endpoints of the same resource support both authenticated and unauthenticated access.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
