### ISSUE TITLE
Label for comments area is "Citizen Comments"

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#743]
On the story detail page, the label for the comments area is "Citizen Comments". This is almost certainly a holdover from the old name. We should probably change this, right, @jwirfs-brock?  Should it just be "Comments" or something a bit more clever?

**Comment by jwirfs-brock** [comment]
@ghing This is a really good observation. I agree that it shouldn't say "Citizen Comments." For now, let's just have it call it, "Comments" (when we revisit the strategy for increasing comment participation, maybe we can revisit this and give it a more creative name).

Also, currently there's a label under the heading and below the comment box that says, "Comment"...seems redundant, right? Can we get rid of that as well?
