### ISSUE TITLE
Margins not quite right in builder/Tag page

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#747]
![screenshot 5 8 13 10 50 am](https://f.cloud.github.com/assets/73439/478632/904675c2-b7ff-11e2-9a2c-2abf5b8387e6.png)

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
