### ISSUE TITLE
Social login buttons misformatted in IE due to oversized icons

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#748]
![screenshot from 2013-05-09 08 23 36](https://f.cloud.github.com/assets/110420/482893/f6766508-b8ab-11e2-9dab-bc97025071be.png)

Update: Social login buttons also look weird in IE9. 

I think in both cases is has to do with the sizing of the Twitter/Facebook icons

**Comment by ghing** [comment]
The icons look fine in IE8

**Comment by patternleaf** [comment]
Weird. While they are far from beautiful, they aren't rendering quite so badly in my IE9:

![screenshot 5 10 13 7 36 am](https://f.cloud.github.com/assets/73439/488162/10946874-b977-11e2-8af7-a2f9a025f535.png)

**Comment by ghing** [comment]
Let me try to get the CSS properties from my browser for you.

**Comment by ghing** [comment]
So this appears to only be an issue when viewing the site from my local development environment from within a virtual machine.  If I access the dev or production site from the VM, it looks fine.  Closing.
