### ISSUE TITLE
Story viewer briefly displays the root section for spider story before the topic map

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#75]
When  you click on the "View Story" link to enter the story viewer for a spider story, briefly (for about half a second), before the topic map is rendered, you see the first/root section in the story viewer. (I can't really get a screen shot of this because it happens quickly.) This only happens the first time you view the topic map.

**Comment by ghing** [comment]
This is just because the browser is rendering the section content before the story viewer JavaScript hides it.  I'll just hide the content by default and then make the JavaScript reveal it so the user doesn't see content flash up and then disappear.
