### ISSUE TITLE
Project owners can monitor and change the settings of their project(s) in their account settings

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#751]

**Comment by jwirfs-brock** [comment]
This was user story 279 in our original list.
More detail is here: https://docs.google.com/document/d/1S9AnEoHeeh65ZOvJV-FYrWxKZo1BeP8eH5DcoNcvaFQ/edit

Settings organization owners should be able to change are:

add or change a logo/photo
change the description
change the contact information

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
