### ISSUE TITLE
Organization owners can add users to their organization via an email search for existing users

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#752]
This was user story 126.

See more analysis here: https://docs.google.com/document/d/1S9AnEoHeeh65ZOvJV-FYrWxKZo1BeP8eH5DcoNcvaFQ/edit

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
