### ISSUE TITLE
Organization owner can add or change an organization's image after the organization has been created

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#754]
For more analysis see: https://docs.google.com/document/d/1S9AnEoHeeh65ZOvJV-FYrWxKZo1BeP8eH5DcoNcvaFQ/edit

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
