### ISSUE TITLE
Project owner can add or change a project's image after the project has been created

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#755]
See more analysis: https://docs.google.com/document/d/1S9AnEoHeeh65ZOvJV-FYrWxKZo1BeP8eH5DcoNcvaFQ/edit

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
