### ISSUE TITLE
Project owners can determine whether they want their projects to be “open” or “closed”

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#756]

**Comment by jwirfs-brock** [comment]
In the recent conversation with Matt Barry/Bill/Geoff, this feature came up as a very important one. Giving users the ability to create open projects will make it a lot easier to curate streams of stories by multiple authors.

**Comment by ghing** [comment]
Assigning to @jwirfs-brock so she can start fleshing out how this feature will work.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
