### ISSUE TITLE
In Chrome, URL for Organization overlaps with members list

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#759]
Example: http://floodlightproject.org/en/organizations/denver-public-schools-office-of-community-engageme/

On my computer, at least, it looks fine in Firefox but crazy in Chrome.

Here's a screenshot:
![screen shot 2013-05-10 at 10 52 41 am](https://f.cloud.github.com/assets/1020518/488555/80a0bcb2-b981-11e2-884e-707115d3a1f6.png)

It also looks weird in Safari. I haven't tried it with IE.

**Comment by ghing** [comment]
Taking this one.
