### ISSUE TITLE
View for customizing/previewing height of embed widget

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#761]
Clicking on a "customize" link in the share popup should open a new tab that let's the user customize and preview the height of the embedding widget and provides additional help text about the widget.  Additional properties beside height could also be set.

Inspiration:
- https://developers.facebook.com/docs/reference/plugins/activity/
- https://twitter.com/settings/widgets/new

Questions:
- Does anyone else have some examples of widget customization that they've used and found to be effective?
- What if any other properties of the widget should we support changing in this view? I don't see any problem with just supporting height right now and adding additional properties later (possibly after we've made some decisions re #741)

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
