### ISSUE TITLE
Updating "edit caption" behavior

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#765]
Currently, it's easy to miss the "Edit caption" bar when it appears below an asset. If an asset is large, the "Edit caption" is only visible by scrolling. This is problematic, because the "save/cancel" button, which appears _below_ the "Edit caption" box, often does not appear on the screen.

Also, this is inconsistent with the proposed behavior in #583.

**Comment by jwirfs-brock** [comment]
Here's a screenshot. This gets really annoying, because when I don't see the Save/Cancel buttons, I often forget to hit Save, and then my caption text disappears when I click away.

![editcaption](https://f.cloud.github.com/assets/1020518/509427/b6287962-bda3-11e2-81c6-3171965d5640.png)

**Comment by ghing** [comment]
To me, the coherent way to fix this is to move the caption field into the asset creation/asset editing form.  I think it still makes sense to display it below the asset, as it would be in the viewer, but to eliminate the in-place editing.

**Comment by jwirfs-brock** [comment]
Discussion on this issue from the email thread:

@bpawlak said: I agree to remove the in-place editing.  I still think the caption should be part of the add image flow.  Pick an image/URL and then add a caption for the image right there (like we do for adding Data Source for a chart, etc.).  Is that what you mean?

@ghing said: Yeah, I mean moving the caption field into the add/edit form with the rest of the asset fields. 

I said: Moving the caption form into the other asset fields could work, but I also worry that it may get lost/users won't see it. As an alternative, this could also be fixed simply by making sure the "Save" button is visible NEXT TO the caption field (instead of BELOW, where it gets cut off).

**Comment by jwirfs-brock** [comment]
If I'm the only one who is concerned the users may miss the caption if it's within the edit asset window, then let's go that route. We will still display the caption below the asset, but users will have to click "edit ASSET" in order to add/change the caption.

**Comment by bpawlak** [comment]
One thing that's always bugged me is that the caption field doesn't _look_ like an input field (like with the title field on the first section).  I think simply making it look like an input field that I can type into would help.

**Comment by jwirfs-brock** [comment]
Just some thoughts from how Blogger approaches this to get a different perspective in there:

When you add an image, by default it doesn't have a caption. Clicking on the image gives you some sizing options, including an "Add Caption" option:

![screen shot 2013-06-25 at 9 45 48 am](https://f.cloud.github.com/assets/1020518/702856/2e68a748-dd9e-11e2-91a9-2f899020a6dd.png)

Once you've clicked "Add Caption" default caption text appears below, automatically highlighted, so you can just start typing in your caption. You click away to save. Once you've done that, you edit by clicking on the text (just like you would any other text). 

![screen shot 2013-06-25 at 9 46 00 am](https://f.cloud.github.com/assets/1020518/702861/57c6c05c-dd9e-11e2-8ff9-efb00a79daec.png)

But, if you want to get rid of the caption you click on the image and there's now a "Remove caption" option.

![screen shot 2013-06-25 at 9 52 03 am](https://f.cloud.github.com/assets/1020518/702865/7b60bbbc-dd9e-11e2-83fa-26ad1714a611.png)

**Comment by jwirfs-brock** [comment]
@patternleaf For now, let's try moving the caption field completely into the main edit view for each asset. If we notice that people aren't seeing the caption feature, we can revisit. 

We should have some placeholder text below the image so that people know captions are available. How about:

> Click "Edit Image" to add a caption

**Comment by ghing** [comment]
I think moving it into the main edit view is a good way to go.  The caption field should be a lot clearer once #767 is implemented as there will be fewer fields visible at any given time.  The caption was originally in the edit view, so I noticed there is even some commented out code to act as a guidepost for moving it back.
