### ISSUE TITLE
Story Viewer not displaying text, photos of published stories in IE8

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#766]
Here is the description I got from a user:

> I believe we were using IE8 when we were trying to access the Floodlight stories. The website worked perfectly, except when we were trying to view the stories themselves. When I clicked view story, the black background and title would load along with the table of content and other buttons, but the pictures and text for the stories would not. When I would try to press "share this story" or any of the other buttons, beside the close, it would not work.
> I was trying to view a published story each time.

**Comment by ghing** [comment]
Looks like a typo in the viewer code caused this problem.  At first glance, this diff fixes it.

```
diff --git a/static/js/viewer/views.js b/static/js/viewer/views.js
index 08574f6..65b61c9 100644
--- a/static/js/viewer/views.js
+++ b/static/js/viewer/views.js
@@ -246,7 +246,7 @@
           context.previous_section.title = this.previousSection.get('title');
         }
         context.totalSectionsNum = this.sections.length;
-        context.currentSectionNum = this.sections.models.indexOf(this.activeSec
+        context.currentSectionNum = this.sections.indexOf(this.activeSection) +

         this.$el.html(this.template(context));
         return this;
```

I need to look at when this was introduced in 44fcd39b6d82055c7788c0e8d37ff485a6b1a3f8

**Comment by ghing** [comment]
Ok.  It's not a typo, but [arrays in IE < IE9 don't have an indexOf method](http://stackoverflow.com/a/3629211/386210) :disappointed:, no :rage4:

The `models` attribute of a collection gives raw access to the array representation of a collection.  But, Backbone collections also have an `indexOf` method [implemented using Underscore](http://underscorejs.org/#indexOf), which [has a polyfill](http://underscorejs.org/docs/underscore.html#section-54)

cc @patternleaf

**Comment by patternleaf** [comment]
> Ok. It's not a typo, but arrays in IE < IE9 don't have an indexOf method

Ugh. I knew that. Sorry for the snafu!
