### ISSUE TITLE
Images not displaying in Firefox for a published story

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#768]
I just published a new story and the images are...
- showing up properly in Chrome
- showing up in the PREVIEW in Firefox
- Not showing up in the published version in Firefox

Here's the story link: http://floodlightproject.org/en/stories/stretch-your-storytelling-muscles/

Screenshot from Chrome:
![screen shot 2013-05-31 at 1 56 07 pm](https://f.cloud.github.com/assets/1020518/592440/7c04cd9c-ca1b-11e2-9039-3aa93c140861.png)

Screenshot from Firefox:
![screen shot 2013-05-31 at 1 56 42 pm](https://f.cloud.github.com/assets/1020518/592443/87e69fbe-ca1b-11e2-914a-52c677de1cc1.png)

**Comment by ghing** [comment]
I think this is a transient issue as I can see the images when I load that story in Firefox. This is most certainly related to our border/caption resizing code.  I think the code isn't waiting for the image to load, and so it sets the width of the frame to 0.  Depending on how fast the images load, it will either work correctly or not.  @patternleaf is re-working this code as part of the #187 implementation.  We can probably close this along with #187.

**Comment by jwirfs-brock** [comment]
@ghing Cool. Yeah I suspected that images may be showing up properly in other versions of Firefox.

**Comment by ghing** [comment]
@jwirfs-brock It's actually not related to the version of Firefox. It has to do with the load times of the different assets.
