### ISSUE TITLE
Style file inputs to match other inputs

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#769]
File inputs look different than other form inputs (at least in Firefox). They're smaller, and lack the rounded corners.  The button lacks the button styles used throughout the site/app.

Warning: [styling file inputs isn't easy and requires some hacking](http://stackoverflow.com/questions/4532733/styling-input-type-file)

![screenshot from 2013-06-04 14 05 23](https://f.cloud.github.com/assets/110420/607703/0d3777ba-cd4b-11e2-8a07-2eb10d060b56.png)

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
