### ISSUE TITLE
Deleted chart asset (made from embedded iframe) - appeared full-size in asset drawer, undragable

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#770]
While testing the "add data sources" feature (#583), I created and then removed a chart asset by pasting embed code that featured a d3 visualization (via an iframe).

When I opened the asset drawer, the chart asset:
- Appeared full size
- Was not draggable (I couldn't drag/drop it back into the builder)

I did this on dev. Here's the link to the story in the builder: http://dev.floodlightproject.org/en/build/e27c53be104d4dbea9ba122a9d4aea06/

Here's a screen shot:
![screen shot 2013-06-06 at 2 47 58 pm](https://f.cloud.github.com/assets/1020518/619968/c3775a38-ced9-11e2-87c0-97c5f031f610.png)

**Comment by jwirfs-brock** [comment]
Here's the embed code I used to make the chart asset:
`<iframe src="http://wirfs-brock.com/jordan/dataviz/six-word-memoirs/index.html" height="700" width="910" seamless></iframe>`

**Comment by ghing** [comment]
This should probably just show up as an icon, right? Until we implement a good way to make thumbnail snapshots of   HTML.

**Comment by jwirfs-brock** [comment]
Yes. I think the chart icon that we to add a new asset would work.

**Comment by ghing** [comment]
I'm going to fix this by using icons. I opened #771 as an idea for a more long-term fix.
