### ISSUE TITLE
Better mobile support in template through responsive design

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#774]
This issue was originally reported because things didn't work well on the iPhone, even scaling the full-width page.  This is now the "main" issue for further responsive template/CSS development and mobile support.

An outline of our mobile/responsive implementation strategy is in the "Responsiveness Notes" doc at https://docs.google.com/document/d/1o2LBK2Y9xoUWLXMoDlT0g00uCtrBoM0OP7G74Fhejvs/edit
## Original issue report

Reported by @tekhneco via email.

When viewing a project detail page such as http://floodlightproject.org/en/projects/tedxmilehigh/, the page looks bad when viewed through the iPhone browser (mobile Safari?)

FWIW, it looks ok on Android.

By specification, we don't have any responsiveness built into any of the Floodlight components. I would say a fix for this involves making things look ok in the scaled version of the iPhone browser.

Assigning to @jwirfs-brock for triage.  Eventually this should be assigned to @patternleaf  because I don't have any iOS devices to test this on, nor do I have any MacOS devices on which to run the emulator.

**Comment by jwirfs-brock** [comment]
One idea is that, if someone is viewing a story on a phone, they could bypass the story detail page and go directly to the story viewer. Thoughts?

Note that we've also had some issues reported when users open Floodlight on iPads. See issue #268.

**Comment by jwirfs-brock** [comment]
@tekhneco I don't have an iPhone, so I can't test it either. Can you let us know if story detail pages and stories in the viewer are also showing up weird? Thanks.

**Comment by wendynorris** [comment]
Here's a screenshot of the front page, if that helps. Same scaling issue as Project Page. 

iOS v 6.1.3

![img_1135](https://f.cloud.github.com/assets/2329239/655702/0b18e776-d51a-11e2-8c58-ae494d7767cc.png)

**Comment by ghing** [comment]
> One idea is that, if someone is viewing a story on a phone, they could bypass the story detail page and go directly to the story viewer. Thoughts?

Detecting "if someone is viewing a story on a phone" is a can of worms and the preferred technique is responsive design using media queries (i.e. detecting the size of the viewport rather than the type of browser/device). Also having the same URL path go to two locations (even if we do the right thing and redirect) isn't a great behavior.  

Also, such a workaround doesn't addresses the fundamental issue of the site not being designed for mobile.  Floodlight never had responsive/mobile requirements for the software.

If this is something we want to address, I think we should make a list of what we want people to be able to do on any given device.  I'd say view pages on any device is pretty important.  But do we want the story viewer to work on a phone?

**Comment by ghing** [comment]
@tekhneco does rotating the phone to be landscape orientation fix things at all?

**Comment by wendynorris** [comment]
Yep, same problem on Explore and Story detail page. 

The "view story" button does not appear at all on mobile Safari. 

![img_1137](https://f.cloud.github.com/assets/2329239/655787/17421516-d51c-11e2-8114-c3db5778daa6.png)

**Comment by wendynorris** [comment]
@ghing Rotation does not resolve the scaling problem.

**Comment by wendynorris** [comment]
@ghing Viewing pages is important. Building stories on a phone is not. That should be distinguished from building stories on a tablet. That's a bit more of a conundrum. 

I did a demo Tuesday with someone using an iPad and the asset embed functions did not work and the builder navigation tool bar appeared in the center of the screen blocking the text entry box. I can re-test that scenario on my iPad and send more specific, detailed issues, if you want. Didn't report it because I know we didn't optimize for mobile devices and our surveys haven't indicated wide-spread use of tablets.

**Comment by jwirfs-brock** [comment]
>  I think we should make a list of what we want people to be able to do on any given device. I'd say view pages on any device is pretty important. But do we want the story viewer to work on a phone?

I would say the highest priority is making sure people can view all content (both pages and content in the story viewer) on a mobile device.

Creating stories on a mobile device is secondary, and something that we would need to approach as it's own set of features.

**Comment by jwirfs-brock** [comment]
@ghing 

> Detecting "if someone is viewing a story on a phone" is a can of worms and the preferred technique is responsive design using media queries (i.e. detecting the size of the viewport rather than the type of browser/device). Also having the same URL path go to two locations (even if we do the right thing and redirect) isn't a great behavior.

Right, I just said phones because phones are usually small screens. Totally agree on detecting the size of the screen being the way to go.

**Comment by ghing** [comment]
I just tried this quick fix and @tekhneco confirmed that it at least makes things readable, though not great:

```
--- a/static/less/template-layout.less
+++ b/static/less/template-layout.less
@@ -11,7 +11,7 @@
 }
 #container { width:100%;  }
 #main { 
-       overflow-x:hidden; 
+       //overflow-x:hidden; 
        min-height: 200px; 
        padding-bottom: 8px;
```

@patternleaf, do you recall why the `#main` div has `overlfow-x` set to hidden, or is that a remnant of the stuff you were given by the themers?

Do you see any problem with getting rid of `overflow-x: hidden;`? Or, should I use a media query to only get rid of it for narrow displays?

**Comment by patternleaf** [comment]
@ghing i'm pretty sure that's a leftover from the themers. i'd say whack it.

**Comment by ghing** [comment]
@tekhneco asked via email:

> Is it possible to detect a user is viewing the site on a mobile device and auto-forward them to the browser view 
> rather than slideshow? That might solve a multitude of CSS problems. 

I'm not sure what is meant by "browser view rather than slideshow".  Do you mean opening the viewer in a new browser tab/window rather than the popup? Or something else?

Note to self: This seems like the best method of detecting a viewport with JavaScript: http://responsejs.com/labs/dimensions/

Such a technique might be neccesary to assign additional body CSS classes (in the same manner that Modernizr does this for feature detection) to adjust link routing.  So you could have separate event handlers for `body.narrow a.launch-viewer` if desired.

**Comment by wendynorris** [comment]
Sorry for the lack of precision. If I open the story as a browser window in Safari I can view and navigate the story. That's not possible in the default modal window that appears after clicking the "view story" button. All of the page features work: table of contents, share button and pagination in both profile and landscape presentations. Though it's still a little tricky to pinch and swipe since the buttons begin to overlap with larger views. 

In the modal window version, only part of the window displays and it cannot be moved by swiping. 

However, the button to open the the new browser window is very tiny and tends to be obscured by the story title. See image: 

![img_1139](https://f.cloud.github.com/assets/2329239/664059/e40d2c40-d77c-11e2-9d87-eca51f286c3f.png)

**Comment by wendynorris** [comment]
Here's a better screenshot of the browser button in the modal viewer. 

![img_1140](https://f.cloud.github.com/assets/2329239/664633/d062d264-d789-11e2-803a-fef23c4681ef.png)

**Comment by ghing** [comment]
I feel like we need to decide the following:
- [ ] Activities we want to support on phones vs. tablets (activities = view pages, view story explorer, view story in viewer, build story, etc.)
- [ ] Decide which platforms we want to support for phones and tablets and if we want to fully support behaviors on platforms or just provide some minimal functionality for more marginal platforms.

@bpawlak has this to say about platforms:

> In terms of "platforms" I think the right thing to do is to say "it should be usable on mobile devices" (iOS, Android, etc.).  I know that makes everything far more gnarly and complex, but it's probably the way we should be thinking about it.

I think it's important to support iOS and Android (though there are now lots of versions of Android, and I'm unsure how much their browser support varies).  But what about things like Blackberry (and I'm sure their older and newer browsers have different capabilities) and Windows Phone?

We can get a breakdown of what our site sees from Google Analytics. @jwirfs-brock, can you look this up?

**Comment by jwirfs-brock** [comment]
In the past month, here's the break down of site visits by operating system:
1.  Windows 667 
2.  Macintosh   348 
3.  iOS 134 
4.  Linux     40  
5.  Android 31  
6.  BlackBerry  1

And here's site visits for the past six months:
1.  Windows 4,515
2.  Macintosh   2,271
3.  iOS 680 
4.  Linux     354  
5.  Android 213 
6.  (not set)   13  
7.  BlackBerry  5  
8.  Windows Phone   5  
9.  Chrome OS   3  
10. Nokia   1

As you can see, iOS does have a fair amount of users. Android has a few (not a lot), and Windows Phone and Blackberry have almost none.

**Comment by ghing** [comment]
Changed issue title from "Pages looks bad on iPhone" so we can use this issue as the starting point for mobile support/responsive design.

**Comment by ghing** [comment]
What to do with the search box? It looks weird as a little icon. One thought that I had was to move it into the dropdown like this:

![header_mockup](https://f.cloud.github.com/assets/110420/1985450/51d6ff8a-843e-11e3-8ef6-0664c8bcd43b.png)

**Comment by bpawlak** [comment]
Might as well make it stretch the whole width, as well.

**Comment by ghing** [comment]
Another thought is sticking with the search icon but making it smaller and pulling it over to the right next to the menu icon:

![header_mockup-search-icon](https://f.cloud.github.com/assets/110420/1985641/819ca1ae-8441-11e3-952a-4fda0c47648b.png)

**Comment by ghing** [comment]
@bpawlak Yeah, I was thinking that, if we put the search box in drop-down it would look better at full-width. The image is mostly due to my lazy photoshopping.

Note this is for a responsive menu on narrower displays.  If you're curious, the work-in-progress is on dev.

**Comment by jwirfs-brock** [comment]
@ghing @bpawlak Having it small and over to the right matches what I was originally thinking. What would it look like when you click on it, though?

**Comment by ghing** [comment]
And here's an example with the "Explore" link broken out of the menu (imagine that it's not replicated in the dropdown).

![header_mockup-search-icon_and_explore_menu_item](https://f.cloud.github.com/assets/110420/1985885/1a54a60a-8445-11e3-8d38-3df3693f331d.png)

This looks a little weird to me, but I can't quite figure out why I don't like it.

**Comment by ghing** [comment]
@jwirfs-brock The search icon would just act as a link to the search page.

**Comment by jwirfs-brock** [comment]
@ghing I agree that it looks weird with Explore broken out. It fits better in the dropdown.

**Comment by bpawlak** [comment]
I'd suggest leaving Explore in the dropdown and having the search be in the dropdown as well...

**Comment by ghing** [comment]
Another idea: small icon and search box in header.

![header_mockup-search_box_in_header](https://f.cloud.github.com/assets/110420/1986080/b704b006-8447-11e3-8b54-d61ba74f19a6.png)

**Comment by bpawlak** [comment]
Really depends on how much people invoke search now (can we pull some data?) and how well the browse filters work in a mobile context

**Comment by ghing** [comment]
Deployed responsive changes into production.  Closing this issue.  We can track individual mobile/responsive issues as they come up in their own issues.
