### ISSUE TITLE
Users can visit a URL to launch the builder with Topics, Projects and Organizations pre-selected

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#781]
This can be done either via a button on the project/organization page ("Add a story to this project," etc.), or by giving project owners a link they can share with other authors.

This will be implemented along with #756 to establish "open projects."

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
