### ISSUE TITLE
Builder form elements get cut off in Internet Explorer

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#783]
I observed this in IE8, IE9, IE10

![screenshot from 2013-06-17 11 04 35](https://f.cloud.github.com/assets/110420/663233/f3e55c6a-d767-11e2-94e4-8b05ba81bc4a.png)

This doesn't affect functionality since the inputs are cut off on the right hand side, and it doesn't look _terrible_, but it looks a bit odd if you see it a couple of times.

**Comment by ghing** [comment]
Assigning to @jwirfs-brock for triage

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
