### ISSUE TITLE
Viewer: clicking on nav button chevron results in JS error, no navigation.

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#785]
I've occasionally seen nav button clicks fail with a JS error. This has seemed to be sporadic. Just figured out it fails when the click is on the inner chevron element. 

In views.js, the code is expecting `event.target` to be the anchor link containing the chevron element. When the chevron is clicked, the event bubbles to the anchor and its handler is triggered, but the event _target_ is still the chevron.

**Comment by ghing** [comment]
Using `event.currentTarget` in the handler will fix this, right?

**Comment by patternleaf** [comment]
Yes.
