### ISSUE TITLE
Viewer: showActiveSection can be invoked before the ViewerApp view is rendered.

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#788]
There is no user-visible issue here; just a note for future reference.

An issue with the solution to #187 was that the iframes wrapping google charts were not getting sized correctly in one case: If you load a story in the viewer via a URL pointing directly to the section with that chart.

It turns out this was on account of showActiveSection being invoked before the view had rendered. The solution wrt #187 was to check the `this._rendered` flag. But the fact that this happens suggests there might be some wonkiness in the view logic at initialization time. (Also, I suppose, the presence of `this._rendered` also suggests this, and that the best, if less-than-ideal solution has already been implemented.)

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
