### ISSUE TITLE
Multiple users wanting to edit a single story: Is there a better solution than a shared account?

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#790]
I just talked to a user who would like to share an in-progress Floodlight story with other people before she publishes it. But she created her Floodlight account by linking it to Facebook, and doesn't want to share her Facebook login (understandably). **This is something other users have asked for in the past, and I always recommended that they create a shared Floodlight account.** However, she already has the account set up and is already in the process of working on the story.

It seems like you can share the preview link with another user (I tried it out on my machine and it worked). But that doesn't allow other users to edit. In the admin control panel, I can switch the designated author of a story from one user to a different user. But, it is limited to one user at a time. **Would it be possible to make it so that multiple users could have editing rights over a single story? Any other ideas for approaching this problem.**

For now, I told the user about the preview trick, and suggested that she create a shared account for the future. So, if there is no quick solution, she should still be ok. I'm just bringing this up because several users have had similar requests.

**Comment by ghing** [comment]
Right now, there isn't an option of a shared account, but we have most of the hooks to make something more flexible happen. This could work in a number of ways:
- anyone in an organization (and/or project) able to edit any story assigned to that org/project
- toggle flag that makes a particular story editable by anyone in a project/organization
- an individual list of editors for a particular story

This might ultimately be a question to throw back to the users to see how they'd like it to work.  In this case I see ease of use and security as being tradeoffs, so I'd be interested in seeing where they place their needs on that spectrum.

**Comment by jwirfs-brock** [comment]
This issue is addressed in the more recent #850. I'm closing this one and we can continue the discussion over on the other issue.
