### ISSUE TITLE
Caption edit field appears BELOW datasets, but saed caption appears ABOVE

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#791]
I was testing out #583 when I noticed this. It's a little tricky to explain, so I'll try to use amply screen shots and a step-by-step process of what I did.
1. I was adding datasets to existing data assets in an already published story (http://floodlightproject.org/en/build/2ae3a70e6adf45b6ad2fec7c14e05a6e/)
2. I added datasets to a chart asset that had a caption. At this point, the caption appeared **above** the datasets:
   ![screen shot 2013-06-21 at 9 17 35 am](https://f.cloud.github.com/assets/1020518/687173/fdb5d85e-da74-11e2-9be1-c9b359df26cf.png)
3. After adding the datasets, I deleted the text from the caption and clicked "Save".
4. Now the "Click to edit caption" field appears **below** the datasets:
   ![screen shot 2013-06-21 at 9 19 27 am](https://f.cloud.github.com/assets/1020518/687181/3b07eb02-da75-11e2-9a66-f51eeb5eef8e.png)
5. If I edit the caption now and click save, once it's saved it appears **above** the datasets:
   ![screen shot 2013-06-21 at 9 20 37 am](https://f.cloud.github.com/assets/1020518/687188/67ef5f38-da75-11e2-8701-b19463cdc138.png)

This isn't a huge problem, but it is confusing that where you edit the caption and where it appears are not the same place. Also, it's disconcerting that it seems to "jump" from place to place.

**Comment by ghing** [comment]
This should get addressed by #765, right?

**Comment by jwirfs-brock** [comment]
@ghing We will still need to check and make sure that the **placeholder text** appears in the right place after we fix #765.

Unless you think that when moving the caption edit feature inside, we should also do away with the placeholder text. If we do, the only way users will know that there is a caption they can edit will be if they click "Edit Image" -- which might be ok. Thoughts?

**Comment by ghing** [comment]
I think we should get rid of the placeholder text.  Note that users will also see the caption field when they first add the asset content. Since the edit form will be the same, there's at least a hint of where the caption lies.
