### ISSUE TITLE
Dataset list cut off on story detail page

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#792]
I added several datasets to the story: http://floodlightproject.org/en/stories/anyone-can-be-a-hans-rosling/

(Three data assets \* 2 datasets each = 6 datasets total.)

From the story detail page, when I click on the "Get the Data" button, only the top three datasets appear. It looks like it's getting cut off at the horizontal rule. There's no way to scroll down to see the other datasets.

![screen shot 2013-06-21 at 9 34 01 am](https://f.cloud.github.com/assets/1020518/687291/49130c02-da77-11e2-9f15-59b5efd681e5.png)

My suggested fix for this is to, when there is a long list of datasets, extend the window that opens up so that it goes below the horizontal rule (and is as tall as needed). These maybe isn't the best solution, so if you have other ideas, please share them.

**Comment by ghing** [comment]
I think we could just make the popup fixed position and set z-index so it's always above the other content, or get rid of the overflow on the container div. Should be easy.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
