### ISSUE TITLE
Links to external data sources are showing up with download icons

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#793]
Check out this story: http://floodlightproject.org/en/stories/anyone-can-be-a-hans-rosling/

All of the data sources (on sections 4, 5 and 6) are to external websites. I entered them all into the "Data URL" field (did not do a file upload for any of them). However, some of them are appearing with the download icon (but not all).

I'm not quite sure what the pattern is, but it seems like the ones that are appearing as external links end with / whereas the others end with .php, .html, .pdf, etc.

Here's a screen shot (but it's probably easier to just go look at the story):
![screen shot 2013-06-21 at 9 39 19 am](https://f.cloud.github.com/assets/1020518/687324/02bf67fe-da78-11e2-9d21-17e9448f1419.png)

**Comment by ghing** [comment]
It's because the URLs have a "filename.extension" as the last part. Let's make a list of filename extensions we want to consider links as opposed to downloads.  So far, I'd say:
- .html
- .php

Or we can say uploaded files get download icons and URLs get external icons (even if they point to files).

**Comment by jwirfs-brock** [comment]
> Or we can say uploaded files get download icons and URLs get external icons (even if they point to files).

Right, I was wondering about whether we should go that route. For example, one of the URLs I added was for a PDF that was externally hosted. Should that one get a download icon or an external link icon? Depending on your browser settings, it could open the PDF in your browser, or it could automatically start the download. What do you think is best? It's definitely **simpler** if we just set it so that everything added into the URL field has the link icon, and everything added via the upload field has the download icon.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
