### ISSUE TITLE
After uploading a chart asset, cannot edit the attribution, get  "{"error": "You must specify an image, body, or url"} " message

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#794]
Here are the steps of what I did:
1. Created a new story
2. Added a chart asset via file upload
3. Gave that asset an attribution field (because charts, maps, tables have an attribution field in the edit view)
4. Hit "Save"
5. Clicked on "Edit Chart"
6. Changed the attribution field and then clicked "Save Changes"
7. Got the following error message: {"error": "You must specify an image, body, or url"}. You can see it as it fades away in the screen shot below. Note also that there is a field for uploading a **different** file.
   ![screen shot 2013-06-21 at 9 47 55 am](https://f.cloud.github.com/assets/1020518/687381/fba95fa4-da79-11e2-8234-8c870d082a8b.png)
8. I was able to click "Cancel" and go back to editing my story.
9. When I clicked "Edit chart" for a second time, there was no longer a field for uploading a different file. I got the same error, though, when I clicked "Save Changes." (See screenshot.)
   ![screen shot 2013-06-21 at 9 54 34 am](https://f.cloud.github.com/assets/1020518/687389/39b6872c-da7a-11e2-90d6-ddc1bf116905.png)

I haven't yet tested this with other asset types. Next, I'll see if it's also happening for other asset types that allow you to upload a file (table, map, image).

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
