### ISSUE TITLE
Set up fixture-based html asset test

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#795]
Assigning to myself. This is based on Geoff's asset dump in fixture format. Can be generally useful but it may make sense to wait until pull #789 is in develop so that HtmlAsset.has_script is available and then make a new branch off of develop to implement this.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
