### ISSUE TITLE
Template sections displayed as "Untitled" in table of contents until edited

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#798]
The current behavior is:
- A section that the user has not added a title for appears as "Untitled" in the table of contents, even though that section may have a name in the template.
- By going to that section, a user can see the title in the title field.
- After editing the title section, it appears in the table of contents.

Here's a screenshot:
![screen shot 2013-06-26 at 10 27 02 am](https://f.cloud.github.com/assets/1020518/710229/c2ddfde6-de76-11e2-8ecd-0426909be69a.png)

"This is my introduction" has been modified and thus shows up in the table of contents. "Definition" (the section we are looking at) has not been modified and shows up as "Untitled" in the table of contents.

The desired behavior is:
- A section that the user has not added a title for appears with the template's section title in the table of contents.
- By going to that section, a user can see the title in the title field.
- After editing the title section, it appears in the table of contents.

**Comment by ghing** [comment]
Moving this into Iteration 15A since a large part of the fix for this was implemented in the fix for #722 and it makes sense to bust this out at the same time.
