### ISSUE TITLE
Section names should also show story name in list view

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#80]
In the "Add section relation" page in Django admin (http://test.denverchildrenscorridor.org/admin/storybase_story/sectionrelation/add/), the sections in the drop down menus should appear as: 

section name - story name

**Comment by ghing** [comment]
Though I'm tempted to do this just by changing the **unicode** method, I think the right way to do it is with a custom form/form field.

See http://stackoverflow.com/a/6851344/386210 and http://stackoverflow.com/a/3694736/386210
