### ISSUE TITLE
Chart image not showing up in story builder or preview

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#803]
Here's the story builder link: http://floodlightproject.org/en/build/4a1205f0d0c947d09fe4c6ba265829ec/

The chart asset on the first section uses an image I got from the U.S. Census Bureau site, added via a URL: http://www.census.gov/dataviz/visualizations/040/res/graphics/040_metro_comp_chg_101-01.png

It isn't rendering in either the builder or the preview.

Here's a screen shot of what I saw after adding the chart's URL:

![screen shot 2013-06-27 at 11 10 35 am](https://f.cloud.github.com/assets/1020518/716697/c681bd50-df3b-11e2-9c28-6acd29c4f975.png)

I was using Firefox 21.0 on a Mac.

**Comment by ghing** [comment]
The issue appears to occur when an image file is specified as a URL for a chart type asset.  That is, specifying an image URL for an image type asset works properly.

Workaround is to just download the image and upload it as a file, rather than copying and pasting the image URL.

**Comment by jwirfs-brock** [comment]
As @ghing suggested, I downloaded the image and them uploaded it as a chart asset in the builder.

It rendered fine in the builder:
![screen shot 2013-06-27 at 11 15 45 am](https://f.cloud.github.com/assets/1020518/716746/8c0d02f0-df3c-11e2-9764-7df34bf624b5.png)

But in the preview, it did not show up correctly:
![screen shot 2013-06-27 at 11 15 58 am](https://f.cloud.github.com/assets/1020518/716748/946d021a-df3c-11e2-9d4e-4e15cea6b183.png)

**Comment by ghing** [comment]
@jwirfs-brock Ok.  That's a separate, known issue that (hopefully) is resolved as part of the #187 fix.  The code for resizing the border and the caption is getting run before the image as downloaded and the JavaScript can properly detect the width. What you're seeing is intermittent.  From some connections, or some loads, it should work properly.  I'll make sure that @patternleaf is aware of this case and includes it in his testing.

**Comment by ghing** [comment]
The fix for this issue is to use [mimetypes.guess_type](http://docs.python.org/2/library/mimetypes.html#mimetypes.guess_type) to determine if a url points to an image rather than just assuming this is the case for image URLs. [This wikipedia article](http://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support) seems like a good list of browser-supported image formats.

**Comment by ghing** [comment]
The issue with the image URL-based chart asset not showing up was fixed in c7fbeb6d6498e85e8b45beaf4c74ae90c40dbbb6
