### ISSUE TITLE
"Method "handleImgResize" does not exist" error in builder

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#804]
To replicate:
1. Open or create a story in the builder
2. Add an image type asset by uploading a file to any container in a section
3. Preview the story

Expected behavior:

Image is shown

Observed behavior:
- Image is not shown
- "Method "handleImgResize" does not exist" error shows up in the error console.

The problem looks to be that the `handleImgResize` method [is wired up as a DOM event handler](https://github.com/patternleaf/atlas/blob/develop/static/js/viewer/views.js#L47) but the method is no longer defined.  I'm guessing this is a regression added by the #187 implementation.

**Comment by patternleaf** [comment]
How ... wha ... ? I am bizarred-out by this, for several reasons.

**Comment by ghing** [comment]
This might be a result of an inelegant auto git merge?  We can just get rid of the event definition for `handleImgResize`, because of [these changes](https://github.com/PitonFoundation/atlas/commit/290817c6a9eb12f0c02865885e538da955e8727b#static/js/viewer/views.js), right?

**Comment by patternleaf** [comment]
Yeah. In fact it looks like that line [was deleted](https://github.com/PitonFoundation/atlas/commit/290817c6a9eb12f0c02865885e538da955e8727b#L7L47). So I feel slightly less insane now. The other thing is that this wasn't occurring yesterday on what I _thought_ was the same codebase. But I must've pulled an update with this change after working in the viewer. 

Makes me wonder what else might've been merged poorly. :8ball:

Maybe this issue can be a quick sanity test/code review, in addition to re-deleting that line.

**Comment by ghing** [comment]
@patternleaf, can you take care of the sanity checking/code review on this one?

For sanity checking, I always start with (manually) walking through this test: https://github.com/PitonFoundation/atlas/blob/develop/apps/storybase_story/features/story_builder_full_process.feature

**Comment by patternleaf** [comment]
It looks like that line is the only unintentional casualty. However, based on #803, it looks like I also need to re-introduce the imagesLoaded plugin so that figure elements are resized at the right time. I think this was on account of some confusion on my part between implementing responsive images and the necessity of that plugin. Man, #187 was a cluster****.

I'll fold that into this issue, unless it seems more appropriate to make it its own issue.

**Comment by patternleaf** [comment]
No—scratch that. I'll make a new issue.
