### ISSUE TITLE
Section list becomes mangled, unusable.

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#805]
I was running through [the storybuilder full process test](https://github.com/PitonFoundation/atlas/blob/develop/apps/storybase_story/features/story_builder_full_process.feature) and ran into a problem. This was in Firefox 22.0.

Right after [these steps](https://github.com/PitonFoundation/atlas/blob/develop/apps/storybase_story/features/story_builder_full_process.feature#L34):
- Given the user clicks the add section button after "Let's try an audio clip"
- Then the section "Untitled Section" should be after the section "Let's try an audio clip" in the section list

The section list was rendered like this:

![screenshot 6 27 13 11 30 am](https://f.cloud.github.com/assets/73439/717583/428c8d9e-df50-11e2-9a84-a6bc7e60d04a.jpeg)

Then later, at [this step](https://github.com/PitonFoundation/atlas/blob/develop/apps/storybase_story/features/story_builder_full_process.feature#L80):
- Given the user drags the "Yet another section" section before the "Let's try an audio clip" section in the section list

There was no "Yet another section" visible, so I attempted to scroll the section list. Nothing happened, and this error appeared in the console:

`TypeError: this._sortedThumbnailViews[index] is undefined`

I'll try to repro this to make sure it's reproducible after finishing the test (assuming I can) for the sake of #804. I don't think this is related to #804 or any merge problems on account of #187, which begat #804.

**Comment by patternleaf** [comment]
I tried again from the top and could not reproduce. I won't close the issue in case it pops up again. For reference, this is off of the develop branch, commit af3c06d.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
