### ISSUE TITLE
Image caption/container resizing can happen before images load.

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#807]
Another regression caused by #187. Solution is to re-introduce imagesLoaded plugin more or less as done originally in 3d50446.

**Comment by patternleaf** [comment]
c98d77d is a refactor of the asset sizing code. It fixes this issue and also gives us:
- figure containers collapse to small images
- images resize responsively (when that resizing will not involve upsampling)
- unifies some sizing logic that was formerly in both static/js/views.js and /static/js/viewer/views.js.

Tested in Chrome, FF, Safari, and IE8. Cross-tested against #187 and #803.

**Comment by ghing** [comment]
The fix for this (c98d77d) was merged and deployed a while ago. Closing.
