### ISSUE TITLE
API Key Authentication for API

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#810]
The story builder (and to a lesser extent, viewer and explorer) are implemented using a REST API.  Right now, you have to be logged into the Floodlight website to be authenticated to the API.  However, the framework used to implement the API allows for multiple authentication methods, including API keys.  Generating API keys for some users would allow external apps to access the API and create/update stories.

Implementing this would be necessary for some of the mobile crowdsourcing ideas @tekhneco has mentioned, where user submitted content would automatically appear in a Floodlight story.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
