### ISSUE TITLE
Builder color scheme doesn't match site color semantics

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#815]
At some point we decided to go with orange for the highlight/action color in the site chrome (megamenu, header), and blue in site content. The builder is much more orange. I could see how the builder might be more "action-oriented" and this might actually be appropriate. But I also think the orange can be overwhelming in large quantities, so we might consider going blue with buttons, etc in the builder. 

This might be a moot point in the brave new builder world.

**Comment by mgrayinnovation** [comment]
Aesthetics taking on new look, possibly, entirely in Pivot of 2015
