### ISSUE TITLE
Stuff breaks with django-uuidfield 0.4

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#828]
For now, keep the dependency at 0.2

It looks like when using Postgres, the field returns a UUID object instead of a string. I don't know if we have to worry about migrating from 0.2 to 0.4.

For us, it seems like the big issue is that a lot of our tests and serialization break.  Others also report having issues with serialization (see https://github.com/dcramer/django-uuidfield/issues/11)

**Comment by mgrayinnovation** [comment]
Wil, might be something to review if you're seeing a lot of breaks in tests.
