### ISSUE TITLE
Improve user experience around URL-based assets

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#833]
We currently don't show an error if a user mistypes a URL for an image asset. If the URL is syntactically valid but does not resolve to a resource, the user is presented with a blank asset container and no explanation for what's going on.

Since the browser is requesting the image, we should be able to catch the case of a bad image load—for example with the [imagesloaded fail event](https://github.com/desandro/imagesloaded#fail).

**Comment by ghing** [comment]
Note that the more likely, or at least intended case for URL-based assets is to link to an oEmbedable resource as opposed to a remote image file, though the latter is supported as well.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
