### ISSUE TITLE
Clarify supported/recommended dataset file types

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#834]
@jwirfs-brock says:

> A user can upload any type of file as a data source file. I tried it with a jpeg and pdf, 
> and both were "allowed." We don't have any instructional copy about the file types 
> we support. Should we? Or should we just leave it completely open? If we do leave 
> it open, I think we should at least include some (very brief) copy about the type of 
> files we recommend (CSV or Excel).

You're correct to observe that we don't do any filtering on file types for data sets.  I think you're right that we could use some clarifying help text, but I'd say we should leave the file type open for now until we get more of a sense of what users are uploading to decide which file types to formally support.

**Comment by jwirfs-brock** [comment]
Here's some new copy:

> Upload a data file from your computer. We recommend using a .csv, .txt or Excel file.

**Comment by mgrayinnovation** [comment]
Might be valuable to add to the help section of the story builder.
