### ISSUE TITLE
Attribution and source url fields are redundant

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#835]
@jwirfs-brock reports:

> Now that we have the "Data Sources" feature, and it's working nicely, some of the 
> fields on the asset information view are redundant. Namely, the Table asset type 
> has "Attribution" and "Source URL." I know we originally had those because tables 
> (and charts, and maps), can sometimes be attributed to a source that is different 
> than the data source. But I think that's a subtlety that will, at this point, just end up 
> confusing users. If people really want to source them differently, they can use the 
> caption to do, so the other fields are still redundant.

**Comment by mgrayinnovation** [comment]
Related to #834? Worth a review when we reach P4
