### ISSUE TITLE
Possible for section title in section list and "real" section title to get out of synch

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#843]
Seen this while generally trying to break synchronization in section bar. Seems to be minimally reproducible in this way:
1. Start a new Sandbox story in builder.
2. Give it a title so that you can create a new movable section.
3. Create a section. Name the first section "section 1" and the second one "section 2".
4. Make sure section 2 is "active" so its inspector is visible.
5. Drag section 2 to before section 1. Right after you drop the section in place, edit its title and change it to something else—"section 2x" or something. Quickly tab away so that the edit "takes". You can also click on section 1.

Expected: After some time, the section title in the section bar and the section title in the section inspector should match.
Result: The section inspector has the latest title, the section bar shows the older one.

It may take a few tries to get this to happen. Repro-ed in FF 23.0 Mac. No bad server responses or JS errors were reported in logs.

I think this is a view sync issue, and not a more serious model consistency issue. But see also #842.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit  

A connected issue (#842) with this has been moved to P4.
