### ISSUE TITLE
Only a few lines of text is visible at a time in editor making text editing difficult within the Story Builder

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#844]
Here's some feedback from user Matt Gray:

> The editing of story text/copy on most pages was quite hard.  Though the build and preview screens allowed you to read the text in full, editing the text forced the user to only see two or three lines of text and then have to scroll down continually to keep editing.  Since copy and pasting from a word document was a very bad idea because of HTML formatting issues, editing onsite was a must.  It would be nice if you could see the full text as you edited.

I have also had similar frustrations while editing text. Notice that this is an issue even in stories that aren't text heavy, because the text box is so small.

**Comment by bpawlak** [comment]
This is probably related to the fact that while we _appear_ to have a WYSIWYG editor, we don't _really_ have one.  Wonder if there's some way to make the editor both WYSIWYG and responsive (in terms of font size) so that if a user resizes the text container (the future version of the builder) or types in so much text, it doesn't all fit (the current version of the builder), we can dynamically size the font to fill the available space?

There are some discussions regarding "shrink-to-fit" and "shrink-by-ratio" techniques as well as a couple of jquery plugins (https://github.com/chunksnbits/jquery-quickfit, https://github.com/jquery-textfill/jquery-textfill, and http://fittextjs.com/)

**Comment by ghing** [comment]
With text, do we want to scale/constrain text to fit a container, or grow the container (and editor) to the text content?

To me, the solution seems to be to allow the editor area and the container to grow as the user adds text.  At the very least this could be an easy fix we could incorporate right now.

**Comment by bpawlak** [comment]
Probably really depends on final presentation. If we're going for more of a slideshow presentation of the story, then scale the text to fit the container (might want to set a minimum font size). If we're allowing vertical scrolling on each page, then perhaps scaling the container might be better.

**Comment by ghing** [comment]
The average length of all published text assets is 916 characters.  That might be useful for optimizing our experience for the most common case.

**Comment by ghing** [comment]
I updated the title from "Text editing within Story Builder is difficult" to make it easier to revisit and prioritize this issue in the future.  Please update further if anyone has ideas for summarizing the issue more clearly.

Also, the user mentioned copying from word docs.  Were they making Floodlight stories out of existing content or just writing text in Word for some other reason? I'd be interested in learning more about their workflow.

**Comment by jwirfs-brock** [comment]
@ghing They were writing original text content for Floodlight. I think this is pretty common behavior. I do this as well (whether I am writing content for Floodlight or for any other blogging platform, actually). I tend to write and edit my text in Word first (or sometimes Google Docs), because that's an easier environment to work in, I can work offline, and I can save drafts locally. A lot of people have a favorite environment for writing, and that's usually distinct from the environment for publishing.

Another thing I've noticed is that if you are writing text directly into a text asset on Floodlight, it's pretty easy to accidentally "lose" your text. If you forget to click "Save" on that asset (which is easy to do, because you don't have to click "Save" on the summary, and sometimes the "Save" button is not visible because it's below the fold), then you move to another section and back, or another asset and back, the text gets cleared.  This is something that has happened to me many, many times. (And it's pretty frustrating.)

I'll have to go back and step through the exact work flow to recreate this and get a more detailed description. When I do, I'll open it as a separate issue. Because, you are right, there are multiple problems making  text editing difficult for users, and we should identify each one specifically.

**Comment by jwirfs-brock** [comment]
Another thought is that our text asset has a lot of unnecessary space/information at the top. Here's the screenshot:
![screen shot 2013-08-21 at 7 52 15 am](https://f.cloud.github.com/assets/1020518/1001761/6a2672c4-0a71-11e3-8d45-fc68b98713d7.png)
Do we really need the "Add text" and "body" labels at the top? This makes it less WYSIWIG-ish and takes up space. I think, once the user clicks on the text asset, they really just need to be able to type, save and cancel. They don't need to see the "Add text" label -- that's inherently obvious. Removing that would give us more space to start with, making the default text box a little bigger.

**Comment by jwirfs-brock** [comment]
As for scaling the text versus expanding the text box as a user adds more text, I prefer the latter.

**Comment by ghing** [comment]
Also note that the comment form right here in GitHub exhibits an auto-growing behavior that I think works well.  I also use GitHub all the time, so I might just be used to it.

**Comment by ghing** [comment]
@jwirfs-brock, do we need the "Add <asset-type>" label for any of the assets anymore?

**Comment by jwirfs-brock** [comment]
@ghing Probably not. Once you've clicked on a particular asset, you don't need to be reminded of what it is.

We may be able to do something cool like using the icons for the assets as a watermark or something, but that's probably not necessary.

**Comment by jwirfs-brock** [comment]
@ghing I just opened this as a separate issue: https://github.com/PitonFoundation/atlas/issues/846

**Comment by patternleaf** [comment]
> Once you've clicked on a particular asset, you don't need to be reminded of what it is.

FWIW, I think the Add/Edit labels are useful and appropriate—I think maintaining context is good in this case. Context could be maintained in some other, less space-intensive way. Also, they're new (or rather their content is new) as of #767.

**Comment by bpawlak** [comment]
Another plug-in that might come into play at some point: http://simplefocus.com/flowtype/

**Comment by ghing** [comment]
@jwirfs-brock, there's a bunch of different ideas thrown around here.  Am I correct in interpreting that the desired fix to the immediate issue reported by the user is to grow the editor as the user types?

**Comment by jwirfs-brock** [comment]
@ghing That is correct. And the "Body" label above the text box needs to be removed.

**Comment by jwirfs-brock** [comment]
@ghing What happens once the text box expands to be the full size of the asset container? Would it then scroll, or would it grow the asset container?

**Comment by jwirfs-brock** [comment]
@ghing Also, what are your thoughts on the behavior of the scroll bar. Right now it "disappears" and stays hidden until you are actively typing beyond the extent of the box, or if you are scrolling (i.e., with your trackpad). When you mouse over it, should the scroll bar also appear?

**Comment by ghing** [comment]
@jwirfs-brock, I think that the asset container should expand along with the text box.  This will give the user more of an idea of the presentation of their text in the viewer.  Similarly, an auto-expanding textbox should eliminate the need for the scrollbar.

**Comment by jwirfs-brock** [comment]
@ghing That sounds perfect!

**Comment by ghing** [comment]
@jwirfs-brock I finished a rough first pass at this. Since it's really rough, it's probably better if we walk through it together some time tomorrow.

**Comment by jwirfs-brock** [comment]
@ghing Sure. Can you do 10:30 central/8:30 pacific?

**Comment by ghing** [comment]
- [ ] In demoing the feature this morning, we found that in side by side layout the border/box next to the text asset seems to grow somewhat along with the text asset.

**Comment by ghing** [comment]
- [ ] Fix styles so that editor border doesn't fall outside of view in side-by-side layout:

![screenshot from 2013-10-09 17 14 25](https://f.cloud.github.com/assets/110420/1302227/66add0c0-3130-11e3-8980-438c23a0be94.png)

**Comment by ghing** [comment]
It looks like the editor element's height is jumping around when it loses focus.  This causes the position of the buttons to shift, making it easy to miss when clicking on the save/cancel buttons and making it seem like it takes two clicks to make the action take effect.

Update: I confirmed that the initial click event isn't firing.
- [ ] Figure out why editor is shifting in size on the composer's blur event.
