### ISSUE TITLE
reclaim vertical space in asset create/edit views

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#846]
Here's what the current text asset looks on the edit screen:
![screen shot 2013-08-21 at 7 52 15 am](https://f.cloud.github.com/assets/1020518/1002008/5d30abf8-0a75-11e3-870a-42ae08cf5cc2.png)
We don't need the "Add Text" or "Body" labels anymore. Similar, for the other assets, we don't need, "Add Chart," "Add Image," etc. at the top.

**Comment by patternleaf** [comment]
As [I noted in the other issue](https://github.com/PitonFoundation/atlas/issues/844#issuecomment-23026494), these are new as of #767. And I think that having floating form fields without some context, label, breadcrumbs, or indication of what will happen when you submit the form is bad UI. If I have to stop what I'm doing and come back, I shouldn't have to cancel out to figure out where I was.

**Comment by patternleaf** [comment]
(That said, I'm not sure what the "body" label is for here.)

**Comment by jwirfs-brock** [comment]
@patternleaf That's a good point. Do you have ideas about other less space intensive ways to indicate the asset type?

The idea I had was a watermark. What else might we do?

**Comment by patternleaf** [comment]
@jwirfs-brock Yeah—do you mean the icons you click on to select an asset type? With that plus a smaller font we should be able to reclaim a lot of that space.

**Comment by jwirfs-brock** [comment]
@patternleaf Yup, that's exactly what I was thinking.

**Comment by ghing** [comment]
@patternleaf, the "Body" label is just the name of the field on the Django/Backbone models.  It's shown by the default form/view implementation.  In the case of the text asset, we should just hide it.

**Comment by ghing** [comment]
Perhaps we should retitle this issue something like "reclaim vertical space in asset create/edit views"

**Comment by jwirfs-brock** [comment]
@ghing I like that. Title has been updated...

**Comment by bpawlak** [comment]
That "Add Text" label has a .6em top & bottom margin... definitely doesn't need to be that large.  Thinking we might also lighten it a bit so it doesn't draw as much focus?

![image](https://f.cloud.github.com/assets/2250519/1140055/e562c464-1c97-11e3-98b7-3e6b1976761a.png)
