### ISSUE TITLE
In story viewer, when you scroll down on a section then advance to the next section, you remain scrolled

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#852]
This is probably most easily observable in this story: http://www.floodlightproject.org/en/stories/the-floodlight-pipeline-creating-stories-within-a/

When I scroll to see all of the text on a given section, then go to the next section, I am still scrolled. I should, instead, be taken to the _top_ of the next section.

Here's what happens:
1. I scroll to the bottom of section 2.
   ![screen shot 2013-08-30 at 3 15 35 pm](https://f.cloud.github.com/assets/1020518/1061046/d9b1720e-11c1-11e3-8369-019a09420176.png)
2. I click to advance to the next section. Instead of seeing the top of section 3, I see the bottom.
   ![screen shot 2013-08-30 at 3 15 44 pm](https://f.cloud.github.com/assets/1020518/1061051/eafe780e-11c1-11e3-8af8-7b817a5ca289.png)
3. Here is what I _should_ see when I advance to the next section.
   ![screen shot 2013-08-30 at 3 15 50 pm](https://f.cloud.github.com/assets/1020518/1061053/f66cb016-11c1-11e3-8f33-da26ccb495aa.png)

**Comment by ghing** [comment]
@jwirfs-brock: Does the test scenario at https://github.com/ghing/atlas/blob/852-viewer_scrolling/apps/storybase_story/features/story_viewer.feature capture the desired behavior?

**Comment by jwirfs-brock** [comment]
@ghing Yes, that's perfect.
