### ISSUE TITLE
Activity grid content

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#853]
@jwirfs-brock says:

> I've been working on some new content for Floodlight, a series of how-to host your own story-raising guides.
> 
> I've modeled them on Mozilla's webmaker guides:
> 
> Overview - https://webmaker.org/event-guides
> Example guide (Hack Jam) - https://webmaker.makes.org/thimble/host-a-hackjam
> Hactivities menu - http://hivenyc.org/hacktivityGrid.html
> 
> I'm at the point where I have enough content that it will help to start thinking about >how it will be displayed/where it will fit on the Floodlight site.
> 
> Here's what I would like to do:
> 
>    Add a "How can I host my own Story-Raising?" section on the Story-Raising >page (http://floodlightproject.org/en/news/story-raisings/). That section would >include an overview of our three types of Story-Raisings (you can view a draft of >the content here), and would look similar to https://webmaker.org/event-guides.
>    A guide page for each type of Story-Raising (three total). This page will include:
> - an overview
> - goals
> - required supplies
> - a sample agenda
> - a recommended activities menu (will take you to that activity on the activity guide page -- see below)
> - what to do before the event
> - what to do during the event
> - what to do after the event
> - general tips
> 
> An activity gallery, similar to http://hivenyc.org/hacktivityGrid.html. I was thinking we could structure this using the FAQ format. RIght now we have four activities, but hopefully we'll continue to add more. Each activity could be formatted like the questions are, with a drop-down/chevron that would reveal:
> - description
> - required supplies
> - time it takes to do
> - links to the full activity (these are materials/handouts we have been using in Story-Rasings; most of the activities have also been adapted into Floodlight stories; we could potentially also make a page for each activity, if there's time)

**Comment by ghing** [comment]
So it looks like there is a way to do this using Django CMS placeholders and template tags.  In the template for an activity page, we could define placeholders for the description, required supplies, time it takes to do, etc. and then include them in a landing page using the [show_placeholder](http://docs.django-cms.org/en/2.3.7/advanced/templatetags.html#show-placeholder) template tag.

Roughly:

```
{% for child_page in request.current_page.children %}
   <h2>{% page_attribute "page_title" child_page %}<h2>
   <h3>Description</h3>
   {% show_placeholder "description" child_page %}
   ...
{% endfor %}
```

So the decision about whether to create a separate Activity model or to use the page really depends on:
- Whether there will be more content for the activities other than the attributes listed above, or whether  it's just that information.  Will that additional content go on a page?
- Whether the attribute information is short and nicely formatted or whether it needs to be more free form

As [one Django CMS developer suggests](http://grokbase.com/t/gg/django-cms/129s4mykaa/add-custom-page-attributes#201209255rm63d5ote7oepk6p7ke6s4jyu), creating a separate model with a relationship to a page seems to be the general pattern for adding extra attributes to a page:

> the most viable workaround is to create a second model holding your custom data with a
> OneToOne/ForeignKey to Page. Then unregister the PageAdmin and re-register
> it with an inline attached that hooks your model onto the PageAdmin.

**Comment by ghing** [comment]
After chatting with @jwirfs-brock, I decided on an approach that creates a new `Activity` model.  It will have a schema something like this:

```
title = CharField()
slug = SlugField()
image = FilerImageField(null=True) # Image that will be shown as a thumbnail for the activity when it's aggregated
description = TextField()
supplies = TextField()
time = CharField()
num_participants = CharField()
links = TextField() # Free-text for links to floodlight stories, PDF, google docs for activity materials
page = models.OneToOneField(Page, null=True)
```

A few notes about the model:
- `links` is a text field rather than being some kind of structured list of links because the number of links and their titles is pretty variable.  For instance, we could have multiple handouts, hosted over a variety of services.
- the `page` field is optional and probably won't get used for now, but it allows us to have a place to put arbitrary content for an activity.  A custom template would be used to suck in the activity metadata from the related `Activity` model.
  - It might be desireable to display a different image to display at the top of the activity page than the one we use as the thumbnail on the grid page.  This can be implemented via a Django CMS placeholder that defaults to `Activity.image` if no plugins are specialized

@jwirfs-brock is going to send sketches of what the landing page will look like

**Comment by jwirfs-brock** [comment]
Here are a few sketches of what the activity grid page might look like.
One column layout with a collapsible/expandable design. The collapsed view just has the thumbnail and the title; the expanded view has the full meta-data:
![activitygrid1](https://f.cloud.github.com/assets/1020518/1092433/f3c08156-167d-11e3-98a9-14b03fa82400.png)

Two column layout with activities always expanded/full meta-data always visible: 
![activitygrid2](https://f.cloud.github.com/assets/1020518/1092474/24e4c908-167f-11e3-961a-bab23a000033.png)

Here's what it might look like with topic/category divisions for the different types of activities. Here, I tried to show what a two-column layout might look like with the collapsible/expandable activities (similar to what we have on the story template selector view of the Story Builder):
![Uploading activitygrid3.png . . .]()

**Comment by ghing** [comment]
@jwirfs-brock It looks like the third sketch didn't finish uploading!

**Comment by jwirfs-brock** [comment]
Yeah...for some reason the third image isn't working. I'll send it via email.

**Comment by jwirfs-brock** [comment]
![activitygrid3](https://f.cloud.github.com/assets/1020518/1092664/482d559a-1686-11e3-9c13-024ef4d2fd9b.png)

**Comment by ghing** [comment]
For my first pass at this, I decided to go with the "Two column layout with activities always expanded/full meta-data always visible" version since there doesn't seem to be enough content to warrant a full-width space for each item and there aren't so many items that it makes sense to collapse some of the info.  I mucked around with Firebug to try out a 3-column vs. a 2-column display and this is what they look like:

![activity_2col](https://f.cloud.github.com/assets/110420/1126021/a34db86c-1b1c-11e3-9d90-e7d5b3060b0c.png)

![activity_3col](https://f.cloud.github.com/assets/110420/1126023/a972c548-1b1c-11e3-9320-f1d769b5be1d.png)

I prefer the 2-column version.

**Comment by jwirfs-brock** [comment]
@ghing If we go with the two-column view, is there a way we can clean up the white space on the right side by evening out the spacing?

We don't necessarily need to have long descriptions -- part of the reason that I included the long one here is to see what it would look like. They will have relatively uniform description lengths (probably about half as long as the "Mini-StoryCorps Interviews" description here), which should make the layout look nicer.

**Comment by ghing** [comment]
@jwirfs-brock, do you mean like this (with `text-align: justify`):

![activity_2col_justified](https://f.cloud.github.com/assets/110420/1126172/a0c0675e-1b1f-11e3-89be-11df6af448af.png)

**Comment by jwirfs-brock** [comment]
I actually meant the space where the horizontal line next to the page title
extends beyond the content. (Which was filled by the right-most activity in
the three column layout.)

**Comment by ghing** [comment]
@jwirfs-brock, can you add more items so I can get a better idea of how this will look with the actual amount of content?

**Comment by jwirfs-brock** [comment]
Sure, but I'm getting on a plane right now so I won't get to it until later
this afternoon.

**Comment by jwirfs-brock** [comment]
@ghing I added two more activities, and then added them as plug-ins to the Activity Grid page. I didn't know which section of the page to add the plug-in to (because none of the other activities showed up in the plug-ins list), so I put them in "two-col content." When I did that, the other items seemed to have disappeared.

**Comment by ghing** [comment]
I deployed the models, admin and first pass at the CMS plugin template and styles into production.  I'm going to close this issue. Refinements to styling should be opened as a separate issue.
