### ISSUE TITLE
Title and summary character limit alert

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#854]
Alert is not displaying when user exceeds character limits in title and summary text box in the Storybuilder.

**Comment by ghing** [comment]
I believe this is now fixed. I had forgotten to recompress the updated JavaScript the last time I did a deploy. @tekhneco, can you confirm that you're seeing this now?

**Comment by wendynorris** [comment]
Confirmed. The alert is working for both the title and summary text field.
