### ISSUE TITLE
Links for connected story broken on Publish/Share page, in published story email

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#856]
This is a user-reported bug from Rebecca Arno. In the email she got telling her the story had been published, the link to the story did not work. Instead, it sent her to a page that said, "Requested page not found."

As far as I can tell, the story link is the only one that is broken.

The link path: http://floodlightproject.org/stories/my-guys-the-last-photo-on-my-phone/?utm_campaign=published+story+reminder&utm_medium=email+reminder&utm_source=floodlight

Note that I also had a broken link when I published my story and tried to click on the "View my story" button from the Publish/Share page.

The link path: http://floodlightproject.org/stories/dont-breathe/viewer/

**Comment by wendynorris** [comment]
FYI: URLs to other users' stories in the publish confirmation email render to their correct pages.
