### ISSUE TITLE
Difficult/impossible to add a connected story from an iPhone

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#857]
This is a user-reported bug from Rebecca Arno. She was trying to add a connected story to http://floodlightproject.org/en/stories/whats-the-last-photo-on-your-phone/.

> I couldn't do it from my phone and got pretty frustrated trying.  Safari browser must not be supported?  Had to email a pic to my computer and do it from here.  Have you guys thought about the implications of this with crowdsourced info?

Rebecca was, I believe, using an iPhone.

I'll try it out with my Android to see if I encounter similar problems.

While it doesn't make sense for people to build full stories from scratch on their mobiles, it does make sense for them to contribute connected stories (especially to _this_ story) from their phones.

**Comment by ghing** [comment]
The connected builder uses the same code base as the regular builder.  Mobile support was explicitly not part of the builder requirements.  Patching the existing builder for mobile support is going to be a big task and I recommend that we just include this as a requirement for a future version of the builder.  It seems resource intensive to make an all new temporary connected builder just for mobile support, but this is of course, doable if this is a high priority.

**Comment by ghing** [comment]
Also, the best workaround is to just upload an image from a phone to Instagram, Flickr, or imgur,  Then add the image _by the URL from that service_ once you have access to a computer.

**Comment by jwirfs-brock** [comment]
@ghing Don't worry, I'm not suggesting that we create a new, mobile-friendly version! I just wanted to make sure this is documented for future versions of the story-builder. Let's just keep an eye on this. The whole point of pushing out this connected story was so we could observe what user-behavior we get and what problems we encounter along the way.

One temporary solution is, given that it takes an extra step (emailing the photo to yourself, of uploading to Dropbox, Instagram, Flickr, etc.), we may want to provide these instructions somewhere prominent on the site. This is a perfect example of a user-requested tip/how-to feature that we can provide as part of our support content.

**Comment by ghing** [comment]
It would be possible, and relatively easy, to create a simple form that would work ok on mobile for creating a photovoice connected story.  For this to be easy, we'd have to really limit functionality.  It would basically let people get an item into Floodlight from their phone and publish it.  Once we add in any re-editing/advanced manipulation features, it stops being an _easy_ workaround.
