### ISSUE TITLE
Update default copy for the Summary field in the Story Builder

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#858]
I'll provide the updated copy, which will point out the suggested character limit.

@ghing once I have the copy I'll assign this issue to you to update.

**Comment by jwirfs-brock** [comment]
Ok, here's the updated summary default text, which comes in under the 250-character limit:

> Your summary goes here. Tell readers, in 250 characters or fewer, why your story matters. Write as if you were speaking with a friend. Sprinkle in a teaser or cliffhanger to entice your audience to read the full story.

Assigning to @ghing to update.

**Comment by ghing** [comment]
@jwirfs-brock, I'm in the process of fixing this, but note that if there's a summary in the template story, that's what will be used.  If you want to update the text in a case where a summary has been specified in a template, you can do that in the Django admin.

**Comment by jwirfs-brock** [comment]
@ghing Good call. I will go through the templates in the admin and make
sure they are updated.
