### ISSUE TITLE
Activity Grid should be grid-like

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#864]
(See #853 and http://dev.floodlightproject.org/en/skills/activities/?preview for context.)

My initial hit is that this should be more grid-like. Currently the description is shown in full, the image height varies, etc. I think it would be useful to constrain each item to a set, fixed-size layout, and provide a "more" link for complete description text.

We might start with the builder template selection page as a model (http://dev.floodlightproject.org/en/build/). But I am also currently kind of fond of the button-ish, contained look of the hacktivites page via @jwirfs-brock's link http://hivenyc.org/hacktivityGrid.html. In fact if we develop a look that works for the activity grid we might consider back-porting it to the template selection page.

/cc @ghing @bpawlak @tekhneco

**Comment by bpawlak** [comment]
Is that the same concept as the grid for choosing a story template? (http://floodlightproject.org/en/build/)

BTW, I keep getting a 404 when trying to view http://dev.floodlightproject.org/en/skills/activities/?preview :

Page not found (404)
Request Method:     GET
Request URL:    http://dev.floodlightproject.org/skills/activities/?preview

CMS: Page not found for "skills/activities"

You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

**Comment by ghing** [comment]
@bpawlak The activity grid is a new type of content that @jwirfs-brock needs to reflect different activities used in story raisings.

You're seeing the 404 error because the page hasn't been published and you need to be logged in to see that page.  I'll just go ahead and publish the page since it's on the dev server anyway.

**Comment by ghing** [comment]
@patternleaf, I hear what you're saying about being more grid-like, self-contained, and fixed-size.  @jwirfs-brock, would it be ok to show only the titles and a thumbnail and then expand the item to show more details when it's clicked?  Or, to show the information on a separate page that the user has to click through to see, as is the case for the [Hacktivities](http://hivenyc.org/hacktivityGrid.html) page? 

I think it will be easier for me to work on this when @jwirfs-brock has entered all the real content and selected thumbnails.

**Comment by jwirfs-brock** [comment]
@patternleaf @bpawlak @ghing I like the concept of having it be a button/grid-item that has more info you can see when you expand it. In the original sketches I proposed posted at #853, that is one of the design ideas (and it was indeed inspired by our template selection grid).

I'll put some more real content in there this morning. @ghing, just to clarify, yesterday you said I should do this on production, right?

**Comment by ghing** [comment]
@jwirfs-brock, yes, production.  I can then sync the dev instance to play with the design.

**Comment by jwirfs-brock** [comment]
@ghing I added the four activities that are ready to go onto production. They have everything but the thumbnails (I'm still working on those -- should have them later this morning).

Which page should I add them to? There's the Activity Guide page I created earlier (http://floodlightproject.org/en/admin/cms/page/29/), but I don't know which page template to set it to. Or I could create a new page under Skills, as you did on dev3.

Thanks!

**Comment by ghing** [comment]
Jordan, feel free to add them to whatever page you think makes the most sense.  The template/placeholder is up to you.  In my demo, I added them to the `Twocol-Content` placeholder using the "Two Column" template.

**Comment by jwirfs-brock** [comment]
@ghing I added them to the "Activity Guides" page (http://floodlightproject.org/en/admin/cms/page/29/) using the "Two Column" template and putting the plug-ins in the "Twocol-Content" area, and here's what it looks like:
http://floodlightproject.org/en/activity-guides/?preview

**Comment by jwirfs-brock** [comment]
@patternleaf There's some real content in there no, so I'm assigning back to you.

**Comment by ghing** [comment]
@jwirfs-brock, I'll take this since @patternleaf will be out next week.

**Comment by ghing** [comment]
Deployed to production as [0.15.1](https://github.com/PitonFoundation/atlas/releases/tag/0.15.1)
