### ISSUE TITLE
Template Improvements - Placeholder content in asset containers?

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#871]
It might be interesting to try putting actual placeholder content in the templates. For example, the PhotoVoice template could have a sample image a sample caption so users could see what it looks like. For more complex templates, this could be a way of demoing the structure of the story.

**Comment by mgrayinnovation** [comment]
Moving away from more templates in Pivot of 2015 ... actually looking to reduce templates in general.
