### ISSUE TITLE
Activity plug-in behavior on pages other than the Activity Guide

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#874]
@jwirfsbrock wrote:

> I had a quick question about embedding the activity plugins on pages other than the Activity Guide page. I wanted to put a small selection of activities (2 or 3) on these story-raising how-to pages:
> 
> http://floodlightproject.org/en/story-raising-how-to/story-raising-sketch/
> http://floodlightproject.org/en/story-raising-how-to/story-raising-scaffold/
> http://floodlightproject.org/en/story-raising-how-to/full-story-raising/
> 
> It would go in the "Suggested Activities" area, replacing the current list of links.
> 
> I played around with adding an activity plugin while editing the pages. The activity plugins were showing up nicely as tiles, but I when I tried clicking on the blue "+" symbol to expand them and see the full content, nothing happened.

And @ghing replied:

> The interactions that open/close the items require JavaScript that's only available if you use the "Activity Guides" template. If you want to add guides to pages using other CMS templates, please open an issue and I can think of the best way to do it.

I think it would be useful to be able to put activity plug-ins on other pages (the Story-Raising guides, possible on the skills pages, too). But enable the expand/collapse behavior on other pages isn't a priority if it's difficult to do. Here are some possible alternative ideas:
1. When you add an activity plug-in to a page other than the Activity Guide page, it appears expanded all the time
2. When you add an activity plug-in to a page other than the Activity Guide page, it appeared collapsed, with the title as a link. When you click on that link, it would take you to the Activity Guide page, with that specific activity expanded.
3. Build out pages for each activity. The activity page plug-in appears collapsed when it's on a page other than the Activity Guide, and the link goes to that activity's page.
4. (Not an alternative, just the original idea...) Activity plug-ins work the same way they do on the Activity Guide page wherever they appear (expandable/collapsible).

It might come down to a time trade-off. I think any of them would work fine. (3) would be time intensive for me, because I'd have to translate all of the activity content into pages on Floodlight -- which maybe should happen anyway. So, that might ultimately be the best option.

This doesn't really logically fit with Iteration 17, but I'm putting it in there for now because this is something I'd like us to handle soon.

**Comment by ghing** [comment]
Note to self: Think about adding js for each plugin with Sekizae and using `Modernizr.load()` to conditionally load Javascript.

**Comment by ghing** [comment]
@jwirfs-brock, you should let me know what the ideal behavior would be.

Of the options you mentioned above:

> 1. When you add an activity plug-in to a page other than the Activity Guide page, it appears expanded all the time

is the most straightforward, least time-consuming way to go.

**Comment by jwirfs-brock** [comment]
@ghing Cool. If we go with that option, how many story points do you think
it would be?

**Comment by ghing** [comment]
If we don't have the expanding/collapsing behavior on other pages, it would only be like 1 or 2 points.

**Comment by jwirfs-brock** [comment]
Ok, let's go with solution 1, activity plug-ins can go on other pages, and will appear expanded all of the time. 

I like that, because I can also use them on the activity landing pages.

I suggest keeping this in Iteration 17 -- @ghing does that work for you?
