### ISSUE TITLE
Story Builder tour needs to be updated to reflect changes in workflow

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#879]
Currently, the first screen of the tour is:

> Building a story takes five simple steps. Clicking on these tabs lets you switch between the different steps in the story building process. You can always move freely between the steps.
> Build - Construct your story using text, photos, videos, data visualizations, and other materials.
> Add Data - Upload or link to source data referenced in your story’s charts, maps, graphs and visualizations.
> Tag - Label your story with topics and places so that people can easily discover it on Floodlight.
> Review - Make sure your story is ready to go with spellcheck and other tools.
> Publish/Share - Post your story to Floodlight and your social networks.

This is already out of date. I suggest we update it according to the other changes in Iteration 19 (#579).

**Comment by jwirfs-brock** [comment]
I took a look at the tour text, and the first step (listed above) is the only one that needs to be updated.

I'll work on the new copy and post it here.

**Comment by jwirfs-brock** [comment]
@ghing Should we add a step in the tour that mentions the title and the byline?

**Comment by jwirfs-brock** [comment]
Here's the text for the first tour item:

**Building a story takes four simple steps.**
Clicking on these tabs lets you switch between the different steps in the story building process. You can always move freely between the steps.
1. **Build** - Construct your story using text, photos, videos, data visualizations, and other materials.
2. **Story Info** - Write a summary and select a featured image to give readers a quick glimpse of your story.
3. **Publish/Share** - Post your story to Floodlight and share on your social networks.
4. **Tag** - Label your story with topics and places so people can easily discover it on Floodlight.

And for the proposed new edit title and edit byline items:

**Edit your title here.**
Click here and start typing. Click anywhere on the screen to save. You can edit your title at any point during the story building process.

**Edit your author information here.**
Share your name and affiliation to let your readers know who you are. Click here and start typing. Click anywhere on the screen to save. You can edit your author information at any point during the story building process.

**Comment by ghing** [comment]
I updated the tour.  I mentioned the title and byline editing in a single tour step.  It looks like this:

![screenshot from 2013-12-10 11 15 39](https://f.cloud.github.com/assets/110420/1716378/120dc7da-61c0-11e3-9d49-a06e6f1acfb9.png)

**Comment by ghing** [comment]
Assigning to @jwirfs-brock for review.

**Comment by ghing** [comment]
@jwirfs-brock, since the UI will change significantly a result of our recent changes, do you think it makes sense to re-show the tour for all users?

**Comment by jwirfs-brock** [comment]
> Since the UI will change significantly a result of our recent changes, do you think it makes sense to re-show the tour for all users?

@ghing I think that's a good idea.
