### ISSUE TITLE
New section changes title from "Untitled Section" to "Section 1" upon refresh

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#881]
I noticed this while going through the test script for the text asset autosave (https://raw.github.com/PitonFoundation/atlas/develop/apps/storybase_asset/features/edit_text_asset.feature).

Here is what I did (all on dev.floodlightproject.org):
1) Logged
2) Launched a new Sandbox story in the builder
3) Completed the first test, autosave a new text asset
4) Added a new section to the story to do the second test, cancel editing a new text asset
5) After refreshing, I noticed that the title of the new section had changed from "Untitled Section" to "Section 1" both in the editor and in the section table of contents
6) I added another new section, this time without editing it at all, and noticed the same behavior after a refresh

This is also happening on production.

I tried it out with other templates, and it seems to be defaulting to the title of the template's first section.

I will look at this some more and add some comments about the desired behavior. I don't think we ever fully worked through what we want to happen when users add new sections to templates -- is the new section layout dictated by the template, or should it just be a generic default?

**Comment by mgrayinnovation** [comment]
Might relate to issues we're seeing with sections.  Might also be irrelevant if we hide the other templates during P4. Worth evaluating/reviewing prior to P4
