### ISSUE TITLE
In embed widget, byline text size should be smaller than story title/link text

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#882]
Here's a screenshot of the current embed widget (as seen in Firefox):
![screen shot 2013-10-22 at 1 43 02 pm](https://f.cloud.github.com/assets/1020518/1383681/7f3047a2-3b41-11e3-802e-29368c1e558e.png)

It looks a bit odd that the byline text is so large -- and appears to be larger than the story title text. For reference, the font-sizes/ratios we have on the homepage slider look a lot nicer:
![screen shot 2013-10-22 at 1 46 13 pm](https://f.cloud.github.com/assets/1020518/1383718/f0cf612c-3b41-11e3-85b9-600107d62388.png)

**Comment by mgrayinnovation** [comment]
Necessary to review while/before working on the embed/share buttons.  Seem to be lots of issues that have arisen around "embedding" ... check into closed issue index for other Embed issues.
