### ISSUE TITLE
Strange formatting in embed widgets where the story has a long summary

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#883]
Check out a few examples where I was playing around with the embed widget:
http://www.wirfs-brock.com/jordan/dataviz/embed_examples.html

In the second and third examples (all are story+list format), the featured story has a somewhat long summary. This is causing the featured image to be cropped in a strange way in the second example. And in the third example, it's causing the title to appear to bulge out from the top of the embed widget, and the featured image isn't visible at all.

I'm not sure if this is something we need to try to fix. We should just be aware that, when we are building custom embed widgets, we have to be on the lookout for stories with long summaries.

If we do want to fix this, I would suggest automatically truncating long summaries to a certain number of characters (whatever our recommended summary limit is).

**Comment by mgrayinnovation** [comment]
Related to #882, and maybe further reasong to be sure we have limitations/parameters on allowable size of story summaries.
