### ISSUE TITLE
Auto-sizing of video asset embeds from YouTube and Vimeo should adapt to section layouts

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#885]
Right now, YouTube and Vimeo embeds have slightly different behavior. YouTube appears small, whether it's in a side-by-side or one-up layout. Vimeo, on the other hand, always appears large.

Ideally, for both YouTube and Vimeo embeds, we would want them to be large (essentially fill up the entire container) for a one-up layout. For a side-by-side layout, we would want them autosized to the width of the container.

Here is an example (in preview mode): http://floodlightproject.org/stories/cf32743136ab4331ab3b7b6517d22f01/preview/

And here are screenshots of the preview:

1) YouTube in a one-up
![screen shot 2013-10-31 at 12 01 14 pm](https://f.cloud.github.com/assets/1020518/1447346/b508707e-4245-11e3-9042-d4290ae1e459.png)

2) Vimeo in a one-up
![screen shot 2013-10-31 at 12 01 42 pm](https://f.cloud.github.com/assets/1020518/1447350/c43c0902-4245-11e3-8485-1cb8c02fa2dc.png)

3) Both Vimeo and YouTube (together) in a side-by-side
![screen shot 2013-10-31 at 12 02 09 pm](https://f.cloud.github.com/assets/1020518/1447356/d56e992e-4245-11e3-9150-b801c4bd9fc7.png)

**Comment by ghing** [comment]
FYI, it looks like YouTube's oEmbed endpoint sets a specific size on the oembed in the response:

That is the request to http://www.youtube.com/oembed?url=http://youtu.be/9ymSnvQM5PE&format=json returns:

```
{
provider_name: "YouTube",
version: "1.0",
width: 480,
html: "<iframe width="480" height="270" src="http://www.youtube.com/embed/9ymSnvQM5PE?feature=oembed" frameborder="0" allowfullscreen></iframe>",
height: 270,
thumbnail_url: "http://i1.ytimg.com/vi/9ymSnvQM5PE/hqdefault.jpg",
provider_url: "http://www.youtube.com/",
thumbnail_height: 360,
type: "video",
thumbnail_width: 480,
author_url: "http://www.youtube.com/user/dpsk12americorps",
author_name: "Dps AmeriCorps",
title: "AmeriCorps Recruitment Video"
}
```

You can override this a bit by passing a `maxWidth` parameter to the oEmbed endpoint.

The request to http://www.youtube.com/oembed?url=http://youtu.be/9ymSnvQM5PE&format=json&maxwidth=1024 returns:

```
{
html: "<iframe width="612" height="344" src="http://www.youtube.com/embed/9ymSnvQM5PE?feature=oembed" frameborder="0" allowfullscreen></iframe>",
thumbnail_url: "http://i1.ytimg.com/vi/9ymSnvQM5PE/hqdefault.jpg",
thumbnail_height: 360,
width: 612,
provider_url: "http://www.youtube.com/",
author_url: "http://www.youtube.com/user/dpsk12americorps",
author_name: "Dps AmeriCorps",
version: "1.0",
title: "AmeriCorps Recruitment Video",
provider_name: "YouTube",
thumbnail_width: 480,
type: "video",
height: 344
}
```

However, it looks like the maximum width that returned iframe code will allow is `612`.

Playing around with the `<iframe>` element's width attributes, it looks like the player responds well to resizing the iframe, but we'd have to play with this more specifically to figure if we can make this work well to provide some kind of fluid sizing.

**Comment by mgrayinnovation** [comment]
This relates to our conversation around parameters/choices within the story builder.  If we move to only a two or three column layout, how will these embedded videos appear?  Might be worth reviewing later in Iteration P4
