### ISSUE TITLE
Summary character counter not displaying correctly in Chrome

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#893]
Here's a screenshot of what I saw while editing a summary in Chrome (Version 31.0.1650.48) on Mac OSX. Note that the "characters" text is visible, but there is no counter. Neither the as-you-type count nor the over-the-limit alert were visible.:
![screen shot 2013-11-13 at 11 46 02 am](https://f.cloud.github.com/assets/1020518/1533506/6b3c85ca-4c86-11e3-8e34-e65e8e4d2b40.png)

When I reopened the story after publishing, the counter was working correctly again. I went back and tried to re-create this error in a new story, but couldn't. I was doing a lot of activity (this was after building a story with multiple sections and assets), so I am not sure what exactly caused the issue. It's not a major priority right now, I just wanted to log this in case it pops up in the future.

**Comment by jwirfs-brock** [comment]
@ghing When I was looking at the new Story Info workflow step on dev (from #578 and #579), I observed that the character counter wasn't working.

**Comment by ghing** [comment]
@jwirfs-brock Yeah, that's a known issue.  I'm going to clean up details like that once I get the broad strokes figured out.

**Comment by mgrayinnovation** [comment]
Pertinent to test if and when we set character limitations for summary in P4.
