### ISSUE TITLE
HTML not enabled in connected story prompt

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#894]
In [this story](http://floodlightproject.org/en/stories/successes-and-obstacles-a-story-in-images-and-word/) I put a link in the connected story prompt using HTML (because there was no WYSIWYG editor). The HTML was not rendered on the story detail page or in the story viewer. Here's a screenshot:
![screen shot 2013-11-13 at 12 16 02 pm](https://f.cloud.github.com/assets/1020518/1533580/75d1f168-4c87-11e3-9027-4d107ad97c67.png)

I think it makes sense to enable HTML in the connected story prompt, if it's an easy fix.

**Comment by ghing** [comment]
This is a good point to add some sanitization into the process. 

I wanted to see what HTML people were actually throwing in their calls to action, and summaries, so I used [this snippet](https://github.com/PitonFoundation/atlas/wiki/Django-Snippets#find-all-html-tags-used-in-published-stories-calls-to-action) to look for tags in published stories and these are the tags that are being used:
- a
- b
- blockquote
- cite
- code
- div
- em
- font
- h3
- i
- li
- ol
- p
- span
- strong
- u
- ul

Some of these seem a little crazy, but should be fine to pass through the sanitizer.

**Comment by jwirfs-brock** [comment]
Yeah, I have a feeling a lot of those are coming from text pasted in from
another source that brought some html tags along with it.

**Comment by ghing** [comment]
Fixed this in 8e8a78a and deployed to production.
