### ISSUE TITLE
Change icon for story templates

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#895]
I created a new story template. By default, it has the icon for "Data Story."

In the story term, the icon needs to be switched (I'll create a new icon and post it here).

In the long term, it would be nice to be able to add a new icon via the admin view. A logical place for this would be in the story template edit view (http://floodlightproject.org/admin/storybase_story/storytemplate/6/).

**Comment by jwirfs-brock** [comment]
Here's the updated icon:
![successes_obstacles_icon](https://f.cloud.github.com/assets/1020518/1543174/4e7dddfe-4d52-11e3-9905-06b9d4b4722a.jpg)

I made this by modifying the original PSD comps we got from Geoff Thomas, so the image should be the same dimensions as the ones we are using in the builder. I didn't have anything to go on in terms of how much white space to add as a border, though. @ghing  If you need me to re-export it, just let me know the dimensions (in pixels) you want. I now have it as a vector file in Illustrator so I can adjust it as needed.

**Comment by ghing** [comment]
@jwirfs-brock This will ultimately need to be a PNG and be merged into the `story-template-icons.png` sprite.  It's probably just easiest if you email me the Illustrator file (or share it via Google Drive).

**Comment by jwirfs-brock** [comment]
@ghing As it so happens, I already put the .ai file on Google Drive:
https://drive.google.com/file/d/0B82exFJJWyJqdmhJdTZNaGIzRlU/edit?usp=sharing

Let me know if you need anything else.

**Comment by ghing** [comment]
@jwirfs-brock This is done and pushed to production.  You might have to do a hard refresh to see it.
