### ISSUE TITLE
Creating a copy of a story in the admin

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#896]
An admin should be able to select a story and make a duplicate of it. 

This could be useful for the purposes of creating story templates and leading workshops that focus on specific, story-driven activities.

Potential mechanics of this:
1. Could happen in the story list view (http://floodlightproject.org/admin/storybase_story/story/)
2. Could be an option from the pull down menu of actions at the top
3. When a story is copied, it could have the title, "Copy of ORIGINAL STORY TITLE"

If you have other suggestions on how this might work, I'd love to hear them.

**Comment by jwirfs-brock** [comment]
Some additional details about how this should work:
1. The owner of the story copy should be the admin who created the copy
2. When a story is copied, all of the assets should also be copied (so that a user can edit the assets in the copy without changing the originals)

**Comment by mgrayinnovation** [comment]
Definitely a worth wild idea to explore later.
