### ISSUE TITLE
Admin should be able to save story templates as drafts and/or stage them

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#897]
Currently, story templates don't have draft/published/staged settings -- they are either created (and published by default) or deleted.

Story templates should have a workflow that allows that admin to set them as a draft, as staged, or as published.

See the news item workflow for a model (http://floodlightproject.org/admin/cmsplugin_storybase/newsitem/10/). It has a status drop-down tab with the options: published, staged, draft, pending (we won't need a pending state).

**Comment by mgrayinnovation** [comment]
Closed and moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
