### ISSUE TITLE
Need to create list of user stories for mobile reading

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#898]
@ghing Suggested in our Iteration 20 planning discussion that we should first: "write user stories to help define goals for using Floodlight on mobile platforms."

**Comment by jwirfs-brock** [comment]
(Note this isn't an issue, it's more of a task -- I just wanted to record it as one of the things that needs to be done in this iteration.)

**Comment by ghing** [comment]
@jwirfs-brock I added a "task" label for these kinds of things in the future.  I think for our purposes it's totally fine to use the GitHub issue tracker for project-related, non-coding todos as well.

**Comment by ghing** [comment]
@jwirfs-brock and I started writing user stories for this in the "Mobile" worksheet of https://docs.google.com/spreadsheet/ccc?key=0AripktENBWzTdFpOaDBJa0JUdGFqaWs3UV9US3pLRUE&usp=sharing

Here are some questions and observations to help us to decide on implementation:
- the google analytics data for recent weeks show that all mobile visits are less than 10% of our traffic
- within mobile, it's 2/3 iOS, 1/3 Android
- What devices should we prioritize?
- Do most people reach stories directly (via their viewer or detail URL) or through some other entry point (search, explore page, homepage)?
- Long summaries will probably cause problems on mobile.  Maybe truncate to first few lines/sentances/chars

**Comment by jwirfs-brock** [comment]
@ghing Here's a draft of the test script for the user stories we came up with:
https://docs.google.com/document/d/1oCgv5fmMyDHdYSPlXfKGIT2eS_3xgr-s622kokbJGps/edit

**Comment by jwirfs-brock** [comment]
@ghing I've also updated our test matrix to include a tab for the mobile readability tests:
https://docs.google.com/spreadsheet/ccc?key=0AvaXS4x_XvJmdG5hbzZuT04ydm1Ra0piZHBOZV9abWc&usp=drive_web#gid=15

**Comment by jwirfs-brock** [comment]
@ghing I completed the tests for iPad and iPhone. Take a look at my notes on our test spreadsheet (https://docs.google.com/spreadsheet/ccc?key=0AvaXS4x_XvJmdG5hbzZuT04ydm1Ra0piZHBOZV9abWc&usp=drive_web#gid=15) and let me know if you have any questions.

I have complete notes on each scenario in the spreadsheet, but the biggest problems were:
1. When you launch a story from the story detail page, the viewer pop-up causes all kinds of problems. You can't scroll in the foreground (viewer), only in the background (story detail page). For stories with content that pushes navigation off the screen, this means you can't navigate through the story. **I think this is the most critical issue we need to address.**
2. The default sizing of most of our pages (homepage, explore page, search results, story detail page) makes the pages nearly unreadable on the iPhone. It's not impossible to scroll around to view content, but it's annoying enough that it would deter most people (including me). On an iPad, it's pretty good if you are in a horizontal orientation, but problematic if you are in a vertical orientation.

Let me know if it would be helpful for you to see screen shots of anything, or if you want to do a walk through via screen share.

**Comment by ghing** [comment]
@jwirfs-brock, I'll try to take a look at these but might not get to it until tomorrow.

> 1. When you launch a story from the story detail page, the viewer pop-up causes all kinds of problems. You can't scroll in the foreground (viewer), only in the background (story detail page). For stories with content that pushes navigation off the screen, this means you can't navigate through the story. **I think this is the most critical issue we need to address.**

Make sense.  Did you also test the viewer on iPhone/iPad  when accessed directly via /stories/SLUG/viewer/?

I've always disliked the popup viewer, and feel like it's even more inappropriate now that we have a more-clear idea of the content inside the story (and that it's needlessly constricted by the size constraints of the popup).  I'd like to do away with the popup and just have the "View Story" button replace the current page with the story viewer, especially since we now have a link back to the story detail page from the viewer.

However, it seems like there are likely some issues in the viewer, even without the popup and I'd like to know more about those issues.

**Comment by jwirfs-brock** [comment]
@ghing Yes, I did test using /viewer, and noted what worked in those cases
in the test matrix.
