### ISSUE TITLE
Microcopy for "Story Information" workflow step

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#899]
Write copy, if needed, for top of "Story Information" workflow step or under the heading for the summary and featured image tasks.

If you don't think anything is needed, or you want to test this out with limited textual guidance, just close this issue.

This is related to the fix for #579 and #578.

**Comment by jwirfs-brock** [comment]
@ghing I think, for the sake of consistency while we test, we should keep the micro-copy as-is in the current summary. This each, each summary has dummy text inherited from its template.

In our current story builder, there's additional micro-copy in the "help" section. For now, let's keep this micro-copy in the blue help tab for the new story information step. If we find, through testing, that people aren't sure what to do on the new story info step, then we can move it to a more prominent place.

This copy is adapted from the current story information section help text:

**Story Information**
Like the cover of a book, this is the first glimpse your audience gets at your story. Pull them in with a brief, thought-provoking summary, and a compelling image.

**Summary**
Tell readers, in 250 characters or fewer, why your story matters. Write as if you were speaking with a friend. Sprinkle in a teaser or cliff-hanger to entice your audience to read the full story. For example:

_There's a new park in Northeast Denver. It's not just any park. It's about reclamation, peace and promise. Meet the kids from the neighborhood who have taken part in building it and learn what peace looks like to them._

**Featured Image**
This is your story's magazine cover. Pick an image that inspires people to read your story. You can choose an image from your story, or add a new image from your computer or a link.

**Comment by ghing** [comment]
@jwirfs-brock, duh. I forgot that there was already help for the story information section in the existing builder.  I wired this up to the new workflow step.  When this is deployed, you can just edit the help item with slug `story-information` in the Django admin to reflect [what you wrote above](https://github.com/PitonFoundation/atlas/issues/899#issuecomment-29299618)  I'll open a new "task" issue for this to more clearly reflect that this needs to be done
