### ISSUE TITLE
Clean up story autosave handling

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#900]
As surfaced in a [usability test](https://docs.google.com/document/d/1SBOml6LgbEF96FdQq1q0XvL2Gb1bI-KKh-1-f2vu1Gc/edit) that @jwirfs-brock did with her mom, the way saving happens can be kind of confusing.

We should write user stories to describe the desired functionality, but I wanted to capture the current behavior and some things that might be desireable

Right now the strategy could be summarized as: 
- aggressively auto-save everything that you can
- in most (but not all) cases, show that this is happening via the save button states
- always let the user click the save button to initiate a save, even when there are no unsaved changes

A better way might be:
- Keep track of what items are unsaved
- Auto-save unsaved items periodically
- Only make the save button active if there are unsaved items

The other benefit of tracking unsaved changes would be that we can alert the user if they're navigating away from the builder with unsaved changes.

**Comment by mgrayinnovation** [comment]
Definitely a feature to review and determine where it's currently at in P4.
