### ISSUE TITLE
Update Story Information help text

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#901]
When the iteration 19 changes are deployed, update the help text for the Story Info workflow step in the Django admin (it has a slug of `story-information`) to reflect the addition of the featured image to this step.

@jwirfs-brock proposed some text for this in [this comment](https://github.com/PitonFoundation/atlas/issues/899#issuecomment-29299618) in #899.

**Comment by ghing** [comment]
@jwirfs-brock, the rest of the changes are deployed, so you can update the help text via the Django Admin.  I'm moving this out of the Iteration 19 milestone and into Critical Issues so I can close Iteration 19.

**Comment by jwirfs-brock** [comment]
@ghing I've updated the help text. Closing.
