### ISSUE TITLE
Write test scenarios for mobile features

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#902]
Based on the user stories for mobile (#898) in "Mobile" worksheet of https://docs.google.com/spreadsheet/ccc?key=0AripktENBWzTdFpOaDBJa0JUdGFqaWs3UV9US3pLRUE&usp=drive_web#gid=18 write test scenarios.  These should try to follow the conventions of the Gherkin language as much as possible.  

http://docs.behat.org/guides/1.gherkin.html is a decent Gherkin reference.

The goal of these tests is to evaluate the current state of Floodlight on mobile to help decide which experiences are most broken and how to prioritize stories for implementation.

**Comment by mgrayinnovation** [comment]
Closed and moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
