### ISSUE TITLE
If a user doesn't enter a byline, the story should display the user's first name, last initial by default when published

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#907]
The default byline, if a user doesn't enter in a custom byline, should be:

[User first name] [User last initial]

Example: Jordan W.

So, the same basic format as the user name that is listed on the story detail page.

Note that we may want to delay doing this until after we've tested the validation, and whether that alerts users to the fact that they can enter author information.

**Comment by ghing** [comment]
@jwirfs-brock, should I go ahead and implement this?

My feeling is that the first name and last initial shouldn't be set in the byline, but should just be displayed as a default when an explicit byline is not present.

What are the contexts where this should be used for the byline:
- Builder?
  - If so, should this be shown as the default in the builder (currently "Unknown Author"), or only when the story has been published?  In the latter case, the visible text would remain "Unknown Author" until the story is published.
- Story detail page?
- Viewer?

**Comment by jwirfs-brock** [comment]
@ghing I think we are ready to implement. In response to your questions:

>    Builder?
>        If so, should this be shown as the default in the builder (currently "Unknown Author"), or only when the story has been published? In the latter case, the visible text would remain "Unknown Author" until the story is published.

I think keeping it "Unknown Author" until the story has been published makes the most sense. If we fill it in, people might not realize they can change it.

>    Story detail page?

Yes, display here.

>   Viewer?

Yes, display here.

I think currently, it is displaying in the viewer but not on the story detail page.

**Comment by ghing** [comment]
@jwirfs-brock, I updated the story detail page template so it falls back to the author's first name and last initial.  Taking a look at the builder code, doing the fallback, and only for published stories, adds complexity that I'm not sure is worth it.  It seems like the only advantage of showing the fallback value in the builder is to mirror what will be shown in the viewer, but it also runs contrary to making the user more likely to fill in an explicit byline.  Let me know if you feel strongly about showing the fallback in the builder and I can implement it, but I'd rather leave out the extra complexity.
