### ISSUE TITLE
Featured image not being automatically set

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#908]
To reproduce:
1. Create a new story using the "Photovoice" template
2. Enter a title to save the story
3. Upload an image in the left-hand container
4. Click on the "Story Info" tab

Expected behavior: Image uploaded in step 3 should be displayed as the current featured image

Observed behavior: Default featured image is shown

**Comment by ghing** [comment]
This is how things are supposed to work:
- `FeaturedAssetView` listens to the `add` event of it's `assets` collection of its `model` property
- When a new asset is added, `FeaturedAssetView.handleAddAsset()` is called
- If the asset is an image asset, the handler waits for the `change:content` event to be triggered on the asset
- And then sets the asset as the featured image.

I need to use the debugger to figure out why this isn't happening.

**Comment by ghing** [comment]
It looks like the problem is that the `change:content` event doesn't seem to be triggered on the asset, and `this.model.setFeaturedAsset(asset);` never gets called.  Perhaps this is due to a difference in how Backbone triggers `change` events between the version used when this feature was implemnented and more recent versions.

It's interesting to note that the featured image gets set correctly on the first reload.

**Comment by ghing** [comment]
Actually, the `change:content` event is triggered, but it's triggered before the event listener is bound.

**Comment by ghing** [comment]
@jwirfs-brock, I believe I've fixed this issue.  Can you confirm that it's fixed on your end?

**Comment by jwirfs-brock** [comment]
@ghing I'm observing that it's fixed on dev, but not on production yet. Is that right?

**Comment by ghing** [comment]
Correct. Fixed on dev but not in production.

On Tue, Dec 10, 2013 at 9:46 AM, Jordan Wirfs-Brock <
notifications@github.com> wrote:

> @ghing https://github.com/ghing I'm observing that it's fixed on dev,
> but not on production yet. Is that right?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/PitonFoundation/atlas/issues/908#issuecomment-30238381
> .

## 

Geoffrey Hing
geoffhing@gmail.com
773.969.6436
http://geoff.terrorware.com/
Twitter: @geoffhing
