### ISSUE TITLE
Images showing up in asset drawer once removed, but not showing up in Story Builder or Preview

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#911]
Here is the story I was working on where I observed this bug: http://floodlightproject.org/en/build/d7a56f9c0566471aae26e8180ffb9847/

If you open the asset drawer, you'll see a bunch of image assets. All of them are embedded via Flickr using a link.

Two of the images (the black and white image of the roller coaster and the color image of the tiered wooden building) did not render originally when I added them. Instead, I got a blank asset that looked like this:
![screen shot 2013-12-04 at 10 46 11 am](https://f.cloud.github.com/assets/1020518/1674584/4a85935a-5cfb-11e3-9147-9a267c5b74fe.png)
And when I did a preview, it looked like this:
![screen shot 2013-12-04 at 10 46 34 am](https://f.cloud.github.com/assets/1020518/1674587/5156d5e0-5cfb-11e3-883b-959a16b091fb.png)

However, once I removed the images, they did appear as thumbnails in the asset drawer. When I dragged them back into the story, they still appeared as blank assets.

Here are the images as they appear (correctly) in the asset drawer:
![delinquent_images](https://f.cloud.github.com/assets/1020518/1674639/16333c32-5cfc-11e3-8ce8-7224f458669e.png)

This could be an issue with loading time, like it gets timed out or something. I initially thought it might have something to do with the permissions on Flickr, but these are all "sharable" images, so I don't think that's it.

Here are the URLs of the images that aren't rendering correctly:
http://www.flickr.com/photos/library_of_congress/3175012360
http://www.flickr.com/photos/boston_public_library/2589580475

**Comment by mgrayinnovation** [comment]
Closed and moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
