### ISSUE TITLE
Tags reverting back to old values when trying to edit metadata for a published story in Firefox

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#916]
I observed this in Firefox but not Chrome was I was walking through the full story feature test script (https://raw.github.com/pitonfoundation/atlas/develop/apps/storybase_story/features/story_builder_full_process.feature).

In Firefox, when I published the story, then added tags (as indicated in the script), then went back to try to remove some of the tags.

I removed the tags and hit "Save." But when I visited the story and did a refresh, the original tags were all still there. When I went back to the Builder and did a refresh there, the original tags reappeared. 

After waiting about 5 or 10 minutes, I went back and tried this same task again, and this time I could successfully remove the tags.

This isn't always replicable and isn't a high priority scenario, but I did want to document it in case it comes up in the future.

**Comment by ghing** [comment]
I tried (quickly) to replicate this and wasn't able to. I'll try to spend some more time trying to replicate this a little bit later.

**Comment by mgrayinnovation** [comment]
Wil, when we test the new tags, we should see if this is still happening.

**Comment by wilbertom** [comment]
@mgrayinnovation yeah, let's test this. If we can't replicate it, let's close it to keep the backlog clean. It's been a year, if it was a bug in firefox then it's probably fixed by now.

**Comment by mgrayinnovation** [comment]
Can you clarify what's meant by metadata in this issue's title?  Where's the best place to test this?

**Comment by mgrayinnovation** [comment]
Still need to test this old issue before closing
