### ISSUE TITLE
Generated thumbnails of (some?) transparent GIFs show up as black

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#917]
Thumbnails for transparent GIFs like this one:

![](https://f.cloud.github.com/assets/1020518/1933126/66cdd674-7ed6-11e3-98b7-c0b98e6330d7.gif)

Have generated thumbnails that look like this:

![](https://f.cloud.github.com/assets/1020518/1933080/6d06bbec-7ed5-11e3-8edf-43851ee64da5.png)

Possibly related to the easy_thumbnails colorspace processor: http://easy-thumbnails.readthedocs.org/en/latest/ref/processors/

**Comment by mgrayinnovation** [comment]
Closed and moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
