### ISSUE TITLE
On responsive design, nav menu converts to two rows with intermediate widths

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#918]
See screen shot:

![screen shot 2014-01-23 at 8 51 32 am](https://f.cloud.github.com/assets/1020518/1985986/493d1b4a-8446-11e3-99bb-4528fdd3f605.png)

This effect is a bit awkward.

I'm not sure what the best solution is. We could activate the drop-down earlier, or have a hybrid (some elements visible, some in the dropdown).

@ghing what are your thoughts?

**Comment by ghing** [comment]
Note that this is an issue with the current site as well.

**Comment by ghing** [comment]
I made some fixes that at least makes things look not broken in terms of the dropdown position.  There are still problems where items aren't easily clickable in some of the dropdowns.  I'm going to try to incorporate a little JavaScript to work around these issues.

**Comment by ghing** [comment]
Ok. It's considerably better now in terms of usability.  I still don't like the way the menu items look when they wrap, but at the moment, I can't think of a great way to deal with that visually.  Let me know if my changes work for addressing the original issue you reported.

**Comment by jwirfs-brock** [comment]
@ghing I think this is good for now. I agree that it isn't the prettiest thing, but at least you can see all of the elements and they work.

Closing.
