### ISSUE TITLE
Title text on story detail page is large, pushed rest of content down when viewed on mobile (phone-sized device)

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#920]
So far, I've looked at this on the iPhone 5 emulator in Chrome and on my Android phone (Galaxy Nexus with Android 4.2.2), and have observed the same problem. (I have yet to test it on tablet-sized screens.)

The title is sized so that it takes up the width of the screen, which looks very nice. But the text is so large that it pushes the rest of the content completely below the fold. 

Here's a screen shot of the "Boy Meets World" story detail page (from the iPhone emulator) with the screen in both the horizontal and vertical orientations:

![screen shot 2014-01-23 at 10 42 21 am](https://f.cloud.github.com/assets/1020518/1987201/43979e76-8456-11e3-913a-f1cae89632b1.png)

![screen shot 2014-01-23 at 10 42 32 am](https://f.cloud.github.com/assets/1020518/1987204/499766d0-8456-11e3-845c-f529164845a8.png)

@ghing Is it possible to make the title text a bit smaller? Is that something we can do based on screen size?

**Comment by jwirfs-brock** [comment]
And here's what an "ideal" story (short title, short summary) looks like in both the horizontal and vertical orientations (vertical is good):
![screen shot 2014-01-23 at 11 15 30 am](https://f.cloud.github.com/assets/1020518/1987520/00e6d600-845b-11e3-98f2-828681ea558a.png)
![screen shot 2014-01-23 at 11 15 21 am](https://f.cloud.github.com/assets/1020518/1987522/00f82022-845b-11e3-82ca-88122f0024b7.png)

**Comment by ghing** [comment]
Yeah. This is ugly.  I'm going to start with a smaller line-height and get rid of the background line on narrow displays.

**Comment by ghing** [comment]
Also bumped down font size to 24px on narrowest displays.

**Comment by jwirfs-brock** [comment]
This looks much better! Closing.
