### ISSUE TITLE
Idea: Move "View Story" button on story detail page to more prominent location for mobile viewing

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#921]
The "View Story" link gets buried in the current layout, especially with stories that have that have long titles ad on phone-sized screens.

Here's a screen shot of our test story in the iPhone emulator (to get the full effect of how far you have to scroll, it's probably easiest to just try it yourself):

![screen shot 2014-01-23 at 10 56 37 am](https://f.cloud.github.com/assets/1020518/1987304/be7c9c44-8457-11e3-99da-be46fc05a3c1.png)

@ghing Thoughts? Any ideas for a better placement? We could try it right underneath the title.

**Comment by ghing** [comment]
I think this is a good idea.  I made some changes to move the button higher on mobile.  Let me know what you think.

**Comment by jwirfs-brock** [comment]
This looks great. Closing.
