### ISSUE TITLE
Front page slider chevron arrows are too big on small screens

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#930]

**Comment by jwirfs-brock** [comment]
Additionally, you can't scroll up/down on a touch screen my touching the space in the vertical gutter of the chevrons, which makes the scrollable area really small (only the middle third of the screen). This makes it easy to miss the fact that you can scroll down to see recent stories.

**Comment by ghing** [comment]
I made the chevrons smaller and the content wider.  Can you confirm that this fixes things for you, @jwirfs-brock?

**Comment by ghing** [comment]
Both @jwirfs-brock and I think this is fixed now.
