### ISSUE TITLE
On explore page, map view icon gets cut off

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#936]
When testing on an Android tablet in the vertical orientation, on the explore page, I could see the "list view" and "tile view" icons, but the "map view" icon wasn't visible. When I switched to the horizontal view, it was visible. Initially, I thought it was there, just off the screen. But in the vertical view, I couldn't scroll side to side.

This is a minor issue/low priority, because the map view doesn't get used much anyway, and probably even less so on mobile devices.

**Comment by ghing** [comment]
The map view icon is actually hidden on narrow displays, not cut off.  I did this because the map didn't work great on narrow displays.  Since it seems like I still have some hours in the development contract, I might spend part of them making the map work better on narrow screens.

**Comment by jwirfs-brock** [comment]
Oh, that makes sense! Ok, it's something to look into if there's time, but
not a high priority.

**Comment by ghing** [comment]
Closing this in favor of #939.
