### ISSUE TITLE
"Floating" filters on top of Explore page

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#937]
On the explore page, I'm a bit ambivalent about the sticky filters that appear to float above the rest of the page when you scroll down. There's limited real estate already, so giving so much space to the filters seems like it might not be the best idea.

@ghing What are your thoughts?

**Comment by ghing** [comment]
The stickiness should be triggered based on the filter height as a
percentage of  the total height. On which device/resolution did you see the
filters stick.

**Comment by ghing** [comment]
@jwirfs-brock, I'm not seeing the filters stick on my phone, either in landscape or portrait orientation.  On what resolutions are you seeing the sticky filters and finding them annoying?

**Comment by jwirfs-brock** [comment]
I observed this on my Nexus 7 tablet. It's not a huge annoyance, so it
that's the only device where it's an issue I say we skip it.

**Comment by ghing** [comment]
What's the resolution on your tablet, and was it in landscape or portrait mode?

**Comment by jwirfs-brock** [comment]
I observed it in portrait mode (vertical). Resolution is 1200x800, I
believe.

**Comment by jwirfs-brock** [comment]
Oops, 1280x800.

**Comment by ghing** [comment]
In my testing, the filters were only sticky in landscape orientation (1200x800) display and not in portrait (800x1200).  The filters didn't really bother me as I could still see one full row of stories.  

@jwirfs-brock, if you feel strongly about getting rid of the sticky filters on all displays, or you're seeing them stick on the 800px wide display (portrait mode), please reopen this issue.
