### ISSUE TITLE
Default author information not displaying for published stories

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#943]
There are two new stories on Floodlight (published today) where it looks like the author did not enter in any author information.

Instead of defaulting to the user's firstname + last initial, it is showing the dummy text ("Your Name and/or Organization. Examples: Jon Denzler; Laura Frank, I-News").

Here are the story links:
http://floodlightproject.org/en/stories/when-everything-changed/
http://floodlightproject.org/en/stories/family-matters/

**Comment by ghing** [comment]
The default text is an [HTML5 placeholder attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input).  So, it should never populate the value of the field (even though that's what it appears to do in the browser.

My only thought is that we use a polyfill for [browsers that don't support the placeholder attribute](http://caniuse.com/input-placeholder), in our case this is probably IE 8 & 9, and this polyfill might actually set the input value.  If this is the case, the value might get submitted and show up in the published story.

**Comment by jwirfs-brock** [comment]
I was considering reaching out to the users and recommending that they add author information (and a summary, while they are at it). If I do that, do you want me to ask what browser they were using?

**Comment by ghing** [comment]
Yeah, please ask what browser they're using.

**Comment by ghing** [comment]
The [placeholder polyfill](https://github.com/PitonFoundation/atlas/blob/develop/static/js/libs/polyfill.placeholder.js) does indeed work by setting the value of the input.  In most cases, the placeholder will be removed when the user leaves away the input, but there might be a scenario where the a particular sequence of clicks and keystroes with our inline editor causes the value to get saved.
