### ISSUE TITLE
Explore page loads slowly

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#945]
/explore loads slowly.  I think this is probably related to the use of Solr and the joins required for translations.

**Comment by ghing** [comment]
One issue is that memcached on the server had stopped.  I restarted it, following the instructions at http://docs.webfaction.com/software/memcached.html.  I need to do some digging to make sure that values are actually getting added.

**Comment by mgrayinnovation** [comment]
Closed and moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
