### ISSUE TITLE
As a reader I should immediately be taken to a story's first page when I click a link to it so that I have a better reading experience

### ISSUE THREAD

**Issue by mgrayinnovation** [denverfoundation/storybase#949]
___ As an audience/viewer of a story, the first page should be the first page of the story viewer: http://www.floodlightproject.org/en/stories/strengthening-communities-preserving-the-land-inno/viewer/ so that when, as a reader, I click on a story from the explorer (http://www.floodlightproject.org/en/explore/) I am jumping right into the viewer and not a "pre-page" ... 

The components available on the "pre-page": http://www.floodlightproject.org/en/stories/strengthening-communities-preserving-the-land-inno/ should still be available on the first page of the viewer, including: a summary, how to take action, a table of contents, the author's name + contributed by, Published, and Updated etc. but we should be able to easily scroll to the next page in the viewer.

**Comment by wilbertom** [comment]
@mgrayinnovation we should discuss how we want to handle other things like the comments of a story, and the layout of this new page.

**Comment by mgrayinnovation** [comment]
In storybuilder/sandbox, this first page/summary page is fixed in the storybuilder, much the same way the call to action page is fixed at the end of a story in the storybuilder.

**Comment by mgrayinnovation** [comment]
Diagram: https://drive.google.com/open?id=0B8TQ3rnaHaogNllaTVBNZFZuSXc&authuser=0

**Comment by mgrayinnovation** [comment]
This is ideally a top priority in this iteration.
