### ISSUE TITLE
Story Builder: Storytelling Checklist

### ISSUE THREAD

**Issue by mgrayinnovation** [denverfoundation/storybase#951]
When a writer is using Sandbox, an early page should be a checklist of things they should consider when attempting to write a strong Floodlight story.  Some of these pieces already exist on Floodlight, but others should also be added to (see A1: Storytelling Checklist).  Writers should be redirected to this page once again, just before publishing their story.

Matt needs to provide checklist.

**Comment by wilbertom** [comment]
There's also the panes to the right of the story builder with "Assets" and "Help". Maybe we can play off of that.
