### ISSUE TITLE
As a user I want to easily share my story with Facebook so that my friends can read it

### ISSUE THREAD

**Issue by mgrayinnovation** [denverfoundation/storybase#954]
Check Floodlight's current optimization with Facebook.  Are there tweaks or necessary additions? Facebook has been identified as the unifying social media site for our intended audience, thus Floodlight stories should be easily shared and read via Facebook.

**Comment by wilbertom** [comment]
@mgrayinnovation let's talk about how we can make this better.

**Comment by mgrayinnovation** [comment]
Brought up in more depth in issue in #976 ... closing this earlier one because of accidental redundancy.
