### ISSUE TITLE
As thought leader, I want to be able to mark a story with a badge so that

### ISSUE THREAD

**Issue by wilbertom** [denverfoundation/storybase#960]

**Comment by wilbertom** [comment]
@mgrayinnovation we should discuss the value this brings to the system.

**Comment by mgrayinnovation** [comment]
Here's the document to the 6 badges we need: https://docs.google.com/document/d/1HViQuZiTNPS-YL8BKmNdvVfRifKXnIm3-lMN887vOTo/edit

We also want the capability to add badges easily, and for amns to provide permission for users to utilize the badge system. Not password protected badges as in #953

**Comment by mgrayinnovation** [comment]
Rebecca forwarded the high res badges to Wil and Matt on 2/16.

**Comment by wilbertom** [comment]
@mgrayinnovation got them. I'll redo my badges with the high res.

**Comment by mgrayinnovation** [comment]
We'll be testing this shortly, along with #959 and all Badge issues, and then closing the issue.
