### ISSUE TITLE
As storybuilder, I should only allow stroytellers to pick from one of the built in topics when tagging their story to better categorize content

### ISSUE THREAD

**Issue by wilbertom** [denverfoundation/storybase#961]

**Comment by mgrayinnovation** [comment]
storytellers could be given the opportunity to post a second tag as it might be necessary for some stories.  Let's limit to two tags, not just one?

**Comment by mgrayinnovation** [comment]
Here's the document to the tags we need: https://docs.google.com/document/d/1HViQuZiTNPS-YL8BKmNdvVfRifKXnIm3-lMN887vOTo/edit

**Comment by wilbertom** [comment]
@mgrayinnovation we're doing this already right?

**Comment by mgrayinnovation** [comment]
Indeed, we are for readers and those exploring stories, but I'm not sure we were doing it for writers ... I rewrote this issue to reflect that we need to put these constraints on writers when they tag their story with a topic in storybuilder.  Does this shift make sense?  I think writers can currently tag their story with as many topics as they want.
