### ISSUE TITLE
As user, I want an easier "share" button available on the first and last page of the story viewer.

### ISSUE THREAD

**Issue by mgrayinnovation** [denverfoundation/storybase#963]

**Comment by wilbertom** [comment]
Our plain email button doesn't work. The Gmail one does, we want the default to be Gmail.

**Comment by mgrayinnovation** [comment]
When clicking the share button, ideally four sections would appear:

Share Button

Social Media
--Popular social media icons here +

Email
--Popular email provider icons here

Copy a Link
--story link here

Print
--print icon here

**Comment by mgrayinnovation** [comment]
When clicking a popular email icon, it would open the users email (if already logged-in) and auto-populate an email draft with the story link.  If the user is not already logged-in, then the link would take the user to the log-in page.
