### ISSUE TITLE
As a user I want to contact the author of a story dirrectly by pressing a "Connect" button

### ISSUE THREAD

**Issue by wilbertom** [denverfoundation/storybase#972]

**Comment by mgrayinnovation** [comment]
Ideally, this button is available on both the first page and last page of the story ... reference the diagram created on 2/17

**Comment by mgrayinnovation** [comment]
Where will this connection go?  Through both users emails account (as we're optimizing the share button to do).  So when a reader clicks the connect button, their preferred email account will open, already populated with the authors email address?

**Comment by mgrayinnovation** [comment]
This conflicts with Issue #965 and #966, and it might create some privacy/confidentiality issues for us.
