### ISSUE TITLE
As a storyteller, I'm wondering if Floodlight is the right tool for me.  I would love to have a more robust definition on the homepage beyond, "Floodlight is an easy tool to create, post and share stories about community issues to inspire people to act." ... before navigating to the about page/menu.

### ISSUE THREAD

**Issue by mgrayinnovation** [denverfoundation/storybase#987]

**Comment by mgrayinnovation** [comment]
Current proposed text:

Floodlight is an easy tool to create, post and share stories about community issues that inspire people to act. Our Story Builder helps you tell digital stories that include photo, video, data, and narrative, and stories that call your readers to action. It’s also a place to uncover connections between stories, and reach even higher levels of community impact.

**Comment by mgrayinnovation** [comment]
The following text was confirmed for use on 4/2/15, please replace and use: 
      Floodlight is a place where people can tell and share inspiring stories from the Metro Denver community. This easy tool allows users to create, post and share digital stories that include photo, video, data, and narrative, calling readers to action. It’s also a place to uncover connections between stories, and reach even higher levels of community impact. 
      Floodlight Super Users are Denver Foundation donors, who have the ability to boost stories through assigning special badges that call out great ideas, inspiring people, and projects that they have funded.

**Comment by wilbertom** [comment]
Hey Matt, I went with the first paragraph for now. It's too long for the space I had accommodated for it. I'll redo the spacing and add the second part.

**Comment by mgrayinnovation** [comment]
We'll leave this issue open as we may still need to find a way to incorporate the super users right on the home page after adding a super user and badge page on the navigation menu.

**Comment by mgrayinnovation** [comment]
We found a fix for this for now.  And Rebecca has mentioned that she wants to work on the About page.  We'll get to that separately.
