### ISSUE TITLE
As Floodlight, we need a new brand to identify TDF and Denver as our focus.

### ISSUE THREAD

**Issue by mgrayinnovation** [denverfoundation/storybase#990]
TDF Logo, next to Floodlight logo, followed by Denver (vertically)?
w/ a new tagline ... see Issue #989

**Comment by wilbertom** [comment]
Floodlight Denver name was floating around.

**Comment by mgrayinnovation** [comment]
Yes, TDF logo (w/out words, like the badge) to the left of the Floodlight logo, with "Metro Denver" worked in so it becomes "Floodlight Metro Denver."  The "Metro Denver" around here considers the 7 counties that make up the metropolis, whereas "Denver" only indicates the City of Denver.  TDF works with "Metro Denver." Definitely important distinction to the many locals using the site.

**Comment by mgrayinnovation** [comment]
![screen shot 2015-03-17 at 12 52 37 pm](https://cloud.githubusercontent.com/assets/7264218/6695142/95f9c8a0-cca4-11e4-895f-7c68e373862a.png)

**Comment by mgrayinnovation** [comment]
This is a mock-up of the logo layout ... the Metro Denver text and orientation could use some help.

**Comment by mgrayinnovation** [comment]
This layout is confirmed.  Rebecca will be working internally within TDF to finalize the aesthetic and design.

**Comment by mgrayinnovation** [comment]
Waiting for final logo, but our work is done for now.
